### ISSUE TITLE
Support for USB-CEC adapters

### ISSUE THREAD

**Issue by Dandy1381** [MonitorControl/MonitorControl#1002]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

I use Sony A8 TV as external Monitor for my Macbook pro 2016 (Intel version), sadly it doesn't work.
A soundbar (Sony HT-A7000) is also connected to the TV through eARC.

I can see the volume icon of the macOS going up and down, it just doesn't have any impact on the actual volume of the soundbar.

### Describe the solution you'd like

control the volume on my Sony TV/soundbar with MacOS itself.

### Describe alternatives you've considered

doesn't really have an alternative solution.

**Comment by waydabber** [comment]
TVs typically do not support any kind of DDC but might be compatible with HDMI-CEC. This is howerver not supported in any way by macOS or MonitorControl.

**Comment by markhicken** [comment]
It would be awesome to add in support for HDMI-CEC if a USB-CEC adapter is present. The [Pulse Eight USB-CEC Adapter](https://www.pulse-eight.com/p/104/usb-hdmi-cec-adapter) could facilitate this. It can be controlled using [libcec](https://github.com/Pulse-Eight/libcec). I've been playing around with this and find it to be pretty solid.
