### ISSUE TITLE
Apple 24" Cinema Display no longer reaching full brightness

### ISSUE THREAD

**Issue by SkipLesion** [MonitorControl/MonitorControl#1004]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

I have a 24" Apple LED Cinema Display - after installing the app I can control the brightness - but from 0 to about 30%. Previously the display was dim and I couldn't adjust with my M1 MacBookPro as there was no Brightness slider for my external monitor. I managed to set it to full brightness by using an ancient MacBook Air. So ti has been on full brightness - until now, when I can't get it above approx 30% - even though the slider in the app goes to full brightness. I'm norw struggling to read my display :-(

### Expected behavior

I expected to be able to run my display at full brightness

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.3.1
- Mac model: MacBook Pro (14-inch, 2021) Apple M1 Pro
- MonitorControl version: 4.0.2
- Monitor(s): Apple 24" LED Cinema Display
- Monitor Cable(s)/Connection(s): USB-C adapter
- Apple Silicon/M1 (yes or no): Yes
```

**Comment by waydabber** [comment]
Hi there, see these for possible solutions:

https://github.com/MonitorControl/MonitorControl/discussions?discussions_q=apple+cinema

**Comment by SkipLesion** [comment]
Dear Istvan,

Many thanks indeed - this has worked perfectly for me and solved my problem - many thanks indeed.

My apologies for not finding the original discussion and thank you so much for your rapid and helpful reply.

And most of all many thanks for creating this app to restore controllable brightness to my ancient but otherwise brilliant display!

Kind regards,

John

On 14 Apr 2022, at 13:48, Istvan Toth ***@***.******@***.***>> wrote:



Hi there, see these for possible solutions:

https://github.com/MonitorControl/MonitorControl/discussions?discussions_q=apple+cinema<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMonitorControl%2FMonitorControl%2Fdiscussions%3Fdiscussions_q%3Dapple%2Bcinema&data=04%7C01%7Cjal70%40universityofcambridgecloud.onmicrosoft.com%7C0500abcc4d6641952af508da1e1508d3%7C49a50445bdfa4b79ade3547b4f3986e9%7C0%7C0%7C637855372928417136%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=w%2FYqWPSkrrZ6bWI%2FnRVfQ7YNbHzG1Em2nd8skBFSm6g%3D&reserved=0>
