### ISSUE TITLE
lowest volume setting still too loud

### ISSUE THREAD

**Issue by Pfrommer1982** [MonitorControl/MonitorControl#1007]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Question

HI, i use monitorControl with macbook m1 pro 14" and an AOC CU34G2/BK via hdmi. But the lowest volume setting is still to loud. I use headphones that i connect with my monitor. Is there a workaround? I preferably don't want to change any connection.

**Comment by waydabber** [comment]
nope, we can't control display volume via the HDMI port of the macbook pro 14" - only USB-C works even if the display supports DDC control. :(

**Comment by the0neyouseek** [comment]
@Pfrommer1982 You can also enable "Use fine OSD scale" in settings or <kbd>alt</kbd> + <kbd>shift</kbd> + <kbd>volume up/down</kbd> to try go even lower

**Comment by Pfrommer1982** [comment]
That actually fixes the issue! Enabled OSD scale and now it works like a charm! Thanks for help and this beautiful piece of software!

**Comment by waydabber** [comment]
Hops. I must have misunderstood the original question. :) Sorry about that. :)

**Comment by Pfrommer1982** [comment]
Np bro, thanks anyway

**Comment by impulse200** [comment]
Hi. I have similar issue with Huawei MateView connected over usb c to MacBook Air M2. Minimal sound volume is deafening. This is not the case with linux/windows, connected via hdmi and dp. I also noticed that there's separate volume controls in OS and on monitor in linux/windows while I have only one control in macOS. I like to set volumes around 50% and it works well but not in macOS.
Is there something could be done with it? It is quite annoying to have manually adjust volume levels each time I switch monitor between machines.
