### ISSUE TITLE
High Energy usage

### ISSUE THREAD

**Issue by elenigen** [MonitorControl/MonitorControl#1008]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

I don't know why, but my Mac is detecting this app as being the Top Energy consumer:
![image](https://user-images.githubusercontent.com/8632319/164079976-29818c9d-482f-46e9-928a-d5b4216de4f7.png)

### Steps to reproduce

I believe I'm using the default configuration, except for:
`Multiple displays: Use combined slider for all displays`

### Expected behavior

Nothing special other than not draining the battery.

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.2.1 Monterey 
- Mac model: MacBook Pro (16-inch, 2019)
- MonitorControl version: 4.0.2 Build 6965
- Monitor(s): Default and sometimes Apple 27-Inch LED Cinema Display
- Apple Silicon/M1 (yes or no): no
```

**Comment by the0neyouseek** [comment]
Hi @elenigen the app is called "Monitor Control", here it really is your display brightness that is using energy 😉 
Try lowering your brightness and check if the "Display brightness" disappear
