### ISSUE TITLE
Fine Scale (Alt+Shift) support with Custom Keybind

### ISSUE THREAD

**Issue by krackers** [MonitorControl/MonitorControl#1026]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

Currently, when using a custom shortcut (e.g. f10/f11) for volume up/down, toggling fine-scale via alt+shift does not seem to be supported like it is for the native volume keys.

### Describe the solution you'd like

Ability to use a custom key, e.g. F11 for coarse volume and a modifier + custom, e.g. alt-shift-f11 for fine volume.

### Describe alternatives you've considered

Considered patching `KeyboardShortcutsManager.swift` and building it myself although I'm not quite sure if MASShortcutRecorder supports passing through modifiers. Maybe another way to approach this would be to add separate keybind for the fine-scale.

**Comment by waydabber** [comment]
Adding a separate shortcut would be the way to go as it is difficult to know what the custom key will be and whether it contains the key we'd regard as 'modifier' to begin with - in which case the modifier would fail.
