### ISSUE TITLE
Max brightness being set constantly once app starts. 

### ISSUE THREAD

**Issue by Gabriel-Sa** [MonitorControl/MonitorControl#1028]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

On my M1 Max MacBook Pro the brightness for the screen is being set to max automatically. The OSD for brightness stays on. The only solution is to unplug and replug in the monitor. Even restarting the computer causes the bug to persist. Not sure if this is an issue with Apple's display drivers or with the app itself. 

### Steps to reproduce

I'll update with the direct steps required to reproduce. Right now it seems that it happens if the laptop has been plugged in over night. 

### Expected behavior

The app should adjust the brightness as usual. However the app continues to display the brightness OSD even when no brightness function keys are being pressed. 

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.3.1
- Mac model: MacbookPro18, 2 (16-inch, 2021) 
- MonitorControl version: 4.0.2 Build 6965
- Monitor(s): LG HDR 5K
- Apple Silicon/M1 (yes or no): yes
```

**Comment by Gabriel-Sa** [comment]
Added below are some screenshots and a video demonstrating the bug.
![Screen_shot](https://user-images.githubusercontent.com/19657801/167229475-c5b8bb81-9d45-4de6-8062-3a78da85dba1.jpg)
The screen shot was taken using the keyboard, so I wasn't pressing any of the brightness buttons. 
The video below contains me moving the slider (without pressing any buttons), then pressing the buttons.

**Comment by the0neyouseek** [comment]
Hi @Gabriel-Sa !

That's a weird one! Do you perhaps have the "Sync brightness" option enabled ?
![image](https://user-images.githubusercontent.com/4009175/167243627-e32756c3-c558-422f-9267-f8437c5630cb.png)

**Comment by Gabriel-Sa** [comment]
> Hi @Gabriel-Sa !
> 
> 
> 
> That's a weird one! Do you perhaps have the "Sync brightness" option enabled ?
> 
> ![image](https://user-images.githubusercontent.com/4009175/167243627-e32756c3-c558-422f-9267-f8437c5630cb.png)
> 
> 

Hi! Yep I made sure it was off. I keep my laptop in clamshell mode too.

**Comment by ltreme** [comment]
I have the same problem, but instead of the brightness, the volume increases constantly after I start MonitorControl.

My specs are:
- macos 12.3.1
- mac model: Macbook Pro 16 (2019)
- MonitorControl version: 4.0.2 Build 6965
- Monitor: LG HDR 5K
- Apple Silicon/M1: no

**Comment by Gabriel-Sa** [comment]
Update, appears to be happening with the volume settings as well. Not sure if this is a Mac bug or a bug with the app.
