### ISSUE TITLE
Volume control doesn't work for my Dell monitor

### ISSUE THREAD

**Issue by kishore-squareup** [MonitorControl/MonitorControl#1033]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

I have MacOs Monterey, and have connected to my dell S3221QS. I have DDC enabled on my monitor. When I try to adjust the volume using the sliders, nothing happens. 

### Steps to reproduce

1. Connect monitor to mac
2. Set the audio output to HDMI
3. Adjust volume using the sliders in Monitor control app

### Expected behavior

Adjusting the volume sliders to change the monitor's volume

### Anything else?

I have tried the m1ddc tool, nothing happens with that.
`./m1ddc display 2 get volume` returns 110
`./m1ddc display 2 set volume 80` doesn't change the volume

### Environment Information (please complete the following information)

```markdown
- macOS version: Monterey
- Mac model:Macbook pro M1 max
- MonitorControl version: 4.0.2 Build 6965
- Monitor(s): Dell S3221QS
- Apple Silicon/M1 (yes or no): yes
```

**Comment by calonye** [comment]
me too~

**Comment by Zane0227** [comment]
same problem

**Comment by Zane0227** [comment]
same problem

**Comment by Zane0227** [comment]
- macOS version: Monterey
- Mac model:Mac mini M1
- MonitorControl version: 4.0.2 Build 6965
- Monitor(s): Dell U2720QM
- Apple Silicon/M1 (yes or no): yes

**Comment by the0neyouseek** [comment]
Hi @kishore-squareup 

Are you using the HDMI port of your macbook pro ?
If so, you're not using DDC control as this not possible with this port. Please see this discussion about it here https://github.com/MonitorControl/MonitorControl/discussions/750

If not, your monitor may simply not support volume ddc control and since you tried with m1ddc and it did not work that may be it

**Comment by kishore-squareup** [comment]
Yes, I have connected to the monitor using the HDMI port on the laptop. Thanks for the link, I see that this is not supported on M1 pro and Max.
