### ISSUE TITLE
Can we have global volumes to all devices? Monitor Speakers + MacBook Speaker for example

### ISSUE THREAD

**Issue by joehquak** [MonitorControl/MonitorControl#1045]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Question

Hey all!

First of all, just wanted to say that this is fantastic software and reflects the hard work that everyones put into it. It's awesome that its open to public contributions, well done everyone who's contributed!

I have a question about a specific setup. 

I have 2 monitors connected to my MacBook via USB-C which work perfectly with Monitor Control

The MacBook has built in speakers and they operate even with the lid closed, I'd like to utilise them as well as they have good bass compared to my monitor speakers which are very low quality, I use the Audi MIDI Setup to create a multi-output device in order to play audio to all output sources at the same time.

When using Monitor Control I am only able to control the output volume of the Monitors but not the MacBook speakers, I have to manually open the audio settings and adjust that volume.

Would it be possible to have a global volume toggle, so when interacting with the audio controls, all output devices get adjusted? Or even an option to select additional devices that get controlled by the volume controls apart from monitors?

Here's a screenshot which shows how my Audio is setup and Monitor Control - `MateView` are the screen speakers.

Thanks in advance 🙏 

![Screenshot 2022-05-21 at 09 03 34](https://user-images.githubusercontent.com/32411671/169642209-9f1d4a78-8206-4fb2-806d-d70160c5e154.png)

![Screenshot 2022-05-21 at 09 05 09](https://user-images.githubusercontent.com/32411671/169642277-0bc33650-f5d1-4dd8-b68f-1ce1b5fd0723.png)

**Comment by joehquak** [comment]
Or maybe even support for Multi-Output devices? Some logic will be needed to read the devices used in `Audio MIDI Setup` for the `Multi-Output Device` and then apply the audio adjustment logic to all of them when the `Use audio device name to determine which display to control`?

FYI `Audio MIDI Setup` is a standard MacOS app, just in case anyone is wondering

![Screenshot 2022-05-21 at 09 09 50](https://user-images.githubusercontent.com/32411671/169642440-06a63d80-fdf4-4988-8c6a-855d6a630955.png)

**Comment by JoniVR** [comment]
Hi, I was working on this a few months ago and had gotten pretty far, I'll try to see if I can recover these changes whenever I get time in the next few weeks.

**Comment by JoniVR** [comment]
Going to close in favour of #618, let's continue tracking in there.
