### ISSUE TITLE
Apple LED Cinema Display and Macbook air M1 brightness reduced after installing MonitorControl

### ISSUE THREAD

**Issue by galgi-droid** [MonitorControl/MonitorControl#1051]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

After installing MonitorControl on Macbook air M1 connected to Apple LED Cinema Display the brightness of monitor decreased about 50% and iI can't increase it nor keyboard nor Control Center. 

### Expected behavior

How to return the brightness of monitor back?

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.4 Monterey
- Mac model: Macbook Air M1
- MonitorControl version: 4.1.0. Build 7034
- Monitor(s): Apple Cinema Display
- Monitor Cable(s)/Connection(s): USB type C
- Apple Silicon/M1 (yes or no): yes
```

**Comment by the0neyouseek** [comment]
Hi @galgi-droid 
Please have a look at these discussions for these issue https://github.com/MonitorControl/MonitorControl/discussions/739 & https://github.com/MonitorControl/MonitorControl/discussions/970
