### ISSUE TITLE
Brightness resets to 100% from time to time

### ISSUE THREAD

**Issue by ivnhysfryr** [MonitorControl/MonitorControl#1064]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

I haven't been able to identify what triggers it. It happens from time to time, even when idle. Pressing any of the brightness buttons will bring back the previous setting and will increase or decrease brightness from this setting, meaning one has to press the opposite button to go back to the preferred setting.

MonitorControl works flawlessly on a MacBook Pro M1 with an external monitor.

### Steps to reproduce

It happens randomly apparently

### Expected behavior

Stay in the same brightness level always

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.2.1 Monterey
- Mac model: Mac mini (2018)
- MonitorControl version: latest (updated minutes ago)
- Monitor(s): HP ENVY 27"
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment]
It might be the HP Envy 27". Some displays don't register DDC commands well and periodically reset to the OSD setting?

**Comment by moritzWa** [comment]
I have the same issue. The issue is temporarily fixed when I adjust the MonitorControl setting slightly. I don't use the shortcuts but just move the slider a few mm to the left and then back to the right.

**Comment by moritzWa** [comment]
```
- macOS version: 12.3.1 (21E258)
- Mac model: MacBook Pro (14-inch, 2021)
- MonitorControl version: latest (updated minutes ago)
- Monitor(s): lg ultrafine 27MD5KL (5k)
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Well, if hardware control is not enabled then it is a software issue. Is syncing enabled?

**Comment by ivnhysfryr** [comment]
> Well, if hardware control is not enabled then it is a software issue. Is syncing enabled?

It was, but yesterday I disabled it before reporting the bug.

**Comment by waydabber** [comment]
The issue might be related to https://github.com/MonitorControl/MonitorControl/issues/1028 ?

**Comment by ivanhoyosfreyre** [comment]
> The issue might be related to #1028 ?

I don't see how. None of those symptoms are present on my case.

**Comment by ivnhysfryr** [comment]
Any other clues? 🙏

**Comment by ivnhysfryr** [comment]
I'm still experiencing this bug everyday, still haven't figured out what causes it. Here's a video showing the behavior. When I wake up my computer, it always resets to full brightness and goes back to the desired setting with one single press of the brightness keys. Also, you can see how before switching screens, the brightness resets itself again. This happens very randomly in regards to times or actions.

https://user-images.githubusercontent.com/106789008/226714846-bf8794b9-eb20-4e1a-ac8d-31e8c9b94717.mov

**Comment by ivnhysfryr** [comment]
So, what makes me think my display isn't the issue is that I also have MonitorControl on a Macbook Pro and when connected to this same display, I've never encountered this issue.

I had the "Upon startup or wake" settings on "Assume last saved settings are valid". I changed it to "Apply last saved values to the display" and "Attempt to read display settings" but none did the trick.

I uninstalled MonitorControl and installed BetterDisplay. The issue still happens, but way less than with MonitorControl. Up until now, it only happens maybe once after a couple of seconds of logging in to my user account.

https://user-images.githubusercontent.com/106789008/227019977-5566c56c-ccd5-4f81-818d-0eb710d20900.mov

**Comment by ivnhysfryr** [comment]
Now I finally got a clue from the app. This appeared after I unplugged my router and the computer disconnected from wifi. After reconnecting, it happened again.
![Screenshot 2023-03-22 at 14 15 56](https://user-images.githubusercontent.com/106789008/227028138-1f20edb7-f921-498b-a3b2-1219d47a2646.jpg)
