### ISSUE TITLE
MonitorControl crashes with a trace trap message when mac comes out of monitor sleep

### ISSUE THREAD

**Issue by waydabber** [MonitorControl/MonitorControl#1065]
### Discussed in https://github.com/MonitorControl/MonitorControl/discussions/1063

<div type='discussions-op-text'>

<sup>Originally posted by **ivahos** June  3, 2022</sup>
Hi
I have discovered a bug when running monitorcontrol on my mac studio. Sometimes the mac uses a longer time than normal to detect the monitor after a monitor sleep, when this happens MonitorControl often crashes. 
ivar@Jumbo MacOS % ./MonitorControl
zsh: trace trap  ./MonitorControl

I have created a workaround by starting the app from a shell script that keeps relaunching it whenever it quits.
[MonitorControl-2022-06-03-111213.ips.zip](https://github.com/MonitorControl/MonitorControl/files/8828935/MonitorControl-2022-06-03-111213.ips.zip)
I am attaching the crash log from the console app. 
</div>

**Comment by balintant** [comment]
Experiencing this too. Downgrade to 4.0.x works.
(M1 Pro, Ventura RC)
