### ISSUE TITLE
Volume control not working on Macbook Pro M1 with LG 27UD88 monitor

### ISSUE THREAD

**Issue by Paveldeg** [MonitorControl/MonitorControl#1069]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Macbook Pro M1 connected via HDMI to LG 27UD88 - voume control does nothing.

### Steps to reproduce

1. Go to MonitorControl menu.
2. Move volume control slider.
3. Observe no effect.

### Expected behavior

Volume control actually controls sound volume.

### Environment Information (please complete the following information)

```markdown
- macOS version: Monterey 12.4
- Mac model: Apple M1 Pro 
- MonitorControl version: latest
- Monitor(s): LG 27UD88
- Apple Silicon/M1 (yes or no): yes
```

**Comment by the0neyouseek** [comment]
Hi @Paveldeg 
HDMI on M1 mac does not allow DDC control, so you are currently using **software** mode (brightness changes only after 50% if ddc is shown as enabled in preferences) which does not allow volume control.
Please see this issue for more infos on the problem : https://github.com/MonitorControl/MonitorControl/discussions/750

**Comment by CzBiX** [comment]
hi @the0neyouseek , you misunderstood that.
he was talking about the Macbook, not the Mac mini you mentioned.
I have the same type of issue, and although I have the different monitor model than his, I can't control the volume either, only the brightness(via hardware control).

**Comment by the0neyouseek** [comment]
Hi @CzBiX 
No I didn't misunderstood, he was talking about an M1 MacBook Pro. This issue affect all Apple Silicon devices so far, including Mac minis and MacBooks. 
If you're using the HDMI port, DDC control is blocked and MonitorControl uses software dimming thus is not able to control the monitor volume

**Comment by CzBiX** [comment]
@the0neyouseek Sorry, I didn't look closely enough. The owner is connected to the HDMI port.
My issue is not the same to this thread.
