### ISSUE TITLE
Dell Display Detected as Apple Hardware

### ISSUE THREAD

**Issue by jjeising** [MonitorControl/MonitorControl#1076]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

A Dell U3415W display previously successfully controlled by DDC is detected as "Control method: Hardware (Apple)" after another monitor changed. As the control method is not correctly detected, controlling the brightness of the display does not work.

Controlling the Dell display with `m1ddc` works as expected.

### Expected behavior

Dell U3415W display can be controlled via DDC as before.

### Anything else?

![dell](https://user-images.githubusercontent.com/40333/173469814-cd4bc1c4-6a1f-434e-98d9-72f58ba979de.png)

```
❯ ./m1ddc display list
1 - StudioDisplay (…)
2 - DELL U3415W (…)
❯ ./m1ddc display 2 set luminance 50
```
These work fine.

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.4
- Mac model: MacBook Pro (16-inch, 2021)
- MonitorControl version: 4.1.0
- Monitor(s): internal, Dell U3415W, Apple Studio Display
- Monitor Cable(s)/Connection(s): 
  - MacBook Pro → OWC Thunderbolt 3 Dock → MiniDP/DP → Dell U3415W
  - MacBook Pro → OWC Thunderbolt 3 Dock → Thunderbolt 3 → Apple Studio Display
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Hmm. This might be because the display identifiers get messed up somehow maybe? You should try resetting the app preferences. Also you can try [BetterDisplay](https://github.com/waydabber/BetterDummy/releases) and see if that works since that is a full rewrite from ground-up and uses a different method for identifying displays.

Let me know if any of these help! Thank you!

**Comment by jjeising** [comment]
> You should try resetting the app preferences.

Using "Reset Preferences" or deleting the apps plist does not seem to change anything.

> Also you can try [BetterDisplay](https://github.com/waydabber/BetterDummy/releases) and see if that works since that is a full rewrite from ground-up and uses a different method for identifying displays.

It seems to have the same issue. Regardless if _Use alternative method to identify displays_ is enabled or not. _Enable advanced display control_ is enabled, _Enable hardware brightness control_ is also enabled. Brightness does not change.

**Comment by waydabber** [comment]
In BetterDisplay, please click on both displays' name and attach as a screenshot the details so I can understnd better how the app sees the display. 

<img width="842" alt="Screen Shot 2022-06-15 at 7 22 00" src="https://user-images.githubusercontent.com/37590873/173743864-0e0c6e7b-b2b4-4bd8-a77a-953b6f2bedaf.png">

**Comment by jjeising** [comment]
![display2](https://user-images.githubusercontent.com/40333/173920535-2f3de119-a390-4888-94de-4333ebc692d2.png)

![display1](https://user-images.githubusercontent.com/40333/173920553-7b4c38d9-9bf1-43c7-a29e-c096abb9c6c2.png)

**Comment by waydabber** [comment]
It is either the OS reports the display as it can change its brightness (`DisplayServicesCanChangeBrightness(CGDirectDisplayID display)` returns true) or `DisplayServicesGetBrightness(displayID, &brightness)` returns with a valid brightness (which means the OS can read the display's brightness. This is why it is detected as an Apple external display by both apps.

Does this happen if you directly connect the displays without the dock?

**Comment by jjeising** [comment]
> Does this happen if you directly connect the displays without the dock?

Yes this also happened if the displays were directly connected. There was also a very strange issue where video content on the Dell display was rotated 90° (as is the Studio Display) in some applications (e.g Safari, looks like some kind of video acceleration mode). Seems to be an incompatibility with the Studio Display on Apples side, I will also report a Feedback.

I think a possible fix for MonitorControl would be a _Force DDC_ option.

**Comment by waydabber** [comment]
What happens if only the Dell display is connected? Does the issue happen then as well? It is super interesting that the OS reports as controllable. There does not seem to be a confusion in identifiers though.

There should be a setting to treat the display as a non-Apple display.
