### ISSUE TITLE
Brightness works great, but I Still can't control the volume from my monitor 

### ISSUE THREAD

**Issue by ulisesyaniz** [MonitorControl/MonitorControl#110]
Brightness works great, but I Still can't control the volume from my monitor 

Please help me fix this issue.

**Comment by ulisesyaniz** [comment]
External Monitor: BENQ PD3220U
Connection: USB-C / Thunderbolt 3
Device: 2019 Macbook Pro touchBar

**Comment by womeimingzi11** [comment]
First, I suggest you can try to install this https://github.com/kfix/ddcctl

Then, run 
> ddcctl -O -d 1 -v 60 

This command may be different for you, which the -d 1 means the first external screen of my MBP, and -v 60 means put the volume to 60%

If it doesn't work on your Monitor, it may be the issue of your monitor's firmware, I don't think MonitorControl can handle this.

**Comment by leondeng** [comment]
Same issue here.
MBP 15 Mid 2015
macOS 10.14.6
DELL U3415W via min DP to DP link

**Comment by JoniVR** [comment]
@leondeng @ulisesyaniz Please try @womeimingzi11 's suggestion and paste your output here.

**Comment by mathieupost** [comment]
Found out that controlling the volume for my Dell U3415W works, but it just does not have effect when I've got a 3.5mm plugged into the monitor for some reason...

**Comment by Spirotot** [comment]
@mathieupost You're saying it works for you, 100% as expected, _without_ 3.5mm plugged into your monitor?

I haven't tried _with_ 3.5mm, but I've noticed that _without_, the U3415w's volume value is changed. However, it does not go into effect until I either:
* Restart the display (by toggling via the monitor's power button, or otherwise putting it to sleep/waking it back up).
* Manually adjust the volume settings via the OSD (i.e. increasing or decreasing the monitor's volume value by 1).

**Comment by r3ppy** [comment]
Same here Dell U2719D with 3.5 mm jack. Volume controls not working.

**Comment by JoniVR** [comment]
> Found out that controlling the volume for my Dell U3415W works, but it just does not have effect when I've got a 3.5mm plugged into the monitor for some reason...


@mathieupost @r3ppy Make sure your display is set as audio output device. If the audio output device is set to anything other than the display you want to control it won't work. This is to make sure that you can still change volume when using headphones and other devices.

**Comment by gmelikov** [comment]
Same here, HP z27, connected via usb type-c

```
$ ./ddcctl -d 1 -v 30
D: NSScreen #59592011 (3008x1692 0°) HiDPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.name: HP Z27
I: got edid.serial: CN49020051
D: action: v: 30
D: setting VCP control #98 => 30
```

Doesn't change anything.

**Comment by JoniVR** [comment]
@gmelikov Unfortunately not every monitor supports ddc perfectly.. there's really nothing we can do about it sometimes.. what you can try (and what does sometimes help for people) is trying another connecter (displayport usually has the most success), but chances are it's just a bad ddc implementation of the manufacturer.

**Comment by JoniVR** [comment]
For anyone else running into issues, see the troubleshooting wiki:
https://github.com/the0neyouseek/MonitorControl/wiki/Monitor-Troubleshooting

Regarding the 3.5mm issue, can you provide some more info? What version MonitorControl, macOS, ...
Also, it would be really helpful if someone with the issue could run the project in Xcode and post the debug output here.

**Comment by r3ppy** [comment]
Regarding the 3.5 mm jack. The 3.5 jack is plugged into the audio output of the monitor (DELL U2719D)  rooted to a set of speakers. Monitor Control is on version 1.7.1 (Build 574) on MacOS Catalina 10.15.4 (19E266). Furthermore, the brightness works fine. However, volume controls do not actually change the volume that the monitor is outputting through the speakers.

Giovanni Telussa

**Comment by sonotley** [comment]
Same issue for me. Mac OS Mojave, Mac Mini 2012, connected via mini-DP to Dell U2715H. The volumn control is re-enabled but has no effect. ddcctl has no effect either, the volume remains at 98 even after trying to change.
`D: NSScreen #724850640 (2560x1440 0°) 109.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: GH85D7CN0KNS
I: got edid.name: DELL U2715H
D: action: v: 20
D: setting VCP control #98 => 20`

**Comment by snooz3r** [comment]
> External Monitor: BENQ PD3220U
> Connection: USB-C / Thunderbolt 3
> Device: 2019 Macbook Pro touchBar

I have the same issue because I have the same exact setup. Were you able to find a solution?

**Comment by r3ppy** [comment]
Software-wise, no. Added a volume control knob in between monitors and speaker: fostex pc-1.

**Comment by snooz3r** [comment]
> Software-wise, no. Added a volume control knob in between monitors and speaker: fostex pc-1.
> […](#)
> Op 9 mei 2020 om 00:49 heeft Rico Lajom ***@***.***> het volgende geschreven: ﻿ External Monitor: BENQ PD3220U Connection: USB-C / Thunderbolt 3 Device: 2019 Macbook Pro touchBar I have the same issue because I have the same exact setup. Were you able to find a solution? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

I played around with this solution (Soundflower) for the volume control and it works! [https://www.macrumors.com/how-to/use-mac-volume-keys-adjust-monitor-audio/]

I use the Monitor Display to only control the brightness. Hope the Soundflower helps. ***Also note to change the knob set to 100 so when you control it through your Mac, it's not too quiet and will have a better volume range.

**Comment by kingo132** [comment]
> @mathieupost You're saying it works for you, 100% as expected, _without_ 3.5mm plugged into your monitor?
> 
> I haven't tried _with_ 3.5mm, but I've noticed that _without_, the U3415w's volume value is changed. However, it does not go into effect until I either:
> 
> * Restart the display (by toggling via the monitor's power button, or otherwise putting it to sleep/waking it back up).
> * Manually adjust the volume settings via the OSD (i.e. increasing or decreasing the monitor's volume value by 1).

I have the same issue with my U3415w. ddcctl successfully changed the volume, but it won't take effect until I adjust the volume via OSD by 1 value. Maybe this is the DDC implementation problem of DELL. Are there any resolutions to workaround?

**Comment by waydabber** [comment]
Unfortunatelly this issue can't be resolved as this is a display firmware specific problem. I'll close this issue for now but let us know if we can help in any way or submit a specific issue using the new issue templates. Thank you!

**Comment by candasm** [comment]
Did anyone tried to update their monitors firmware version? As I saw on dell's website there was a firmware update released on 2017.
