### ISSUE TITLE
F1/F2 not working with Fn key

### ISSUE THREAD

**Issue by Simboiss** [MonitorControl/MonitorControl#1102]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

When holding the Fn key while presing the F1/F2 keys, nothing happens.

### Steps to reproduce

Hold Fn key, press F1 or F2.

### Expected behavior

Expected behavior is to have the regular F1/F2 key presses change the rightness of the monitor.
Holding the Fn key while pressing F1/F2 should produce the normal effect in the frontmost application.

### Anything else?

Keyboard is Apple A1243 extended French Canadian CSA, wired.
The Fn key is under the F13 key.

Other F keys do work as expected when holding the Fn key.

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.4 Monterey
- Mac model: Mac Studio (2022)
- MonitorControl version: 4.1.0 build 7034
- Monitor(s): LG 27UP650
- Apple Silicon/M1 (yes or no): yes, M1 Max
```

**Comment by waydabber** [comment]
F1/F2 and Brightness Up/Down generate two separate events and handled differently. If somehow one affects the other, something specific is not right. Do you maybe use any other app like Karabiner, Hammerspoon etc. that taps into the keyboard?

**Comment by estebanavv** [comment]
I've been a long time MonitorControl user and this issue is happening since I upgraded to v4.10, using standard Keyboard the brightness doesn't work but for audio works as it used to. UI works.

```~ sw_vers
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79

MonitorControl:
      Version: 4.1.0
      Obtained from: Identified Developer
      Last Modified: 6/18/22, 10:00 AM
      Kind: Universal
      Signed by: Developer ID Application: Joni Van Roost (CYC8C8R4K9), Developer ID Certification Authority, Apple Root CA

~ system_profiler SPHardwareDataType
Hardware:
Model Name: iMac Pro
      Model Identifier: iMacPro1,1
      Processor Name: Quad-Core Intel Core i7
      Processor Speed: 4 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 8 MB
      Hyper-Threading Technology: Enabled
      Memory: 32 GB
      System Firmware Version: 1731.100.130.0.0
      OS Loader Version: 540.120.3~6

~ system_profiler SPDisplaysDataType
Graphics/Displays:

    AMD Radeon RX 580:

      Chipset Model: AMD Radeon RX 580
      Type: GPU
      Bus: PCIe
      PCIe Lane Width: x16
      VRAM (Total): 8 GB
      Vendor: AMD (0x1002)
      Device ID: 0x67df
      Revision ID: 0x00e7
      Metal Family: Supported, Metal GPUFamily macOS 2
      Displays:
        DELL P2319H:
          Resolution: 1080 x 1920
          UI Looks like: 1080 x 1920 @ 60.00Hz
          Framebuffer Depth: 30-Bit Color (ARGB2101010)
          Display Serial Number: 56N5LK3     
          Mirror: Off
          Online: Yes
          Rotation: 90
          Connection Type: Thunderbolt/DisplayPort
        DELL U3818DW:
          Resolution: 3840 x 1600 (Ultra-wide 4K)
          UI Looks like: 3840 x 1600 @ 60.00Hz
          Framebuffer Depth: 30-Bit Color (ARGB2101010)
          Display Serial Number: 97F8P76804RL
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Rotation: Supported
          Television: Yes

**Comment by skoushan** [comment]
I have the same issue. When MonitorControl is running (even if keyboard shortcuts are disabled), Fn + F1 and Fn + F2 do nothing OS-wide.

**Comment by OleksandrKvl** [comment]
@waydabber just for the record. On my laptop, I control brightness via Fn+F1/2 keys and right after the installation MonitorControl couldn't do it for my Dell display (neither could its native DDPM though it had corresponding toggle ON). Solution was to manually give it `Accessibility` permission in system settings and (it's important) to restart the app. Maybe it should ask for them during installation or have a note about it in the `Keyboard` menu.
