### ISSUE TITLE
Disable MacBook built-in display

### ISSUE THREAD

**Issue by Tabiskabis** [MonitorControl/MonitorControl#1105]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

When working with external monitors, I still prefer having my MacBook's lid open, as this allows for improved cooling and Wi-Fi reception. Opening the lid activates the built-in display, which is physically too small and too distant to be useable. I'd always have to reconfigure the screen's virtual position to somewhere hard reachable by mouse, but it still makes for difficulties such as a corner being unavailable. Plus the additional active screen consumes more CPU/GPU.

### Describe the solution you'd like

I'd love a simple way to disable the internal display when an external monitor is connected (while to lid is open, of course, ).

### Describe alternatives you've considered

Some nvram manipulation almost gets to what I want, but it requires rebooting and disables the display permanently.  
I've tried DisableMonitor, but it just blacks out all screens.  
Also tried Lunar, but the claimed black out feature is not supported in the outdated OS X Mojave version.  
My only alternative is to physically place a small magenet on the MacBook's body, to trick it into sensing a closed lid.

**Comment by waydabber** [comment]
Hi there - unfortunately there is no known simple way to disable the built-in display. What Lunar does is that it turns down the brightness to zero and hides the display by making it a mirror target of some other display. This kinda works, but not really the best solution and has side-effects. This feature probably won't be added to MonitorControl, but since it is a popular request, I plan to add it to [BetterDisplay](https://github.com/waydabber/BetterDisplay#readme), however that does not support Mojave as well. :(

**Comment by waydabber** [comment]
Hmm. There is a feature request for this already https://github.com/MonitorControl/MonitorControl/issues/907 - so I'll close this one and reference it there instead. :)

**Comment by andr2k** [comment]
SwitchResX somehow can disable any display

**Comment by waydabber** [comment]
That comment is very outdated. I implemented disconnect option for both internal and external displays in [BetterDisplay](https://github.com/waydabber/BetterDisplay#readme) for Apple Silicon (afterwards SwitchResX implemented it too). Works for Intel too albeit not as nicely with Apple Silicon.

I won't add this feature to MonitorControl I am afraid - if you need this, I advise you to switch to BetterDisplay.

**Comment by Tabiskabis** [comment]
Спасибоньки Andriy. Unfortunately, this one too does not actually disable the screen. Background illumination stays powered on. In that respect, a pony magnet beats all software, so far :)

**Comment by waydabber** [comment]
Hi, what Mac do you have? On Apple Silicon the screen is actually put to sleep. On Intel this is not possible unfortunately, but the app can turn off the backlight via DDC if the display supports it or should turn the built-in screen's brightness to zero.

**Comment by Tabiskabis** [comment]
A 2015 MacBook Pro (Intel ofc) running Mojave. But don't worry, I've long learned to appreciate my trusty magnet ;-)

**Comment by waydabber** [comment]
Yeah, the magnet is the best. :)

**Comment by Achyut198** [comment]
https://github.com/Achyut198/LumaPilot?tab=readme-ov-file

follow this repo , it has all required features that you are looking for
