### ISSUE TITLE
Feature Request: Configurable Maximum Monitor Volume Threshold

### ISSUE THREAD

**Issue by odenak** [MonitorControl/MonitorControl#111]
My monitor LG 43UD79-B volume can get really loud above 30.  It would be nice if a maximum monitor volume can be configured in the app.  So for example, if I set a max of 30, the Mac volume control between 0-100 will map to 0-30 on the monitor.

**Comment by inf0dr0id** [comment]
That would be really great. The LG 38UC99-W has the same problem.

**Comment by waydabber** [comment]
This will be taken care here:

https://github.com/MonitorControl/MonitorControl/issues/310
