### ISSUE TITLE
Safari Keyboard Shortcut Issue

### ISSUE THREAD

**Issue by MaisonPatchouli** [MonitorControl/MonitorControl#1117]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

In Safari, "command 0” shortcut for scaling change is not working when monitor control is turn on. 

Upon using the app shortcutdetective to test, monitor control is receiving keyboard shortcuts. And turning monitor control off resolves the issue.

### Steps to reproduce

Open any webpage on Safari, use "command +” or "command -” to zoom in or out the page. Then use "command 0” to set to default 100% scaling.

### Expected behavior

Press "command 0” would roll back to the default 100% scaling.

### Anything else?

For Anyone who also runs into this, here are a few workarounds.
— Directly click the menu item in Safari, “View” -> “Actual Size”
— Directly click preferece icon in the toolbar (gear icon) and select 100% in page zoom
— In System Preferences, set up a new keyboard shortcut for “Actual Size” in the “App Shortcuts” in ” Keyboard" under “Shortcuts.” Apple has instructions on this one.

### Environment Information (please complete the following information)

```markdown
- macOS version: Monterey 12.4
- Mac model: MacBook Air M1
- MonitorControl version:4.1.0
- Monitor(s): LG 27UN850-W
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
I cannot seem to reproduce this one. Are sure there is no custom shortcut defined for Command+0 somehow? Are you using native keys for control?

**Comment by macbookproiceland** [comment]
Yah, I checked with shortcutdetective (it shows monitor control is receive the shortcuts when I use command+0 in safari) and I also turned off all the programs and tested one by one. Only upon closing monitor control, the shortcut command+0 would then work.
It is not pressing issue though.

**Comment by MaisonPatchouli** [comment]
**With a fresh installation, it is fixed.** 

It was showing problems before with the autoupdated latest version (Version 4.2.0 Build 7048) but with a reinstallation it was fixed. Perhaps it was the helper not being installed correctly before, but that is just speculation.
