### ISSUE TITLE
Multiple screens do not adjust exactly at the same increments

### ISSUE THREAD

**Issue by bmrs** [MonitorControl/MonitorControl#112]
Hi,

First, thanks a lot for this app which is far better all the other I have tried. My configuration is: same two monitors (Iiyama ProLite X2283HS) plugged via DP to a Radeon RX 580 Sapphire on a 2012-Mac Pro.

MonitorControl is set to adjust both screens at the same time when using the keys. However, when going down from maximum in a full screen app, one of the monitor decreases from two increments at the same time, whereas the other one decreases normally from one increment at each key press.

Minor but curious bug which only appears when the monitor uses full screen app.

![Capture d’écran 2019-08-16 à 17 51 20 (2)](https://user-images.githubusercontent.com/17748518/63180483-ac2b1f00-c04e-11e9-97b7-4a5ded0f1539.png)
![Capture d’écran 2019-08-16 à 17 51 20](https://user-images.githubusercontent.com/17748518/63180484-ac2b1f00-c04e-11e9-89a8-84bd667a8d85.png)

Regards.

**Comment by JoniVR** [comment]
Strange, are they connected using the same cables (both DP) too? And do the actual display brightness values differ when you check them through the displays OSD?

**Comment by phao5814** [comment]
I have a similar problem. And yes both monitors are connected using the same HDMI cables to my graphics card.

**Comment by waydabber** [comment]
As this seems to be a rather old issue, I'll close this one. If this issue persiests with recent releases, please let us know! Thanks!
