### ISSUE TITLE
Create an intelligent algorithm for saving identified monitors to decrease the time for searching

### ISSUE THREAD

**Issue by MHX792** [MonitorControl/MonitorControl#113]
One of my monitors takes way too long to be identified, while others get identified really quick. It would be great, if you could maintain an array of already identified monitors. The next time a monitor gets attached, first search this array. If unsuccessful, search the whole list.

Thanks

**Comment by JoniVR** [comment]
It's a nice idea but I'm not sure if that could work, in the meantime, once the advanced prefs panel is released, I'd recommend trying the `longerDelay` option for that specific display, that might fix it taking so long to identify.
