### ISSUE TITLE
Option to exclude a monitor from "Sync brightness"

### ISSUE THREAD

**Issue by apgiorgi** [MonitorControl/MonitorControl#1139]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

I use an iPad as a Sidecar display (Virtual Display), and its brightness can only be controlled with shade (SW). Sometimes I get it with very low brightness as it tries to stay in sync with the built-in sensor, etc.

I've tried deselecting it on the advanced settings, but it keeps being affected when "Sync brightness changes..." is active.

Would it be possible to remove individual monitors from the sync?

### Describe the solution you'd like

A checkbox on Display's advanced settings to include/exclude from brightness sync

### Describe alternatives you've considered

Disabling "Sync Brightness..."

**Comment by waydabber** [comment]
Hmm. This is a reasonable request/good idea.

**Comment by riobard** [comment]
@waydabber Is there a bug somewhere in the Displays preference panel? I tried to deselect Brightness/Available checkbox for the Sidecar Display, and it worked alright. Then after a while, the Sidecar Display got software dimmed again! 

The option to completely exclude Sidecar Displays from MonitorControl would be nice.

**Comment by riobard** [comment]
@waydabber I _think_ the reason the pref panel does not work reliability is because the identifier of the Sidecar Display changes from time to time (e.g. after wakeup from sleep). Hope it would help for you to debug this issue.

<img width="375" alt="image" src="https://user-images.githubusercontent.com/22984/191017392-3398bca7-e363-4592-8ea4-2e7b7fc0078c.png">

**Comment by riobard** [comment]
Alright, the issue is more complicated. The Sidecar Display got software dimmed even when its identifier doesn't change and its brightness control disabled from MC.

**Comment by waydabber** [comment]
Hi @riobard - for virtual displays that (always changing) identifier should not interfere with display identification. There might be a bug with the brightness control being disabled and the Sidecar is still affected by the sync.

**Comment by riobard** [comment]
@waydabber I see. Please let me know if there's anything I can do to pinpoint the bug. :)
