### ISSUE TITLE
MonitorControl quit when pc goes standby or close lids or disconnect external monitor

### ISSUE THREAD

**Issue by FrancoTampieri** [MonitorControl/MonitorControl#1144]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

When my MacBook Air M1 goes in standby, or close lid or disconnect the external monitor the app quit

### Steps to reproduce

close lid and wait some minute to make Mac goes standby. Wakeup Mac and the monitor control.app is quitted

### Expected behavior

remain in background with icon in the top

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.5 Monterey
- Mac model: Mackbook Air M1 2020
- MonitorControl version: 4.1.0 build 7034
- Monitor(s): Integrated, and LG 34WP75C
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
This seems to be a bug. If you have a crash log, you might want to attach it. Thank you!

**Comment by FrancoTampieri** [comment]
Hi I find this, hope help
[MonitorControl-2022-08-26-163856.ips.txt](https://github.com/MonitorControl/MonitorControl/files/9435219/MonitorControl-2022-08-26-163856.ips.txt)
s

**Comment by boninj** [comment]
Hello,

I've got the same problem on my Here:
- macOS vesion: 12.5.1 Monterey
- Mac model: Mac Studio
- MonitorControl version: 4.1.0 Build 7034
- Monitor(s): 2 AOC U3277PWQU (HDMI on Mac Studio + Displayport on [CalDigit USB-C Dock](https://www.caldigit.com/usb-c-dock/)
- Apple Silicon/M1 (yes or no): yes (M1 Max)

Here is the Crash Diagnostic Report :
[MonitorControl-2022-08-29-103044.ips.txt](https://github.com/MonitorControl/MonitorControl/files/9443019/MonitorControl-2022-08-29-103044.ips.txt)

**Comment by macsnider** [comment]
Hi,

got the same problem on my M2 MBA

- macOS 12.6 Monterey
- MacBook Air M2 2022
- MonitorControl version: 4.1.0 Build 7034
- external Monitor: Samsung LU28R55 via DisplayPort cable

here is my crashlog [MonitorControl-2022-09-22-123814.ips.txt](https://github.com/MonitorControl/MonitorControl/files/9624932/MonitorControl-2022-09-22-123814.ips.txt)

**Comment by vincenty1ung** [comment]
Hi,

got the same problem on my M1 MBA

macOS 12.6.1 Monterey
MacBook Pro  M1 Max 2021 14 
MonitorControl version: 4.1.0 Build 7034
external Monitor: Philips 279m1rev via DisplayPort1.4 cable
-----------
Full Report
-----------

{"app_name":"MonitorControl","timestamp":"2022-10-29 16:11:30.00 +0800","app_version":"4.1.0","slice_uuid":"a857b9bd-10a7-3197-84b9-221022fe0b4d","build_version":"7034","platform":1,"bundleID":"me.guillaumeb.MonitorControl","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6.1 (21G217)","incident_id":"A3B1D084-ABB6-41C2-B547-22537B50957A","name":"MonitorControl"}
{
  "uptime" : 2600,
  "procLaunch" : "2022-10-29 16:00:21.7089 +0800",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,4",
  "procStartAbsTime" : 46700402343,
  "coalitionID" : 1491,
  "osVersion" : {
    "train" : "macOS 12.6.1",
    "build" : "21G217",
    "releaseType" : "User"
  },
  "captureTime" : "2022-10-29 16:11:28.8751 +0800",
  "incident" : "A3B1D084-ABB6-41C2-B547-22537B50957A",
  "bug_type" : "309",
  "pid" : 1947,
  "procExitAbsTime" : 62711812649,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "MonitorControl",
  "procPath" : "\/Applications\/MonitorControl.app\/Contents\/MacOS\/MonitorControl",
  "bundleInfo" : {"CFBundleShortVersionString":"4.1.0","CFBundleVersion":"7034","CFBundleIdentifier":"me.guillaumeb.MonitorControl"},
  "storeInfo" : {"deviceIdentifierForVendor":"323B92B6-864E-5DB7-9614-1F4333DF10B7","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "me.guillaumeb.MonitorControl",
  "crashReporterKey" : "0FB825A9-6D27-383A-0F15-78B77580BAE6",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000104b51f68","rawCodes":[1,4373946216],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":1947},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":11},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":43003,"threadState":{"x":[{"value":0},{"value":259},{"value":2},{"value":1},{"value":115},{"value":115},{"value":115},{"value":0},{"value":0},{"value":0},{"value":1},{"value":2147483646},{"value":1},{"value":2147483646},{"value":3538401280},{"value":247},{"value":6538449820,"symbolLocation":0,"symbol":"_os_nospin_lock_unlock"},{"value":8052957408},{"value":0},{"value":0},{"value":1},{"value":4},{"value":1},{"value":0},{"value":105553169454288},{"value":0},{"value":1},{"value":1},{"value":105553130323968}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6288010246601645556},"cpsr":{"value":1610616832},"fp":{"value":6092988032},"sp":{"value":6092987888},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":4373946216,"matchesCrashFrame":1},"far":{"value":5595366408}},"queue":"com.apple.main-thread","frames":[{"imageOffset":57192,"imageIndex":0},{"imageOffset":56820,"imageIndex":0},{"imageOffset":320716,"imageIndex":0},{"imageOffset":320436,"imageIndex":0},{"imageOffset":324452,"imageIndex":0},{"imageOffset":338644,"imageIndex":0},{"imageOffset":314696,"imageIndex":0},{"imageOffset":16820,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":1},{"imageOffset":30320,"symbol":"_dispatch_continuation_pop","symbolLocation":500,"imageIndex":1},{"imageOffset":108768,"symbol":"_dispatch_source_invoke","symbolLocation":1596,"imageIndex":1},{"imageOffset":75296,"symbol":"_dispatch_main_queue_drain","symbolLocation":756,"imageIndex":1},{"imageOffset":74524,"symbol":"_dispatch_main_queue_callback_4CF","symbolLocation":44,"imageIndex":1},{"imageOffset":813464,"symbol":"__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__","symbolLocation":16,"imageIndex":2},{"imageOffset":539656,"symbol":"__CFRunLoopRun","symbolLocation":2532,"imageIndex":2},{"imageOffset":535172,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":2},{"imageOffset":205624,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":3},{"imageOffset":204980,"symbol":"ReceiveNextEventCommon","symbolLocation":564,"imageIndex":3},{"imageOffset":204392,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":72,"imageIndex":3},{"imageOffset":267548,"symbol":"_DPSNextEvent","symbolLocation":860,"imageIndex":4},{"imageOffset":261652,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":1328,"imageIndex":4},{"imageOffset":204768,"symbol":"-[NSApplication run]","symbolLocation":596,"imageIndex":4},{"imageOffset":23272,"imageIndex":0},{"imageOffset":6868,"symbol":"autoreleasepool<A>(invoking:)","symbolLocation":64,"imageIndex":5},{"imageOffset":23064,"imageIndex":0},{"imageOffset":20620,"symbol":"start","symbolLocation":520,"imageIndex":6}]},{"id":43020,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":43032,"name":"AMCP Logging Spool","frames":[{"imageOffset":6380,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":8},{"imageOffset":125484,"symbol":"caulk::mach::semaphore::wait_or_error()","symbolLocation":28,"imageIndex":9},{"imageOffset":10156,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":56,"imageIndex":9},{"imageOffset":9164,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*)","symbolLocation":96,"imageIndex":9},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":43063,"name":"com.apple.NSEventThread","frames":[{"imageOffset":6320,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":8},{"imageOffset":7456,"symbol":"mach_msg","symbolLocation":76,"imageIndex":8},{"imageOffset":545296,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":2},{"imageOffset":538304,"symbol":"__CFRunLoopRun","symbolLocation":1180,"imageIndex":2},{"imageOffset":535172,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":2},{"imageOffset":1761536,"symbol":"_NSEventThread","symbolLocation":196,"imageIndex":4},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":50516,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":50625,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":50815,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4373889024,
    "CFBundleShortVersionString" : "4.1.0",
    "CFBundleIdentifier" : "me.guillaumeb.MonitorControl",
    "size" : 901120,
    "uuid" : "a857b9bd-10a7-3197-84b9-221022fe0b4d",
    "path" : "\/Applications\/MonitorControl.app\/Contents\/MacOS\/MonitorControl",
    "name" : "MonitorControl",
    "CFBundleVersion" : "7034"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6536495104,
    "size" : 290816,
    "uuid" : "b3c7a004-1069-3171-b630-2c386a8b399c",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6538657792,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5533696,
    "uuid" : "fc3c193d-0cdb-3569-9f0e-bd2507ca1dbb",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1866"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6686064640,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3358720,
    "uuid" : "aaf900bd-bfb6-3af0-a8d3-e24bbe1d57f5",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6584438784,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15437824,
    "uuid" : "5ece5db5-a167-3ab1-a1cf-af442beecea6",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.60.148"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6886629376,
    "size" : 12288,
    "uuid" : "26a1bf11-c23f-3aab-aad0-0b83471709e6",
    "path" : "\/usr\/lib\/swift\/libswiftObjectiveC.dylib",
    "name" : "libswiftObjectiveC.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4379115520,
    "size" : 393216,
    "uuid" : "24d09537-e51b-350e-b59e-181c9d94d291",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6538334208,
    "size" : 53248,
    "uuid" : "63c4eef9-69a5-38b1-996e-8d31b66a051d",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6538104832,
    "size" : 229376,
    "uuid" : "dbf55fdd-2b9b-3701-93b6-7a3ce359bd0e",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6683439104,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.audio.caulk",
    "size" : 159744,
    "uuid" : "fbaaa1ec-abbe-3c0d-a491-0dc66ee9d8ce",
    "path" : "\/System\/Library\/PrivateFrameworks\/caulk.framework\/Versions\/A\/caulk",
    "name" : "caulk"
  }
],
  "sharedCache" : {
  "base" : 6535036928,
  "size" : 3144728576,
  "uuid" : "7cf73f63-0640-33ec-8444-138d9834ecb5"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=1.8G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.8G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               896K        7 \nActivity Tracing                   256K        1 \nCG image                           960K       38 \nCG raster data                      80K        2 \nColorSync                          608K       27 \nCoreAnimation                     26.2M      263 \nCoreGraphics                        48K        3 \nCoreUI image data                 4512K       33 \nFoundation                          16K        1 \nImage IO                            16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           326.3M       61 \nMALLOC guard page                  192K       10 \nMALLOC_MEDIUM (reserved)           1.1G        9         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.1M        7 \nStack                             11.2M        7 \nVM_ALLOCATE                        352K       11 \n__AUTH                            2665K      299 \n__AUTH_CONST                      20.5M      491 \n__CTF                               756        1 \n__DATA                            15.8M      481 \n__DATA_CONST                      17.5M      498 \n__DATA_DIRTY                      1809K      201 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       577.9M        5 \n__OBJC_CONST                      3337K      263 \n__OBJC_RO                         83.0M        1 \n__OBJC_RW                         3168K        1 \n__TEXT                           497.2M      515 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nmapped file                      457.5M       43 \nshared memory                      848K       13 \n===========                     =======  ======= \nTOTAL                              3.5G     3298 \nTOTAL, minus reserved VM space     2.1G     3298 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6112dda2fc54bc3389840642",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "631730a28520965d1cba0681"
      },
      "deploymentId" : 240000145
    },
    {
      "rolloutId" : "60f8ddccefea4203d95cbeef",
      "factorPackIds" : {

      },
      "deploymentId" : 240000021
    }
  ],
  "experiments" : [

  ]
}
}

**Comment by cbeible** [comment]
Refreshing this issue. MacBook Air M2, Ventura 13.5. App is closing whenever Mac goes to sleep.
