### ISSUE TITLE
BenQ BL2420PT weird problems

### ISSUE THREAD

**Issue by GroovyDrifter** [MonitorControl/MonitorControl#1179]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

BenQ BL2420PT volume  control not working using HDMI, Brightnes works but 60% bar is 100% brightness.
Same monitor, same computer, using a Thunderbolt 3 to Displayport cable all works perfect, volume works and the full scale of brightness is used.
Same monitor, other computer, using HDMI port, volume works perfect and brightness gets to 100% at 60% bar in app.

### Expected behavior

The expected behaviour is that this monitor with this software worked the same no matter the computer or port in that computer/monitor used.

### Anything else?

Previously I used this BenQ BL2420PT monitor with different computers but always via HDMI and Monitor Control never failed, even when used throug a KVM,  until I adquired a M1 Mac Mini.

I suspect the problem is in the HDMI output of the Mac Mini M1 (2020) that may be limited by design in some way. I can do further tests by request.

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.6 Monterey
- Mac model: Mac Mini (2020) M1
- MonitorControl version: v4.1.0
- Monitor(s): BenQ BL2420PT (two of them same behaviour)
- Monitor Cable(s)/Connection(s):HDMI & Thunderbolt-Displayport
- Apple Silicon/M1 (yes or no): yes
```

**Comment by the0neyouseek** [comment]
Hi @GroovyDrifter 
> I suspect the problem is in the HDMI output of the Mac Mini M1 (2020) that may be limited by design in some way

This exactly that. Unfortunately, on apple silicon macs, the HDMI port does not allow for DDC (hardware) control, you can disable hardware control by unchecking "Use Hardware control" in MonitorControl Preference or use a usb-c cable.

Have a nice day !
