### ISSUE TITLE
LG HDR 4K monitor Contrast-control slider stopped working (no change in hardware or MonitorControl.app)

### ISSUE THREAD

**Issue by johnnyutahh** [MonitorControl/MonitorControl#1182]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

LG HDR 4K monitor (LG 32UL500, full specs: https://i.imgur.com/uPQ2wFC.png; advanced settings: https://i.imgur.com/sj4ZV8X.png) Contrast-control slider stopped working after no other, apparent change in hardware or MonitorControl.app v4.1.0 app. Downgrade to MonitorControl.app v3.1.1 (Build 3096) has same symptom.

Everything worked prior to [2022-005 Catalina security-patch upgrade](https://support.apple.com/en-us/HT213343) and Safari 13.x --upgrade_to--> 15.x. Constrast-slider stopped working after. Brightness and Volume controls work. Everything on AOC U3277WB monitor (same MacBook) works.

Another user [reports](https://github.com/MonitorControl/MonitorControl/issues/1182#issuecomment-1253773608) similar behavior when upgrading macOS 12.5.4 -> 12.6 on a [LG 32BL95-U-W 4K monitor](https://github.com/MonitorControl/MonitorControl/issues/1182#issuecomment-1255127191).

### Expected behavior

Contrast-changing slider should work.

### Environment Information (please complete the following information)

MonitorControl.app v4.1.0

system version (edited 2022-09-21 after [2022-005 Catalina security-patch upgrade](https://support.apple.com/en-us/HT213343)):
```markdown
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2026
$
```

**Comment by waydabber** [comment]
- Does brightness and volume control work over DDC?
- Does contrast control with older versions of the app?

**Comment by johnnyutahh** [comment]
> * Does brightness and volume control work over DDC?

Yes.

> * Does contrast control with older versions of the app?

Unkown. I'll try this later.

I'll also test to see if the monitor's hardware control can adjust it's contrast.

(I'm away from the monitor right now)

**Comment by mjnohai** [comment]
This also happened to me when I upgraded from macOS 12.5.4 -> 12.6.

**Comment by johnnyutahh** [comment]
1. MonitorControl.app v3.1.1 (Build 3096) has same problem in all above and below scenarios.
2. I finished [2022-005 Catalina security-patch upgrade](https://support.apple.com/en-us/HT213343) install... same (problematic) symptom.
3. LG monitor contrast control works when not plugged into MacBook. After plugging into MacBook the hardware-based contrast-control widget/slider "greys out"/becomes_disabled.

Anything else to check?

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2026
$
```

**Comment by johnnyutahh** [comment]
Additionally:

1. I (re)restarted macOS (after [2022-005 Catalina security-patch upgrade](https://support.apple.com/en-us/HT213343) successful install), same problem.
2. I (re)upgrade to MonitorControl.app v4.1.0, same problem.

Brightness and Volume sliders work; Constrast (slider) does not.

**Comment by johnnyutahh** [comment]
Contrast slider (and Brightness slider, fwiw) _does_ work on above MacBook (`macOS v10.15.7, build 19H2026`) with an AOC U3277WB monitor.

Thus far only the LG HDR 4K monitor has a constrast-slider-failure symptom.

ALSO... I recall (before the [2022-005 Catalina security-patch upgrade](https://support.apple.com/en-us/HT213343)) said LG monitor being listed as some specific model ID/number other than a generic "LG HDR 4K" ID. Hmmmm.

**Comment by johnnyutahh** [comment]
Update: the AOC U3277WB Volume slider (as well as Brightness and Contrast slider) _does_ work, just now tested it (with and audio sample).

**Comment by johnnyutahh** [comment]
The problematic monitor is (apparently) an LG 32UL500. Here's photo of the back of said monitor with all the specs:  https://i.imgur.com/uPQ2wFC.png

**Comment by johnnyutahh** [comment]
> This also happened to me when I upgraded from macOS 12.5.4 -> 12.6.

@mjnohai - for which monitor(s) did you have a Contrast-control-slider-not-working problem?

**Comment by johnnyutahh** [comment]
> The problematic monitor is (apparently) an LG 32UL500. Here's photo of the back of said monitor with all the specs: https://i.imgur.com/uPQ2wFC.png

1. The LG 32UL500 display advanced settings: https://i.imgur.com/sj4ZV8X.png
2. the checkboxes in (1.) (above) previously had a blue background, now it's a white background (in just the checkbox). That's a little weird and I thought it worth noting.

**Comment by johnnyutahh** [comment]
More updates:

> 2. the checkboxes in (1.) (above) previously had a blue background, now they have a white background (in just the checkboxes... as shown in the above screenshot). That's a little weird and I thought it worth noting.

a. The blue-background checkmarks are back (in v4.1.0 after I downgraded to v3.1.1 re-upgraded bac tl v4.1.0).

b. I have edited the [first post in this issue thread](https://github.com/MonitorControl/MonitorControl/issues/1182#issue-1378658466) to include all the pertinent (I hope) info from the successive replies.

**Comment by johnnyutahh** [comment]
Please note: I plan to be away from the the above, problematic monitor (and therefore not able to test it) for about 8 days (reconnecting with it FriSep30), starting in about 1.5 hours. If anyone would like me to perform additional tests, pls reach me in (at least) the next 90 mins. :-)

**Comment by mjnohai** [comment]
> Sorry for the late reply, I have two LG 32BL95-U-W 4K monitors. I didn't see the issue you saw where the checkboxes became grayed out though.

**Comment by johnnyutahh** [comment]
Update: I will have the problematic monitor available to me until approx 1pm EDT tomorrow (FriSep23).

> Please note: I plan to be away from the the above, problematic monitor (and therefore not able to test it) for about 8 days (reconnecting with it FriSep30), starting in about 1.5 hours. If anyone would like me to perform additional tests, pls reach me in (at least) the next 90 mins. :-)

**Comment by johnnyutahh** [comment]
Is there any other exploration (info gathering, debugging, etc) that I/we can do on this besides testing other monitors?

**Comment by waydabber** [comment]
Hey @johnnyutahh - can you try [BetterDisplay](https://betterdisplay.pro) as a test and see if contrast control works with that app or not. As an alternative you can try [m1ddc](https://github.com/waydabber/m1ddc) as well.

**Comment by johnnyutahh** [comment]
Tanks @waydabber. Unfortunately...

1. BetterDisplay does.not.run/is.not.supported on my Catalina OS (according to my first install try).
2. m1ddc build fails (not sure this is the correct way to install it...? I did not spend much time looking), details below.

```
$ gitinfo
  Fetch URL: https://github.com/waydabber/m1ddc.git
  Push  URL: https://github.com/waydabber/m1ddc.git
7d6760a6175311f81a1940e30f5763f08a4b160a
$ make
clang -fmodules -o m1ddc m1ddc.m
m1ddc.m:84:63: error: use of undeclared identifier 'kIOMainPortDefault'
            io_registry_entry_t root = IORegistryGetRootEntry(kIOMainPortDefault);
                                                              ^
1 error generated.
make: *** [all] Error 1
$ date
Tue Oct  4 11:28:15 EDT 2022
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2026
$
$ alias gitinfo
alias gitinfo='giturls ; gitcurrentsha'
$ alias giturls
alias giturls='git remote show origin | grep URL'
$ alias gitcurrentsha
alias gitcurrentsha='git rev-parse HEAD'
$
```

> Hey @johnnyutahh - can you try [BetterDisplay](https://betterdisplay.pro) as a test and see if contrast control works with that app or not. As an alternative you can try [m1ddc](https://github.com/waydabber/m1ddc) as well.

**Comment by johnnyutahh** [comment]
Above LG monitor continues to be Contrast-control-broken problematic. U3277WB monitors continue to work okay, details below. A _separate_ and different LG monitor does seem to fully function (inlucing Contrast control), but I do not have said LG monitor immediately available, I'm only going from memory, and I'll try to get the details later (but won't have access to the working LG monitor for at least a week).

![2022-10-18-MonitorControl-U3277WB-display-settings-screenshot](https://user-images.githubusercontent.com/8906609/196534736-54044e28-030c-4802-bcec-4b7816942f39.jpg)

**Comment by waydabber** [comment]
All right, thanks @johnnyutahh for the info and sorry about the lackluster handling of the problem on our part!
