### ISSUE TITLE
monitor control.app has issue with the hdmi port on mac studio

### ISSUE THREAD

**Issue by cookbook-ms** [MonitorControl/MonitorControl#1183]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

I want to report a (software) issue with mac studio 2022.
Using your brightness control software and using an external monitor (we tried 3 different monitors from different brands and they all had this issue), when adjusting the brightness via your app after a few seconds the screen (external display) shows a black background with many grey horizontal lines which flicker/change position. When after this occurs the cable is removed and re-inserted into the mac, there is not signal to the monitor anymore. This issue only occurs when using the HDMI output. Using other brightness control apps the issue doesnt seem to occur. We have tried with different hdmi cable so its not a cable issue. Hopefully you can find the issue using the info above and make your app even better. 

### Steps to reproduce

1. connect an external monitor via hdmi port to a mac stuio
2. adjust the brightness with monitor control.app 
3. adjust a few times (could just slide the brightness from the dimmest to the brightest)
4. the connection will be lost, or there will be flashing stripes 

### Expected behavior

we expect the monitor connection will not be lost and there is not flashing horizontal strips 

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.6
- Mac model: Mac Studio (2022)
- MonitorControl version: latest
- Monitor(s): lg 27ul500
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Hi there - take a look at this: #750

**Comment by the0neyouseek** [comment]
Hi @cookbook-ms 

This is a known issue with Apple Silicon devices, the HDMI port does not allow for DDC (hardware) communication. Sadly this is something only Apple can fix. 

There are two options for you to control your monitor: use an usb-c cable or control brightness via software (you just need to uncheck "Use Hardware DDC control" under the app "Displays" Preferences)

Have a nice day !

**Comment by waydabber** [comment]
I was faster lol!
