### ISSUE TITLE
Volume controle incomplete (cannot mute) on Philips 272p

### ISSUE THREAD

**Issue by asheenlevrai** [MonitorControl/MonitorControl#1193]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

Brightness control AND volume control are working although incompletely. What I mean is that the screen doesn't become completely black at minimal brightness (that's OK with me) and sound is not muted at minimal volume (or when the mute key is pressed). This one is more inconvenient. Brightness/volume both increase/decrease when the corresponding keys are pressed. It seems like the "minimal value" or something is not correctly set.

### Expected behavior

mute when volume is set to 0 or the mute key is pressed

### Environment Information (please complete the following information)

```markdown
- macOS version: 10.15.17
- Mac model: (hackintosh) i7 8700K, Rx590 8GB, 16GB DDR4 2400
- MonitorControl version: 4.1.0 build 7034
- Monitor(s): Philips Brilliance 272p
- Monitor Cable(s)/Connection(s): PC -> DP cable -> monitor
- Apple Silicon/M1 (yes or no):
```

**Comment by the0neyouseek** [comment]
Hi @asheenlevrai 

MonitorControl does not issue a "real" mute command due to various issue discovered on several monitors while working on this app. Volume is simply set to zero. you can however try to enable "true" mute in the app "Display" settings after enabling "Advanced setting" and see if works for you
