### ISSUE TITLE
Syncing the brightness setting of the built-in display occasionally fails

### ISSUE THREAD

**Issue by mianly** [MonitorControl/MonitorControl#1194]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

When I open the software for a period of time, when the ambient light decreases and the brightness of the built-in display decreases, the brightness of the built-in monitor displayed by the software is still the previous high brightness, and the brightness of the external display will not decrease accordingly.
I have turned on sync apple and built-in display brightness settings.
If the ambient light brightness is reduced immediately after opening the software, the brightness of the built-in display and the brightness of the external display will be reduced at the same time

### Steps to reproduce

The problem reappears when I open the software for a while and then I lower the ambient light level.

### Expected behavior

I would like to reduce the brightness of the built-in display when the ambient light is reduced, and the brightness of the external display is also reduced

### Environment Information (please complete the following information)

```markdown
- macOS version:13.0 Beta版(22A5352e)
- Mac model:MacBook Pro 2020
- MonitorControl version:4.1.0
- Monitor(s):AOC 24b1w1
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment]
Well, indeed, syncing should replicate the ambient light sensor induced changes to the external display. There is an internal process that periodically checks and syncs things up, that might have some kind of issue (btw it could be rewritten to be fully event driven, that would probably be a good idea).

The following can be used for the event driven solution (BetterDisplay also uses this when needed, it's a better approach generally):

```
DisplayServicesRegisterForBrightnessChangeNotifications(...)
DisplayServicesUnregisterForBrightnessChangeNotifications(...)
```

We could tap into the ambient light sensor directly as well.
