### ISSUE TITLE
Slider UI appearance when not using “Reduce Transparency”

### ISSUE THREAD

**Issue by augustsaintfreytag** [MonitorControl/MonitorControl#1195]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

While the UI for Monitor Control is generally excellent and very native in feel, I’ve noticed a slight difference in the pop-up via the menu bar application vs. the appearance of brightness and volume control present in Control Center.

The difference is only present when *not* using the “Reduce Transparency” accessibility preference. The issue is likely related to the use of vibrant appearance on the used controls’ layers.

Unlike the other controls of Control Center, the sliders appearing like this have *almost no contrast* and blend with the background, creating a legibility issue.

### Steps to reproduce

1. Ensure the accessibility setting “Reduce Transparency” is disabled
2. Open the menu bar pop-up for Monitor Control
3. Compare slider appearance to other controls in Control Center

### Expected behavior

From a first glance, borders around sliders and the bed sliders move in should have more contrast. They should appear like other slider controls in Control Center.

#### Panel of Monitor Control
![Screenshot 2022-09-28 at 10 50 50@2x](https://user-images.githubusercontent.com/7656669/192738160-c67dacda-9f93-4f5b-bfde-5d2909524b2a.jpg)

#### Panel of other controls
![Screenshot 2022-09-28 at 10 50 37@2x](https://user-images.githubusercontent.com/7656669/192738173-d4d2a1cd-5c8f-4057-81bf-f7cd419f55d3.jpg)

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.6
- Mac model: Mac Pro
- MonitorControl version: 4.1.0
- Monitor(s): 3× Dell UltraSharp Series
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment]
Yes. I tweaked the slider control appearance in [BetterDisplay](https://betterdisplay.pro) quite a bit so it has more contrast and looks better both in light and dark mode. I'll maybe carry over the changes to MonitorControl in a future version, but it's not an easy fix as even though the slider controls in BetterDisplay is a descendant of what I made for MC, it is modified in several ways.

<img width="594" alt="Screenshot 2022-09-28 at 11 58 09" src="https://user-images.githubusercontent.com/37590873/192750673-5b398328-ec2c-4723-abdb-05dac3d7f10b.png">

Ventura further flattened the look of the slider knob, I might apply that as well but I think the older look with the subtle shadow is nicer.

If you want, you can play with the MC version of the slider yourself as well and if you improve it, you can create a PR.
