### ISSUE TITLE
I did a stupid: turned down the brightness in app on my vintage Cinema Display. Couldn't see to turn back up. Restarted, now stuck like that.

### ISSUE THREAD

**Issue by gingerbreadxxx** [MonitorControl/MonitorControl#1198]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

Can't get Apple Cinema Display to work again since "temporarily" reducing brightness on Monitor Conrol to 0%

### Expected behavior

Operational monitor

### Anything else?

I have a tri monitor set up with the main monitor a 30" Apple Cinema Display, running off a M1 Macbook Air in clamshell mode. I have a co-morbid issue that is complicating my problem.

All three monitors were worklng tonight, but the ACD didn't seem as bright as it could be. Checked in Monitor Control, and it was at 100%. Thought I would lower the brightness and bring it back up again (as it has "reset" from similar in the past and found a brighter 100%) so from the menu bar pull down, I dragged it all the way left —  but lost my grip on the cursor position to click where I needed to so couldn't restore it back up to 100%.

Figured I'd restart the computer to hopefully fix. So I restarted, remaining in clamshell. The ACD is still not coming on, presume because the setting persisted. So to log on I have to open laptop and unplug the dock to actually see the login screen.

Here's where my co-morbid issue comes in: because of something with the way devices/monitors are handled with Mac or macos (or my ageing monitor, idk), my ACD will not wake up from sleep — only when the computer boots does the monitor get recognized for being what it is and actually work. Plugging it back in after logging in, it's not recognised as a Cinema HD as usual but an unknown device, so I can't change the settings for it that way.

I tried logging in, plugging the dock back in and changing the Display settings to show the same thing on every display, but the login screen has only ever showed on the main display, the ACD. Usually the settings for each set up are retained, but because the Cinema HD is an unknown device, it doesn't affect the settings for that set up.

Feels like there may be a basic way to overcome this but at this station I am stumped. Appreciate your time/consideration. 

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.6
- Mac model: MacBookAir10.1
- MonitorControl version:
- Monitor(s): 4.1.0
- Monitor Cable(s)/Connection(s): Dell D6000 dock, mini display port to USB-C adaptor
- Apple Silicon/M1 (yes or no): yes
```

**Comment by the0neyouseek** [comment]
Hi @gingerbreadxxx,

Please have a look at this discussion and let me know if it fixes your issue:  https://github.com/MonitorControl/MonitorControl/discussions/739

**Comment by gingerbreadxxx** [comment]
Resolved — thanks for your reply, @the0neyouseek! Setting the DDC to maximum 255, minimum 0 and (probably most importantly) unplugged and replugged all of the connections, and I'm back up and running.  Cheers for your response!

**Comment by gingerbreadxxx** [comment]
Resolved — thanks for your reply, @the0neyouseek! Setting the DDC to maximum 255, minimum 0 and (probably most importantly) unplugged and replugged all of the connections, and I'm back up and running.  Cheers for your response!
