### ISSUE TITLE
An option to sync sliders of two (or more) monitors

### ISSUE THREAD

**Issue by krtkush** [MonitorControl/MonitorControl#1201]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

I have two monitors hooked up to my Mac mini, and they have different brightnesses while at the same level on the slider. For example, monitor 1 and monitor 2 sliders are at 50% but monitor 1 is brighter than monitor 2. To fix this, I have to move the corresponding slider of monitor 1 to 30% for the brightness to match with that of monitor 2.

However, the more annoying part is that I have to fiddle around the sliders all the time when I have to change the brightness. 

### Describe the solution you'd like

A nice solution would be able to sync the sliders such as when you slide slider 1, the slider 2 automatically gets adjusted relative to the brightness difference between the two monitors.

### Describe alternatives you've considered

Can't think of an alternative.

### Anything else?

I envision an implementation like this -

1. Slider 1 - User sets to 50%
2. Slider 2 - User sets to 30%
3. User checks a box which syncs/ pairs the sliders
4. Moving either of the sliders now makes the other slider move in corresponding percentage

**Comment by stacksjb** [comment]
I came here to report this issue as well. I have three monitors, and none of them ever seem to be in sync. It's incredibly frustrating and I'm not sure how to easily adjust it.

The type of solution described above is exactly what is needed. 

A more elaborate solution might be something like synching them when they are both off, and then both full, then calculating the scale.

PS, I was able to partially resolve this by disabling the "Allow zero brightness" option.

**Comment by waydabber** [comment]
The syncing feature is not planned to be improved in MonitorControl as the current feature set is considered final. I plan to add advanced syncing options to [BetterDisplay](https://betterdisplay.pro). You can also check out [Lunar](https://lunar.fyi) by @alin23 as it has sophisticated syncing features as well.
