### ISSUE TITLE
⚠️ What to do if Ventura update messes up keyboard control?

### ISSUE THREAD

**Issue by mike126126** [MonitorControl/MonitorControl#1211]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

更新了macOS13.0之后，键盘上的快捷键失效了。电脑型号Mac mini M1。
--
After updating macOS 13.0, the shortcut keys on the keyboard are invalid. Computer model Mac mini M1

### Steps to reproduce

更新了macOS13.0之后，键盘上的快捷键失效了。电脑型号Mac mini M1。
--
After updating macOS 13.0, the shortcut keys on the keyboard are invalid. Computer model Mac mini M1

### Expected behavior

暂无

### Environment Information (please complete the following information)

```markdown
- macOS version:13.0
- Mac model:Mac mini M1
- MonitorControl version:4.1.0
- Monitor(s):LG
- Apple Silicon/M1 (yes or no): yes
```

**Comment by joehquak** [comment]
It would be helpful if you share with the team which shortcuts you are referring to (sound or brightness or both)

Also to confirm if you have MonitorControl displaying correctly in your taskbar and share a screenshot of all of your settings

**Comment by mike126126** [comment]
thank you. I solved the problem by "uninstalling the app and reinstalling it"

**Comment by Fire5Lion** [comment]
Hi, I have a similar problem.
After the update, standard keyboard brightness key don't working. Custom keyboard shortcuts work. Reinstall does not help
- macOS version:13.0
- Mac model:Mac mini M1
- MonitorControl version:4.1.0
- Monitor(s):LG
- Apple Silicon/M1 (yes or no): yes

**Comment by nvlashi** [comment]
I'm encountering the same issue since upgrading to Ventura on my Intel silicon Macbook Pro.

**Comment by sxflynn** [comment]
Same problem. It literally just started happening. I had MacOS 13 already installed and it was okay, this monitor brightness was working correctly. I have a Dell P2027 and an M1 Mac Mini.

**Comment by waydabber** [comment]
Hi guys, it should be working fine, but you might have to re-add the application under Privacy&Security / Accessibility. If all things fail, you can reset the entire accessibility list and then re-add the application.

**Comment by waydabber** [comment]
Let me know if this issue is still valid or we can close it! Thank you!

**Comment by Fire5Lion** [comment]
> > Hi guys, it should be working fine, but you might have to re-add the application under Privacy&Security / Accessibility. If all things fail, you can reset the entire accessibility list and then re-add the application.
> 
> it works thanks

no, sorry, it works for 1 minute after reboot. Then only the volume buttons work.
I don't have any other brightness control apps. Maybe there is an opportunity to take the application logs and send it?

**Comment by waydabber** [comment]
Well, I am not sure app logs will help much as it should generally work, but MC might have some other Ventura specific issues (these should be investigated, maybe there is a connection, but there was no similar reports from others so far - #1221).

You can also try the latest beta of [BetterDisplay](https://github.com/waydabber/BetterDisplay/releases) and see if that works. That version contains some Ventura specific fixes and should not have any issues + it has brightness control feature as well. If BD exhibits the same problem then that gives some additional insights and helps figuring out what could be going on.

An other approach is to reset the accessibility permissions database by issuing the `sudo tccutil reset Accessibility` or if it fails `sudo tccutil reset All` command in Terminal. Note, that you'll have to re-add the the app and all other apps as this creates a blank slate.

**Comment by Fire5Lion** [comment]
BetterDisplay also worked for a minute after a reboot.

I uninstalled BetterDisplay, run sudo tccutil reset Accessibility and sudo tccutil reset Accessibility , rebooted, opened the monitor control, added it to Privacy&Security / Accessibility. It Works.
Then added Chrome Remote Desktop and VMware Horizon Client to Privacy&Security / Accessibility. Now MonitorControl works. watching

**Comment by waydabber** [comment]
All right, then the problem was not BD vs MC, but simply a corrupted permissions database. It probably got messed up during the update.

**Comment by waydabber** [comment]
I pinned this issue so others can easily find the solution, probably more ppl will encounter this.

**Comment by jvanakker** [comment]
> Hi guys, it should be working fine, but you might have to re-add the application under Privacy&Security / Accessibility. If all things fail, you can reset the entire accessibility list and then re-add the application.

This solved the issue for me on macOS Monterey.
