### ISSUE TITLE
Separate DDC control for audio / video

### ISSUE THREAD

**Issue by mbierman** [MonitorControl/MonitorControl#1212]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

First, thank you very much. This app is exactly what I was looking for!  

I am using USBC connector to my Dell monitor. If I turn on DDC I can control audio as expected but  every time I adjust brightness the monitor it flashes up a prompt on the monitor and I don't see a way to remove that.  

### Describe the solution you'd like

Allow the audio and brightness to have separate DDC settings so one can be on and not the other. 

### Describe alternatives you've considered

I am not aware of any except to have to fuss with the monitor switch every time I adjust brightness.

**Comment by x-magic** [comment]
You might want to state which device combination you're using. 

I'm using MBA M2 + Dell U4320q and it works smoothly. No flashing. 

Here's the monitor settings: 
<img width="842" alt="image" src="https://user-images.githubusercontent.com/3180639/199702924-6be05913-cb59-4471-90f8-5307391eac8d.png">

**Comment by mbierman** [comment]
Thanks that seems to have helped.
