### ISSUE TITLE
Allow fine tuning for volume by default

### ISSUE THREAD

**Issue by elipsoid-cz** [MonitorControl/MonitorControl#1215]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

My external display has too large steps between volume settings. Using +/- results in too big of a jump in volume. I am forced to use Option+Shift+Volume key to adjust my volume on this external screen.

### Describe the solution you'd like

I'd like to be able to set this screen to increase/decrease by smallest possible increments by default, without having to press Option+Shift. 

Thanks!

### Describe alternatives you've considered

Using the Option+Shift+volume -- works, but is not as elegant and seamless.

**Comment by waydabber** [comment]
This option is already in the app. 

<img width="842" alt="Screenshot 2022-11-02 at 5 07 06" src="https://user-images.githubusercontent.com/37590873/199386057-afdcae30-0b7d-4bd4-8885-a8795c4645ee.png">
