### ISSUE TITLE
Macbook monitor brightness reduces to low on itself randomly

### ISSUE THREAD

**Issue by elipsoid-cz** [MonitorControl/MonitorControl#1216]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

When MC is on, sometimes brightness of my macbook (not external screen) reduces on its own significantly.

### Steps to reproduce

1. MonitorControl is active
2. I am sitting in a dimly lit room
3. I increase brightness of my macbook pro 13 inch Intel i5
4. The brightness reduces to lower value randomly in a while (no change in external lighting conditions)
5. I increase the brightness manually again.
6. The brightness reduces again in a while.
7. When MC is off, this does not happen.

### Expected behavior

Brightness should stay the same when external lighting conditions do not change.

### Environment Information (please complete the following information)

```markdown
- macOS version: Ventura, happened on the previous one as well
- Mac model: Macbook Pro 13 2019 core i5
- MonitorControl version: 4.1.0
- Monitor(s): LG, not affected
- Apple Silicon/M1 (yes or no): no
```

**Comment by Kapocsi** [comment]
Does this happen when you don't have _Monitor Control_ Open? This seems like an issue with macOS itself.

**Comment by elipsoid-cz** [comment]
It does not. Shutting Monitor Control down resolves the issue. As if MC was making the ambient light sensor act up.

**Comment by Kapocsi** [comment]
Could you send a picture of all your settings? I can't seem to replicate this.

**Comment by elipsoid-cz** [comment]
Sure, thanks for looking into it.

<img width="842" alt="Screenshot 2022-11-10 at 8 03 00" src="https://user-images.githubusercontent.com/117190824/201022575-b80d00b6-ca15-42ec-9dcb-81f181a1ca69.png">
<img width="842" alt="image" src="https://user-images.githubusercontent.com/117190824/201022615-7727cc42-f64e-4317-8569-0d4f831b5140.png">
<img width="842" alt="image" src="https://user-images.githubusercontent.com/117190824/201022651-13f70090-720b-4c1e-8471-e63aa95c7878.png">
![image](https://user-images.githubusercontent.com/117190824/201022895-ab065913-620c-4001-9fdc-a817edce1c69.png)
![image](https://user-images.githubusercontent.com/117190824/201022918-a844083b-e208-4f5d-853b-b0708010632f.png)
![image](https://user-images.githubusercontent.com/117190824/201022936-2a265540-0ea0-47ea-9049-6809c9f6bcbc.png)

**Comment by elipsoid-cz** [comment]
![image](https://user-images.githubusercontent.com/117190824/201023356-c5ba7db2-7377-4a0b-ab95-57f2e166e239.png)
![image](https://user-images.githubusercontent.com/117190824/201023381-b5678c37-5d9d-4979-abad-4e7781969b50.png)
![image](https://user-images.githubusercontent.com/117190824/201023399-63fb24b3-c4da-4dae-9fd1-5b6a07309c8b.png)

**Comment by waydabber** [comment]
@elipsoid-cz - I am not sure I am getting the videos right. I see a changes in brightness but it might be the auto-exposure adjustment of the camera and not a real-world effect. On the first video I see the bar resetting to 50%. Is it maybe automatic brightness interfering (does not look like it though)? It would be useful to see the sliders as they might reflect better what is happening.

**Comment by elipsoid-cz** [comment]
@waydabber I didn't think of opening the menu to see the slider moving, I'll try to catch that next time. But you can see that the brightness setting is changing, as you pointed out -- I set it to max and soon it gets back to about 50%. 

It indeed looks like the automatic brightness is interfering. Two things that are weird about that though:
1) External lighting situation does not change at all, yet the brightness is being adjusted automatically.
2) These unwanted brightness adjustments seem to stop as soon as I quit Monitor Control.

**Comment by waydabber** [comment]
As a reference, can you try whether you experience the same issue with [BetterDisplay](https://github.com/waydabber/BetterDisplay#readme)? That app has a different method of detecting system induced brightness changes (event driven instead of periodic checking).

**Comment by elipsoid-cz** [comment]
Ok, I'll give it a go. The issue pops up irregularly, but I'll try to report back in about a week if I encounter an issue with BetterDisplay running instead of MonitorControl.

**Comment by waydabber** [comment]
All right, thank you!

**Comment by elipsoid-cz** [comment]
Hmm, that was quick. Same thing happening with BetterDisplay on. It was 3 times in a row, sitting in a dark room, watching youtube. I cranked up the brightness to about 50% and it always gradually dropped back to about 2 chiclets within 2 minutes. I turned BetterDisplay off and no issue since. This time it was without an external screen hooked up, so that doesn't seem to influence the issue.

**Comment by waydabber** [comment]
Is this happening with automatic brightness adjustment disabled in System Settings?

**Comment by elipsoid-cz** [comment]
The issue is intermittent. I disabled automatic brightness in macos settings and it did not happen for about two days. Today I switched it back on and the issue was back within an hour. This time it keeps bumping the brightness up, not down.

**Comment by elipsoid-cz** [comment]
I have disabled smooth transitions in the meantime, just FYI.

**Comment by elipsoid-cz** [comment]
Here's a screen recording. The only button I am touching is the brightness-down button (you can tell that by the OSD popping up). Brightness goes up on its own, which you can tell from the BetterDisplay controls moving in the upper right corner.

This is with auto brightness on. Does not happen when BetterDisplay is off and auto brightness is on. 

https://user-images.githubusercontent.com/117190824/204087890-025936b7-ebbe-4b48-9980-b76608ca802e.mov

**Comment by sjstark** [comment]
Just wanted to chime in to say that I was also getting this issue. Attaching screenshots of my app settings. I'm trying to disable macOS's setting for the built-in retina display to `Automatically adjust brightness` and it seems to have stopped for the time being... just annyoing because if I'm not attached to my monitor I'd love for that to still be enabled.
![Screen Shot 2022-12-13 at 4 14 56 PM](https://user-images.githubusercontent.com/6759557/207465913-db6710bd-663a-467f-b35f-635635e6239d.png)
![Screen Shot 2022-12-13 at 4 15 00 PM](https://user-images.githubusercontent.com/6759557/207465919-883d4571-0d57-491c-81fa-ba8e50b5485c.png)
![Screen Shot 2022-12-13 at 4 15 04 PM](https://user-images.githubusercontent.com/6759557/207465923-0b6170db-a054-436b-9fcf-3bc6826d32a8.png)
![Screen Shot 2022-12-13 at 4 15 13 PM](https://user-images.githubusercontent.com/6759557/207465933-4f3931e6-c919-40a8-927b-b6b3e2757589.png)
![Screen Shot 2022-12-13 at 4 15 17 PM](https://user-images.githubusercontent.com/6759557/207465953-db116cdc-f3ec-40c0-967a-200bb6535604.png)

**Comment by n-hass** [comment]
Also confirming I am experiencing this bug with the same exact behaviour on an Intel 2019 Macbook Pro but **not** at all on an M1 Macbook Pro. Both are nearly identical; same OS version and MonitorControl version, both very basic user accounts with identical system extensions (none of which related to the functionality of monitor control)
