### ISSUE TITLE
Hardware Brightness Control not working on LG 27UL850-W over HDMI

### ISSUE THREAD

**Issue by rgaufman** [MonitorControl/MonitorControl#1217]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Hardware Brightness Control not working on LG 27UL850-W 4K over HDMI

### Steps to reproduce

1. Press brightness controls with software brightness off
2. Observe there is no brightness change whatsoever

### Expected behavior

1. Brightness should change like it does when using Lunar

### Environment Information (please complete the following information)

```markdown
- macOS version: Ventura 13.0
- Mac model: Mac Mini M1 2020
- MonitorControl version: 4.1.0
- Monitor(s):  LG 27UL850-W
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
The HDMI port of post 2018 macs do not support DDC control. More info: https://github.com/MonitorControl/MonitorControl/discussions/750
