### ISSUE TITLE
Monitor Disconnect / Reboot on macOS Catalina (10.15.0 B6)

### ISSUE THREAD

**Issue by cybertunnel** [MonitorControl/MonitorControl#122]
OS: macOS 10.15.0 B6

Sorry ahead of time if this is a repeat. However I am running macOS 10.15.0 B6 which causes my external ASUS monitor to disconnect/reboot after playing with the sound too quick or often. Mainly occurs around the volume control via. menu or keyboard commands.

**Comment by cybertunnel** [comment]
Are there any logs I can grab for you?

**Comment by JoniVR** [comment]
Is this still an issue? This seems like more of a monitor issue to me seeing that this is the only report about this so far. 😕
