### ISSUE TITLE
Enable automation for brightness controls

### ISSUE THREAD

**Issue by khammo01** [MonitorControl/MonitorControl#1224]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

I'm always frustrated when I have to manually adjust brightness for three monitors at the beginning and end of each day for night use. 

### Describe the solution you'd like

As a power user, I would like to be able to develop desktop automations to adjust brightness to match room and outside lighting. 

This could be done by providing a time based brightness adjustment automation within the app, or enabling external adjustment through methods such as Automator's "Watch me do" action. This action does move the brightness slider but exits with a failure code. 

### Describe alternatives you've considered

I tried using the Watch Me Do action in Automator but it exited with a failure code, stopping subsequent action processing and throwing a dialog on the screen that must be closed.

**Comment by waydabber** [comment]
This feature is planned in [BetterDisplay](https://github.com/waydabber/BetterDisplay) but is not planned to be implemented in MonitorControl.

Note: [Lunar](https://lunar.fyi) has this feature right now.
