### ISSUE TITLE
Mute/Unmute is Reversed in My Monitor on Ventura

### ISSUE THREAD

**Issue by owenzhao** [MonitorControl/MonitorControl#1225]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

My Monitor is 32C1U and control through DDC. At first the sound volume change in MonitorControl took no effect. 

So I enabled the "Allow DDC Mute Command" in Advance Setting. After that the mute and unmute was reversed, when MonitorControl set mute, the system played with sound normally. When MonitorControl set unmute, the system played with no sound. 

That also lead to another issue, when something is playing and change the sound volume, the system gets mute immediately. Also, the sound volume set seems taking no effect. As whatever sound level I set, when change to mute, which is unmute in my system, the sound level seems the same.

### Steps to reproduce

1. Enable "Allow DDC Mute Command"

### Expected behavior

MonitorControl can control sound volume.

### Anything else?

When connecting through HDMI with Nvidia GTX 970 on Windows 10, the volume control worked.

### Environment Information (please complete the following information)

```markdown
- macOS version: macOS Ventura 13.0.1 (22A400)
- Mac model: Mac mini M1
- MonitorControl version: 4.1.0 build 7034
- Monitor(s): INNOCN 32C1U
- Apple Silicon/M1 (yes or no): yes
```

**Comment by owenzhao** [comment]
I used ULT-unite Type-C to DP1.2 to connect the Mac and the monitor.

**Comment by owenzhao** [comment]
I tried BetterDisplay. When I reversed value of "DDC Mute" to ON 2 and OFF 1, default is 1 and 2. The mute went fine.

However, the sound volume still didn't work. Also, if I turned the sound level to mute, the mute didn't work either. Only the directly mute button worked.

**Comment by waydabber** [comment]
That is interesting, the firmware might wire the DDC command in reverse for this display then. Unfortunately in MC you don't have the option to specify ON/OFF values for mute (like you have with BetterDisplay). However if you have a specific issue with BetterDisplay, you can post an issue in that repo about it, and I'll try to sort it out. I want to improve mute compatibility anyway in BD. Thank you!

**Comment by owenzhao** [comment]
> That is interesting, the firmware might wire the DDC command in reverse for this display then. Unfortunately in MC you don't have the option to specify ON/OFF values for mute (like you have with BetterDisplay). However if you have a specific issue with BetterDisplay, you can post an issue in that repo about it, and I'll try to sort it out. I want to improve mute compatibility anyway in BD. Thank you!

I don't have specific issue, but a common issue. Both of the apps can not change my sound volume. Any suggestion on this?

**Comment by owenzhao** [comment]
On more thing, I set the Monitor Control try to read the monitor's setting when start or awake. It worked. MC can read my sound volume correctly, which is 60. However, changing the sound volume never worked.

**Comment by waydabber** [comment]
These are all monitor firmware issues, there is no much to do about it. Even big name display makers can fail with. You can try experimenting by using different control codes maybe.

**Comment by owenzhao** [comment]
I workaround this issue by took my old 2.1 speakers to 3.5 mm jack. The bad side is my desktop is almost out of space.🐒

The speakers are over 12 years. But they sounds like they were new. Great!
