### ISSUE TITLE
Apple Keyboards F10 close/open volume do not work

### ISSUE THREAD

**Issue by TristenChenTao** [MonitorControl/MonitorControl#124]
1、Apple Keyboards F10 close/open volume do not work
2、Apple Keyboards F11 lower volume to zero， but still have a little volume

MonitorControl：1.7.0
macOS：10.14.6
DisplayName：PHL 328M6FJS

**Comment by JoniVR** [comment]
If I understand your question correctly, see #107

**Comment by TristenChenTao** [comment]
> If I understand your issue correctly, see #107

i can use "ddcctl -d 1 -v"  mute volume, but still F10 still does't works
do you have plan to fix this bug ?
by the way soundflower can use F10 mute volume
