### ISSUE TITLE
Version History option unlocalized

### ISSUE THREAD

**Issue by Jerry23011** [MonitorControl/MonitorControl#1241]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

`Version History` in the popup window after checking update  is not localizable.

### Steps to reproduce

1. Launch MonitorControl under a language other than English (Chinese for instance)
2. Click the icon in the menu bar
3. Click `Check for updates`
4. You will see there's no translation for `Version History`

### Expected behavior

Make `Version History` Localizable in source project.

### Anything else?

<img width="372" alt="截屏2022-12-04 14 56 12" src="https://user-images.githubusercontent.com/89069957/205478601-9b6e7ed7-bf61-4fb6-a962-7bfd20f4b520.png">

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.6.1
- Mac model: MacBook Pro 14'
- MonitorControl version: 4.1.0
- Monitor(s): ViewSonic VP series
- Apple Silicon/M1 (yes or no): Yes
```

**Comment by isametry** [comment]
Please see #1078.
