### ISSUE TITLE
Monitor cannot unmute after being muted

### ISSUE THREAD

**Issue by rentalanimal** [MonitorControl/MonitorControl#1254]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

When I reduce volume to zero via keyboard, monitor will remain muted after raising volume again. Have to use hardware button on monitor to resolve. The mute button will also mute but cannot unmute without using monitor hardware button. This is on an LG HDR 4K monitor (27UK500). 

### Steps to reproduce

1. Installed Monitor Control from latest
2. Gave access to all keys via Sys Settings
3. Mute via keyboard mute button
4. Raise volume or unmute... issue persists. 

### Expected behavior

Once raising volume or unmuting... volume should return. 

### Environment Information (please complete the following information)

```markdown
- macOS version: 13.0.1
- Mac model: M1 MacBook Pro
- MonitorControl version: 4.1.0
- Monitor(s): LG HDR 4K
- Apple Silicon/M1 (yes or no): Yes
```

**Comment by sabanworld** [comment]
Not sure if it helps to know, but this does work as intended on an LG 34WL850-W
Same specs MacBook Pro M1 (Pro) 2021, macOS 13.0

**Comment by waydabber** [comment]
Hey guys, I implemented a host of mute related settings in BetterDisplay, if MC does not work well in this regard, you can try playing with these:

https://github.com/waydabber/BetterDisplay/issues/1248

**Comment by waydabber** [comment]
All mute problems will go under this banner from now on:

https://github.com/MonitorControl/MonitorControl/issues/1289
