### ISSUE TITLE
Change brightness by time (for people with sleep problems, please)

### ISSUE THREAD

**Issue by fermmm** [MonitorControl/MonitorControl#1258]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

I have a problem with sleep, if I see too much light at night then I cannot sleep. My monitor minimum brightness is to high. Please implement a feature to automatically dim at night, I really need it to have a normal life.

I'm currently using this app and manually changing brightness at night every day but sometimes I forget and then I have problems sleeping and having a normal day.

There is many people like me please implement this. I'm a developer but I don't have experience developing for macos.

Thanks

### Describe the solution you'd like

The time when the screen dims should be configurable, also a time to restore normal brightness. If the app starts inside the "dim time" it should dim at launch. That is all.

### Describe alternatives you've considered

The only application that currently does this is called "Lunar" and currently for me it does not work at all, I reported a bug and was never fixed. Also it's a paid app and not cheap.

### Anything else?

Pleaseee I'm suffering

**Comment by alin23** [comment]
@fermmm have you tried [Lunar](https://lunar.fyi/#location)'s Location Mode? 

Sounds like it does what you want: dim brightness gradually from noon to sunset, and increase brightness back from sunrise to noon.

I'm the developer of Lunar by the way, algorithms like these take time to implement so I thought you might want to know about an already existing solution.

**Comment by fermmm** [comment]
> @fermmm have you tried [Lunar](https://lunar.fyi/#location)'s Location Mode?
> 
> Sounds like it does what you want: dim brightness gradually from noon to sunset, and increase brightness back from sunrise to noon.
> 
> I'm the developer of Lunar by the way, algorithms like these take time to implement so I thought you might want to know about an already existing solution.

I mentioned Lunar in the original issue text. In Lunar the dimming stops working randomly, it's not useful for me. I reported the bug in your github page: [Issue](https://github.com/alin23/Lunar/issues/502)

Also I have other complains with Lunar:

1. It's the only app for MacOS that have this feature, having only one option without alternative it's not healthy unless the app is totally perfect which is not the case.
2. The UI looks pretty but does not follow standards and it's hard to get things configured
3. It's hard to understand how clock mode will behave in detail, I needed many tries to get it working as I wanted. You can add many time points but that leaves you with many questions about how it works, in general with 2 times, for "on" and "off" should be enough, if you have users that want to add more times then that should be like and advanced mode of that UI.
4. The selector for the "modes" it's also not made with standard UI, I didn't understand if all modes can work at the same time or just one, because the modes selector looks like a UI menu changer not like a switch for the entire app behavior.

I have more complains but if you manage to get the app working I'll be happy because I paid for the app and it doesn't work, and it's not cheap.

**Comment by waydabber** [comment]
Hey guys @fermmm @alin23 - I see there are some issues about Lunar. I am sure @fermmm 's complaints are understandable and I am also sure @alin23 would want to respond as he is a super caring developer - this would howeer result in a discussion here that does not really belong to this repository. So if it is all right with you guys, I'll just remove these parts of the discussion but leave the original Feature Request here for MonitorControl for any dev to take who is willing to implement the feature it into the open source app.

Thanks both of you for your understanding! :)

**Comment by truonglong88** [comment]
I need this too. I have a Macbook M1 and I close the lid all the time and I use an LG extended monitor. In this way of using, the ambient light of the Mac never works and I need a scheduling brightness change. It will have a set of brightness controls based on time. Thanks so much.

**Comment by waydabber** [comment]
@truonglong88 - you can try Lunar by @alin23 as it has great scheduling capabilities for brightness. This feature is unlikely to make into MonitorControl anytime soon (of course PRs are always welcome!).
