### ISSUE TITLE
Generally improve mute compatibility

### ISSUE THREAD

**Issue by dannymout** [MonitorControl/MonitorControl#1289]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

I'm having troubles getting mute to work properly on my 32UN880-B. It's connected to a 2021 MBP over USB-C, and I'm using speakers connected to the 3.5mm audio output on the monitor.

- Volume controls work with the keyboard & menu bar app, but when going down to the last tick or hitting the mute button, my speakers don't go fully silent. My monitor's OSD shows muted though.
- When I fully lower volume or mute through the monitor OSD, it works fine.
- Mute works fine through macOS if I don't plug in external speakers to the monitor.

### Expected behavior

I'm expecting no output from my monitor's audio when I turn the volume all the way down or hit mute.

### Anything else?

- Using `m1ddc` and `set mute on` command, my speakers mute properly & the OSD indicates that.
- After running `set mute off` and then `set volume 0` audio still comes through.

The macOS volume UI didn't update to reflect these updates after I ran the commands, not sure if that's normal.

### Environment Information (please complete the following information)

```markdown
- macOS version: Ventura 13.0
- Mac model: MacBook Pro (14 inch, 2021)
- MonitorControl version: 4.1.0
- Monitor(s): LG 32UN880-B
- Monitor Cable(s)/Connection(s): USB-C
- Apple Silicon/M1 (yes or no): Yes
```

**Comment by waydabber** [comment]
Hi @dannymout  - would you be willing to check if any of these settings make things work right? I tried to cover all possible scenarios in BetterDisplay to fix various mute incompatibilities, any feedback is appreciated:

https://github.com/waydabber/BetterDisplay/issues/1248

**Comment by dannymout** [comment]
I installed BetterDisplay, rebooted and opened it. Everything works as expected through BetterDisplay, with mute and the lowest volume setting in sync on the OSD and in macOS.

I tried **Leave mute key under OS control** just to see what would happen, and it wouldn't let me mute at all. The macOS mute HUD would come up with a crossed out circle.

**Comment by dannymout** [comment]
Just looked at #892, and I enabled **Enable Mute DDC command** in advanced settings and mute is also working through MonitorControl too.
 
Thought it was worth mentioning that when I lower the volume all the way in macOS, the OSD only goes as low as 6 / 100 volume on my monitor. It will still goes silent so it's not an issue for me, but when I used BetterDisplay, my OSD would also go all the way to 0.

**Comment by waydabber** [comment]
That's because the current versions of BetterDisplay try to maximize compatibility by both setting the volume to zero and issuing a mute DDC command as default. MC on the other hand, when `Enable Mute DDC command` is enabled for the display, will not turn the volume to zero but issue a mute DDC command only. This should work equally well for compliant displays on a practical level.
