### ISSUE TITLE
Volume control is unavailable with new M2 Pro chip

### ISSUE THREAD

**Issue by JoennaCN** [MonitorControl/MonitorControl#1305]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Hi, I'm having some problems with m2 Pro chip on my new MacBook Pro 2023. The volume control bar is not displayed in the software, and it is useless to use shortcut keys to control the volume. In addition, the DDC switches in the software cannot be enabled. Replace the m1 MacBook Pro and everything will be fine. Is it because of incompatibility with the new chip?

### Steps to reproduce

111

### Expected behavior

111

### Anything else?

no

### Environment Information (please complete the following information)

```markdown
- macOS version:13.2
- Mac model:14 inch MacBook Pro 2023
- MonitorControl version:latest
- Monitor(s):
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
MC will be updated sometime in the future. Until that time check out this post for more info/alternatives:

https://github.com/MonitorControl/MonitorControl/discussions/1299

**Comment by waydabber** [comment]
Since this is the same as https://github.com/MonitorControl/MonitorControl/issues/1301, I'll close this one.
