### ISSUE TITLE
[Freature Request] Enhancing Display Brightness Synchronization with Customizable Brightness Curves for Individual Monitors.

### ISSUE THREAD

**Issue by jaddel** [MonitorControl/MonitorControl#1311]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

Hi, I highly apprechiate the synchronization of the brightness adjustment by the integrated display. However, my external monitor tends to appear brighter / darker than the built-in display. To resolve this, users should be able to set a brightness curve based on the built-in display's brightness for a selected resolution. 
Another option could be to use an algorithm that tracks manual brightness adjustments over time to automatically determine the desired brightness of the external monitor, eliminating the need for manual setup.

### Describe the solution you'd like

1. User-Defined Brightness Curves per Monitor.
2. Auto-Brightness Correction adapting to the users needs. 

### Describe alternatives you've considered

-

### Anything else?

Related Issues:

https://github.com/MonitorControl/MonitorControl/issues/943

https://github.com/MonitorControl/MonitorControl/issues/962

https://github.com/MonitorControl/MonitorControl/issues/889

**Comment by base08** [comment]
Yes! I have the same request... My MacBook monitor gets a lot darker (or brighter) than my Philips 4k monitor. This means that the scale on my MacBook is different than my external monitor.

Ex: 
Macbook 0% = ~80nits
External Monitor 0% = ~120nits

or

Macbook 100% = ~350nits
External Monitor 100% = ~300nits

**Comment by waydabber** [comment]
The feature set of the app is now considered final by the team, no more feature additions are planned. I advise you to try [Lunar](https://lunar.fyi) by @alin23 as that app has various advanced syncing features. I plan implementing advanced syncing in [BetterDisplay](https://betterdisplay.pro) as well.
