### ISSUE TITLE
mac mini m2 reset

### ISSUE THREAD

**Issue by hemingyang** [MonitorControl/MonitorControl#1320]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Macmini m2 clicks reset settings, there is an infinite flower screen, it freezes, and the computer can only be restarted

### Steps to reproduce

[![截屏2023-02-23 22.41.23.png](https://s1.locimg.com/2023/02/23/5e10ddd72b546.png)](https://s1.locimg.com/2023/02/23/5e10ddd72b546.png) reset settings,

### Expected behavior

[![截屏2023-02-23 22.41.23.png](https://s1.locimg.com/2023/02/23/5e10ddd72b546.png)](https://s1.locimg.com/2023/02/23/5e10ddd72b546.png) reset settings,

### Environment Information (please complete the following information)

```markdown
- macOS version: 13.2.1 ventura
- Mac model: Apple M2
- MonitorControl version:
- Monitor(s):
- Apple Silicon/M2 yes
```

**Comment by waydabber** [comment]
Somebody with an M2 Mac should confirm this issue - could not reproduce it.

**Comment by Sherlockwxd** [comment]
I have also experienced this situation. When adjusting the brightness of the Mac mini M2, the screen will flash. As a result, the HDMI port cannot be used, and switching the lightning interface is normal. Can only restart the mac

**Comment by waydabber** [comment]
MonitorControl does not support the HDMI port of the M2 mini for DDC: https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting#known-incompatibilities

**Comment by Sherlockwxd** [comment]
> 

thanks

**Comment by Sherlockwxd** [comment]
> 
Thanks.
