### ISSUE TITLE
Totally no support for the Dell U3219Q monitor

### ISSUE THREAD

**Issue by supczinskib** [MonitorControl/MonitorControl#1321]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Question

Dell U3219Q connected by the USB-C - HDMI adapter to MacBook Pro 14 2021. Nothing works in general. M1DDC does not work either. Although the monitor supports and has DDC/CI enabled, the Dell Display and Peripheral Manager for macOS control the monitor without problems.

Is there a chance that BetterDisplay or MonitorControl will be compatible with this monitor?

best regards,
Bartek

https://user-images.githubusercontent.com/40168732/221072568-8646b183-9d1a-448b-bd65-3945f73bab04.jpg
https://user-images.githubusercontent.com/40168732/221072592-ae7540c0-75ee-43b2-907e-776bdd07a6b6.mp4

**Comment by waydabber** [comment]
What features of the Dell Manager work for macOS? Did you try connecting directly via a HDMI cable (works with BetterDisplay only) or USB-C cable?

**Comment by Herrner** [comment]
For a Dell U3223QE connected via USB-C, Brightness and Contrast do work, Volume Control doesn't. Dells Display and Peripheral Manager doesn't offer Volume Control, at least for that monitor. The only way to control volume is right at the speakers or with eqMac (which doesn't use DCC).

**Comment by waydabber** [comment]
It seems like this display does not support volume control over DDC then.
