### ISSUE TITLE
Synchronizing the Brightness of Built-in and External Displays - Design Issue

### ISSUE THREAD

**Issue by lianshuze** [MonitorControl/MonitorControl#1329]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Discussion

This design is excellent, but in my usage scenario, I have discovered an area for improvement:

I am using two external displays: 1) an iPad (which has automatic brightness adjustment) and 2) a non-automatic brightness-adjusting display. In this situation, if I enable synchronization of the built-in display's brightness, it will cause the iPad to further adjust its brightness through software, resulting in a dimmer display.
The brightness of different displays is not consistent. Currently, the brightness percentage is synchronized, but it would be better if the brightness adjustment percentage could be calculated based on the difference in brightness settings between multiple screens.

**Comment by lianshuze** [comment]
这个设计非常优秀，但是在我的使用情况中，发现了一个可以优化的点
1. 我使用了两个扩展显示器：1: ipad（显示器本身具有自动调光功能） 2: 不具有自动调光的显示器；在这样的情况下，我如果开启同步内置显示器亮度，会导致ipad进一步使用软件调光，会很暗
2. 不同显示器亮度是不一致的，目前是同步亮度百分比设置亮度值，如果可以根据多个屏幕目前设置的亮度差值再累加亮度调整百分比会更棒

**Comment by waydabber** [comment]
The feature set of the app is now considered final by the team, no more feature additions are planned. I advise you to try [Lunar](https://lunar.fyi) by @alin23 as that app has various advanced syncing features. I plan implementing advanced syncing in [BetterDisplay](https://betterdisplay.pro) as well.
