### ISSUE TITLE
Preset brightness & contrast for apps.

### ISSUE THREAD

**Issue by kaifuj** [MonitorControl/MonitorControl#1337]
### Before opening the issue, have you...?

- [x] Searched for existing issues

### Is your feature request related to a problem? Please describe

I am a heavy user of IntelliJ IDEA. When I am using IntelliJ, I need to increase the brightness and contrast of the external monitor to better see the code because of the default dark theme. While I need to browse the web, I need to decrease the brightness and contrast down to normal level again. I switch between IntelliJ and browser very often.

### Describe the solution you'd like

It would be great that if MonitorControl can have preset brightness and contrast for apps, and automatically change to preset values when certain app's window is activated and change back when no longer activated.

### Describe alternatives you've considered

I found a similar project but it doesn't support external display: https://github.com/MrRobz/menubar-auto-brightness
Also Lunar has so-called App preset, but works awful.

### Anything else?

Thanks for this great App!

**Comment by waydabber** [comment]
The feature set of MonitorControl is now considered final by the team, no more feature additions are planned. I can move this feature request over to BetterDisplay's repo where I might implement it in the future. Is it ok with you @kaifuj?

**Comment by mika1337** [comment]
I am also greatly interested in this feature.
I do a lot of photo editing and I bought a tool to calibrate my screen to get accurate colors.
I find the "accurate" brightness/contrast settings too luminous, so I lower those settings while I'm not editing photos. Which means everything time I start my photo editing software I use MonitorControl to change brightness/contrast, and I do it again when I'm done.
Having this as an automatic behavior in MonitorControl would be great !

**Comment by waydabber** [comment]
Added this to BetterDisplay's enhancement list. Will close it here as MonitorControl is considered feautre-complete and no more additions are planned.

As @kaifuj mentioned, Lunar by @alin23 also has this feature (note: I recommend giving some feedback there if you feel the feature could be improved).

**Comment by mika1337** [comment]
I've tested Lunar and it does exactly what I was looking for. Thanks for pointing it.
