### ISSUE TITLE
Unable to use DDC controls on Dell U4320q, macos M2 although it *should* work.

### ISSUE THREAD

**Issue by acama** [MonitorControl/MonitorControl#1340]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

I am having an issue using DDC controls on my monitor for Volume and Brightness. The reason I believe this *should* work is because I saw an issue where @waydabber mentioned that he wrote the tool at https://github.com/waydabber/m1ddc/blob/main/m1ddc.m as a toy program for the support he hadded in MonitorControl here https://github.com/MonitorControl/MonitorControl/blob/main/MonitorControl/Support/Arm64DDC.swift.

I built tried out the tool `m1ddc` and it works as expected: I am able to control Volume and Brightness through that tool. However when I try MonitorControl, it says in the settings that it is using "Software" and DDC is greyed out. I am unable to control volume and brightness. What could be the issue here ?

The exact same configuration is used during the two tests (same cable, same computer, same monitor, etc.)

Thanks,
    Amat

### Expected behavior

MonitorControl should be able control Volume and Brightness on M2 devices.

### Environment Information (please complete the following information)

```markdown
- macOS version: 13.2.1
- Mac model: MacBook Pro (16-inch 2023) M2 Max
- MonitorControl version: 4.1.0
- Monitor(s): Dell U4320q
- Monitor Cable(s)/Connection(s): USB-C
- Apple Silicon/M1 (yes or no):yes
```

**Comment by waydabber** [comment]
Hi there, unfortunately MC does not support M2 Pro macs as of now. It's interesting that m1ddc does wok, but the framebuffer is there, MC and Arm64DDC would need some refactoring, m1ddc is maybe a bit more relaxed and probably by chance finds the right port on your config.

You can use [BetterDisplay](https://github.com/waydabber/BetterDisplay#readme), it basically has all the features MC has regarding DDC and brightness/volume control + a lot more and all DDC/brightness/volume stuff is free and unlimited and it has official M2 Pro support.

**Comment by acama** [comment]
Thanks for your quick reply, tried out BetterDisplay and it seems to work perfectly. Thanks a lot!
