### ISSUE TITLE
One display only dims at <50%, how to equalize?

### ISSUE THREAD

**Issue by bastibe** [MonitorControl/MonitorControl#1363]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Question

I have two external displays on a Mac Mini. Ostensibly, they are the same model, but if I change their brightness with MonitorControl, one starts dimming right away, while the other only responds if brightness <50%.

Is there a way to "equalize" their responses, so they dim similarly? DDC min/max in advanced settings sounds correct, but there's no indication what sort of values should be filled in the text fields.

**Comment by bastibe** [comment]
Fantastic app, by the way! Thank you very much for developing it and putting it out here for free!

**Comment by bastibe** [comment]
Dragging one display's "Combined dimming switchover point" fully to the right improves things. The dimming curve is obviously still different, but at least they now both dim over the entire value range.

Some documentation of the advanced settings would help a lot.

**Comment by waydabber** [comment]
The one which responds only up to 50% if using software dimming only, the DDC part of the slider does not work. Either the display does not support DDC or you are using the HDMI port which MonitorControl does not support (in this case you can use [BetterDisplay](https://betterdisplay.pro) as an alternative with HDMI support - all DDC features are free and unrestricted).

**Comment by bastibe** [comment]
Thank you very much, that explains it. One display is indeed connected via HDMI.
