### ISSUE TITLE
Dasung paperlike

### ISSUE THREAD

**Issue by napoo80** [MonitorControl/MonitorControl#1364]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Question

I want to be able to control an e-ink display (dasung paper like)
The problem with e-ink is they acumulate shadows and you need to press the clean button. This can be done sending comands to the monitor.

I found two proyects related but no one worked:
https://github.com/kfur/Dasung-GoodNight
https://github.com/leoluk/paperlike-go

Having something like (Ctrl + Alt + Cmd + c - refresh screen) will be great for my daily life.

The app recognize the dasung and i can change resolution and bright.

Is a way to refresh the screen?

If not, would be great to have this feature or having some guide of what is the way to implemented.

Thnks!!

**Comment by waydabber** [comment]
If there is a custom DDC/CI command you can send to the display to refresh the display, then it should be possible, yes. Let me know if you have this info!
