### ISSUE TITLE
YouTube (and html 5 video) playback 100% broken across all browsers (likely since Ventura 13.3.1 update) 

### ISSUE THREAD

**Issue by barneym** [MonitorControl/MonitorControl#1368]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Complete writeup on the issue is on the [Reddit YouTube](https://www.reddit.com/r/youtube/comments/13449c7/youtube_streaming_broken_100_repro_across_safari/) forum.  

Issue started approximately 2-3 weeks ago (as of 1-May), probably tied to the last Venture 13.3.1 update, but can not confirm directly.  With MonitorControl running and audio output directed at controlled monitor, attempting to play any web based video via video html tag (YouTube, Reddit, or other standard embedded videos) will result in an entirely broken experience with video audio de-synced, video/audio length corrupted, and tracks jumping or skipping forward at high rate of speed (100x speed or greater).  

This is a 100% failure case in my situation across all browsers (Safari, Chrome, Edge tested so far) and failure is immediate even with a fresh install of a new browser.  No login to YouTube required.  Impacts Ads, Shorts, and Videos, and seemingly any sources that use the video html tag for playback.

In contrast video html tag is set to muted will play normally, or if audio is routed to a non-DDC/CI output then the video will play normally.

Issue does not occur if you disable Monitor Control on Startup and reboot.

Major video services such as Netflix, HBO, and Prime Video do not experience this issue when played directly from their sites.

I did briefly have glitches with QuickTime Player jumping to the end of a video.  However, it was very rare.

### Steps to reproduce

1. Install Monitor Control (latest version as of 1-May-23)
2. Update to Ventura 13.3.1 (assuming this is source of issue)
3. Direct output to external monitor (maybe reboot for good measure)
4. Attempt to play YouTube videos (or any video 5 html test site can work).
5. Audio with bug out immediately, Video will start misbehaving within a few seconds, or skipping ahead on the scrubber will eventually trigger the behavior...or just be patient and it will start freaking out.  Most of the time it breaks within fractions of a second, but rarely a video will play through for a bit with audio broken.
6. Repro's on all videos tested and ads, whether signed in or not or even fresh install of new browser.
7. Mute browser and fast forward, videos will play normally; or use HTML 5 test sites which usually run tests in muted mode which will work fine.  So audio specifically seems to be the breaking issue.
8. Disable "Start on Login" and Reboot for videos to play normally with stable audio and video.

### Expected behavior

Expect YouTube videos and other web based videos to play normally.  

Related Videos:
* Edge Recording - https://youtu.be/IpHQXmWJmVQ
* Recording of several failure behaviors - https://youtu.be/9WHRW0jE7B4
* See Video Notes in each description for more context of recording.

### Anything else?

Full write-up of the situation available here: https://www.reddit.com/r/youtube/comments/13449c7/youtube_streaming_broken_100_repro_across_safari/

### Environment Information (please complete the following information)

```markdown
- macOS version: Ventura 13.3.1
- Mac model: Macbook Pro M1 Max (Max specification)
- MonitorControl version: Current as of 1-May
- Monitor(s): (2 monitors) LG OLED and QLED Ergo Brand 27"
- Apple Silicon/M1 (yes or no): Yes
```

**Comment by waydabber** [comment]
Do you have the same issue with [BetterDisplay](https://betterdisplay.pro)? Do you have still have this issue with 13.4? I could not reproduce the issue.

Audio routing does not happen through DDC/CI, it is only volume control - but the issue in hand should not be related to that as it clearly seems to be some sort of software issue (maybe something interferes with MonitorControl or pushes MC into a continuous configuration loop which takes away resources briefly? I am not sure).

**Comment by marcos-vinicius-mafei** [comment]
Same issue here!

Macbook Air M2.

It happens when I try to use my LG Monitor as the audio output.
