### ISSUE TITLE
App doesn't read brightness after waking up

### ISSUE THREAD

**Issue by fidwj01** [MonitorControl/MonitorControl#1398]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

When the screen wakes up from being off, changing the brightness from the MacBook keyboard won't update the app which causes "sync brightness" to not work. I've tried every options under "Upon startup or wake", nothing worked.

Restarting the app can fix the issue.

![Screenshot 2023-06-30 at 7 39 18 PM](https://github.com/MonitorControl/MonitorControl/assets/17058228/91c0a7fc-836f-48c2-aee5-6617a1d75a4f)

### Steps to reproduce

1. Enable "Sync brightness changes from Built-in and Apple displays"
2. Put the computer to sleep or wait until the display is off
3. Wake up the computer
4. Change brightness from the Touch Bar/built-in keyboard
5. The change in brightness won't be detected by the app unless you restart the app

### Expected behavior

It should behave the same after the computer wakes up from sleep/display off.

### Environment Information (please complete the following information)

```markdown
- macOS version: 13.4 Ventura
- Mac model: MacBook Pro 15 2017
- MonitorControl version: 4.1.0 Build 7034
- Monitor(s): Built-in screen and LG HDR WQHD
- Apple Silicon/M1 (yes or no): no
```

**Comment by Volodymyr-13** [comment]
Same here, also **Volume** reset too. When I change volume using keys - it sets to 0 in real, but still showing like it set.

<img width="178" alt="Screenshot 1" src="https://github.com/MonitorControl/MonitorControl/assets/3391456/12200511-1677-445a-bc98-d3fabd7c177d">

**Comment by Volodymyr-13** [comment]
@waydabber pls implement!

**Comment by waydabber** [comment]
Hi @Volodymyr-13 - this should work in [BetterDisplay](https://github.com/waydabber/BetterDisplay#readme). All MC features (and more) are available for [free](https://github.com/waydabber/BetterDisplay/wiki/List-of-free-and-Pro-features) in BetterDisplay. I don't plan on any major future changes in MonitorControl 4 as it's code is very outdated by now.

**Comment by Volodymyr-13** [comment]
@waydabber i already told about it, it’s super overwhelmed app which is just hard to use for a basic needs. I will never use it. 
so please update this app, thanks.

**Comment by waydabber** [comment]
I understand your perspective. I might release a simplified version as MonitorControl 5 focusing only on brightness and volume control, if I get permission from the other maintainers to move forward with MonitorControl. Right now the consensus is that MC is done and I have no permission to take over the project alone. If this by any chance changes, it will be obvious. Sorry.

I don't see the point in creating a BetterDisplay Lite just to simplify an aspect of the app as that would be confusing + majority of users can live with the complexity or if they don't want to, they can simply turn off the offending menu items under Settings/Menu to make the app menu clean and simple. :) Making an app with an other name (other than MonitorControl or BetterDipslay) also seems like a bad idea, I don't want to start building an other "similar but still somewhat different" app  from scratch under a different name trying to gather a suitable userbase for it.

**Comment by Volodymyr-13** [comment]
@waydabber just hide all nonsense and make your BetterDisplay same as this app. 
I think you could add some landing options: 
 - basic 
 - advanced
 
 so if I chose basic, I will get like monitor control app in general, and also all overwhelmed menus structure will not be there.. oh my I even now trying to remember how I tried to navigate there.. that is madness.

**Comment by waydabber** [comment]
I think by default the app simply shows the brightness and resolution slider only, all other menu items collapsed. This does not seem too complicated to me, but I understand we all have different perspectives.

<img width="357" alt="Screenshot 2024-08-09 at 13 06 53" src="https://github.com/user-attachments/assets/ce648954-537c-40d0-bfd2-6a6850a3098e">

If you want to see different things in the menu, please navigate to Settings > Menu > Customize Menu Options.

Or of course you can keep using MonitorControl 4, but please understand, I will not substantially update the app. I added basic Sequoia compatibility in an unofficial release - if it is required, I'll probably provide more such unofficial compatibility updates, but that's about it (note: I don't have the credentials required to build a version that can properly auto-update official builds). The unofficial build can be found here: https://github.com/waydabber/MonitorControl

**Comment by Volodymyr-13** [comment]
I just downloaded it and remove it, again. So the madness is here:
I have to scroll 4 screen pages of settings of monitor? Lol no thanks. 

![Screenshot 2](https://github.com/user-attachments/assets/6f663398-a212-4f8b-a60b-af1554c1cbfe)
![Screenshot 3](https://github.com/user-attachments/assets/9241aff7-b650-43e6-8175-b222156f7b32)
![Screenshot 4](https://github.com/user-attachments/assets/8896290f-e8f0-4634-883e-ee24e4c12108)

![Screenshot 5](https://github.com/user-attachments/assets/ff834bae-78cd-45e4-b066-ef43235b6230)
 

![Screenshot](https://github.com/user-attachments/assets/f72e9161-8bc6-49ce-814e-e4a5acd0f7fd)
![Screenshot 1](https://github.com/user-attachments/assets/beeb5c6b-68e7-4fac-8426-16d48b3520e0)


Vs just simplicity: 

![Screenshot 6](https://github.com/user-attachments/assets/cf0f5e8b-90bc-4423-a018-3844e28f8483)
![Screenshot 7](https://github.com/user-attachments/assets/cff2f164-940c-4750-8244-129af7b3f126)

**Comment by waydabber** [comment]
Right, if you open all Additional settings... block, then indeed, the Settings screen can get quite large. :) Also, the menu if you keep open the Tools section and unfold additional menus can get quite large. As for the onboarding and DDC configuration notifications, those go away as soon as you click on them at least once so you get to know how to use the app and let the app auto-configure DDC (you can of course do it manually as well).

But as I said, you can use either app, both are great and I live them both dearly, it's just that MonitorControl as it stands won't be developed further at least not officially - even if I wanted to develop it further, it's not entirely my decision anyway.

Thanks for all the feedback and take care! :)

**Comment by waydabber** [comment]
All right, thanks again for the feedback and perspective, I'll consider these inputs as I develop the app. For sure, you or any developer is free to fork MonitorControl (as it is open source) and improve upon it any way you find best suited to your needs. Just note that changes will probably not get to the official builds, but any number of unofficial builds can exist or even take over the original in popularity, no problem with that.

**Comment by waydabber** [comment]
The original issue is that after wake, there is a wait period after the app reconfigures itself - during this period is disengaged from controlling the keyboard so the built in screen's brightness can be changed by the system itself through the normal keyboard control. It's just how MonitorControl was made and there is a valid reason for the delay. The behavior can be refined in many ways of course with further development - BetterDisplay has an option to change wake delay, configuration delay and also by default restores last saved brightness after wake or can update its setting based on changes the user made meanwhile. @Volodymyr-13's issue about volume is probably something else though.

I am not sure about the exact motivations of all team members, I guess everybody has other priorities now. For more context see this: https://www.reddit.com/r/mac/comments/1e30j3h/possible_limitation_of_monitorcontrol_development/?rdt=59029

**Comment by fidwj01** [comment]
I don't think what you described the delay is breaking it. If it's the delay, shouldn't it work after the delay is over? The problem is after wake, the app seems to lost what the displays are doing (basically the app doesn't know the changes made outside of it) until you restart MonitorControl. This is then breaking auto-brightness sync between the internal display and external display. Because the brightness of the internal display changes depending on ambient light, and MonitorControl doesn't know it when it does so it doesn't change the external display accordingly.

**Comment by waydabber** [comment]
You mean the brightness change tracking is not resuming after wake? MonitorControl does it in a rather old fashioned way (basically there is a job that runs and regularly tracks the brightness changes from time A to time B and adjusts synced displays with some gentle curve accordingly - this is not the best way to do it actually, but at the time it was fine). Or it is that during this initial delay the sync is off and does not recover until the brightness is min/maxed or the slider is used? The app only does delta syncing from the built-in display to external displays (in BD you can have both absolute and delta + fine-tune how syncing works), so keeping an exact 1:1 match was not a design idea to begin with.

Either this or that, I don't think I'll work on this or try fixing it in any form as I believe everything should be rebuilt from the ground up differently - and I already did that in BetterDisplay, there is no inspiration to do it again trying to patch old code. What I'd do if MonitorControl was to be kept going is to start from the code of BetterDisplay, strip excess functionality and create a MonitorControl 5 from that. But for that to happen, a team decision must take place and in essence I'd take over the project - but this was not the consensus about how to move on and I am totally fine with that.

So I understand all of your feedback, really wish the best to all - I am also super happy if anybody steps up to improve MonitorControl in a fork - much like I did with my unofficial Sequoia compatible version. But probably it's time to face the fact that as things now stand, it is somewhat unlikely that the official MonitorControl project will have any future releases produced. The official version of the app crashes instantly on Sequoia on Macs with built-in displays, which means the official project is effectively sunsetting sooner than later.
