### ISSUE TITLE
contrast and start up problems with monitorcontrol

### ISSUE THREAD

**Issue by cosicrac** [MonitorControl/MonitorControl#1408]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

I use monitor control on a macmini m2 with an apple led cinema display. I'm Very happy to be able to control brightness and volume. 
But, I have to start up the application every time I start up the computer, I have  clicked -the start up after login- box in preferences several times but after starting up it's empty
And the contrast control does not work. the slider is working in the menu but does not change contrast.

Can anyone help me with this,
Ce.

### Expected behavior

The programme to automatically start up.
and the contrast control slider to work 
Thank you

### Environment Information (please complete the following information)

```markdown
- macOS version: Ventura 13.5
- Mac model: mac mini m2
- MonitorControl version: 4.1.0
- Monitor(s): aplle led cinema display
- Monitor Cable(s)/Connection(s):USB-C to Mini DisplayPort and USB-C PD adapter with DP Alt Mode (4K 60 Hz) 
- Apple Silicon/M1 (yes or no): no
```

**Comment by guidogoni** [comment]
Same here, running on Mac Studio M2 Max (Ventura 13.5.2) with an AOC CQ32G3SE attached by DP. Any information I can provide to help on this bug let me know. Thanks!
