### ISSUE TITLE
Brightness and Popup issue

### ISSUE THREAD

**Issue by abejeyapratap** [MonitorControl/MonitorControl#1414]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

I really like this app, but having two minor issues:

1. Every time my laptop goes to sleep and then wakes up, my monitors are at full brightness (instead of last saved brightness)
a) I tried the following settings: "Apply last saved values to the display" and "Assume last saved settings are valid". Both don't resolve this issue.
3. Occasionally, when trying to adjust brightness (specifically after wake up), I get a pop-up telling me to close other apps that manage brightness (like f.lux). However, I don't have any other apps that adjust brightness.

### Expected behavior

1. When laptop wakes up, monitors should be at last saved brightness
2. Should not get the pop-up

### Environment Information (please complete the following information)

```markdown
- macOS version: Ventura 113.5
- Mac model: MacBook Pro (13-inch, 2020)
- MonitorControl version: v4.1.0
- Monitor(s): 2 of Planar PLL2210W
- Monitor Cable(s)/Connection(s): same for both monitors
    - MacBook Pro -> Mokin docking station -> HDMI-DVI cable -> Planar PLL2210W
- Apple Silicon/M1 (yes or no): no
```

**Comment by IntegerOverlord** [comment]
I have a very similar problem, but when my computer wakes up it goes to a minimum brightness (not full) and takes 30-40 seconds to recover to the last saved brightness
