### ISSUE TITLE
Bightness lower after i installed the software and tried adjusting the brightness.

### ISSUE THREAD

**Issue by boutzamat** [MonitorControl/MonitorControl#1415]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

I am using an Apple Cinema Display 27 and when i set it to maximum brightness, it's still darker than it was before i installed the software.

### Expected behavior

To increase the brightness of my display more than it was, but ended up the opposite. 

### Environment Information (please complete the following information)

```markdown
- macOS version: Ventura 13.4.1 
- Mac model: iMac 27" 2016
- MonitorControl version: 4.1.0
- Monitor(s): Apple Cinema Display 27
- Monitor Cable(s)/Connection(s): Thunderbolt to USB-C
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment]
Hi there,

these might help:

https://github.com/MonitorControl/MonitorControl/discussions/739
https://github.com/MonitorControl/MonitorControl/discussions/1381
