### ISSUE TITLE
Brightness goes to max when I close MacBook lid with "sync brightness" option enabled

### ISSUE THREAD

**Issue by igRo** [MonitorControl/MonitorControl#1416]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Brightness on the external display resets to 92..99% each time I close MacBook lid. In the office MacBook is always open, but at home I usually work solely on the external display and open my MacBook only when I attend video calls.

### Steps to reproduce

1. Open MacBook
2. Connect external display
3. Set brightness to 65% (using the slider in the app OR system brightness slider on the touch bar)
4. Close MacBook lid

### Expected behavior

Previously set brightness preserved

### Anything else?

- "Sync brightness" enabled
- "Upon wake" is set to "read display", also reproduces for "apply last"
- When "upon wake" is set to "assume valid" - brightness in the app also updates to 100%, but previous brightness is preserved de facto until you move the slider

### Environment Information (please complete the following information)

```markdown
- macOS version: 13.5.1 Ventura
- Mac model: MacBook Pro (16-inch, 2019)
- MonitorControl version: v4.1.0
- Monitor(s): Dell S3423DWC (USB-C)
- Apple Silicon/M1 (yes or no): no
```

**Comment by sophin123** [comment]
having same issues because of that switching to BetterDisplay. 
Waiting for this issue to be fixed and then I will switch back again because I love auto brightness features MonitorControl provides.

**Comment by waydabber** [comment]
The auto-brightness should be available in BetterDisplay as well (under Settings/Groups/Synchronization). :)

**Comment by sophin123** [comment]
Thanks wasn't aware of Synchronization

**Comment by waydabber** [comment]
I had some trouble replicating this issue. Not sure if this is still a problem, as the original was reported with Ventura. I'll close this now but can reopen if needed.
