### ISSUE TITLE
Build a newer version for release? (support M2Pro/Max

### ISSUE THREAD

**Issue by huoshenlaile** [MonitorControl/MonitorControl#1423]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Question

Currently written in wiki is that M2 Pro/Max does not work with this software, but a few recent commit already made it support M2 Pro/Max, and I tested it on my M2Max Macbook Pro with Dell U2723QE, it works perfectly. So I wonder if you plan to make a public release containing these new features

**Comment by JoniVR** [comment]
Done, we were planning on doing so, but my time is rather limited and last time I tried releasing I ran into some build related issues. Should be live now :)
