### ISSUE TITLE
After installing MonitorControl 4.2 my Apple Led Cinema Display went darker

### ISSUE THREAD

**Issue by johandanielnilsson** [MonitorControl/MonitorControl#1430]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

After installing MonitorControl 4.2, the brightness level of my Apple Led Cinema Display was lowered. Can't find a way to get back the same light level as before the upgrade to 4.2. Have tried all possible settings in MonitorControl. 

Estimated max brightness dropped by about 25%.

### Expected behavior

A higher brightness in my Apple Led Cinema Display

### Environment Information (please complete the following information)

```markdown
- macOS version: 13.5 Ventura
- Mac model: Mac Mini M2 Pro (2023)
- MonitorControl version: 4.2
- Monitor(s): Apple Led Cinema Display 27
- Monitor Cable(s)/Connection(s):Mac mini -> USB C to Mini DisplayPort Adapter -> Apple Led Cinema Display
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Pls check the discussions, search for cinema display, there are several threads about this. You'll probably have to set the DDC range to 0-255 instead of 0-100.
