### ISSUE TITLE
Why "Use hardware DCC control" is greyed out on iMac 27" Monterey and MBP 15" Big Sur?

### ISSUE THREAD

**Issue by bendoo** [MonitorControl/MonitorControl#1431]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Question

I want to reset the DCC value of the  "Use hardware DCC control" but this is greyed out on both iMac 27" Monterey and MBP 15" Big Sur.
I am using them with a 27" Thunderbold Cinema Display, can not change the max brightness settings.

Any idea what might be wrong?

**Comment by waydabber** [comment]
Can you provide a screenshot?
