### ISSUE TITLE
DDC enabled for only one Monitor in Daisy chain

### ISSUE THREAD

**Issue by desek90** [MonitorControl/MonitorControl#1433]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Hello,
I'm using the newest version of MonitorControl (v.4.2.0) with my setup consisting of a M2 MacBook Pro 14" and two LG 24MD4KL driven in Daisy Chain. I have an issue that only for one of the monitors the DDC is enabled.
Is this a desired behavior?

Best Regards,
Bart
<img width="842" alt="MonitorControl" src="https://github.com/MonitorControl/MonitorControl/assets/81962520/3701a441-8d22-4a5a-8ba9-6359ba824fee">

### Steps to reproduce

Connect the Monotors in daisy chain with Thunderbolt 4 cables. Macbook is not open.

### Expected behavior

I would expect the DDC control to be enabled for both displays

### Environment Information (please complete the following information)

```markdown
- macOS version: 13.5.2
- Mac model: MacBook Pro 14" 2023 with M2 Pro
- MonitorControl version: 4.2.0
- Monitor(s): Two 24MD4KL
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
The 24MD4KL should support native brightness control. Actually for this display MC should not be needed at all. It seems like only the first member of the daisy chain works however. Without MC can you control brightness?

**Comment by desek90** [comment]
Hello,

yes, without MC I can also control the brightness. I just thought, that thanks to DDC I can make some extended settings, that's why I tried to find out why it only works for one display.
Yesterday I found out, that if I reconnect the display at the end of the Daisy Chain, the DDC option appears for both. If I reconnect the whole daisy chain, the DDC is again unavailable on the second screen.

**Comment by waydabber** [comment]
In [BetterDisplay](https://betterdisplay.pro) you can set a display to be treated as a "third party display" so force-enable DDC. This feature is not planned in MonitorControl however as the current feature set is now considered final by the team.
