### ISSUE TITLE
Adjusting HDMI causes monitor to blow up

### ISSUE THREAD

**Issue by mbierman** [MonitorControl/MonitorControl#1443]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

If I start to adjust things on a monitor the screen goes grey/scattered (not sure how to explain) as if it is ½ unplugged or something. I have to reboot to get things to work again. 

### Steps to reproduce

1. Connect via HDMI 
2. Make adjustments in MonitorControl

### Expected behavior

adjustments should happen and monitor should work 

### Environment Information (please complete the following information)

```markdown
- macOS version: Sonoma 14.0 (23A344)
- Mac model: Macmini M1, 2020
- MonitorControl version: 4.2.0
- Monitor(s): DELL S2722QC 
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
As stated in the compatibility section, HDMI connections for the 2018 Intel, M1 and entry level M2 minis are not supported. You can use [BetterDisplay](https://betterdisplay.pro) instead as it supports all connections.

**Comment by waydabber** [comment]
Redundant of #1432
