### ISSUE TITLE
Allow controlling volume for all output devices (Internal MacBook speakers, Headphones, etc)

### ISSUE THREAD

**Issue by noah-nuebling** [MonitorControl/MonitorControl#1444]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

Sometimes I use headphones plugged into my MacBook while the MacBook is connected to a keyboad and monitor. I'd like to use the same keyboard keys that I use to control the volume of the external display audio (through MonitorControl) to also control the volume of my headphones.

### Describe the solution you'd like

I'd like it if MonitorControl changed the Macs' internal volume alongside the volume of the external monitor.

### Describe alternatives you've considered

I think I could possibly use another program to map the keys that MonitorControl uses to control external monitor volume, to also control internal macOS volume. But I'm not sure this is possible.

Alternatively I could map other keys to control internal macOS volume from my external keyboard. But I'd have to install some program for that, too, since it's not possible in the macOS shortcuts settings as far as I can see.

### Anything else?

See [this](https://github.com/noah-nuebling/mac-mouse-fix/blob/ec72e008c5a11bd5d515370191ca3eb743c03c50/Helper/Core/Actions/Actions.m#L99C20-L99C20) and [this](https://github.com/noah-nuebling/mac-mouse-fix/blob/ec72e008c5a11bd5d515370191ca3eb743c03c50/Shared/Constants.h#L272C15-L272C15) code for an example of how to change internal system volume programmatically.

Also thanks for making this great app, I think it's super neat and useful and I'm glad it exist! I especially love how it allows you to dim below the lowest brightness without any extra setup and how the dimming is nicely animated.

**Comment by waydabber** [comment]
Added this to BetterDisplay's enhancement list for future consideration. Will close it here as MonitorControl is considered feauture-complete and no more additions are planned.

**Comment by noah-nuebling** [comment]
I think it's a bit unfortunate, because I like this app better than BetterDisplay since it's simpler and free. But I guess I'll have to migrate to BetterDisplay at some point. Thank you for getting back.

**Comment by waydabber** [comment]
Simpler for sure, but basically all features of MonitorControl is free in BetterDisplay as well.
