### ISSUE TITLE
Brightness control is not exact with the iMac 5k 2020 panel (LM270QQ1F1)

### ISSUE THREAD

**Issue by odedia** [MonitorControl/MonitorControl#1459]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

I am using a the iMac 5k 2020 Panel with a custom DisplayPort 1.4 board as shown here: https://youtu.be/0VXQu0fAc8s. 

Overall it works amazing. 

The only slight issue is that brightness control doesn't work 100% as expected - when playing with the sliders or the keyboard shortcuts, it will reach 100% brightness at 50% of the slider. From 50% to 100% it is basically at full brightness. From 50% to 0% it is working well. 
Is there a way to override these settings? I know when my old Apple LED Cinema Display I needed to set DDC Max to 250 to get it working as expected. I tried it with this new setup but it doesn't do much.

### Expected behavior

Brightness control works from 0% to 100%

### Environment Information (please complete the following information)

```markdown
- macOS version: macOS Ventura 13.6
- Mac model: MacBook Pro M1 Max 16"
- MonitorControl version: 4.2.0
- Monitor(s): Apple LED Cinema Display, MacBook Pro built-in display, custom iMac 5k 2020 panel LM270QQ1F1
- Monitor Cable(s)/Connection(s): DisplayPort 1.4 connected via Thunderbolt 3 WD19 dock
- Apple Silicon/M1 (yes or no): Yes
```

**Comment by waydabber** [comment]
disable DDC and the scale will be uniform. By default the app uses software dimming from 0-50% and DDC from 50-100%.  Seems like the board is not DDC compatible so hardware backlight control is not happening.
