### ISSUE TITLE
Not working properly with ViewSonic VX2758-2KP-MHD

### ISSUE THREAD

**Issue by metehandemir** [MonitorControl/MonitorControl#1472]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

I'm using a 2018 Mac Mini i5. I connected my ViewSonic VX2758-2KP-MHD monitor to HDMI 2.0. I enabled DDC/CI in the on-screen menu. With MonitorControl I can control brightness and contrast but not the sound.

### Expected behavior

I have researched a lot but i couldn't find any solution. I hope I can help to look at this problem. Thanks.

### Environment Information (please complete the following information)

```markdown
- macOS version: Ventura 13.6.1
- Mac model: 2018 Mac Mini i5
- MonitorControl version: v4.2.0
- Monitor(s): ViewSonic VX2758-2KP-MHD
- Monitor Cable(s)/Connection(s): HDMI 2.0
- Apple Silicon/M1 (yes or no): no
```

**Comment by metehandemir** [comment]
Sorry I've read [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting) and see hdmi port of 2018 mac mini is not working properly with MonitorControl. I am closing issue.

**Comment by waydabber** [comment]
Hi @metehandemir - you can use [BetterDisplay](https://github.com/waydabber/BetterDisplay#readme) for HDMI support for the 2018 Mini (that is currently the only app that supports Intel 2018 HDMI DDC).
