### ISSUE TITLE
Monitor grouping

### ISSUE THREAD

**Issue by GAZDOWN** [MonitorControl/MonitorControl#1473]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

No, not a problem, hence a feature request.

### Describe the solution you'd like

As a user,
I would like to make group of screens,
so I can control all my screens at once.

### Describe alternatives you've considered

Set every screen individually
Create a Keyboard Maestro macro.

**Comment by waydabber** [comment]
Hi @GAZDOWN - MonitorControl is considered feature complete, no new features are planned. If you'd like a feature like this, you can add it as an issue under [BetterDisplay](https://betterdisplay.pro) where I plan to introduce advanced syncing capabilities and this might be a good idea to implement there.

**Comment by GAZDOWN** [comment]
OK, thanks!
