### ISSUE TITLE
macOS 14.1.2 bug: Volume control not working

### ISSUE THREAD

**Issue by lukedumboy** [MonitorControl/MonitorControl#1476]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

I Just bought the M2 Mac mini, and when I connect to the monitor, the Volume control is not working, the volume indicator shows volume is changing when i press the volume UP/DOWN key, but when I open safari to test, it doesn't work as expect, and yet I have no clue how this happened , blow is the detail.

### Steps to reproduce

1. Press UP/DOWN key of volume 
2. The volume indicator shows the volume has changed
3. open any app could play music or video
4. the volume doesn't change at all

### Expected behavior

Press UP/DOWN key and the volume change

### Environment Information (please complete the following information)

```markdown
- macOS version:macOS 14.1.2 (23B92)
- Mac model:Mac mini M2
- MonitorControl version:4.2.0 Build 7048
- Monitor(s):LG HDR WFHD Display
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
MonitorControl does not support the HDMI port of the entry level M2 mini. Use BetterDisplay instead. If you are using USB-C and DDC generally works, then it might be a display incompatibility issue.

**Comment by heliumllc** [comment]
Same here. USB-C connected monitor's (INNOCN 29C1F-D) volume won't change. Any possible fixes?
(brightness does thought)
