### ISSUE TITLE
Enable True Tone on Screen replace Macbook

### ISSUE THREAD

**Issue by bientt210** [MonitorControl/MonitorControl#1484]
### Before opening the issue, have you...?

- [ ] Searched for existing issues

### Question

I have a MacBook Air M2 with a screen broken and replaced with another Air M2 screen, but the True Tone option was lost, Could this app re-enable True Tone on MacBook was replace screen?

Thanks for the excellent app.

**Comment by waydabber** [comment]
No, this app won't be able to do that.
