### ISSUE TITLE
Crashes on key action.

### ISSUE THREAD

**Issue by Diex** [MonitorControl/MonitorControl#1485]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

When trying to set brightness down using a keyboard shortcut it crashes the display driver. reconnecting the display won't solve. 

### Steps to reproduce

press fn+F1 (several times)

note: fn+F1 defaults to the mac keyboard standard shortcut for laptops.

### Expected behavior

It normally works fine. I found this after several months of uninterrupted use.

### Environment Information (please complete the following information)

```markdown
- macOS version: ventura 13.5.2
- Mac model: M2 8GB mac mini 
- MonitorControl version: 4.2.0
- Monitor(s): OEM LG 23"
- Apple Silicon/M1 (yes or no): M2
```

**Comment by Mowmowj** [comment]
I am experiencing the same issue as you.
My monitor flashes with white and black lines constantly. The only solution I have found is to force shut down my Mac Mini. This seems to be a serious bug that needs to be fixed as soon as possible.

**Comment by waydabber** [comment]
You guys might be using HDMI on these Macs. If this is the case, please use [BetterDisplay](https://betterdisplay.pro) instead as it properly supports DDC via HDMI properly. MonitorControl might not have any feature updates in the future so support for these devices probably won't be added.
