### ISSUE TITLE
Move apps from MacBook display to external monitor when at zero brightness (equivalent to Lunar BlackOut feature)

### ISSUE THREAD

**Issue by AdnanHodzic** [MonitorControl/MonitorControl#1486]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

Not related to a problem, but rather a potential extension of one of the existing features.

### Describe the solution you'd like

Currently MonitorControl has an option to "Allow zero brightness via software or combined dimming". 

However it would be great once MacBook display is at zero brightness if all apps on that display would automatically be moved to an external monitor. This way it would allow me to have an open laptop and all of its screen contents on external monitor.

Lunar app has this feature which it [calls Blackout](https://lunar.fyi/#blackout). 

### Describe alternatives you've considered

Only alternative is to manually move all apps on MacBook display to external Monitor before completely setting zero brightness. Even then, some apps might be open on display that's at zero brightness which is far from ideal.

**Comment by waydabber** [comment]
I added this feature to [BetterDisplay](https://betterdisplay.pro). Not planned for added to MonitorControl, sorry about that.
