### ISSUE TITLE
Max display Brightness significantley lowered after app install

### ISSUE THREAD

**Issue by jacobgeorgeband** [MonitorControl/MonitorControl#1509]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

After download and opening monitor control my max display brightness was significantly lower than before at max sliding to the right. I tried restarting my Mac mini m2pro and uninstalling the app to try to fix but the brightness is staying the lowered brightness (max brightness of monitor control but lower than pre installation of the app.) Help!

### Expected behavior

I expected the app to function properly allowing the max brightness to be the original max brightness. The scale is all wrong. 

### Anything else?

- macOS Version: 14.2.1 Sonoma
- Mac model: Mac mini M2pro
- MonitorControl version: latest
- Monitor: Apple Cinema Display

### Environment Information (please complete the following information)

```markdown
- macOS version:
- Mac model:
- MonitorControl version:
- Monitor(s):
- Monitor Cable(s)/Connection(s):
- Apple Silicon/M1 (yes or no):
```

**Comment by jacobgeorgeband** [comment]
Fixed my issue, set DDC max to 255 in "Displays" advanced settings of the monitor control app.

**Comment by waydabber** [comment]
Yes, this is the right solution to this issue, sorry for not responding earlier.
