### ISSUE TITLE
Can only control brightness with combined hard/soft dimming set

### ISSUE THREAD

**Issue by memeplex** [MonitorControl/MonitorControl#1510]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

I've a Samsung 4k 28'' U28e590d external screen connected through a Satechi HDMI-USBC adapter at 60hz.

I'm only able to get brightness control working if I enable the "Combine hardware and software dimming" setting, so I guess hardware dimming is not working.

### Steps to reproduce

I don't see how to add anything useful here.

### Expected behavior

I can control my monitor brightness using hardware dimming.

### Environment Information (please complete the following information)

```markdown
- macOS version: Sonoma 14.2.1
- Mac model: MBP M1 2020
- MonitorControl version: 4.2.0
- Monitor(s): Samsung 4k 28'' U28e590d
- Apple Silicon/M1 (yes or no): yes
```

**Comment by memeplex** [comment]
I tested this with BetterDisplay and it's the same.

**Comment by waydabber** [comment]
I recommend trying an USB-C to DisplayPort cable, that should work. USB-C to HDMI is a hit and miss. Some Samsungs however don't support DDC via DisplayPort but I think this display is not among them.

**Comment by memeplex** [comment]
Ok, thank you very much for the reply, my cable is pretty expensive and I remember it was hard to find at the time (most of them only work at 30hz), but I'm going to look at the options again. Anyway, is there any downside to software dimming? I believe you use a gamma table approach. Can it shrink the dynamic color range at low brightness perhaps? Is it safe for the screen?

**Comment by waydabber** [comment]
Macs output DisplayPort natively so an USB-C to DisplayPort cable will provide a native connection. USB-C HDMI cables/adapters contain a converter chip - many designs exist with various firmwares, some of them can translate DDC I2C communication properly, some don't.

Software dimming is fine, but it is better to dim the actual backlight. Software dimming with a fixed backlight will decrease the contrast ratio which not undesirable.

**Comment by memeplex** [comment]
Thanks again!
