### ISSUE TITLE
Allow changes of Input Via App

### ISSUE THREAD

**Issue by jdm0830** [MonitorControl/MonitorControl#1517]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

In the past I have used monitors that require me to press the buttons to switch between the various inputs. I'd do that because I had multiple machines connected to the screen. The reason I wont use a HDMI switcher is because most dont immediately support high refresh rates, resolutions, or in some cases DDC. I've been locked out in the past of switching inputs because the buttons broke. Maybe it was time to change montiors, but I am a buy it for life guy. The monitor worked, just on one channel.

### Describe the solution you'd like

make it so we can click a button or use a configurable key combo to switch screens. I use AIM OS KVMs to switch my keyboard mouse to my PS5. Id like a similar configurable combo to switch between inputs. 

### Describe alternatives you've considered

https://github.com/waydabber/m1ddc 
This tools seems to have the ability to implement it via a cli. I can create a script and store it locally. maybe set it to run via keycombos.

### Anything else?

I attached the links to implementations via a CLI tool. Love your tool. just discovered it. Was going to return my new LG I got on sale, but decided to keep it due to your tool.

**Comment by jdm0830** [comment]
its a dupe!
https://github.com/MonitorControl/MonitorControl/issues/720

**Comment by appdcs** [comment]
> Hi there, this feature is available for free in [BetterDisplay](https://betterdisplay.pro). Recommend trying that!

Input control is not available in BetterDisplay, via hotkeys, after the trial run ends.

I would recommend reopening this issue and making **simple** input switching available in MonitorControl.
