### ISSUE TITLE
Update error - monitorcontrol.app domain issue

### ISSUE THREAD

**Issue by n0rt0nthec4t** [MonitorControl/MonitorControl#1523]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Using 4.2.0, when check for updates, the app now constant reports "Updated Error" rather than "Latest version"

<img width="266" alt="Screenshot 2024-02-14 at 8 23 19 am" src="https://github.com/MonitorControl/MonitorControl/assets/19759130/a20b314b-ad15-4b12-bde3-da63d5893b30">

### Steps to reproduce

1. Go to Icon on menu bar
2. Click on "Check for Updates"

### Expected behavior

Update check should report latest version or new version

### Environment Information (please complete the following information)

```markdown
- macOS version: Sonoma 14.3.1
- Mac model: MacBook Air M1
- MonitorControl version: 4.2.0
- Monitor(s): Dell U2720Q
- Apple Silicon/M1 (yes or no): Yes
```

**Comment by CalHoll** [comment]
Also seeing this issue

**Comment by waydabber** [comment]
Hmm. There seems to be an issue with the monitorcontrol.app domain? @the0neyouseek - can you take a look?

**Comment by waydabber** [comment]
Ok, it seems like the monitorcontrol.app doman was expired and taken by a third party. It is now in a transfer period.The new owner's identity is not public. The registration was done via Cloudfare. Sent them an email regarding the issue, hopefully they will answer. Sadly there is a chance that the domain is lost.

**Comment by the0neyouseek** [comment]
@waydabber Everything should be okay as I was the one who transferred the domain (we previously used Google Domain but Google has stopped offering that service)
I'll take a look asap at the config to see what's wrong with it

**Comment by the0neyouseek** [comment]
I made the necessary changes and everything should be okay now

**Comment by waydabber** [comment]
All right, thanks @the0neyouseek. What a relief! 😅
