### ISSUE TITLE
Faster keyboard access to the program via Launchpad

### ISSUE THREAD

**Issue by forthrin** [MonitorControl/MonitorControl#1525]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

This is quite nitpicking, but typing "Mo" in Launchpad, macOS suggests "Activity Monitor" before "Monitor Control" until you type "Monitor C", far beyond others name collision (the most frequent encountered here is Calculator / Calendar).

Curiously, in Spotlight, "Mon" is enough. Don't know if this is based on historical user data or plain logic.

### Describe the solution you'd like

Is it possible to nudge Spotlight / Launchpad by the use of application metadata?

Suppose a name change is a tall order over such a minuscule issue.

### Describe alternatives you've considered

Rescue a small animal.

**Comment by waydabber** [comment]
Let's rescue a small animal. :)

But honestly, I am not sure how to fix this, I think Spotlight is trying to learn what the user wants, I don't know of any way to influence how it comes up with results. :)
