### ISSUE TITLE
Some monitors have an independent "backlight" option in its settings

### ISSUE THREAD

**Issue by bjhtldy** [MonitorControl/MonitorControl#1532]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

Some monitors have an extra "backlight" option in its settings alongside the usual brightness and contrast, which is used to adjust the LCD backlight panel's brightness, while the labelled "brightness" changes the whiteness/blackness of the displayed image instead (when adjusted, the entire screen appears as if it is covered in a white/black fog). This is often found in monitors sold by Chinese manufacturers.

### Describe the solution you'd like

Perhaps include a new functionality to accommodate this extra option?

### Describe alternatives you've considered

None, really

**Comment by waydabber** [comment]
If this can be controlled via DDC, then in advanced settings you can override the control code for DDC brightness to something else the display understands. Let me know if you have any info about it. It probably won't make into MonitorControl as we try keep things simple but I am always happy to add less mainstream and obscure features to https://github.com/waydabber/BetterDisplay.
