### ISSUE TITLE
Presets ,modes and monitor picture mode

### ISSUE THREAD

**Issue by xxDURGEXxx** [MonitorControl/MonitorControl#1536]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

I used to work in dark so ill keep my brightness and contrast low due to prevent eye strain. Many websites and forums dont have night mode feature, the white light will be very bright.Tto avoid that ill reduce my contrast low as possible . But when i want to watch movie or use my monitor in bright light i have to change the brightness and contrast every time, so i can see the display under bright lights. If there is option to set and save settings as modes which can be toggle will be very convinient to use this app and it makes much more sence to have that feature .

### Describe the solution you'd like

- Able to  save brightness and contrast setting so could be switched with just click of button.
- If added shortcut to toggle different preset setings with hotkey will be very convinient to use.
- If able to extract monitor's picture modes which was set by the  manufacturer and also toggle it with hotkey will be sick.

### Describe alternatives you've considered

- Able to  save brightness and contrast setting so could be switched with just click of button.
- If added shortcut to toggle different preset setings with hotkey will be very convinient to use.
- If able to extract monitor's picture modes which was set by the  manufacturer and also toggle it with hotkey will be sick.

**Comment by waydabber** [comment]
Presets are not planned to be added to MonitorControl, however https://github.com/waydabber/BetterDisplay will have this feature in an upcoming release. Meanwhile you can use Shortcuts or `betterdisplaycli` to create any kind of shortcut for brightness and various other settings with https://github.com/waydabber/BetterDisplay.
