### ISSUE TITLE
auto min brightness when display has no windows on it

### ISSUE THREAD

**Issue by realies** [MonitorControl/MonitorControl#1575]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

tick box

### Describe alternatives you've considered

automation

**Comment by waydabber** [comment]
I don't think this will be added to MonitorControl but might be a good feature for BetterDisplay - https://github.com/waydabber/BetterDisplay/issues/3113
