### ISSUE TITLE
Keep brightness in sync between MacBook and external Display

### ISSUE THREAD

**Issue by svh1985** [MonitorControl/MonitorControl#159]
I would like to request a feature where the external monitor syncs itself to the macbook's display.
This way you can use the MacBook's Touchbar and it's Ambient sensor.

**Comment by lougreenwood** [comment]
This would be super useful!

**Comment by JoniVR** [comment]
The problem with this is that different display have different amounts of brightness levels though, right? 

So for example, my 16" has a 500 nits peak brightness screen while my LG Ultrawide only has 300 nits peak brightness. If we sync both to 100%, they still won't have the same amount of brightness (500 nits vs 300 nits).

**Comment by svh1985** [comment]
Yeah thats true, but better than nothing. Maybe if there is some sort of ratio or offset added like in the brightness menulet. Although I think it should work a bit better than that.

https://github.com/Kalvin126/BrightnessMenulet

![image](https://user-images.githubusercontent.com/5213210/72137263-cad9db80-338a-11ea-9e28-35aea9f2902e.png)

**Comment by L-C-P** [comment]
Hi,
great Tool. And I agree, a sync setting would be perfect. In other case I can also press the button on my monitor. Maybe like Apple is doin. If the reported environment lumina is dark and the user manual controls the monitor to a value, store the ration. If the environment lumina is more in the bright area, take also the user setting. Then you can calculate the max and min values for the external monitor based on the current environment lumina.

**Comment by L-C-P** [comment]
I just found https://lunar.fyi
There are more or less doing it. But the calculation is not working very well. But from there: A Bézier curve would be a good way for the setting and calculation.

**Comment by steo-ml** [comment]
Has this been addressed in v4.0.0? I've seen some similar settings, but nothing exactly like OP has mentioned.
