### ISSUE TITLE
Activate / Deactivate any monitor

### ISSUE THREAD

**Issue by funbben** [MonitorControl/MonitorControl#16]
Feature request : be able to Activate / Deactivate any monitor

Here is the the use case :
When my external monitor is plugged, I deactivate my mac internal monitor, using shortcut 
(I use SwitchResX to do that)
Also one thing to be careful about with SwitchResX, I sometimes fall in a situation where not display I working. For instance, when unplugging an external display, or when the computer go out of sleep.
The nice thing with SwitchResX, is that you can define any display scenario and assigne a shortcut for it.

Here is my setting : 
<img width="421" alt="capture d ecran 2018-02-19 a 07 29 58" src="https://user-images.githubusercontent.com/30370246/36364827-bc77a752-1546-11e8-8bc8-7df1a9217601.png">

**Comment by the0neyouseek** [comment]
Hi @funbben,

By default the app ignore any built-in screen (as it can be controlled normally) but I'm not sure what you mean by "deactivate" ?

If you want to disable the screen, as in, it not showing in the menu and not responding to shortcut keys, you can already do that by unchecking the box next to it's name in the Preference window. 

Do you want this settings to be accessible in the menu directly or something else entirely ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by funbben** [comment]
By default MacOs will not let you turn-off built in monitor. This is my reason to use SwitchResX.

So I created a shortcut ⌘ + < to turn-of / Deactivate the internal display, and activate my external one
I created another shortcut to activate both display
I created a final one to activate only internal display.

Is it more clear ? 

Si tu veux on peut échanger en français, ici ou ailleurs

**Comment by the0neyouseek** [comment]
J'ai bien compris l'utilité de SwitchResX mais du coup j'ai du mal à voir l'intérêt avec MonitorControl... 
Ton but final c'est que l'app puisse faire quoi exactement ? La même chose que SwitchResX ? Avoir des raccourcis pour des scénarios d'écrans à allumer/éteindre ? 
Qu'est-ce qui ne fonctionne pas pour toi dans les fonctions actuelles 🙂 ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by funbben** [comment]
For english readers : I would like to only use MonitorControl and get rid of SwitchResX

Ce que j'aimerai c'est pouvoir me passer de SwitchResX qui à la base est une application pour gérer des résolutions. Je trouve que la vocation de MonitorControl répond mieux au Use Case "activer / désactiver des écrans"

A titre d'illustration voici mon installation :
![img_3984_1](https://user-images.githubusercontent.com/30370246/36530128-8d3096f4-17ba-11e8-8de8-7eeee3a9c706.jpg)
