### ISSUE TITLE
MonitorControl unable to open after setting Min. DDC to 5000

### ISSUE THREAD

**Issue by kzemin** [MonitorControl/MonitorControl#1600]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

When setting Min. DDC for a monitor, the app crashes and doesn't get to open again. 
Running the App's executable under Contents > MacOS doesn't work either.

### Steps to reproduce

1. Go to settings
2. Select Displays tab
3. Under a monitor brightness setting,  type the Min. DDC to 5000 and Max. DDC to 255.

### Expected behavior

App wouldn't crash and inhibit me from entering 5000 as a value.

### Anything else?

**Terminal output after running MacOS executable:** 
/Applications/MonitorControl.app/Contents/MacOS/MonitorControl ; exit;          
user@User-Macbook ~ % /Applications/MonitorControl.app/Contents/MacOS/MonitorControl ; exit;
zsh: trace trap  /Applications/MonitorControl.app/Contents/MacOS/MonitorControl

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

https://github.com/user-attachments/assets/6dd3c157-82df-4229-a7fa-daa6db10a91d

### Environment Information (please complete the following information)

```markdown
- macOS version: Sonoma 14.5
- Mac model: M1 Air
- MonitorControl version: 4.2.0
- Monitor(s): Apple LED Cinema Display (27-inch)
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
I recommend deleting app settings (use the `defaults delete` command with the bundle identifier).

**Comment by kzemin** [comment]
Yey! That worked. I had to do `defaults delete app.monitorcontrol.MonitorControlLite` for my case.
Thanks you.

**Comment by waydabber** [comment]
Note to self: this is a valid bug, a proper min/max check is needed.

**Comment by waydabber** [comment]
Not sure what's wrong, I just entered 5000 to DDC min, 255 to DDC max and the app just went on fine, could start up etc. I think it's handled properly. Will reopen this is it's still a  problem.

<img width="842" alt="Screenshot 2024-10-04 at 12 14 52" src="https://github.com/user-attachments/assets/137a4703-1cae-4d65-acfd-c5baaaa64968">
