### ISSUE TITLE
Unable to control sound versions 4.2.0-4.1.0

### ISSUE THREAD

**Issue by corgiyusezu** [MonitorControl/MonitorControl#1605]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

MacOS Monterey version 12.6.1 M1 pro cannot set custom shortcut keys to control MAC sound size

### Steps to reproduce

设置-键盘-音量控制（仅DDC)：自定义快捷键   设置完成后 无法调用

### Expected behavior

cannot set custom shortcut keys to control MAC sound size

### Anything else?

`

### Environment Information (please complete the following information)

```markdown
- macOS version:12.6.1
- Mac model:M1 PRO
- MonitorControl version:MAC
- Monitor(s):MAC
- Apple Silicon/M1 (yes or no): YES
```

**Comment by corgiyusezu** [comment]
> ### Before opening the issue, have you...?
> * [x]  Searched for existing issues
> * [x]  Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
> * [x]  Updated MonitorControl to the latest version (if applicable)
> 
> ### Describe the bug
> MacOS Monterey version 12.6.1 M1 pro cannot set custom shortcut keys to control MAC sound size
> 
> ### Steps to reproduce
> Settings - Keyboard - Volume Control (DDC only): Custom shortcut key settings cannot be called after completion
> 
> ### Expected behavior
> cannot set custom shortcut keys to control MAC sound size
> 
> ### Anything else?
> `
> 
> ### Environment Information (please complete the following information)
> ```
> - macOS version:12.6.1
> - Mac model:M1 PRO
> - MonitorControl version:MAC
> - Monitor(s):MAC
> - Apple Silicon/M1 (yes or no): YES
> ```

**Comment by real-felix** [comment]
Hey, same error here. My monitor is an Android smart TV in PC mode, connected through HDMI. When I change the volume with the keyboard, I see the volume bar going up and down, but it doesn't actually change the monitor's volume.

**Comment by waydabber** [comment]
Not all displays support DDC volume control. TVs generally don't support DDC at all.

Use this thread to generally talk about DDC volume control support:

https://github.com/MonitorControl/MonitorControl/discussions/1597
