### ISSUE TITLE
Crash when pressing Brightness keys

### ISSUE THREAD

**Issue by 343max** [MonitorControl/MonitorControl#1608]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Whenever I press the Brightness Keys on the keyboard MonitorControl crashes

### Steps to reproduce

- Open MonitorControl
- press brightness key
- see MonitorControl crash (menu item disappears, prefs window disappears when still open)

### Expected behavior

The app would allow me to change the brightness without crashing

### Environment Information (please complete the following information)

```markdown
- macOS version: 15.0
- Mac model: MacBook Air M2
- MonitorControl version: 4.2.0 Build 7048
- Monitor(s): builtin display, LG HDR 4K
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Hi there, the current version is not compatible with Sequoia. Please use this instead: https://github.com/MonitorControl/MonitorControl/issues/1570
