### ISSUE TITLE
Crashing when changing brightness level

### ISSUE THREAD

**Issue by guilherme-n** [MonitorControl/MonitorControl#1609]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

The app crashes when I try to change the brightness of secondary monitor (Macbook retina display)

### Steps to reproduce

- Hold control + press brightness key
![macbook-keyboard](https://github.com/user-attachments/assets/044ca697-47c9-414d-80c0-e0286d0b4219)

OR
- Use the slider from menubar icon
![pic1](https://github.com/user-attachments/assets/8512d7a0-7a3d-4d4e-9538-e4bc0bed680f)

### Expected behavior

Brightness changed

### Anything else?

It used to work before upgrading to macOS Sequoia 15.0

### Environment Information (please complete the following information)

```markdown
- macOS version: 15.0
- Mac model: macbook m3 pro
- MonitorControl version: 4.2.0
- Monitor(s): LG HDR WFHD
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Hi there, please download the Sequoia compatible version currently available here:

https://github.com/MonitorControl/MonitorControl/issues/1570
