### ISSUE TITLE
Not working in macOS Sequoia

### ISSUE THREAD

**Issue by shipotech** [MonitorControl/MonitorControl#1611]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Hi, first of all thank you for your hard work. I have been using this for a long time.

After updating to macOS Sequoia, the monitor control app is no longer working for the MacBook Air M1 built-in display. 

If I try to manipulate the brightness of my built-in display, (either from the keyboard shortcut or the slider in the menu bar), the app just "crashes" (it closes itself) without changing the brightness.

Weird thing, it does work with my external monitor (LG 32 UN550).

<img width="725" alt="image" src="https://github.com/user-attachments/assets/2755cb1f-52b7-4c64-94e8-2542a4297324">

<img width="717" alt="image" src="https://github.com/user-attachments/assets/f621b3aa-57e0-4fa1-8d24-2244a05e44da">

<img width="722" alt="image" src="https://github.com/user-attachments/assets/3c5444ac-0be5-49d4-a771-d5d3fc35ae3e">

### Steps to reproduce

1. Open the monitor control app
2. Either click on the icon on the menu bar and slide the brightness for the built-in retina display
3. The app closes itself and the brightness remains the same 

### Expected behavior

The app manages the brightness as it was before (please 🥹)

### Environment Information (please complete the following information)

```markdown
- macOS version: 15.0 Sequoia 
- Mac model: Macbook Air M1 (2020)
- MonitorControl version: Version 4.2.0 build 7048
- Monitor(s): LG 32 UN550 (working), Built-in Retina display (Not working)
- Apple Silicon/M1 (yes or no): yes
```

**Comment by shipotech** [comment]
https://github.com/user-attachments/assets/67229c3e-67da-4584-99a5-be31a4f04ab7

**Comment by ewerx** [comment]
I have the same issue with M1 MacBook Pro and Dell UltraSharp monitor. App closes/crashes immediately when trying to adjust the brightness on the built-in display (via UI or hotkeys), but adjusting the brightness on the Dell works.

**Comment by waydabber** [comment]
Hi guys - take a look at this please: https://github.com/MonitorControl/MonitorControl/issues/1570 :)
