### ISSUE TITLE
Problem after Sequoia update

### ISSUE THREAD

**Issue by alexfilothodoros** [MonitorControl/MonitorControl#1612]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

After updating to Sequoia, there is an issue.
First of all the app will not start after logging in.
Then, after I start it manually I can change the brightness of the secondary monitor.
However, if I change the brightness of the main built in display, the app crashes.
 I am using an M2 14" Mac Pro.

### Steps to reproduce

1. Update to Sequoia.
2. Start the app manually.
3. Change the brightness of the built-in display.

### Expected behavior

The app should not crash.

### Environment Information (please complete the following information)

```markdown
- macOS version: 15.0
- Mac model: 14" M2 Pro 
- MonitorControl version: 4.2.0
- Monitor(s): built-in, PHL 273V7
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Please take a look at this: https://github.com/MonitorControl/MonitorControl/issues/1570
