### ISSUE TITLE
Stopped working on adjusting built in monitor brightness after updating to MacOS Sequoia

### ISSUE THREAD

**Issue by pureve** [MonitorControl/MonitorControl#1614]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

After updating to MacOS Sequoia, the application crashes (the process terminates) whenever I try to adjust the brightness of the built-in monitor on both my MacBook Air M1 and MacBook Pro M1 Pro. However, adjusting the brightness on external displays still works as expected. Prior to the update, the brightness control for the built-in display functioned correctly, but now no brightness changes are applied through the app, and the app crashes when attempting to make adjustments.

### Expected behavior

The application should successfully adjust the brightness of both the built-in monitor and the external display.

### Environment Information (please complete the following information)

```markdown
- macOS version: 15.0 Sequaio
- Mac model: Macbook Air M1
- MonitorControl version: 4.2.0 Build 7048
- Monitor(s): LG HDR 4k and built-in Retina Display
- Monitor Cable(s)/Connection(s): USB-C
- Apple Silicon/M1 (yes or no): yes
```

**Comment by davidbonnet** [comment]
Witnessing the exact same behaviour (silently quits as soon as the built-in display of the MacBook becomes active, e.g. by moving the cursor on it and clicking).

**Comment by pureve** [comment]
> Witnessing the exact same behaviour (silently quits as soon as the built-in display of the MacBook becomes active, e.g. by moving the cursor on it and clicking).

I found a temporary workaround for this issue. This one isn't an official build but it works as expected 😄 
https://github.com/MonitorControl/MonitorControl/issues/1570#issue-2346240609

**Comment by waydabber** [comment]
Right, you need to use that build. :)
