### ISSUE TITLE
Crash when assigning to start at login

### ISSUE THREAD

**Issue by zywhin** [MonitorControl/MonitorControl#1615]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

When selecting "Start at log" from the General page the app freezes while displaying rainbow loading wheel. Only way to fix it was to force quit from activity monitor where the prosses is in red indicating an issue.

### Steps to reproduce

1. start app and allow access to accesability.
2. Go to Prefrences.
3. Main page "General will pop up.
4. In Genral go to Application, and check the box labeled "Start at Login.

### Expected behavior

When hovering mouse over window, a loading symble will appear. Only way to fix is by force quitting proccess through Activity Monitor where the process will be in red and not the regular whitce text. 

I you try to forcequit through the force quit application in the top right Apple logo, the application will not appear in the list.

### Anything else?

NA

### Environment Information (please complete the following information)

```markdown
- macOS version: 15.o
- Mac model: MacBook Pro (16-inch, 2021)
- MonitorControl version: v4.3.1-beta
- Monitor(s): Xiaomi G34WQI-EU WQHD
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Just checked the version, seems to work fine so it might be an installation specific issue. However if this method fails on your config, you can simply grab MonitorControl and add it to the Login Items list.
