### ISSUE TITLE
MacOS 15 kills the Monitor Control program every once a while

### ISSUE THREAD

**Issue by GaryKong1029** [MonitorControl/MonitorControl#1616]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

It's closed by itself a few times a day. Start at login has been enabled and the app is up to date

### Steps to reproduce

It appears few time a day randomly

### Expected behavior

Fix the issue

### Environment Information (please complete the following information)

```markdown
- macOS version: 15.0
- Mac model: 2021 Macbook Pro 14 inch
- MonitorControl version: 4.2.0
- Monitor(s): LG 27BP85U
- Apple Silicon/M1 (yes or no): yes
```

**Comment by ianmasters** [comment]
Also experiencing this exact same issue.

- Intel iMac 2019.
- MonitorControl 4.2.0.

**Comment by elchead** [comment]
same here.
- macOS 15.0
- Macbook M2 Pro

**Comment by waydabber** [comment]
Try using this: https://github.com/MonitorControl/MonitorControl/issues/1570

**Comment by GaryKong1029** [comment]
> Try using this: #1570

Thanks you for the contribution! May I ask when the official build would be available for macOS sequoia support

**Comment by waydabber** [comment]
I am not sure, there is no timeline, but plan to provide one sooner or later. It will probably be the same as the unofficial one though (except with possibly re-enabled update capability but due to the new signatures 4.2.0 won't be able to update to that anyway), so no much reason for waiting.
