### ISSUE TITLE
Custom keyboard shortcuts don't work on Sequoia

### ISSUE THREAD

**Issue by waydabber** [MonitorControl/MonitorControl#1623]
### Discussed in https://github.com/MonitorControl/MonitorControl/discussions/1622

<div type='discussions-op-text'>

<sup>Originally posted by **samfriedmann** September 26, 2024</sup>
<img width="842" alt="Screenshot 2024-09-26 at 3 46 19 PM" src="https://github.com/user-attachments/assets/3968af14-0d2a-4c0c-9489-5626b746b726">

I do not have the ability to set keyboard shortcuts. I am on Sequoia 15.0. I have tried quitting and restarting the app. This issue persists on both 4.3 and 4.3.1

<img width="392" alt="Screenshot 2024-09-26 at 3 49 47 PM" src="https://github.com/user-attachments/assets/43afb933-7b12-46af-9c00-81a98328d899"></div>

**Comment by waydabber** [comment]
About the random opening issue: are you using the 4.3.1 version? The keyboard shortcuts won't work with that version either.

**Comment by samfriedmann** [comment]
Thanks for the quick response and fix. Works like a charm! Really appreciate the work you've put into this project.
Also, just so you know, it looks like the "General menu items style" settings are mixed up again: "Show as icons" shows the text ("Preferences...", "Check for updates...", "Quit"), whereas "Show as text" displays icons.
