### ISSUE TITLE
MonitorControl quits everytime iMac built-in monitor's brightness is adjusted

### ISSUE THREAD

**Issue by kevinyuan** [MonitorControl/MonitorControl#1624]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

MonitorControl quits everytime when adjust the built-in iMac monitor, through either of the following:

1). Apple Keyboard bridgness key is pressed when mouse cursor is on the iMac monitor
2). Adjust iMac monitor's bridgeness through the MonitorControl's context menu

Howevery, adjust bridgeness for the external HP-U28 monitor (through either way) doesn't have any problem.

### Steps to reproduce

1. Open MonitorControl
2. Adjust iMac monitor's bridgeness throught above 1) or 2) 

### Expected behavior

MonitorControl don't quit.

### Anything else?

no

### Environment Information (please complete the following information)

```markdown
- macOS version: 15.0 (24A335)
- Mac model: iMac 24-inch, M1, 2021
- MonitorControl version: 4.2.0 Build 7048
- Monitor(s): 2 (iMac 24-inch, HP U28)
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
https://github.com/MonitorControl/MonitorControl/issues/1570
