### ISSUE TITLE
Command+P Keyboard shortcut for Print not Working on some configurations?

### ISSUE THREAD

**Issue by pnfn** [MonitorControl/MonitorControl#1635]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Hit Cmd+P for print window in macOS Sonoma 14.6.1 won't launch the Print window. Notice that Cmd+P is a common shortcut for printing purposes in several apps, including the macOS itself.

### Steps to reproduce

With the MonitorControl, hit Cmd+P shortcut on the keyboard. Nothing happens. Exit MonitorControl then hit Cmd+P again, then the Print window is shown.

### Expected behavior

As Cmd+P shortcut is typed on the keyboard, the Print window shall appear.

### Environment Information (please complete the following information)

```markdown
- macOS version: 16.4.1
- Mac model: MacBook Air 13" M2
- MonitorControl version: 4.2.0 b7048
- Monitor(s): LG 32UL750-W
- Apple Silicon/M1 (yes or no): yes M2
```

**Comment by pnfn** [comment]
Congrats for that great app!

**Comment by waydabber** [comment]
I think the default keystroke for that is Command+P.

**Comment by pnfn** [comment]
> I think the default keystroke for that is Command+P.

Well noted. Is Cmd+P indeed.  I've changed the ticket. Thank you!

**Comment by waydabber** [comment]
Ok, but then this still does not work? I can't seem to reproduce the issue (the shortcut works fine while the app is running). But I can record this up as a bug if you wish, just not sure it's not something else that causes the issue + if it cannot be reproduced, then the Issue ticket will probably just languish here. :)

**Comment by pnfn** [comment]
> Ok, but then this still does not work? I can't seem to reproduce the issue (the shortcut works fine while the app is running). But I can record this up as a bug if you wish, just not sure it's not something else that causes the issue + if it cannot be reproduced, then the Issue ticket will probably just languish here. :)

I'm still getting the same (no print window) result. I just wrote it wrong (Ctrl) when posting the issue first hand. Do you think other colleagues here on the channel could try to reproduce this?
PS. I have no other apps running in background and I can use Cmd+P to view the print window when I quit MonitorControl. Then just by starting MonitorControl again I lose the shortcut. Additionally, I verified in macOS if I have another shortcut function mapped to Cmd+P, which could be causing conflict, but I don't.

**Comment by waydabber** [comment]
All right. I am not entirely sure about the reasons (are you sure you did not use it as a custom shortcut in the app for example?) and how to reproduce it, but I tag it as a bug then for now.

**Comment by pnfn** [comment]
> All right. I am not entirely sure about the reasons (are you sure you did not use it as a custom shortcut in the app for example?) and how to reproduce it, but I tag it as a bug then for now.

Thanks.
PS. The app was installed on a fresh macOS 14.6.1 install. No previous shortcuts for Cmd+P created.

**Comment by waydabber** [comment]
I see. I am sorry, I am simply unable to reproduce the issue. What I do is this:

1) Remove the app and remove accessibility permissions
2) Install the app
3) Add accessibility permissions so native keyboard control works
4) Start the app
5) Open a Safari webpage and hit Command+P

Result: Printer dialog opens

Am I doing something differently?

**Comment by pnfn** [comment]
> I see. I am sorry, I am simply unable to reproduce the issue. What I do is this:
> 
> 1. Remove the app and remove accessibility permissions
> 2. Install the app
> 3. Add accessibility permissions so native keyboard control works
> 4. Start the app
> 5. Open a Safari webpage and hit Command+P
> 
> Result: Printer dialog opens
> 
> Am I doing something differently?

Hey, Waydabber. Just installed the v4.3.2 and now the Cmd+P works! Notice that before that I had reinstalled the v4.2.0 and still had the Cmd+P problem. You may close this issue if you want, or keep it for other users to help investigate or try to reproduce. Thanks for your help!

**Comment by waydabber** [comment]
Nice! :)
