### ISSUE TITLE
app crashing 

### ISSUE THREAD

**Issue by wedishprocentahc** [MonitorControl/MonitorControl#1643]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

app keeps crashing (without crash pop-up btw) when I'm trying to change my macbook's air m2 monitor brightness (the crash doesn't happen when using the slider on my acer monitor)

### Steps to reproduce

1. open monitor control manually (cause it crashed b4)
2. click menu bar icon
3. change macbook's built-in monitor brightness using the slider

### Expected behavior

i except the brightness to be changed without crashing

### Anything else?

when app crashes, settings from it disable, so my monitor goes full bright and blinds me xD

### Environment Information (please complete the following information)

```markdown
- macOS version: sequoia 15.0
- Mac model: macbook air m2 (cheapest version)
- MonitorControl version: 4.2.0
- Monitor(s): Acer KG251Q
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Hi there - simply use the v4.3.2 version! Check the releases page! :)
