### ISSUE TITLE
App menu in the menu bar is showing icons when text is selected — and vice versa

### ISSUE THREAD

**Issue by guibracco** [MonitorControl/MonitorControl#1644]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

This is a minor bug.

I noticed that the app menu viewing preferences seem to be switched, showing icons when "Show as text" is selected and text when "Show as icons" is selected.

### Steps to reproduce

1. Go to the app menu in the menu bar.
2. Click in Preferences.
3. Go to the App menu tab
4. In "General menu item style", select "Show as icons" or "Show as text".
5. Check the app menu in the menu bar again.

### Expected behavior

The app shows icons when "Show as icons" is selected and text when "Show as text"is selected.

### Anything else?

<img width="736" alt="Screenshot 2024-10-04 at 10 38 31" src="https://github.com/user-attachments/assets/49a857cc-7005-49c0-a4fe-034996aa4f13">

<img width="735" alt="Screenshot 2024-10-04 at 10 39 33" src="https://github.com/user-attachments/assets/55d494cf-acf2-44ec-b755-4dc81a2721ac">

### Environment Information (please complete the following information)

```markdown
- macOS version: 10.0.1 Sequoia
- Mac model: MacBook Pro M1 Pro (14-inch, 2021)
- MonitorControl version: v4.3.2
- Monitor(s): Philips 329M1RV
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Argh. Indeed. I fixed this once but now it regressed lol. All right, will fix it again! :)

**Comment by guibracco** [comment]
Thought so! 😅

Felt like trying to help and fix it myself, but data guy here, zero Swift experience. Better safe than sorry. 🫠
