### ISSUE TITLE
App crashes when adjusting MacBook screen brightness while using external display as main

### ISSUE THREAD

**Issue by ivangonzalezg** [MonitorControl/MonitorControl#1649]
### Before opening the issue, have you...?

- [x] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

I have my external monitor set as the main display. The brightness adjustment works perfectly for the external monitor. However, when I try to adjust the brightness of the built-in MacBook display, the app crashes and stops controlling the brightness of my monitor. I have the setting enabled to adjust the brightness of the display where the mouse cursor is located.

### Steps to reproduce

1. Set an external monitor as the main display.
2. Enable the setting that adjusts brightness based on the mouse cursor location.
3. Adjust the brightness of the external monitor (works as expected).
4. Move the mouse to the built-in MacBook screen and try to adjust the brightness.
5. Observe that the app crashes and stops working.

### Expected behavior

The app should adjust the brightness of the built-in MacBook display without crashing, while still retaining control over the brightness of the external display.

### Anything else?

I don't know if it's the same issue as this one https://github.com/MonitorControl/MonitorControl/issues/1643

### Environment Information (please complete the following information)

```markdown
- macOS version: Sequoia 15.0.1 (24A348)
- Mac model: MacBook Pro 13-inch, 2020, Four Thunderbolt 3 ports
- MonitorControl version: 4.2.0 Build 7048
- Monitor(s): SAMSUNG S24C432GAN https://www.amazon.com/dp/B0CNDDGPYY
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment]
Try the v4.3.3 version. :)
