### ISSUE TITLE
No ability to change volume with keyboard

### ISSUE THREAD

**Issue by reeneex70** [MonitorControl/MonitorControl#1653]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

i´m running Sequoia 15.0.1 on a MacMini M2 Pro, connected via HDMI with a LG32UN88A. The keyboard is a Magic A2520 connected via Apple bluetooth. 
In the beginning everything worked fine. I could change the Brightness (F1 & F2) and the volume (F10-F12) via keyboard. 
After Sequoia update, Fn+F1 is ending the app and then I get on volume only the volume sign (Volume on/off) on the screen, but not louder or quieter. 
If I press straight fn+F11 or 12, there is no reaction, but the app is still running. 

If the app is off, the brightness controls worked as suspected. The volume control still nothing.

### Expected behavior

I expect a agin working Loud control via keyboard

### Environment Information (please complete the following information)

```markdown
- macOS version: Sequoia 15.0.1
- Mac model: MacMini M2 Pro 
- MonitorControl version: 4.2.0
- Monitor(s): LG32UN88A
- Monitor Cable(s)/Connection(s): HDMI
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Please upgrade to the latest version and if it still does not work, redo accessibility permissions. :)
