### ISSUE TITLE
Monitor App crashes when using (magic) Keyboard keys to control lights

### ISSUE THREAD

**Issue by Euro3000** [MonitorControl/MonitorControl#1661]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Hey
I use a Dell U2720Q connected to my M1 2020.
When I try to use my (magic) keyboard to adjust the brightness of my screens, the app crashes. (Just disappears from the menu bar, without any error or such). When I use the touchbar of my M1 it doesnt crash.
When I try to adjust the brightness of my laptop monitor in the app, it crashes. When I adjust the brightness of my monitor it doesnt crash. 

### Steps to reproduce

Open app, adjust brightness of laptop via app or keyboard it crashes.

### Expected behavior

Use my keyboard to adjust brightness. Use the slider in the menu to adjust brightness of my laptop.

### Environment Information (please complete the following information)

```markdown
- macOS version: 15.0.1
- Mac model: 13-inch, M1, 2020
- MonitorControl version: Latest
- Monitor(s): Dell U2720Q 
- Apple Silicon/M1 (yes or no): Yes
```

**Comment by waydabber** [comment]
Try to update to the latest version and see if the issue is resolved. https://github.com/MonitorControl/MonitorControl/releases
