### ISSUE TITLE
Crash - 2 screens control / after OSX Sequoia update

### ISSUE THREAD

**Issue by renanmalatonnncapital** [MonitorControl/MonitorControl#1662]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

I have 2 screens at home and 3 at the office. 
I can control my external screens brightnesses well
but when I move the slider for my own macbook screen is crashing recently after Sequoia update... 

Here is a gif showing 
![ezgif-2-e75e3fc679](https://github.com/user-attachments/assets/79dc8eee-90d1-462e-adae-35bb0045ba06)

I though that was an update version requirement but im all updated

anybody experiencing this issue?

### Steps to reproduce

1. open the app in a Macbook with OSX Sequoia 15.0.1 with an external screen
2. Control the external screen brightness
3. Move the slide control of macbook own screen - here is crashing

### Expected behavior

Control of both sliders without crash and the Icon remains in the top settings Mac bar

### Environment Information (please complete the following information)

```markdown
- macOS version: 15.0.1
- Mac model: M1 MAX 2021
- MonitorControl version: 4.2.0
- Monitor(s): Apple Cinema Display / Macbook 
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Try upgrading to the latest app version first and see whether this fixes the issue. https://github.com/MonitorControl/MonitorControl/releases

**Comment by renanmalatonnncapital** [comment]
Fixed. thanks!

I did a symbolic contribution. Your app is really useful to me to reach the full brightnesses of Apple Cinemas Displays

**Comment by renanmalato** [comment]
Fixed. thanks!

I did a symbolic contribution. Your app is really useful to me to reach the full brightnesses of Apple Cinemas Displays

**Comment by waydabber** [comment]
Thank you! :)
