### ISSUE TITLE
F1 F2 not work macos 15.1 M2

### ISSUE THREAD

**Issue by zhu-hongwei** [MonitorControl/MonitorControl#1664]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

<img width="597" alt="image" src="https://github.com/user-attachments/assets/87767886-fdc0-4f9e-aa60-a3c43ded4040">

<img width="730" alt="image" src="https://github.com/user-attachments/assets/5b561929-7f11-4412-9100-d6a70499f0f8">

### Expected behavior

Today I just updated macOS from 14.4 to 15.1. Then I found that the F1 and F2 shortcut keys are not working properly.

### Environment Information (please complete the following information)

```markdown
- macOS version: 15.1
- Mac model: mac mini
- MonitorControl version:4.3.3
- Monitor(s): 
- Monitor Cable(s)/Connection(s):
- Apple Silicon/M1 (yes or no): yes M2
```

**Comment by zhu-hongwei** [comment]
It's amazing—now the F1 and F2 keys are working properly!

**Comment by waydabber** [comment]
Nice! :)
