### ISSUE TITLE
App keeps on asking Accessibility access every start even if it already allowed.

### ISSUE THREAD

**Issue by willerbee** [MonitorControl/MonitorControl#169]
![ss1](https://user-images.githubusercontent.com/10969215/72061358-ab9e6800-3310-11ea-97a2-9fc7181385dd.jpg)

![ss2](https://user-images.githubusercontent.com/10969215/72061343-a3dec380-3310-11ea-8c49-d014a58d943b.jpg)

Same goes for other forks, it always ask for accessibility, except for JonyVR's 1.3.1 (the only one that doesn't seem to ask after allowing)

OS: Mojave 10.14.6

**Comment by JoniVR** [comment]
Have you tried removing it from the list and then adding it again?

**Comment by willerbee** [comment]
Yep, did that. I also tried removing it, closing the app, adding the app by dragging the app to the list (and also another round using + button) before I started the app. It's as if the app doesn't know that it has already been allowed. Your 1.3.1 seems to have no problems.

**Comment by JoniVR** [comment]
Can you test if the hotkeys actually work regardless? If they do then it's probably a bug with the dialog itself.

**Comment by willerbee** [comment]
Nope, hotkeys doesn't work. (but in your 1.3.1 it does)

**Comment by JoniVR** [comment]
Seems to be happening on Catalina too for some people. Will have to look into it in the future.

**Comment by willerbee** [comment]
God bless you

**Comment by JoniVR** [comment]
Hi, is this still an issue?

**Comment by willerbee** [comment]
Hi Joni, no this is fixed <3 thank you

**Comment by JoniVR** [comment]
Glad to hear! 🙂

**Comment by MahatmaFatalError** [comment]
This issue re-appears with macOS 12.2 and MonitorControl 4.0.2

**Comment by waydabber** [comment]
Hi, this is a known macOS bug. Drag the MonitorControl app from the Applications folder into the list of approved apps even if MonitorControl is already listed there, that should fix it.

**Comment by MahatmaFatalError** [comment]
> Hi, this is a known macOS bug. 

Is there already a radar https://openradar.appspot.com/ filed?

> Drag the MonitorControl app from the Applications folder into the list of approved apps even if MonitorControl is already listed there, that should fix it.

Thx, will try.

**Comment by waydabber** [comment]
I don't know. It's been like this since the feature appeared in macOS. :)
