### ISSUE TITLE
App quits when changing main display's (Mac) brightness

### ISSUE THREAD

**Issue by allen-liaoo** [MonitorControl/MonitorControl#1699]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

When plugged into am external display and I try to change my Mac's own display's brightness, the app quits immediately. It has no problem changing the external display's brightness, whether it is software-controlled or DDC. If no external; display is connected, the problem doesn't occur. "Screen to control" setting doesn't change the bugged behavior either.

### Steps to reproduce

1. Connect an external display
2. Change Mac's display brightness
3. See that the app quits

### Expected behavior

The app should remain open

### Environment Information (please complete the following information)

```markdown
- macOS version: Sequoia 15.1.1
- Mac model: M1, 2020
- MonitorControl version: 4.2.0 Build 7048
- Monitor(s): Color LCD (Mac's display), DELL P2213
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
You need to upgrade to the latest version (auto update won't work on 4.2.0).
