### ISSUE TITLE
App not working for Samsung M8 (M80D) 32inch monitor

### ISSUE THREAD

**Issue by pankajet** [MonitorControl/MonitorControl#1711]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

App not working to control volume for Samsung M8 (M80D) 32inch monitor. But app was able to control brightness 

### Expected behavior

Volume +/- suppoes to work with keyboard. 

### Anything else?

No

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.7.6
- Mac model: Macbook Pro 15inchs (2016)
- MonitorControl version: 4.3.3
- Monitor(s): Samsung M8 (M80D)
- Monitor Cable(s)/Connection(s): USB Type C to C
- Apple Silicon/M1 (yes or no): No
```

**Comment by waydabber** [comment]
See this: https://github.com/MonitorControl/MonitorControl/discussions/1077

**Comment by pankajet** [comment]
I tried many possible settings but didnot work. Tried updated display driver as well but did not work.
