### ISSUE TITLE
Thank you!!!

### ISSUE THREAD

**Issue by shamilovtim** [MonitorControl/MonitorControl#173]
this is amazing. so glad to have native controls on my 32UD99W. LG should donate to everyone who has contributed to this application.

**Comment by the0neyouseek** [comment]
@shamilovtim Thanks for the kind words !
And really, @JoniVR & @reitermarkus have put a lot of effort into making this little piece of software I wrote over a weekend into a fine tool. So, thanks to you guys too !

**Comment by ndobson** [comment]
I second that, I've only just found this today and you have made my day!

**Comment by jspv** [comment]
This app is a godsend. Really nice work.

**Comment by svenjacobs** [comment]
I, too, want to say thank you for this handy application! Now I don't have to use the complicated OSD of the monitor anymore! 🎉  Thanks!

**Comment by alshakero** [comment]
Came here to create such an issue! Such a helpful app. I would donate $10 in a heartbeat. Thank you very much.

**Comment by EzraLopez** [comment]
It just works! Thank you :D I would like to donate or get a paid version

**Comment by LYJSPEEDX** [comment]
Such a very amazing APP! Though I don't know how U do this, but your work is incredible!
I am here so convey my appreciation.
If I can do anything to help your development (donate .etc), pls, feel free to say that.

**Comment by didaquis** [comment]
+1   Thank you!

**Comment by yuriyromadin** [comment]
I can't find donate button. This is incredible application. It should be paid, with a 5 min trial, because once you try it, you want to buy it. 
I work on three external monitors and adjusting brightness/contrast every night/morning is a chore.

**Comment by voltechs** [comment]
> we were thinking of setting up OpenCollective and/or Issuehunt accounts for this repo, this way we can transparently spend the donations and reinvest some of them into this project. Any other suggestions would be welcome too.

Please do! I've been searching for something like this. It's a shame Apple doesn't support CEC natively, but I'm so pumped y'all were able to make this work. I was skeptical at first, that maybe you were doing some trickery by simulating brightness and volume, but rest assured, it's actually changing the values on the display/hardware!! Fantastic. (Y'all can check by going into the menu on the monitor).

As soon as I saw that, I went searching for a donate button. Well done. I'll be watching this thread for when you set something up (maybe GitHub "sponsors" or whatever it's called?)

**Comment by cpressland** [comment]
Seconded, I'd love to donate some money to the project. This is an awesome project.

**Comment by JoniVR** [comment]
Hi everyone, a sponsor button has been added to the project, we'll mostly use this for funding either our yearly apple dev account subscriptions (required for signing etc), domain costs, ... depending on budget etc.

![image](https://user-images.githubusercontent.com/7591717/130129456-af4d27b4-2b63-4e0c-b361-fc6975e70e20.png)

If you want to thank contributors individually (for example @waydabber), ask them to set up a personal donation button and we'll link it in the repo :)

I'm going to close this issue now :)
