### ISSUE TITLE
Add option to not listen for any keys

### ISSUE THREAD

**Issue by kevingrabher** [MonitorControl/MonitorControl#181]
First off - absolutely great tool!

A bug I found:
When not using the tool you can use option/alt + volume/brightness keys to open the corresponding system preferences dialog. This no longer works when the tool is used.

Another nice option to work around this would be to be able to set to listen to neither brightness nor volume keys. That way they behave native but I'd still have the option to control the monitor with the menubar item.

**Comment by JoniVR** [comment]
> A bug I found:
When not using the tool you can use option/alt + volume/brightness keys to open the corresponding system preferences dialog. This no longer works when the tool is used.

This is not really a bug, just that when we listen for the mediakeys, we consume the key, so it's not passed on to the OS itself. This is however being worked on in #168, so once me or someone else gets to reviewing that it'll be fixed.

> Another nice option to work around this would be to be able to set to listen to neither brightness nor volume keys. That way they behave native but I'd still have the option to control the monitor with the menubar item.

Good suggestion, shouldn't be too hard to implement I think.

**Comment by chavlji** [comment]
Would love to be able to disable listening to brightness key (so they still controll builtin screen).
What about adding possibility to remap brightness up/down keys? So we can have both...

**Comment by anbroid** [comment]
Would also like to see this. Moreover whenever I start MonitorControl I have to click around 2 dialogs, first one that says "Shortcuts not available" and then another one that asks me to give access to Accessibility features (which I Deny). The app should have a way to be happy without keys so that these dialogs don't pop up at every start. Great app otherwise, love it!
