### ISSUE TITLE
Feature Request: True Tone external monitor

### ISSUE THREAD

**Issue by Vxider** [MonitorControl/MonitorControl#182]
Is it possible to True Tone the external monitor to synchronize the color temperature of external monitors and macbook's inner monitor?

**Comment by andrewcrook** [comment]
I was thinking the same using the MacBook's sensor 
for Mac mini's, older MacBooks or MacBook in clamshell mode etc may be use an external webcam as a sensor?

**Comment by Vxider** [comment]
In addition, when using multiple monitors, the eyes will fell uncomfortable if the color temperatures are inconsistent.

**Comment by kumowoon1025** [comment]
I mean True Tone is the feature that makes colors inconsistent but I agree it would be really cool. Would have to be implemented in software like using ColorSync though I think. If monitor color settings could be managed to mimic True Tone that would be amazing, but don't think it's possible.

Also webcams make for poor ambient light level/temperature sensors in my experience, is there one you found works well or do you put a filter over it or something?

**Comment by Vxider** [comment]
@kumowoon1025  Thank you for reminding me, I can try to manually create a color profile. After all, the light in the office will not change, which means that the True Tone color should not change.

**Comment by kumowoon1025** [comment]
> @kumowoon1025 After all, the light in the office will not change, which means that the True Tone color should not change.
Right, if your viewing condition has consistent lighting (i.e. no daytime natural lighting – afternoon fluorescent tube shenanigans) basically white balance. 
Though be sure to remember if you ever need to do work where accurate color reproduction is a factor, True Tone confused me so much when it first appeared in all my apple devices, it's so natural I didn't notice until I had a reference.

**Comment by Vxider** [comment]
True Tone might already work on some external displays, include: Apple’s Thunderbolt Display, which uses the Apple Thunderbolt 3 to Thunderbolt 2 adapter, LG’s UltraFine 5K, and LG’s UltraFine 4K.

source: [Apple’s True Tone technology will work with a few external displays](https://www.theverge.com/2018/7/13/17569330/apple-true-tone-tech-lg-display-ultrafine-macbook-pro-2018)

**Comment by andrewcrook** [comment]
>  LG’s UltraFine 5K, and LG’s UltraFine 4K.

Yes, those monitors have an ambient light sensor I presume similar to a MacBook Pro’s multi-channel ambient light sensor which is located next to the built-in FaceTime HD camera.

**Comment by Vxider** [comment]
> > LG’s UltraFine 5K, and LG’s UltraFine 4K.
> 
> Yes, those monitors have an ambient light sensor I presume similar to a MacBook Pro’s multi-channel ambient light sensor which is located next to the built-in FaceTime HD camera.

I do not have any of these monitors, but according to [report](https://appleinsider.com/articles/18/07/18/external-true-tone-display-feature-only-works-when-2018-macbook-pro-lid-is-open), it used macbook's light sensor and True Tune will not available when  macbook is put into clamshell mode by closing the lid.

**Comment by andrewcrook** [comment]
> it used macbook's light sensor and True Tune will not available when macbook is put into clamshell mode by closing the lid.

It must add it as an additional channel and work in combination.
