### ISSUE TITLE
How to hide the icons on taskbar？

### ISSUE THREAD

**Issue by valasco** [MonitorControl/MonitorControl#189]
1st. thx for this app，it works on my display.
but the icon is too ugly :>, how can i hide it? I think it will be gone if I delect it,but I can't find where is it.  if there is a way to hide it, please tell me,thx!

best regards!

**Comment by sn0wyfall** [comment]
You can use Bartender or a similar free app to do it

**Comment by JoniVR** [comment]
I agree that it might be better to just use bartender or vanilla to hide the icons you want to hide. 

If we allow you to hide the icon there’s no way to access your preferences with the current implementation.

**Comment by legendaryaman** [comment]
We can implement this feature like **Rectangle app.**
<img width="476" alt="Screen Shot 2020-04-21 at 8 45 30 PM" src="https://user-images.githubusercontent.com/3285444/79883406-7fb37800-8411-11ea-9ea6-4b6d517fc1cc.png">

**Comment by acousticbiker** [comment]
> I agree that it might be better to just use bartender or vanilla to hide the icons you want to hide.
> 
> If we allow you to hide the icon there’s no way to access your preferences with the current implementation.

Thanks, JoniVR - great app that fills a curious gap in macOS. If you're open to reconsidering, I too would appreciate an option to hide the menubar icon, since once preferences have been set initially there's not much reason to go back to it.

**Comment by JoniVR** [comment]
I agree that the rectangle implementation might work pretty well, PR's always welcome though! 🙂

**Comment by Mobofunk** [comment]
Just signed up to Git to also request this feature, the rectangle way sounds nice to me :)

Thanks for the app, working well on my 2 x Philips 328e1ca monitors

**Comment by raivivek** [comment]
Or something like, show up only when external display is connected would also be nice. Thanks again for the great software.

**Comment by sdaitzman** [comment]
Gigantic +1 on this issue ☺️

**Comment by legendaryaman** [comment]
I easily implemented in my build by using **applicationShouldHandleReopen**

`func applicationShouldHandleReopen(_: NSApplication, hasVisibleWindows _: Bool) -> Bool {
    self.prefsClicked(self)
    return true
  }
`

**Comment by sdaitzman** [comment]
@legendaryaman where do you make that change? Do you have a fork somewhere? Thanks so much! 😃

**Comment by sdaitzman** [comment]
Oh I see, you added it within AppDelegate.swift inside the AppDelegate class. I had to add a semicolon to get it to compile:

```swift
func applicationShouldHandleReopen(_: NSApplication, hasVisibleWindows _: Bool) -> Bool { self.prefsClicked(self); return true }
```

This adds my expected behavior of "the preferences pop up when you open the app again" but does not hide the icon. Is there an easy way to do that? I'm also poking into the code to try and see.

**Comment by legendaryaman** [comment]
> Oh I see, you added it within AppDelegate.swift inside the AppDelegate class. I had to add a semicolon to get it to compile:
> 
> ```swift
> func applicationShouldHandleReopen(_: NSApplication, hasVisibleWindows _: Bool) -> Bool { self.prefsClicked(self); return true }
> ```
> 
> This adds my expected behavior of "the preferences pop up when you open the app again" but does not hide the icon. Is there an easy way to do that? I'm also poking into the code to try and see.

Just comment out these two lines in **AppDelegate**

 `self.statusItem.image = NSImage(named: "status")`
` self.statusItem.menu = self.statusMenu`

Status bar **menu** will also disappear after this change so don't forget to add a quit button in **MainPrefsViewController**
`@IBAction func quitButton(_: AnyObject) {
    app.quitClicked(self)
  }`

**Comment by sdaitzman** [comment]
@legendaryaman thank you!!

**Comment by xflashxx** [comment]
Could you folks who managed to hide the icon in the menu bar please share the files you changed (or say where to insert/delete code) and give instructions how to build the app using Xcode for less experienced users who do not want to wait until this feature is integrated (if ever)? 
Would be really cool and for sure be appreciated by many reading this here!

**Comment by 8va** [comment]
I also wouldn't know how to put together a custom build myself but would really appreciate this feature.

**Comment by waydabber** [comment]
I added an option for that in settings.

<img width="572" alt="Screen Shot 2021-08-09 at 15 53 08" src="https://user-images.githubusercontent.com/37590873/128717500-082dd9ef-8160-40e2-9948-659952652261.png">
