### ISSUE TITLE
Magic Keyboard 2 brightness keys (F1/F2) no longer control external monitors, only MacBook pro display

### ISSUE THREAD

**Issue by johnnyutahh** [MonitorControl/MonitorControl#192]
For a few weeks after initial install, the Magic Keyboard 2 brightness keys (F1/F2) controlled the external monitors -- which is what I want.

Now said keys only control the native, MacBook Pro display.  (I'm running macOS 10.14.6.)

I've uninstalled and re-installed, both as a .dmg and a homebrew cask. I've removed the `~/Library/Preferences` file. I've pressed the "reset the preferencess" (button) multiple times. I still can not get the app to do what it did (again, for a few weeks, maybe a month or two) upon initial install.

Thoughts?  Need more data from my system?

I'm happy to wipe out all my `MonitorControl.app` software and related files and try again.

**Comment by johnnyutahh** [comment]
I installed [2.0.0](https://github.com/the0neyouseek/MonitorControl/releases/tag/v2.0.0) and no change in the above, problematic behavior.

If the software authors have no clue what's happening it'd be nice to know that, and I can stop "manually watching" the issue and try to solve it on my own.

Regardless, my team still loves the features this software provides, way better than manually having to press buttons on external monitors.

**Comment by johnnyutahh** [comment]
Does anyone know if I might be able to map [BetterTouchTool keyboard shortcuts](https://docs.bettertouchtool.net/docs/201_keyboard_shortcuts.html) to the external-monitor's brightness control?

**Comment by johnnyutahh** [comment]
If a project collaborator could provide pointers on:

1. where in the code they'd start investigating this problem, and
2. a build procedure

this might provide me an option to look into this myself. I can not commit to doing this, but if I have the info and find myself motivated and resourced (at some point in the future) I might be able to investigate.

**Comment by JoniVR** [comment]
Hi @johnnyutahh 

MonitorControl currently uses [MediaKeyTap](https://github.com/the0neyouseek/MediaKeyTap) for key listening under the hood. If you want to start debugging the issue that would probably be the best first place to start looking. Building that project should be as easy as cloning it and opening in Xcode.

As for MonitorControl build instructions, they are provided in the README.

I have a spare magic keyboard 2 laying around here so I'll try testing here soon but I'm currently a bit busy with some other stuff.

**Comment by JoniVR** [comment]
I just tested with my own Magic Keyboard 2 and the brightness keys seem to work as they should for me. Could you provide some info on your layout (hardware & software), macOS version, etc?

**Comment by shahanesanket** [comment]
@JoniVR I am having the same issue. keys on both the laptop's keyboard and the magic keyboard 2 do not control the brightness of the external monitor.

Specifications:
macOS High Sierra Version 10.13.6
MacBook Pro (Retina, 15-inch, Mid 2015)
Processor 2.2 GHz Intel Core i7
Memory 16 GB 1600 MHz DDR3
Graphics Intel Iris Pro 1536 MB

**Comment by JoniVR** [comment]
I'll try to provide a test build of MediaKeyTap soon when I get time. Have both of you tried removing MonitorControl from the permissions settings (Security & Privacy > Accessibility) and re-adding it when you relaunch?

**Comment by johnnyutahh** [comment]
**_Important update_**:

I've found, on at least one of my MacBook Pro's, that the behavior changes depending on which monitor/display contains the macOS menubar (which I change via the `Displays.prefPane` UX). _Initial_ testing shows that when I place the menubar only on the MacBookPro display, it controls only said display. Separately, placing the menubar on one of the external displays controls (thus far) **all** displays (which is fantastic).

[To note: I can live with this behavior for now and possibly indefinitely. I'd rather the brightness keys work for **all** displays regardless of monitor placement, but it's more of a minor issue. And as @JoniVR (I'm guessing) might mention: this behavior is possibly/probably determined by [MediaKeyTap](https://github.com/the0neyouseek/MediaKeyTap).]

My testing is yet _far_ from comprehensive, but if others can reproduce the behavior things might more-definitely point to the root of the behavior.

**Comment by gopycode** [comment]
@johnnyutahh Thanks for that tip about moving the menubar in Displays.prefPane! I found that as long as the menubar is active on the external display then the keys will work. For example, if I just click on my Desktop on the external display, the menubar becomes active and the keys will work, without needing to swap my primary display.

**Comment by johnnyutahh** [comment]
> @johnnyutahh Thanks for that tip about moving the menubar in Displays.prefPane! I found that as long as the menubar is active on the external display then the keys will work. For example, if I just click on my Desktop on the external display, the menubar becomes active and the keys will work, without needing to swap my primary display.

Good to know @gopycode. It does not work like that (yet), on my system.

I'm also, now, back to the brightness displays only working on external displays, which is what I was initially seeking. I'd love to eventually get it working again concurrently on all external displays AND the native, MacBook Pro display, like it was yesterday. That was fantastic.

For now, I'll take it (the brightness keys on my external keyboard working on the external displays).

**Comment by kumowoon1025** [comment]
I sort of have the opposite issue, I noticed after I started using this app that F14 and F15 were also acting as the brightness adjustment keys. This overrides any shortcut I assign or have as a preset for those keys completely, as it doesn't matter if I use them as regular function keys (with fn held down) or not.

I think I vaguely remember some function keys on the right hand side being brightness shortcuts by default on an older apple keyboard, but I can't check if it's MediaKeyTap making this happen, my TB display is at the apple store and I didn't get the chance to pick it up before they all closed to weather the pandemic...

**Comment by gopycode** [comment]
> Good to know @gopycode. It does not work like that (yet), on my system.
> 
> I'm also, now, back to the brightness displays only working on external displays, which is what I was initially seeking. I'd love to eventually get it working again concurrently on all external displays AND the native, MacBook Pro display, like it was yesterday. That was fantastic.
> 
> For now, I'll take it (the brightness keys on my external keyboard working on the external displays).

I must have misread the comment I replied to, or the thread leading up to it:

>Separately, placing the menubar on one of the external displays controls (thus far) all displays (which is fantastic).

Maybe you meant "all [external] displays"? I only have the one external display to test with, but that's what happened when I made the menubar active on the external without going through Displays.prefPane: both the internal and external displays changed brightness using the brightness keys. 

I have the same MacBook Pro 13,3 as you, installed via Homebrew, and the same Magic Keyboard, but am running Catalina. I really hope you don't have to upgrade to Catalina to make it work for you.

**Comment by johnnyutahh** [comment]
Thanks @gopycode for your diligence on this issue thread, quite appreciated.

> Maybe you meant "all [external] displays"?

I'll try to clarify:

A) 2 external displays
B) 1 macbook pro display

When menubar is moved to either one of the 2 external displays (A), then the brightness keys can only control (A).

When menubar is on (B), it only controls (B).

At one point (a couple days ago?) I was able to witness the brightness keys control all 3 displays, ie, (A) + (B). This the optimal solution. However, I am now unable to witness this behavior.

**Comment by gopycode** [comment]
Ahh, yes, now I understand your problem, @johnnyutahh. Does it matter which display the Dock is on? That's the only other thing I could think of. I do hope you find a solution though!

**Comment by kumowoon1025** [comment]
@johnnyutahh Do you have the "Displays have separate Spaces" option checked in the Mission Control preferences pane unchecked by any chance?

**Comment by buffaloseven** [comment]
I'm experiencing the same thing. I have a single Asus VG249Q monitor hooked up to my 2018 15" MacBook Pro (by DisplayPort or HDMI). When the laptop screen is defined as the primary monitor, _most_ of the time MonitorControl will not control the brightness of my external display. When my external display is set as the primary monitor (denoted by moving the menu bar to it in the Display preferences), the app behaves as expected (controlling the brightness of the external display, including the laptop display if control all displays is selected in preferences).

Running macOS 10.15.4. Also it seems to work via the Touch Bar's dedicated brightness controls in the expanded tool palate, but not via the quick-access brightness control. Using BetterTouchTool's brightness adjustments on the touch bar _does_ trigger the external display brightness adjustment as well.

**Comment by johnnyutahh** [comment]
@gopycode writes on 2020-04-09:
> Ahh, yes, now I understand your problem, @johnnyutahh. Does it matter which display the Dock is on? That's the only other thing I could think of. I do hope you find a solution though!

It does depend on the menubar. When the menubar is on the internal/native monitor/display, the keyboard controls (at least in my initial testing) the native monitor. When menubar's moved to one of the external monitors, keyboard brightness keys control (both of) the external monitors.

@kumowoon1025 writes 2020-04-11:
> @johnnyutahh Do you have the "Displays have separate Spaces" option checked in the Mission Control preferences pane unchecked by any chance?

I do indeed have said option unchecked (that is to say, NOT checked).

**Comment by kumowoon1025** [comment]
I forgot my reasoning but presumably I had an idea that the setting would affect this behavior somehow? Also this is unrelated but how did you customize the window title text to be so huge?

**Comment by kumowoon1025** [comment]
My local apple store finally opened up for curbside pickup so I will be able to do multiple external monitors with combinations of Apple supported displays and the ones that require MonitorControl for software control, can't wait! 😄

**Comment by MarkBlanco** [comment]
> This may or may not be fixed in #237, I'm not sure but we'll find out soon enough.. You could also already test the PR if you know how to and find out faster 🙂

Hi, I have just started using MonitorControl on my late 2011 macbook pro. I was running into the same issue where the keyboard controls for both volume and brightness did not work for the external display until I moved the menubar to the second display. My system details are the following:

- Late 2011 Macbook Pro, 15 inch
- AMD Radeon HD 6770M 1024 MB (in use)
- Intel HD Graphics 3000 512 MB (not in use)
- Monoprice V3L6W 35-Inch Display over minidisplayport to displayport adapter & cable
- MonitorControl version 2.0, build 640, installed via homebrew
- MacOS High Sierra version 10.13.6 (17G13035)
- I am piping sound from my Mac through the displayport connection to some external speakers

As noted, the volume and brightness controls did not work until I moved the menubar to the external display.
I do note that the volume control is very nonlinear at the moment, but that may be how the external display handles the input rather than MonitorControl.

I hope this information is helpful.

Mark

**Comment by johnnyutahh** [comment]
Update: I can now consistently get MonitorControl to work the way I want (the external-keyboard brightness keys work on all 3 displays) by closing and restarting it. (Yeah, it was that simple.)

I would be happy to test #237 , but I do not know, or know where to find, build procedure to do it. Suggestions or pointers welcome.

> This may or may not be fixed in #237, I'm not sure but we'll find out soon enough.. You could also already test the PR if you know how to and find out faster 🙂

( @JoniVR )

**Comment by JoniVR** [comment]
@johnnyutahh Can you test v2.1.0? It's released now and I'm hoping it fixes the issue...

**Comment by johnnyutahh** [comment]
@JoniVR - thanks much. I have v2.1.0 installed now. If there's any similar issue(s) I will post here. Since a previous version [was working okay](https://github.com/MonitorControl/MonitorControl/issues/192#issuecomment-684928147) (outside of sometimes my needing to restart it), I may not noticing anything different.

I also will try to post here If I find I no longer have to do [restarts](https://github.com/MonitorControl/MonitorControl/issues/192#issuecomment-684928147).

**Comment by negebauer** [comment]
I had this same issue in v2.1.0 (721) when connecting my magic keyboard for the first time. Closing and opening MonitorControl again fixed it

**Comment by waydabber** [comment]
Since this issue seems to be resolved I'll close it. Please feel free to comment or reopen it if it is still unresolved. Thank you!

**Comment by Macintosh-Fan** [comment]
The issue sometimes occurs now, but on M1 Pro. Other controls do work just fine, and even the manual brightness slider in the app works just fine.

**Comment by johnnyutahh** [comment]
Update: I upgraded to MonitorControl v4.1.0 Build 7034 and this "keyboard/touchbar control for external monitor(s)" symptom is back. I have resetarted MonitorControl, does not fix. (My previous, v2.1.0 was functional for the external monitor I'm using right now... I think.)

I'll try relogging-into (my macOS account) and/or rebooting in a bit to see if that fixes it. For now, I thought it worth noting this matter here.

ps. I love love love all the progress that MonitorControl has made in this latest version -- well done!

**Comment by johnnyutahh** [comment]
Update on my [above comment from 19 mins ago](https://github.com/MonitorControl/MonitorControl/issues/192#issuecomment-1166362573) :

**Problem solved, presumably**. I just found `Screen to control: Change for all screens` Preference setting... and that does what I want. Thanks!

An aside: `Screen to control: Use window focus...` does not appear to work as I would expect, but this is not a significant issue for me as said feature is not important to me right now. (It would be nice if I could get that to work in the future, but I do not need it now.)

**Comment by estebanavv** [comment]
This issue is happening since I upgraded to 4.10 using standard Keyboard. The brightness doesn't work but for audio works as it used to.

```~ sw_vers
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79

MonitorControl:
      Version: 4.1.0
      Obtained from: Identified Developer
      Last Modified: 6/18/22, 10:00 AM
      Kind: Universal
      Signed by: Developer ID Application: Joni Van Roost (CYC8C8R4K9), Developer ID Certification Authority, Apple Root CA

~ system_profiler SPHardwareDataType
Hardware:
Model Name: iMac Pro
      Model Identifier: iMacPro1,1
      Processor Name: Quad-Core Intel Core i7
      Processor Speed: 4 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 8 MB
      Hyper-Threading Technology: Enabled
      Memory: 32 GB
      System Firmware Version: 1731.100.130.0.0
      OS Loader Version: 540.120.3~6

~ system_profiler SPDisplaysDataType
Graphics/Displays:

    AMD Radeon RX 580:

      Chipset Model: AMD Radeon RX 580
      Type: GPU
      Bus: PCIe
      PCIe Lane Width: x16
      VRAM (Total): 8 GB
      Vendor: AMD (0x1002)
      Device ID: 0x67df
      Revision ID: 0x00e7
      Metal Family: Supported, Metal GPUFamily macOS 2
      Displays:
        DELL P2319H:
          Resolution: 1080 x 1920
          UI Looks like: 1080 x 1920 @ 60.00Hz
          Framebuffer Depth: 30-Bit Color (ARGB2101010)
          Display Serial Number: 56N5LK3     
          Mirror: Off
          Online: Yes
          Rotation: 90
          Connection Type: Thunderbolt/DisplayPort
        DELL U3818DW:
          Resolution: 3840 x 1600 (Ultra-wide 4K)
          UI Looks like: 3840 x 1600 @ 60.00Hz
          Framebuffer Depth: 30-Bit Color (ARGB2101010)
          Display Serial Number: 97F8P76804RL
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Rotation: Supported
          Television: Yes
