### ISSUE TITLE
Freezing when using NVIDIA GT 650/750M

### ISSUE THREAD

**Issue by khal3d** [MonitorControl/MonitorControl#193]
Hi, 

My Dell P2715Q display and the MacBook screen freeze when I open the app and while it's connected to the mDP <> DP, and it comes back to work right after removing the cable and closing the app. This issue doesn't happen if I used the same screen with the HDMI port.

I have tried using `ddcctl` command, and it's working perfectly.

### Displays

|       Display       	|                 GPU                 	|      Resolution      	|
|:-------------------:	|:-----------------------------------:	|:--------------------:	|
| Built-in Display    	| NVDIA GeForce GT 750M 2 GB Graphics 	| 15.4" (28880 x 1800) 	|
| Dell P2715Q Display 	| NVDIA GeForce GT 750M 2 GB Graphics 	| 27" (3840 x 2160) - 4k 	|

### Device

| Device                                   	| GPU                                                	| OS               	| MonitorControl    	|
|------------------------------------------	|----------------------------------------------------	|------------------	|-------------------	|
| MacBook Pro (Retina, 15-inch, Late 2013) 	| NVIDIA GeForce GT 750M 2 GB Intel Iris Pro 1536 MB 	| Catalina 10.15.3 	| 1.7.1 (Build 574) 	|

**Comment by JoniVR** [comment]
Seems to be an issue relating to the NVIDIA 750 card needing a different `minReplyDelay` I think.. judging that there's already an issue like this #125 also having the Nvidia card. Can you post this in #82?

**Comment by jjeffrey01** [comment]
Seconding this, immediately freezes my 750M based system as well.

**Comment by kumowoon1025** [comment]
The 650M and 750M are the same chip, so @SongHoang might have the same issue. I tried with a 650M laptop with no issues over HDMI, I'll update when I find a mDP - DP adapter/cable, I didn't realize TB cables didn't work as mDP cables o_o

**Comment by kumowoon1025** [comment]
My god, the freeze, or rather, the immediate complete grind to halt, is real. 15-inch MacBook Pro (Retina, Mid 2012). Makes collecting logs a pain, I'll still see if there's anything in there though.

I'm pretty sure I also have an iMac with a 755M, again, exact same GPU, almost as crappy but doesn't lose when it comes to instability. Catalina beta install killed the EFI though, so I'll either need to wait out the pandemic or program it myself, this does seem to be an orthogonal issue from problems with HDMI connections though.

**Comment by tormave** [comment]
I have the hanging issue as well. MBP 15 with GT650M, Dell U2717D connected via mini-Displayport -> Displayport cable, latest Catalina 10.15.4. Just got the external monitor and it's too bright when it gets darker. Can of course use the monitor menu, but it's a pain as it's deep in the clickety click menu.

I was so happy to find this app I crashed my laptop 3 times before believing it's MonitorControl that killed it. Hope I had read the instruction of removing the monitor cable before rebooting... Despite it doesn't work for me, awesome that you've developed this app!
