### ISSUE TITLE
Turn off monitor

### ISSUE THREAD

**Issue by MaartenBorsje** [MonitorControl/MonitorControl#194]
Is it possible to make an option to disable an monitor when it's still connected?(in a way that if I turn of my monitor it doesn't push a signal to it) If it can be added to the app it will be an awesome feature.

**Comment by kumowoon1025** [comment]
I'm not sure if such a feature is related enough to be incorporated into this project, but check out [DisableMonitor](https://github.com/epalzeolithe/DisableMonitor-3.0) (NOT the home-brew cask which is the original archived project, this is a fork that's been maintained, works on 10.15, doesn't kill TB ports, etc)

**Comment by maartenbithub** [comment]
That's exactly what I needed. 

I thought that it makes the utility more complete. But maybe also to complicated.

**Comment by kumowoon1025** [comment]
idk about complicated, its just they're very different in nature, DisableMonitor is pretty much a hack while MonitorControl implements a standard protocol missing in macOS. Also they're pretty much orthogonal in terms of what they do and how they do it, it'd kinda be like combining an email client and web browser into one app (read: Thunderbird).

**Comment by JoniVR** [comment]
I agree that this is probably out-of-scope for this project, but I'll leave it open for now.
If you simply want to disable DDC control, you can disable it in the Display settings by unchecking the `enabled` checkbox for that display.

![image](https://user-images.githubusercontent.com/7591717/85228321-251fa380-b3e3-11ea-9afe-718d7641ae54.png)

**Comment by Atcold** [comment]
Clicking the Enable check box does not turn off the corresponding display.
I agree with @maartenbithub that being able to shut off a display would be a good addition.
Say I'm listening to music and I'd like the screen to be black. Now I need to physically turn off the external screen and push the brightness of the integrated display to zero.

**Comment by waydabber** [comment]
I think this is out of scope and would be a replicate of https://github.com/epalzeolithe/DisableMonitor-3.0. I'll close this for now. As it was mentioned, https://github.com/epalzeolithe/DisableMonitor-3.0 might work to handle this scenario. Thanks for the suggestion though! :)
