### ISSUE TITLE
Media keys produce no control when MonitorControl menu is open

### ISSUE THREAD

**Issue by Hokkusai** [MonitorControl/MonitorControl#195]
When MonitorControl menu (the menu in the menu bar with the sun icon) is open, pressing the media keys (brightness, volume) does not produce any effect. Moreover, when the menu is closed the last media key pressed for both volume and brightness will produce one increment or decrement.

**Comment by waydabber** [comment]
This will be fixed by this:

https://github.com/MonitorControl/MonitorControl/issues/475
