### ISSUE TITLE
Display glitches and disconects

### ISSUE THREAD

**Issue by thor27** [MonitorControl/MonitorControl#197]
When this app is enabled, sometimes I receive some weird display glitches. I couldn't record it because it doesn't happens always, but it looks like big blocks of gray pixels on the screen and some sound crackling. Sometimes it even shutdown the screen and I have to disconnect and reconnect to come back. If I disable polling it helps a bit.

Mostly what I could notice is that, with polling this happens most of the time I reduce volume or brightness as soon as I raised, and without it it happened once when waking up from sleep.

I don't know exactly what type information will be good to help with this issue, but my monitor is an ASUS MX34VQ Designo Curve Ultra-wide Curved Monitor - 34 inch, UWQHD and my Macbook is a MacBook Pro (15-inch, 2018) running macOS Catalina 10.15.4

**Comment by kumowoon1025** [comment]
>  and some sound crackling. 

Does this display have an audio connection because if not that sounds terrifying.
As far as helpful info, how you connect the display to your computer is an example.

**Comment by thor27** [comment]
Hi! I replaced the cable I used and the visual glitches is gone, but if you move the sound or brightness too fast the screen turns off. At least the issue is smaller :)

**Comment by JoniVR** [comment]
See:
https://github.com/the0neyouseek/MonitorControl/wiki/Monitor-Troubleshooting

Unfortunately, besides from pointing you to the general troubleshooting there isn't much we can probably do about it. It could simply be a problem with the implementation of your display manufacturer.

**Comment by kumowoon1025** [comment]
I actually don't understand why it works with HDMI in the first place... Where are CEC commands made? Or is it something like Macs with more than one gpu use I2c api for either and translated by gmux?

Is your laptop iGPU only or the dual gpu model? Can try DisplayPort cable instead of HDMI?

**Comment by thor27** [comment]
It shouldn't work with HDMI?? As far as I understand about this, HDMI supports CEC just fine, I even use with my chromecast to control it with my TV remote.

it's working fine after using a newer and more modern cable. It only shows a black screen If I move the sliders too fast, but nothing happens with "normal usage". So I think this is not an issue anymore.

It's dual GPU Radeon Pro 555X 4 GB & Intel UHD Graphics 630 1536 MB
I Don't have a USB-C Display port cable to test, unfortunately.

**Comment by kumowoon1025** [comment]
@thor27 I'm sorry I guess I put it in a confusing way, I mean I don't understand where CEC support is implemented in this app. It supports DDC/CI, which is a bidirectional I<sup>2</sup>C interface, which is not the same as CEC, though they do serve a lot of the same purpose. In terms of the implementation details for CEC in HDMI, I think qualitatively I can think of as many differences as I can similarities.

Anyhow, I'm glad it's working better for you, you might want to try adjusting the polling and delay according to the troubleshooting guide @JoniVR pointed you to earlier to make it even more stable.

But HDMI not working very well has been a recurring issue for a while now, and when I looked into it to see if I could help out in fixing it, I could not find the code that handled HDMI/CEC, so I would have thought it wouldn't work with HDMI connections at all, but obviously, it does, and quite well at that for many setups.

I'm thinking maybe it is the gmux chip doing protocol translation in hardware (your dual-GPU MBP has this chip, it's either an fpga or something like a 16-bit general processor That handles graphics switching, eGPU routing, etc. ), or the same API being used for both MCCS and CEC at the moment, if  anyone can point me in the right direction or confirm/reject my guesses I'd be much obliged.

**Comment by JoniVR** [comment]
I'm pretty sure no CEC is implemented, only DDC for control and a private API for internal display control. HDMI is indeed a recurring issue 🙂
