### ISSUE TITLE
Add internal display brightness slider to menulet

### ISSUE THREAD

**Issue by shamilovtim** [MonitorControl/MonitorControl#198]
I recall back when I had a Thunderbolt Display when it was plugged in the Macbook's brightness keys would control only the Macbook while my external keyboard controlled the external monitor's brightness. Is that possible to replicate?

Additionally 2 separate brightness controls in the menubar application would be a godsend.

Thanks for considering

**Comment by JoniVR** [comment]
v2.0.0 Adds support for internal display brightness controlling. You can use <kbd>ctrl</kbd> + brightness to control only the internal display or configure it in the display settings with the `enabled` checkbox.

I agree that adding the internal display to the menulet would be a good thing to have now that we have internal display control.

**Comment by shamilovtim** [comment]
What about having the macbook's brightness keys control its own brightness? E.g. 2 separate keyboards

**Comment by shamilovtim** [comment]
Also separate note: might want to elucidate that shortcut and any others in a quick textbox on the first screen of the app?

**Comment by JoniVR** [comment]
> What about having the macbook's brightness keys control its own brightness? E.g. 2 separate keyboards

I'm not 100% sure but I doubt that's possible with the current implementation.

> Also separate note: might want to elucidate that shortcut and any others in a quick textbox on the first screen of the app?

Agreed, but might be something for when we can finally get custom shortcuts implemented in the future.

**Comment by shamilovtim** [comment]
Is that a stock macOS shortcut? Wonder what others I don't know about 🤔

**Comment by waydabber** [comment]
It is possible to add a slider for the internal display as well (as an advanced option). I'd like to add Apple branded display support as well which uses the same APIs for control method as internal displays anyway.

https://github.com/MonitorControl/MonitorControl/issues/364

**Comment by waydabber** [comment]
There is a build in the following isse with slider for built-in screens (and also proper support for Apple displays): https://github.com/MonitorControl/MonitorControl/issues/539

**Comment by waydabber** [comment]
Since the brightness of Apple and internal displays can change due to several external factors (ambient light sensor, touch bar, control center slider etc) I updated the functionality so these changes are reflected in the sliders as well (this requires a light periodic polling - it has no visible effect on cpu load). This can easily be extended later to support https://github.com/MonitorControl/MonitorControl/issues/27.
