### ISSUE TITLE
Volume/brightness increments don't work properly on non standard scales

### ISSUE THREAD

**Issue by victorchabbert** [MonitorControl/MonitorControl#201]
Hello,

When using my monitor over usb-c with the lid closed and a magic keyboard 2, my volume is capped at 4 bars when using the media keys (12/50 in monitor values).
However, when using ⇧ + ⌥ + Volume up/down, I can increase the volume above 4 bars.
Moreover, once this threshold crossed, I cannot increase volume in normal increments; decreasing works fine.

![Screen Recording 2020-04-16 at 15 03 54](https://user-images.githubusercontent.com/10966568/79459626-d7a64500-7ff3-11ea-9fcf-e26c5fd1f670.gif)

Using the sliders from the menu bars works even though the volume and brightness sections are greyed out.
<details>
<summary>Greyed out sections in the menubar screenshot</summary>

![Screenshot 2020-04-16 at 15 11 19](https://user-images.githubusercontent.com/10966568/79460203-c1e54f80-7ff4-11ea-8ec7-93d3002e30b3.png)
</details>

## Troubleshooting:

- [x] Restarted macbook
- [x] Restarted monitor
- [x] Ran ddcctl (see below)
- [x] Tried different cables:
  - USB-C to USB-C
  - HDMI to USB-C

### ddcctl
I compiled ddcctl locally for amd and intel.
Running `./ddcctl -d 1 -v <volume>` was successful in changing the volume.
(My monitor volume ranges between 0 and 50)

## Information:
| Type | Model/Version |
|-------------------------|-------------------|
| Display                 | BenQ EX2780q over USB-C     |
| Device                  | MBP 15" (2016)    |
| OS                      | 10.15.4           |
| Monitor Control | 2.0.0 (Build 640) |

**Comment by marosholly** [comment]
I have the issue with the same monitor + mac mini 2018

**Comment by bottlebug** [comment]
I have a similar issue. 

At this level, my monitor displays it at 95/100. Any higher and it will go above 100 which doesn't make any sense. Each increment is also not the same value.

![Screen Shot 2020-05-14 at 5 20 56 PM](https://user-images.githubusercontent.com/16513636/81895876-631cf100-9607-11ea-9185-24a7bd86192e.png)
