### ISSUE TITLE
I can not adjust the volume size but I can adjust the bright on the Dell p2415q

### ISSUE THREAD

**Issue by csyt5190** [MonitorControl/MonitorControl#202]
Hi, there,

The software was successful instal my MacBook pro-Middle 2015, I could adjust the bright size by ur software, but I can not adjust the volume size... even I could adjust volume size on ur software but it does not affect the practical volume size. Any thought? the Bluetooth speaker which I connected with my monitor is sony SRS-XB22.

Looking forward to ur replay,

Thank you!

**Comment by mkoegel** [comment]
I have the same issue with a Dell U2715H. Contrast works sound doesn't. Analog speakers connected to audio jack.
Just upgraded from 1.7.1 to 2.0.0, but still the same.
Also Audio controls on the TouchBar are greyed out, but work.
MacBook Pro 16" latest Catalina version.

**Comment by JoniVR** [comment]
> the Bluetooth speaker which I connected with my monitor is sony SRS-XB22.
The purpose of this tool is not really to control bluetooth speakers. It's to control the internal speakers of your screen (as well as brightness), however, it always looks at what your current audio output is. If your output is set to an external speaker (or internal ones) that you can control normally without MonitorControl, it will not do anything.

Could be that I misunderstood your issue, let me know if that's the case, however, it's pretty hard to help everyone out with their own specific displays (and issues) as they're all pretty different (some don't implement the spec very well) and we don't really have the hardware to test on. 

This might help:
https://github.com/the0neyouseek/MonitorControl/wiki/Monitor-Troubleshooting

**Comment by Kayne** [comment]
Hi, 

I have similar issue. I've connected Dell U3219Q via USB-C to CalDigit TS 3 Plus hub and the hub via USB-C to MacBook Pro 15" 2019. My speakers are connected via audio jack through monitor's audio port.

I can control brightness but volume control does nothing. Slider is moving, I can hear "ping" sound but volume is not changed a bit. Using latest version, 2.0 (build 640).

**Comment by Kayne** [comment]
Still the issue. That's why I decided to pay for this funcionality and started using SoundSource.
