### ISSUE TITLE
just isn't working, please help 

### ISSUE THREAD

**Issue by Gimbo1664** [MonitorControl/MonitorControl#205]
<img width="213" alt="Screen Shot 2020-04-20 at 01 44 29" src="https://user-images.githubusercontent.com/63985875/79704373-157fc380-82a9-11ea-89f0-af4d53983959.png">
please help, it seems to be dimmed. doesn't work at all. what am I missing.

many thanks guys!

**Comment by Gimbo1664** [comment]
sorry as in the font is dimmed, not the screen itself haha. thats what I'm after

**Comment by JoniVR** [comment]
Try:
https://github.com/the0neyouseek/MonitorControl/wiki/Monitor-Troubleshooting
