### ISSUE TITLE
Brightness control doesnt work on Dell UP2715k

### ISSUE THREAD

**Issue by markpradhan** [MonitorControl/MonitorControl#206]
It does work on my 4k (acer) screen, but not on my 5k (dell up2715k).
How can i fix this?

**Comment by JoniVR** [comment]
Try:
https://github.com/the0neyouseek/MonitorControl/wiki/Monitor-Troubleshooting

**Comment by sanjayc77** [comment]
./ddcctl -d 1 -b \?
D: NSScreen #722475479 (2560x1440 0°) HiDPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: F1JCM581064S
I: got edid.name: DELL UP2715K
D: action: b: ?
D: querying VCP control: #16 =?
E: No data after 10 tries!
E: DDC send command failed!
E: VCP control #16 (0x10) = current: 0, max: 0

**Comment by markpradhan** [comment]
@sanjayc77 Should i try it with that setup? I don't know what to do or how to interpret your comment 😕.

**Comment by sanjayc77** [comment]
> @sanjayc77 Should i try it with that setup? I don't know what to do or how to interpret your comment 😕.

Edited my reply that it did not work for me either. Sorry for the confusion.
