### ISSUE TITLE
Dell U2720Q - Brightness doesn't work when Color Space is set to DCI-P3

### ISSUE THREAD

**Issue by aklekotka** [MonitorControl/MonitorControl#208]
Hey,
I have a Dell U2720Q, the brightness control works fine when the monitor color space is set to sRGB. When I change the settings to the wider color gamut - DCI-P3 - I can't control the brightness from my keyboard. 

Any ideas?

Thanks!

**Comment by yixinh** [comment]
same problem

**Comment by larouxn** [comment]
Potentially related, brightness cannot be controlled if you have "High Dynamic Range" checked.
<img width="269" alt="Screen Shot 2020-05-13 at 18 39 15" src="https://user-images.githubusercontent.com/1557529/81796947-15da4a00-9549-11ea-8c26-7d065ece2bac.png">

**Comment by ypresto** [comment]
A twitter user in Japan says it does work with P3 or HDR (U2720QM). I finally bought this monitor 😉 so I'll test it after shipped.

**Comment by ypresto** [comment]
I tested some configuration with my new monitor, and found Display P3 is working.

@aklekotka and @yixinh perhaps set color preset to Display P3 in OSD. U2720QM blocks brightness change when `Colors -> Preset Modes -> Color Space -> Display P3` is set in OSD (setting sRGB is also the same). It seems it is by design:

![image](https://user-images.githubusercontent.com/400558/84562822-31c44c00-ad92-11ea-810a-1648881486fa.png)

Fortunately, Display P3 gamut is working fine with other Preset Modes (Standard, Movie, or Custom Color etc.). You also does not need to change Display profile in macOS (Use "DELL U2720QM" (or U2720Q)).

You can test it with here:
https://webkit.org/blog-files/color-gamut/
(Webkit logo should be shown in red background if your monitor supports P3).

I'm not color management specialist so I have no idea why that "Color Space" Preset Mode is for (maybe to test how a photo looks in sRGB color space?), but it just working without it.

**Comment by ypresto** [comment]
Also NOTE: when setting `Display -> Smart HDR` to other than `Off`, this monitor uses sRGB gamut. Unfortunately it is required for "High Dynamic Range" toggle to be shown in macOS's display preferences.

macOS version: 10.15.5（19F101）

**Comment by aklekotka** [comment]
@ypresto thanks for your input. Yes, I meant setting both - the `Display P3` Display profile in macOS AND `Color -> Preset Modes -> Color Space -> DCI-P3` in OSD, because I thought that's the correct combination used for the color calibration in the factory.
When you set the `Color Space` to `sRGB` the reds are washed out (for example compare the red used in Chrome logo)

I haven't noticed the sentence about the default brightness set to 48cd/m2. Probably that's the reason why MonitorControl doesn't work, unfortunately.

> Fortunately, Display P3 gamut is working fine with other Preset Modes (Standard, Movie, or Custom Color etc.). You also does not need to change Display profile in macOS (Use "DELL U2720QM" (or U2720Q)).

While I agree with your first sentence here - I can see the webkit logo, when I set the macOS profile to `Display P3`. But I don't think I follow your last sentence. You're saying that I don't need to the `Display P3` macOS profile, but the default "DELL U2720Q" doesn't support DCI-P3 in my case (the webkit logo is not visible).
I have the HDR feature disabled.

**Comment by ypresto** [comment]
@aklekotka You're right, I looked again and certainly macOS display profile should be set to `Display P3`.
(Maybe U2720 profile was not applied on click but why :joy:)

**Comment by ypresto** [comment]
Also tested HDR again, and P3 is working with `Smart HDR -> DisplayHDR` in OSD (and without checking `High Dynamic Range` in macOS. Maybe you should restart Preferences.app if it is not working.

**Comment by ypresto** [comment]
Conclustion:

MonitorControl is

- Working even when selecting P3 gamut display profile in macOS.
- Working when `Smart HDR` in OSD is selected
- NOT working when `Preset Modes -> Color Space` is selected (by monitor design)
- NOT working when macOS "High Dynamic Range" check is enabled (bug or OS design?)

(P3 gamut is working regardless of HDR is enabled or not.)

**Comment by elitvynov** [comment]
Hey guys. I bought Dell U2720 and as I see, brightness is working for me, but sound volume is not. Could you please check if you connect Speakers / Headphones to the Audio Out of monitor, do you able to control it volume with MonitorControl?
I connect MacBook Pro 2016 with USB-C (Display Port 2.0).
Thank you

**Comment by aklekotka** [comment]
Closing this issue, as I agree with @ypresto's summary above. 

Also, `DCI-P3` and `Display P3` are two different color spaces - https://en.wikipedia.org/wiki/DCI-P3#Display_P3

If you want to achieve similar colors to your MBP bulit-in P3 display, et your monitor to `Color -> Preset Modes -> Standard` and your macOS display profile to `Display P3` (explanation:
https://www.reddit.com/r/Monitors/comments/f4avo3/dell_u2720q_review/foi0cpl/?context=10000). MonitorControl works fine with these settings.

-- 

@elitvynov Yes, the volume control works via usb-c with MBP 15" 2019 and via micro displayport with MBP 13" 2015. You just need to pick the correct output:
![image](https://user-images.githubusercontent.com/730969/84602559-42d69100-ae56-11ea-94c0-a32f51d52948.png)
