### ISSUE TITLE
Doesnt work on LG TV

### ISSUE THREAD

**Issue by jasontucker** [MonitorControl/MonitorControl#210]
Using a USB-C to HDMI connector to connect to my LG UHD TV I'm unable to change the brightness or volume.

<img width="689" alt="Screen Shot 2020-04-30 at 12 37 59 PM" src="https://user-images.githubusercontent.com/108426/80751877-709e8b00-8adf-11ea-9aa0-2b30554c5736.png">

<img width="643" alt="Screen Shot 2020-04-30 at 12 38 22 PM" src="https://user-images.githubusercontent.com/108426/80751901-7c8a4d00-8adf-11ea-86df-728f8bfedca5.png">

<img width="248" alt="Screen Shot 2020-04-30 at 12 37 35 PM" src="https://user-images.githubusercontent.com/108426/80751844-5fee1500-8adf-11ea-9e28-22d6302fd432.png">

Quick stats from System Information:

Radeon Pro 555:

  Chipset Model:	Radeon Pro 555
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	2 GB
  Vendor:	AMD (0x1002)
  Device ID:	0x67ef
  Revision ID:	0x00c7
  ROM Revision:	113-C980AJ-927
  VBIOS Version:	113-C9801AP-A02
  EFI Driver Version:	01.A0.927
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.29 [3.2.8]
  Metal:	Supported, feature set macOS GPUFamily2 v1
  Displays:

Color LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	2880 x 1800 Retina
  Framebuffer Depth:	30-Bit Color (ARGB2101010)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	No
  Connection Type:	Internal

LG TV:
  Resolution:	3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition)
  UI Looks like:	3840 x 2160 @ 30 Hz
  Framebuffer Depth:	30-Bit Color (ARGB2101010)
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
  Connection Type:	HDMI
  Adapter Firmware Version:	7.55
  Television:	Yes

**Comment by JoniVR** [comment]
Hi, we have a Monitor Troubleshooting wiki for this:
https://github.com/the0neyouseek/MonitorControl/wiki/Monitor-Troubleshooting

This might be a good place to look first 🙂
