### ISSUE TITLE
Apple Thunderbolt Display slider scaling wrong (display too dim; audio too quiet)

### ISSUE THREAD

**Issue by cpcallen** [MonitorControl/MonitorControl#212]
When used a Thunderbolt Display, MonitorControl can adjust the brightness of the external monitor only between very dim and almost completely off (and one or the other; nothing in between).  Comparing against the Brightness slider in System Preferences > Displays, it is clear that MonitorControl is selecting between the lowest and second-lowest possible settings.

Similarly, the volume control, when set on maximum, is equivalent to about 2/16ths of full range compared to setting by the volume keys / volume menu.

Monitor: Apple Thunderbolt Display (A14070)
Laptop: MacBook Pro 13" 2015 (MacBookPro12,1)
GPU: Intel Iris Graphics 6100
OS: macOS 10.13.6 (17G12034)

Info from Settings, in case it is useful:

![Screen Shot 2020-05-06 at 22 56 00](https://user-images.githubusercontent.com/5603958/81232613-1d4f9f80-8fed-11ea-93fd-703b7f506e87.png)

**Comment by esusatyo** [comment]
I have a Thunderbolt display and have the same problem. The brightness slider is completely broken though, sliding it to any direction will decrease the brightness to minimum.

Monitor: Apple Thunderbolt Display (A14070)
Laptop: MacBook Pro 15" 2018
GPU: Radeon Pro 560X 4 GB graphics
OS: macOS 10.15.5

Let me know if there is any debugging steps I can do. I also have Xcode so can step through the code.

**Comment by jlcd** [comment]
I also have a Thunderbolt display, first thing I noticed is that once I pressed the "lower/increase brightness" key, the brightness went to fully dark and didn't change at all after that, not even on the app's slider.

**Comment by JoniVR** [comment]
Judging by the fact that this is only reported on Thunderbolt displays, I'm going to mark this as a display issue for now. Does the Thunderbolt display not support brightness controls natively?

**Comment by cpcallen** [comment]
> Does the Thunderbolt display not support brightness controls natively?

It [certainly does](https://manuals.info.apple.com/MANUALS/1000/MA1594/en_US/thunderbolt_display_getting_started.pdf):
<img width="410" alt="Screenshot 2020-06-16 at 09 43 19" src="https://user-images.githubusercontent.com/5603958/84752673-f2764500-afb5-11ea-960e-3e669f559ee7.png">
(And I can confirm that these controls work as expected on the display in question.)

**Comment by JoniVR** [comment]
In that case, what’s your specific use case for MonitorControl (or what’s missing)? Can’t you just disable the display and or MonitorControl and use the controls natively without DDC?

**Comment by cpcallen** [comment]
I have in fact stopped using MonitorControl because of this bug (and it not being needed); nevertheless, there are a few advantages to MonitorControl compared to the native controls:

* Brightness slider as a menu bar item.
* Fine-grained control over brightness.
* Can adjust the brightness of whichever screen I am on using the brightness keys alone, without needing to remember to use control if I happen to be on the external display.
* (Theoretically:) ability to adjust brightness of two external displays independently.

**Comment by jlcd** [comment]
In my case I have a second monitor that benefits directly from MonitorControl, as the other way to change brighntess is by pushing buttons under it.
I'm not using MC for the Thunderbolt Display.

**Comment by dlopuch** [comment]
A potential clue? It seems the MC brightness knob has a tiny jump or deadzone from "0-position" to "gradual scaling". On my apple thunderbolt, the MC 0-position sets it at minimal brightness, then after the deadzone jump the monitor goes up one click in brightness, but then it doesn't change any more.

So it's almost as if it has exactly two levels: minimum-dimness, and one-click-above-minimum-dimness

**Comment by cpcallen** [comment]
This issue still exists in MonitorControl v2.1.0.  I am unable to test for it in v3.0.0-beta5 due to #508.

**Comment by cpcallen** [comment]
I've now tried 3.0.0-beta6 and the behaviour is as reported initially.

**Comment by waydabber** [comment]
Hey @cpcallen, the Apple Thunderbolt display can be controlled via a completely different protocol (much like internal displays) than generic non-Apple displays. I'd like to add this as a feature also. Hopefully I'll have some time to work on this. If yes, then your help would be much appreciated as I don't have an Apple branded display to test.

**Comment by cpcallen** [comment]
> If yes, then your help would be much appreciated as I don't have an Apple branded display to test.

Sure; I'd be glad to help (as time allows).

**Comment by waydabber** [comment]
We'll be working on Apple display and other USB controlled displays here:

https://github.com/MonitorControl/MonitorControl/issues/364

I close this issue so we don't have two.

**Comment by waydabber** [comment]
For those with Apple displays, there is a link to a test build with proper support here: https://github.com/MonitorControl/MonitorControl/issues/539
