### ISSUE TITLE
Volume controls are working in reverse

### ISSUE THREAD

**Issue by Tyler98ky** [MonitorControl/MonitorControl#216]
When I move the volume slider up, the volume goes down and vice versa. However, if you move the volume slider all the way to the left (no volume), it still mutes the system. Brightness slider works as expected. This also happens when I use keyboard shortcuts for volume (volume up decreases volume etc.)

**Comment by waydabber** [comment]
This is the same as this one: https://github.com/MonitorControl/MonitorControl/issues/305

I'll close this. Keep following the other thread. If I have the time I'll implement reversing the controls as an advanced setting as it seems to be an issue affecting several displays with weird firmwares.
