### ISSUE TITLE
Ability to manually set Brightness and Contrast levels for keyboard control

### ISSUE THREAD

**Issue by waydabber** [MonitorControl/MonitorControl#22]
Unfortunatelly my display (LG's 27UD88) cannot dim the Brightness that much. At night time I would like to dim it even more by reducing the Contrast a bit with Brightness set to "0". The app now has an option to "Lower Contrast after Brightness", however this is sets the contrast way too low (+ my display does not seem to have proper support for reading DDC values, so Contrast is not properly restored afterwards since the app does not know what was the original Contrast level to begin with).

**My recommendation is this:** there should be an "advanced" setting, where the user can exactly specify the Brightness and Contrast levels manually for all 17 steps ("ticks") of the brightness levels that can be set by the F1/F2 keyboard keys. 

This way I could set the _level 0_ to 30% Contrast, 0% Brightness, _level 1_ to "50%C, 0%B", _level 2_ to "70%C 0%B", _level 3_ to "70%C 5%B", and so on..., _level 17_ being "70%C 100%B" (the default/optimal contrast level for my display is 70% opposed to the more common 75%).

This addition would make the app perfect for me!

Thank you for your great work!

**Comment by the0neyouseek** [comment]
Hi @waydabber ,

I can see how that could be useful. I'll look into making that happen in a futur version.

**Comment by nekrasovdmitriy** [comment]
Adjusting the step of increasing/lowering Brightness+contrast will be cool feature, +1

**Comment by joeyhoer** [comment]
@waydabber The idea of manually defining values for each step is a really interesting concept, though I think you're right, it would require a more complicated ("advanced") preference panel. I imagine that an option to scale brightness and contrast together, within a defined range (for contrast, or possibly for both brightness and contrast) would more effectively adjust the perceived "brightness". I've described this approach in more detail in another thread: https://github.com/the0neyouseek/MonitorControl/issues/31#issuecomment-485432536
