### ISSUE TITLE
DDC not working properly on some Dell monitors

### ISSUE THREAD

**Issue by ydoupo** [MonitorControl/MonitorControl#226]
The Brightness Control are working fine with me, but the Volume Control are not working at all when I connect earphone to monitor, like the following pic:
![image](https://user-images.githubusercontent.com/15712755/82770954-0aeab800-9e6d-11ea-9ca2-415b529dc888.png)
And I am using macOS Catalina 10.15.4,
Thank you so much for help.

**Comment by JoniVR** [comment]
What version of MonitorControl? Did it work before?

**Comment by cirorandazzo** [comment]
Same here, with Dell U2419HC, Catalina 10.15.5, MonitorControl 2.0.0. Just downloaded, so I don't know if it worked previously.

The on-screen volume icon appears, but the speaker that I have plugged into my monitor with AUX doesn't change volume.

**Comment by sunhch** [comment]
Same problem with Dell U2720Q, Catalina 10.15.5, MonitorControl 2.0.0. The volume control window will appear and seems functioning correctly, but the actual volume does not change.

**Comment by sunhch** [comment]
I also tried the ddcctl from troubleshooting page, and it does not work on my U2720Q. However, I found an extension called Soundflower, and I got OSD volume control working after following this guide:https://www.macrumors.com/how-to/use-mac-volume-keys-adjust-monitor-audio/

Could this be a hint on how to make MonitorControl working with U2720Q?

**Comment by YihangGuo** [comment]
I met the same problem for my U2720Q

**Comment by taebong** [comment]
The volume control doesn't work on my Dell S2718D either.

**Comment by millnerryan** [comment]
I have a Dell U3415W and I have a similar issue: the volume setting on the monitor changes successfully when I increase/decrease volume from my keyboard, which I can see on the monitor, but the actual volume output from the speaker doesn't change unless I manually press the volume buttons on the keyboard.

**Comment by jerry1230** [comment]
MonitorControl2.0 mbp 2015 osx 10.15.3,    monitor u2414h.  The Brightness Control are working fine with me, Volume Control are Not Working. I have tried 3 kinds of cable, hdmi-hdmi;  thunder2-hdmi ; thunder2-dp. the monitor settings can switch dp 1.1a / dp1.2, after all these, still not work

**Comment by Lisheng2016** [comment]
MonitorControl2.0 mbp 2018 osx 10.14.6, monitor dell p2415q. The Brightness Control are working fine, Volume Control are Not Working. I has been using the DP cable(DP - DP) that comes with the monitor, SoundFlower does work for me,ddctl doesn't seems to have any issue controlling the volume but nothing happens when i make changes to the volume.

**Comment by johannes-kk** [comment]
Exact same issue with U2515H via HDMI: brightness controls work, volume doesn't.

**Comment by val3riefr** [comment]
Can you please fix this! we need audio control :(

**Comment by Lisheng2016** [comment]
Finally a workable solution! Thanks to **briankendall/proxy-audio-device**
I've been using it for like a week,and it works like a charm.It does intruduced a little latency but at least it worked.
For anyone interested, take a look at it ,you wont be disappointed.haha

**Comment by neilpanchal** [comment]
Volume control is not working on UP2718Q as well. 

This would be a game changer. I tried looking at the code to see if I can make it work but I am afraid I am not too familiar with OSD/CEC API.

**Comment by JoniVR** [comment]
Keep in mind that tools like Soundflower use a different technique. If I understand it correctly, they use a virtual audio loopback device. 

MonitorControl talks to the display itself directly, which means that if your display doesn't properly support DDC or has a wrong implementation it'll never work unfortunately. 

Both solutions have their own advantages/disadvantages, it would be nice if we didn't need all these tools and Apple just built-in a solution for us.

**Comment by nbolender** [comment]
Speaking from experience, the U2720Q does not support volume control for its line-out port. The proxy audio device project mentioned above should work. If you want a better user experience, the paid application SoundSource has a feature called "Super Volume Keys" which provides this functionality.

**Comment by pseidemann** [comment]
hello,

I can confirm that volume control for the dell U2720Q does not work.
however, the **volume control does work** with this monitor, when booting **windows 10** from a macbook.

so it seems there is some way to control it via software. maybe the windows driver can be used as a template for this monitor?

**Comment by vinhtnk** [comment]
I found a solution:
https://www.dell.com/community/Monitors/U2720Q-Audio-line-out-MacBook-Pro-no-volume-control/td-p/7676295

**Comment by waydabber** [comment]
I recommend using eqMac or SoundSource for controlling volume on this display (these are software solutions and do not control the amplifier inside the display). I'll close this issue as there is nothing to do on MonitorControl's end. Thank you!

**Comment by dufferzafar** [comment]
@waydabber On My Dell U2414H Monitor, only the brightness controls work. That's fine by me, but I want to know whether that is directly controlling my monitor's brightness, or is it using a software approach like Gamma?

I tried Lunar app and it said that there's no way to control my monitor's brightness so it fell back to Gamma.

How can I know if MonitorControl is also falling back to Gamma?

**Comment by owenzhao** [comment]
> @waydabber On My Dell U2414H Monitor, only the brightness controls work. That's fine by me, but I want to know whether that is directly controlling my monitor's brightness, or is it using a software approach like Gamma?
> 
> I tried Lunar app and it said that there's no way to control my monitor's brightness so it fell back to Gamma.
> 
> How can I know if MonitorControl is also falling back to Gamma?

That is easy. For DDC, when you change the brightness, you can find the value of the brightness of the Monitor is changed as well. You can check it with the button on the monitor.

**Comment by waydabber** [comment]
Yes, that's a valid approach. Also, if you see that only the 0-50% of the brightness slider has any effect, it's doing software only.

**Comment by antoooooooooooonie** [comment]
Can confirm eqMac works perfectly (Dell U2520D) –it's the only app that has a free forever version. It's a disgrace Dell forces us to rely on 3rd party apps to get all promised usability out of our €366 monitors. Thanks for the tip @dufferzafar!
