### ISSUE TITLE
CMD + F1 shortcut to alternate between mirror desktop or extended desktop stop working

### ISSUE THREAD

**Issue by didaquis** [MonitorControl/MonitorControl#227]
First of all, thank you very much for this software! 😍

CMD + F1 to alternate between mirror desktop or extended desktop stop working after install MonitorControl.
There are some way to configure MonitorControl default keys to prevent override "CMD + F1" keyboard shortcut ????

**Comment by waydabber** [comment]
We could catch F1+BrightnessDown and induce mirroring manually using `CGConfigureDisplayMirrorOfDisplay()`.

**Comment by waydabber** [comment]
I added this in 3.1.0. I had to implement the feature programmaticaly as I could not figure out how to kick in the original implementation of the OS. To me it seems to work the same way as the original but testing will be needed.
