### ISSUE TITLE
Check for updates / auto-update

### ISSUE THREAD

**Issue by jhildenbiddle** [MonitorControl/MonitorControl#231]
It would be great to see this functionality added. I only discovered that MonitorControl 2.0 was released after reviewing my menubar items and realizing I needed to manually check for new versions.

BTW, really appreciate this app. Makes life much easier. Thank you!

**Comment by JoniVR** [comment]
This is related to #5. I've been really wanting to look into this but haven't gotten to it yet as other things seemed like higher priority. Soon I'll hopefully get some more time to look into it.
