### ISSUE TITLE
Compatibility with iTunes Volume Control

### ISSUE THREAD

**Issue by JonasGessner** [MonitorControl/MonitorControl#232]
Hi Guillaume, I have been using this tool for a while and it is great!

I also use another app called [iTunes Volume Control](https://github.com/alberti42/iTunes-Volume-Control) that I use to be able to control AirPlay volume. Sadly they both do not work well together. Basically it seems either tool overrides the actions of the other. If I launch MonitorControl after iTunes volume control then MonitorControl completely takes over and controlling AirPlay volume no longer works. Whereas the other way round the volume of the monitor is never changed.

I also opened an issue in the iTunes Volume Control project: https://github.com/alberti42/iTunes-Volume-Control/issues/26

I am hoping that there is some simple way to make these two apps compatible with each other. I'm willing to help, but I am first asking here since you surely know the involved APIs better than me.

Thanks,
Jonas

**Comment by JonasGessner** [comment]
Not really a fix, but In my fork I simply added the functionality of iTunes Volume Control into MonitorControl and no longer use iTunes Volume Control at all: https://github.com/JonasGessner/MonitorControl/tree/music-control

**Comment by waydabber** [comment]
Great! This issue seems to be resolved then, so I'll close it! Thank you!

**Comment by JonasGessner** [comment]
No, I resolved this for myself in a way that isn't generally applicable. In general this problem still exists.

**Comment by waydabber** [comment]
Hi, maybe I did not understand the problem. We plan to add customization options to the keyboard in the following issue:

https://github.com/MonitorControl/MonitorControl/issues/118

Will that solve the problem? It means that you'll be able to remap the standard volume keys to something else.

**Comment by JonasGessner** [comment]
The issue is simply that this tool does not work when installed together with iTunes Volume Control.
 
> Basically it seems either tool overrides the actions of the other. If I launch MonitorControl after iTunes volume control then MonitorControl completely takes over and controlling AirPlay volume no longer works. Whereas the other way round the volume of the monitor is never changed.

**Comment by waydabber** [comment]
I see. How do you propose to solve the problem? What should be changed in MonitorControl in order to solve the issue? Does the issue persist if you turn set the keyboard to listen to the Brightness keys only?
