### ISSUE TITLE
Thanks! work perfectly for DELL U2720QM

### ISSUE THREAD

**Issue by 1c7** [MonitorControl/MonitorControl#236]
![image](https://user-images.githubusercontent.com/1804755/84076676-c896ae80-aa08-11ea-8b6f-4492168c83b7.png)

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/84076782-fa0f7a00-aa08-11ea-9cb7-5c6d2981dc87.png)

**Comment by 1c7** [comment]
This is a 4k 27 inch monitor made by DELL
![image](https://user-images.githubusercontent.com/1804755/84076857-14e1ee80-aa09-11ea-94c3-f080b86418fc.png)

**Comment by 1c7** [comment]
I just want open this issue to say thank you
and let other people know it work with this montior model

**Comment by 1c7** [comment]
@ypresto OK, I would try this and let you know the result

**Comment by 1c7** [comment]
#208 Says after setting the color profile to `DCI-P3`, the **brightness control** doesn't work
(from keyboard)

because I am using a Macbook Pro 2017 15 inch,
I don't have brightness control on keyboard(Physical F1-F12 key), it's on touchbar

also, Keyboard Brightness control or touchbar brightness control should only be able to change the laptop brightness, it should not affect external monitor at all.

Anyway, back to the topic.

## SMPTE RAP 431-2-2007 DCI(P3)
On `DELL U2720QM`
After changing color profile to `SMPTE RAP 431-2-2007 DCI(P3)`
the brightness control still work from taskbar

![image](https://user-images.githubusercontent.com/1804755/84361846-de6dc480-abfe-11ea-974c-359d14f53ffa.png)

![image](https://user-images.githubusercontent.com/1804755/84361858-e3327880-abfe-11ea-9549-d348708fa0fd.png)

## Display P3 work fine too
![image](https://user-images.githubusercontent.com/1804755/84361901-f3e2ee80-abfe-11ea-9edd-a62f881d3f6e.png)

**Comment by 1c7** [comment]
## `image P3` work fine too
![image](https://user-images.githubusercontent.com/1804755/84361956-09f0af00-abff-11ea-8d40-0ee41ca5afb9.png)

**Comment by 1c7** [comment]
You can't tell the brightness from screenshot.
but it does work

**Comment by 1c7** [comment]
@ypresto if you want more testing before you buy it.
let me know
I am happy to help

it's quite expensive, cost `4099` RMB here in China
I brought it from Taobao

**Comment by 1c7** [comment]
I can't find this setting

![image](https://user-images.githubusercontent.com/1804755/84362611-145f7880-ac00-11ea-8e27-7c950ce3820d.png)

**Comment by ypresto** [comment]
Thanks! I finally bought this monitor and tested combinations of settings.

https://github.com/MonitorControl/MonitorControl/issues/208#issuecomment-643726203

Now it is working very well. :tada:

**Comment by sunhch** [comment]
Is volume control also working on your U2720Q? The brightness control is fine, but the volume control does not work on my U2720Q. The OSD window will appear to be working, but the actual volume from speakers does not change.
