### ISSUE TITLE
Volume keys show up but work

### ISSUE THREAD

**Issue by kevindecaf** [MonitorControl/MonitorControl#240]
The volume controls and brightness controls show up as working But they don’t do anything when I turn them up or down

**Comment by JoniVR** [comment]
Hi, we have a Monitor Troubleshooting wiki for this:
https://github.com/the0neyouseek/MonitorControl/wiki/Monitor-Troubleshooting

This might be a good place to look first, additionally, you usually should fill out the issue template and provide some information about your system. It's really hard to help you without any information given.

**Comment by kevindecaf** [comment]
Apologies my system in a Mac mini 2018 hooked up via HDMI
