### ISSUE TITLE
Brightness constantly changed back to system values on LG UltraFine 4K when Night Shift kicks in

### ISSUE THREAD

**Issue by musichien** [MonitorControl/MonitorControl#244]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

### Describe the issue
Hi there, I noticed that MonitorControl is not working on my LG UltraFine 4K when Night Shift kicks in. As for what I observed for the Night Shift activation, the macOS changes the colour temperature of the monitors gradually for about 30 minutes to make a transition. And at each little step of the colour temperature change, **the system will also restore the macOS brightness state value, which is usually different from the MonitorControl value**.

### Steps to reproduce
1. The brightness in the System Preferences is set to 50% for LG UltraFine 4K and none for LG HDR 4K (not controlled by macOS).
2. The brightness of both monitors is set to 100% by MonitorControl
3. MonitorControl doesn't override the 50% of brightness set for LG UltraFine 4K in the System Preferences, but changes the actual brightness of both displays to 100%.
4. When the Night Shift kicks in, the system will constantly set the brightness of LG UltraFine 4K back to 50%, at each little step of the colour temperature transition for about 30 minutes in total. This is not the case for LG HDR 4K as its brightness is not controlled by macOS.
5. Change the brightness of the LG UltraFine 4K back to 100% via MonitorControl. But it will be changed back to 50% by system in just a few seconds.
6. The issue only happens when the Night Shift is making a gradual transition. Not before or after the Night Shift is totally activated.

### Expected behavior
The brightness of both monitors should be controlled by MonitorControl and not constantly changed back by system, i.e. staying at 100%

### Additional context
For now I could see that the issue is probably caused by the nature of the Apple-sold displays: LG UltraFine 4K (and 5K), their brightness is directly controlled by the System Preferences, and the brightness change via MonitorControl seems not being reflected in the system preference. And the problem becomes significant when a LG UltraFine 4K or 5K display is paired with other non-Apple-sold displays, as macOS system preference has the brightness control for the former ones but not for the later ones.

What I can do to remediate the issue for now is to deactivate the Night Shift, or change it to a fixed schedule to possibly reduce the span of the gradual colour temperature transition imposed by the macOS system. I would appreciate it a lot if you guys could look into this issue and hopefully find a better solution.

PS: I noticed a similar issue here https://github.com/MonitorControl/MonitorControl/issues/154, for which I believe that the main cause might be the same.

**Environment Information (please complete the following information):**
 - macOS version: 10.15.5
 - MonitorControl version: 2.0.0
 - Monitor(s): LG UltraFine 4K, LG HDR 4K (27UL850-W)
 - Mac model: MacBook Pro 16-inch
 - Monitor Cable(s)/Connection(s): LG UltraFine 4K (Thunderbolt 3), LG HDR 4K (USB-C)

**Comment by JoniVR** [comment]
Hi, thanks for the detailed information, really helps!

Could it perhaps be that the brightness is of the LG UltraFine is being controlled through DDC and that these changes are not reflected in macOS settings because it doesn't sync 2-way? 

We recently added internal display brightness control through a private api, I wonder if we could somehow figure out a way to use that API for the UltraFine display, perhaps that would work. Does it seem like the UltraFine is being controlled through DDC?

**Comment by musichien** [comment]
Thanks for the reply.

Yes, I think it's controlled by DDC. I tried another brightness control app here https://github.com/alin23/Lunar based on DDC and they work well with the UltraFine.
