### ISSUE TITLE
Volume changes only up to 4 boxes

### ISSUE THREAD

**Issue by yx1100** [MonitorControl/MonitorControl#246]
**Checklist**
- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
(My English is not very good, I hope you can understand what I'm saying.)
My monitor is BenQ EW2780U, the volume control of the monitor itself is form 0 to 50.
After I start the MonitorControl, When I use my magic keyboard to control the volume of the system, the volume can only up from 0 to 4 boxes(=12 of the volume of the monitor itself), like the screenshoot below, and then the up key doesn't work anymore ,but the down key can reduce to 0 in any time.
The volume control in menu bar is always normal.
The volume control of monitor itself is always normal.
And the control of brightness is normal.

**Expected behavior**
I want the control of the volume can change from 0 to the highest.

**Screenshots**
<img width="221" src="https://user-images.githubusercontent.com/12426322/85498004-7d3bed00-b611-11ea-8404-1938ef8011e3.png">
**Environment Information (please complete the following information):**
 - macOS version: macOS 10.15.5
 - MonitorControl version: 2.0.0 build 640
 - Monitor(s): BenQ EW2780U
 - Mac model: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
 - Monitor Cable(s)/Connection(s): USB-C(DisplayPort)

**Comment by JoniVR** [comment]
Probably related to #201, closing as duplicate 🙂
