### ISSUE TITLE
ASUS VG289 Display Brightness Control not working

### ISSUE THREAD

**Issue by futandrew** [MonitorControl/MonitorControl#250]
ASUS VG289 Display Brightness control not working, but Volume works great with this app. Hopefully, this could be fixed soon!

**Comment by JoniVR** [comment]
Hi, we have a Monitor Troubleshooting wiki for this:
https://github.com/the0neyouseek/MonitorControl/wiki/Monitor-Troubleshooting

This might be a good place to look first
