### ISSUE TITLE
Brightness not working on Asus XG35VQ

### ISSUE THREAD

**Issue by vikeshhh** [MonitorControl/MonitorControl#251]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
Installed Monitor Control. Sound Adjustment works fine but Brightness control stopped working. It use to work. Then suddenly stopped. Also when I adjust the brightness via the monitor only, say to 50%, when I use monitor control to increase it drops to 0.

**Expected behavior**
Pressing Brightness Up and Down will adjust my external Monitor (Asus XG35VQ) Brightness respectively

**Screenshots**
![Screen Shot 2020-07-08 at 7 09 26 PM](https://user-images.githubusercontent.com/30156635/86985818-61773180-c14f-11ea-929c-6cfd4785f613.png)

**Additional context**

**Environment Information (please complete the following information):**
 - macOS version: 10.15.5
 - MonitorControl version: 2.0.0 (Build 640)
 - Monitor(s): Asus XG35VQ

 - Mac model: MacBook Pro 13" 2019, Four Thunderbolt 3 Ports
 - Monitor Cable(s)/Connection(s): Displayport to Elgato Thunderbolt Dock 3

----------------                                   -----------------------------                                                         ------------------
-Asus XG35VQ- <==DisplayPort==>-Elgato Thunderbolt 3 Dock- <==USB 3 thunderbolt cable==> -MacbookPro 13-
----------------                                  ------------------------------                                                        ------------------

**Comment by JoniVR** [comment]
Did it stop working after upgrading MonitorControl or just randomly?

**Comment by vikeshhh** [comment]
I installed v2.0.0 Build 640 and always was on that version. Just stopped working. Volume works great though.
