### ISSUE TITLE
String Consistency

### ISSUE THREAD

**Issue by reustle** [MonitorControl/MonitorControl#255]
<img width="291" alt="image" src="https://user-images.githubusercontent.com/304560/87131815-ee48f900-c2cf-11ea-9506-fdc7794cd8a7.png">

I could be wrong, but these strings could be uniformly capitalized.

This one seems fine: https://github.com/MonitorControl/MonitorControl/blob/9fd78dc17fe16dc9a6e05c66364a87c874285f4b/MonitorControl/UI/en.lproj/Main.strings#L54

We could lowercase "Login" here.
https://github.com/MonitorControl/MonitorControl/blob/9fd78dc17fe16dc9a6e05c66364a87c874285f4b/MonitorControl/UI/en.lproj/Main.strings#L30

We could lowercase "Brightness" and "Contrast" here
https://github.com/MonitorControl/MonitorControl/blob/9fd78dc17fe16dc9a6e05c66364a87c874285f4b/MonitorControl/UI/en.lproj/Main.strings#L24

Thoughts?

**Comment by the0neyouseek** [comment]
Please feel free to open a Pull resquest for this changes :)

**Comment by reustle** [comment]
@the0neyouseek Happy to do so, but I've never done xcode dev before. I'm guessing it isn't as easy as changing this file, but also doing some building / compiling?

**Comment by the0neyouseek** [comment]
No need if you’re just changing strings 😊. You can simply edit the file (even directly in github if you don’t want to download the whole project)
