### ISSUE TITLE
Add modifier keys to control multiple monitors by keyboard

### ISSUE THREAD

**Issue by dlopuch** [MonitorControl/MonitorControl#256]
**Checklist**
- [x] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**
MonitorControl picks up my keyboard brightness adjustments and adjusts the brightness of my external monitor. Awesome tool! Love being able to control from my keyboard!

But, I have two external monitors. It would be great to have a modifier key like cmd or shift or alt to automatically adjust the brightness of the second monitor.

Hitting the "adjust all monitors together" preference doesn't fit my needs because they are different monitors and so especially at night I adjust them to different brightness scalings.

**Comment by StevenM1** [comment]
I second this request 👍 I'd like to be able to control my MacBook Pro screen & volume (used as a secondary display) separately from my external monitor. For me even better would be to manually specify the keys that MonitorControl listens to - I sometimes use a non-Apple keyboard that doesn't feature the brightness adjustment settings on F1/F2 or volume control keys.

**Comment by EugenTarasenko** [comment]
I agree. We need shortcuts to control the brightness of several monitors separately. (e.g. F1/F2 → built-in monitor brightness, ⌥F1/F2 → external monitor brightness)

**Comment by waydabber** [comment]
Hey, we already have this - ctrl+F1/F2 controls internal display brightness, while simple f1/f2 controls the display with the mouse on. Please let me know if this is not a good solution and something else should be added. Until that time I'll close this issue. Thank you!
