### ISSUE TITLE
Application will not open with macOS Big Sur Beta 20A4299v

### ISSUE THREAD

**Issue by edmfperez** [MonitorControl/MonitorControl#257]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
The application will no open in Big Sur. Could not find any relevant similar issues when searching. Hopefully it'll work in the future.

**To Reproduce**
1. Download .dmg
2. Move .app to /Applications/
3. Use `open -a MonitorControl.app` within terminal

**Expected behavior**
I expected the .app to at least open, lol.

**Screenshots**
n/a
**Additional context**
n/a

**Environment Information (please complete the following information):**
 - macOS version: 20A4299v
 - MonitorControl version: 2.00
 - Monitor(s): BenQ EW2780U

**Comment by JoniVR** [comment]
I have not tried Big Sur myself. Did you get a crash report trying to open it?

**Comment by waydabber** [comment]
Hey I am using Big Sur since Dev Beta1 and Monitorcontrol works fine for me. I have upgraded from Catalina though and the app was carried over from the Catalina installation.

<img width="338" alt="Screen Shot 2020-07-11 at 10 37 08" src="https://user-images.githubusercontent.com/37590873/87220248-85f72780-c362-11ea-9f3e-8b04fa35de49.png">

**Comment by edmfperez** [comment]
Hmm, so I definitely did not carry over the install since I downloaded it through Big Sur. This could probably be it. My install of Big Sur is FUBAR at the moment so I could try a fresh Catalina and see it if carried over for me. Will report back with my findings.

**Comment by waydabber** [comment]
@sn0wyfall The processor icon is the standard MacOS icon for eGPUs. The double belong to the [Mac Media Key Forwareder](http://milgra.com/mac-media-key-forwarder.html) app.

**Comment by sn0wyfall** [comment]
@waydabber That's awesome, thank you!

**Comment by JoniVR** [comment]
How has Big Sur been for people who are running it? Any issues with MonitorControl? I'm thinking about upgrading myself soon.

**Comment by waydabber** [comment]
> How has Big Sur been for people who are running it? Any issues with MonitorControl? I'm thinking about upgrading myself soon.

Works perfectly! I am using the latest dev beta.

**Comment by JoniVR** [comment]
Running Big Sur myself now, seems to work well too, I'll close this for now.
