### ISSUE TITLE
Redesign sliders to reflect Big Sur Control Center's brightness and volume sliders

### ISSUE THREAD

**Issue by waydabber** [MonitorControl/MonitorControl#258]
Big Sur has a new Control Center with a dedicated brightness slider which is always present even when the display does not support brightness control and cannot be removed.

<img width="309" alt="Screen Shot 2020-07-11 at 10 39 46" src="https://user-images.githubusercontent.com/37590873/87220405-a4a9ee00-c363-11ea-8dd9-b43483695352.png">

The brightness control can also be added as a stand alone taskbar item:

<img width="317" alt="Screen Shot 2020-07-11 at 10 50 06" src="https://user-images.githubusercontent.com/37590873/87220473-53e6c500-c364-11ea-92c9-29a046fba050.png">

If hooking up MonitorControl with this slider is not possible it'd be nice for MonitorControl to mimic the design of the standalone display control as close as allowed for a more organic, "integrated" feel.

**Comment by extric99** [comment]
@waydabber Does brightness control work for you on BigSur? On my Dell U2720Q only contrast slider is working while under Catalina both work fine..

**Comment by waydabber** [comment]
> @waydabber Does brightness control work for you on BigSur? On my Dell U2720Q only contrast slider is working while under Catalina both work fine..

Yes, it is working. I am using an eGPU though, the issue might be adapter specific.

**Comment by kevinjohncutler** [comment]
+1, this would be excellent. Also should implement the volume control slider at the same time!

**Comment by jtbandes** [comment]
I found some private APIs that work for adjusting brightness on Big Sur — though I only tested for my M1 MacBook Air's built-in display. But maybe it will help for MonitorControl as well. I wrote more about it here: https://github.com/Hammerspoon/hammerspoon/issues/2668#issuecomment-782905780.

**Comment by gferreroferri** [comment]
I vote for this!

**Comment by waydabber** [comment]
Well since now I am a developer of monitorControl now, I'll addign this to myself. Would have to build a custom slider for that though so this will not happen any time soon. :)

**Comment by JoniVR** [comment]
I can take a go at this when I get the time, I tried recreating it with SwiftUI a few days ago but SwiftUI doesn't seem very usable with build scripts or generally in the project. Shame though as it seems like an ideal use-case for this.

**Comment by waydabber** [comment]
I was looking into it myself as well but was quickly discouraged lol. :)

**Comment by JoniVR** [comment]
I was getting fairly close manipulating the default slider but I couldn't get it stable so seems like it'll probably be a custom AppKit component.

**Comment by waydabber** [comment]
Part of redesigning the slider could be adding scroll wheel (magic mouse swipe) support to the slider:

https://github.com/MonitorControl/MonitorControl/discussions/592

It indeed works in Control Center but it is not a standard thing for NSSlider.

**Comment by waydabber** [comment]
Scrolling/swiping now works on sliders - see https://github.com/MonitorControl/MonitorControl/issues/601.

**Comment by waydabber** [comment]
This seems to be harder than I thought. I can customize NSSlider to look like we want but I can't get around the fact that during mouse tracking the slider wants to redraw only the part that is near the knob and the original slider bar area only (dirtyRect). This is problematic because we want the full background to redraw because of the filled white bar left of the knob. If one moves the mouse too fast, then artifacts happen and don't go away until mouse release when the entire control is redrawn.

**Comment by JoniVR** [comment]
I had crossed to the same problem using NSSlider customisation, I think an approach that might work is using SwiftUI without preview (basically just building like we do now) since preview doesn't work properly, or just building it fully custom in AppKit, though I think that's probably harder than SwiftUI.

**Comment by waydabber** [comment]
I think we should just leave this as it is. I created a custom slider to fix the tick mark issue in dark mode and also to have the ability to show more than one display on a single slider in combined slider mode when keyboard and apple brightness syncing is not enabled (in this case multiple displays can have different brightnesses but there is one slider). It looks kinda funny but I like it:

<img width="300" alt="Screen Shot 2021-09-22 at 21 24 42" src="https://user-images.githubusercontent.com/37590873/134411373-fc9b698d-fe36-4f98-89d5-ad63f84dd047.png">

Here is with the tick mark style:

<img width="280" alt="Screen Shot 2021-09-22 at 21 25 07" src="https://user-images.githubusercontent.com/37590873/134411451-bcaf1f2a-7c46-46bd-a0a5-8a1d6c0aafb0.png">

When apple brightness syncing is active (ambient light sensor or touch bar is used), the various knobs can move in unison while keeping their distance which looks cool.

**Comment by waydabber** [comment]
All right we should not abandon it. I was just angry at this thing yesterday. :)

**Comment by waydabber** [comment]
Ok, it seems like I found an easy solution to the artifact problem. Why did I spend so much wasted time on this yesterday and did not find the solution is beyond me... :/

**Comment by waydabber** [comment]
(the solution is that you can simply override the function that defines the bar rectangle and if you do that then dirtyRect will honor this apparently and will redraw everything as intended. It should have been obvious from the start but I somehow missed it.)

**Comment by waydabber** [comment]
<img width="274" alt="Screen Shot 2021-09-23 at 17 38 39" src="https://user-images.githubusercontent.com/37590873/134538998-576f21ce-e1d2-40e9-8ffa-90022344eda8.png">

😎 

I even replicated the shadow and the way the knob slowly fades away as it is getting closer to the icon.

**Comment by waydabber** [comment]
The control can also display a range (if there are multiple displays combined into a single slider and syncing stuff is disabled). If there are more than 2 displays then small dots will signify each display's location on the slider.

<img width="265" alt="Screen Shot 2021-09-23 at 21 30 22" src="https://user-images.githubusercontent.com/37590873/134571877-16e5aef3-480c-430e-a899-1ce1df1af55a.png">
