### ISSUE TITLE
Will not work when monitor is set on DisplayPort1.2 mode

### ISSUE THREAD

**Issue by kotani123** [MonitorControl/MonitorControl#259]
I have a Dell UP2414Q monitor, and I have been trying to get MonitorControl to work with no luck. I tried ddcctl as well, and I have a message telling me that it could not poll the monitor.

When I disable the DisplayPort1.2 mode, I am able to use MonitorControl and ddcctl perfectly, but of course, I'm stuck at 30hz. Is there any reason that this mode would prevent DDC from working properly, or is it a issue with the Dell hardware?

Anyone else with this issue?

Any insight would be greatly appreciated!

**Comment by JoniVR** [comment]
Could be a number of things, cable not supporting it would probably be the easiest one to try first. 
See: https://github.com/the0neyouseek/MonitorControl/wiki/Monitor-Troubleshooting

**Comment by waydabber** [comment]
I'll close this issue since it seems we are not able to do anything about this on MonitorControl's side.
