### ISSUE TITLE
Listen for contrast only

### ISSUE THREAD

**Issue by nekrasovdmitriy** [MonitorControl/MonitorControl#26]
Please add an option for listening for contrast value only. On some displays contrast value has much more steps for dimming display.

**Comment by funbben** [comment]
Hi, I just installed 1.3.0, and it works fine for Volume/Brightness. Thanks a lot.

As to dim constrat, It could be useful to use option+Brigthness (Or cmd+Brightness)

What's the Apple algorithm is regarding brigthness. I'm pretty sure they use contrast and brightness dimming at the same time when dimming "brightness".

**Comment by the0neyouseek** [comment]
Hi @nekrasovdmitriy and @funbben ,

Contrast and Brightness are two separate and completely different things. Here's an image found on [dspguide.com](http://www.dspguide.com/ch23/5.htm) that explains how it works.

[![](http://www.dspguide.com/graphics/F_23_10.gif)](http://www.dspguide.com/ch23/5.htm)

So, having the brightness and contrast synced would not work for a lot of monitors.

But it is a good idea to be able to control it from your keyboard, <kbd>cmd ⌘</kbd> + Brightness seems good as im thinking to use <kbd>option</kbd> for finer dimming (more steps) like on a mac.

I'll try to put that in the next version,
Have a nice day

**Comment by funbben** [comment]
Of course brigthness ans contrast are not the same thing, however on Mac internal display you can’t change the contrast. 
It seems  you dim the brightness, but i’m pretty sure you dim both at the same time

**Comment by joeyhoer** [comment]
I also believe that Apple is scaling both values (brightness and contrast) at the same time. At the very least, when using an external monitor, I must change both values to achieve a similar "brightness" as the native display on my MBP.

I believe defining a contrast range, and then interpolating along that range, may more closely mimic the "brightness" of the native display. I've described this feature request in more detail within another thread: https://github.com/the0neyouseek/MonitorControl/issues/31#issuecomment-485432536
