### ISSUE TITLE
More granular Volume controls with Magic Keyboard

### ISSUE THREAD

**Issue by MatthiasSomay** [MonitorControl/MonitorControl#260]
**Checklist**

- [x] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**
Increasing/decreasing the volume of my LG monitor through the volume buttons on the Apple Magic Keyboard is always by 6 levels. For example, I cannot to go from 6 to 8, only from 6 to 12, 12 to 18,...

**Describe the solution you'd like**
An option in preferences where you can set how much the volume increases/decreases with each keypress

**Describe alternatives you've considered**
Control volume directly from the display itself or from MonitorControl on the taskbar

**Comment by frankpape** [comment]
It would be nice to have the option to configure the default, but you can use option+shift+volume controls to make more granular changes (this is standard MacOS behavior, also works without MonitorControl).

**Comment by MatthiasSomay** [comment]
> It would be nice to have the option to configure the default, but you can use option+shift+volume controls to make more granular changes (this is standard MacOS behavior, also works without MonitorControl).

This is good workaround, thank you for this!
