### ISSUE TITLE
Proportional settings because second screen doesn't light like the macbook

### ISSUE THREAD

**Issue by ouacheter** [MonitorControl/MonitorControl#264]
Great tool, thank you.

My external display has way more backlight than my macbook.
1) So when I am 100% on macbook, external display is 100% and too bright.
2) When I am 0% on macbook, external display is a 0% and still too bright.

Since I can't use the synchronisation of mac and external screen light for now, MonitorControl just saves me from bending to the screen button lol. 

For 2) You can't do about it I know.

For 1), it could be great to have an upper and lower limit setting to visually feel the same backlight.

**Comment by sn0wyfall** [comment]
It would be nice having a "decrease contrast" option where beyond the lowest brightness a black shade could be added to that display (like ScreenShade, but monitor-specific). Then, you could, say, assign 100% MacBook = 70% display, 10% MacBook = -30% display (where a negative number is the contrast thing kicking in)

**Comment by quinncomendant** [comment]
I just came here to request the same feature. I have the same situation: at low levels, my external display is always brighter than my Macbook display. 

It would be solved by adding individual display brightness offset value, e.g., I'd set my Macbook display to have a brightness of `+15` (percentage points) higher than the other displays, which would shift linearly:

- external 0% ↔︎ Macbook 15%
- external 50% ↔︎ Macbook 65%
- external 100% ↔︎ Macbook 100% (100% is max, obviously)

Having both min and max brightness settings for a display seems more flexible, but would be more complicated to implement. I think for most cases using an offset value would be sufficient.

**Comment by waydabber** [comment]
This issue can now somewhat be resolved by using the new 3.0.0 versions's 'Further lower brightness...' option. Please try if it helps!

About display brightness synchronization among several displays we have a different thread where we track that issue:

https://github.com/MonitorControl/MonitorControl/issues/418

I'll close this one, but feel free to add your thoughts in a new issue or the abovementioned one!
