### ISSUE TITLE
Alternate key bindings

### ISSUE THREAD

**Issue by Muirium** [MonitorControl/MonitorControl#266]
Superb utility! Fantastic work, folks!

I use my MacBook Pro in clamshell mode, with an external display (Dell P2415Q, works great with MonitorControl!) and external keyboards. I’m into mechanical and vintage boards, which have standard F1-F12 keys but no media keys like Brightness Up and Down. So I’d *love* to be able to assign F1 and F2 to brightness up and down, and indeed F3 and F4 for separate control of contrast.

The Mac can control its own built in display using plain old fashioned F1 and F2 keys, as set up in System Preferences here:

![Screen Shot 2020-07-24 at 10 25 43 am](https://user-images.githubusercontent.com/221646/88378123-47b52b80-cd98-11ea-9db9-6751db25fbb8.png)

I’d like MonitorControl to do the same, or even better: let me define Brightness and Contrast keys myself in its UI.

For now, all I can do is drive MonitorControl by mouse. That’s doable, but I so much prefer keys, and doing it from any arbitrary keyboard rather than just my laptop’s own would be gold.

**Comment by CharlesCCC** [comment]
There already a issue opened for this https://github.com/MonitorControl/MonitorControl/issues/118
