### ISSUE TITLE
Same Display is recognized different via Thunderbolt or Displayport

### ISSUE THREAD

**Issue by dieoma76** [MonitorControl/MonitorControl#267]
I do connect my LG5k right now via Thunderbolt to my MacMini 2020, MacOS Catalina (10.15.6) MonitorControl is 2.0 b640.
Controlling Brightness and Volume of the Device ONLY works via Displayport, but not when connecting via Thunderbolt - expectation was it will work either way.

Comparing how Monitor Control detects the Display in Thunderbolt vs Displayport shows it "thinks" its even a different vendor:

**Here the Device via Thunderbolt** (Volume/Brightness **NOT** working)
![MC_Thunderbolt](https://user-images.githubusercontent.com/65195997/88410021-0fccd900-cdd6-11ea-8a1b-66381e0e3e4b.png)

**Here the Device via Displayport** (Volume/Brightness working fine)
![MC1_Displayport](https://user-images.githubusercontent.com/65195997/88410137-3f7be100-cdd6-11ea-9e42-07b551c5862e.png)

Is there a way to tweak MonitorControl to control the Monitor regardless of the Connection method?

**Comment by JoniVR** [comment]
There is not, it could just be that your thunderbolt cable doesn't properly support DDC. I'd suggest trying a different cable first (if you have one laying around). Maybe try with [ddcctl](https://github.com/kfix/ddcctl) first to isolate if it's a cable or MonitorControl issue.

**Comment by dieoma76** [comment]
Well, it´s the Thunderbolt Cable that came with the Monitor. I don´t have an other one, but a different Mac: I tested the Monitor with the same cable on a MacBook Pro and here Monitor Control works as expected - i can change Brightness and Volume! But the situation does sound like #265 [https://github.com/MonitorControl/MonitorControl/issues/265](url). The combination of MacMini 2018, Thunderbolt and Monitorcontrol seems to have issues... How can i help to fix it?

**Comment by JoniVR** [comment]
Closing in favour of #265, let's continue tracking there.
