### ISSUE TITLE
Keyboard shortcuts should not be required

### ISSUE THREAD

**Issue by eligrey** [MonitorControl/MonitorControl#269]
I don't want the keyboard shortcut integration. Every time I launch MonitorControl the app attempts to set shortcuts and warns about lacking permissions, which is quite annoying on startup.

Could you please make it so that users can disable keyboard shortcut functionality? I'd rather not give accessibility permissions to an app for a feature that I don't even want.

**Comment by JoniVR** [comment]
Hi, 
This is already implemented but not released yet, will be out in the next version. You'll be able to select "none" as a "keys to listen for" option and it won't bother you with the permission dialogs anymore.
