### ISSUE TITLE
Keys are working only when the monitor's desktop is active

### ISSUE THREAD

**Issue by vanikin** [MonitorControl/MonitorControl#270]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
I can control the external monitor's volume with keyboard only when the main desktop of the external monitor is active. When there are any fullscreen app active I can't control the volume, and the brightness is changing only on the built-in monitor of my notebook.
I can also change both volume and brightness in menu and when the MonitorControl window is active on top of the fullscreen app.

**To Reproduce**
1. Go to fullscreen 
2. Press volume control button on the keyboard
3. See the volume OSD with the stop sign on the built-in monitor (not the monitor I want to control)
![Скриншот 2020-07-28 09 27 13](https://user-images.githubusercontent.com/17569143/88630232-f919d100-d0b8-11ea-9caf-c1869c563d54.png)

**Expected behavior**
Keyboard keys will change brightness and volume on both monitors

**Additional context**
I can control all settings of the same monitor when it's the only one connected (from my desktop computer running macOS Mojave)

**Environment Information (please complete the following information):**
 - macOS version: macOS High Sierra 10.13.6
 - MonitorControl version: 2.0.0 (build 640)
 - Monitor(s): LG 27UD58-B connected via HDMI
 - Macbook pro 13 late 2011

**Comment by vanikin** [comment]
During describing this bug I found that I can just leave MonitorControl window open and keyboard controls will work fine

**Comment by JoniVR** [comment]
Already fixed, just not released yet. see #237 🙂
