### ISSUE TITLE
Acer X34P Sound Volume change does nothing, while contrast and Brightness work well

### ISSUE THREAD

**Issue by wojciechczyz** [MonitorControl/MonitorControl#271]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
Acer X34P Sound Volume change does nothing, while contrast and Brightness work well.

**Expected behavior**
Changing volume should control the monitor volume

**Additional context**
Connected using Thunderbotlt 3 to Display Port adapter

**Environment Information (please complete the following information):**
 - macOS version: Latest released Catalina 10.15.6
 - MonitorControl version: Latest released 2.0.0
 - Monitor(s): X34P 
 - Mac model: Mac Book Pro 2018
 - Monitor Cable(s)/Connection(s): (e.g. DisplayPort) Thunderbotlt 3 to Display Port adapter

**Comment by wojciechczyz** [comment]
I believe this is monitor firmware bug, reported it as well in acer communities:
https://community.acer.com/en/discussion/620010/control-sound-volume-in-monitor-x34p-from-windows-mac-via-ddc-with-tool-such-as-monitorcontrol#latest

**Comment by vincentcox** [comment]
Any fix available?

**Comment by wojciechczyz** [comment]
Hi,Please open case directly with Acer support, we need enough votes/pressure to fix this.Cheers!On Jul 30, 2021 12:08 PM, Vincent Cox ***@***.***> wrote:
Any fix available?

**Comment by vincentcox** [comment]
Thanks for the advice, but they’ll never going to update firmware of an 5+ years old monitor (in my case the acer X34a). 

https://eqmac.app/ Worked for me. 

I prefer this project and app (ui and design), but the other app can be used as free as well and has it working for me. 

No hard feelings towards this, I love this project but in my very specific case that other app is my only working solution.

**Comment by wojciechczyz** [comment]
Were you able to control audio volume on Mac with this other app?Thanks!On Jul 30, 2021 1:19 PM, Vincent Cox ***@***.***> wrote:









Thanks for the advice, but they’ll never going to update firmware of an 5+ years old monitor (in my case the acer X34a). 







https://eqmac.app/ Worked for me. 







I prefer this project and app (ui and design), but the other app can be used as free as well and has it working for me. 







No hard feelings towards this, I love this project but in my very specific case that other app is my only working solution.

**Comment by vincentcox** [comment]
@wojciechczyz it's not adjusting the volume on the screen itself, but the master out volume to the screen. Entirely different things, i know, but in my case it was sufficient. I just put the volume of my screen on 60% and adjust the master out to the screen if needed.

**Comment by waydabber** [comment]
Hi, with displays that has problems with volume control, I recommend eqMac or SoundSource (these are software solutions and do not control the amplifier inside the display). Since there is no much we can do with this on MonitorControl's side, I'll close this issue for now. Please feel free to comment anyway if you feel that we can be of any help with this! Thank you!
