### ISSUE TITLE
How about a digital simulation of brightness for non-DDC devices?

### ISSUE THREAD

**Issue by tylerweitzman** [MonitorControl/MonitorControl#272]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

I could not get monitor control to work with my projector and the ddcctl tool shows this error
```
iMac-Pro:ddcctl user$ ./ddcctl -d 1 -b 30
D: NSScreen #1951450272 (1280x720 0°) HiDPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.name: BenQ PJ
D: action: b: 30
D: setting VCP control #16 => 30
E: Failed to send DDC command!
```
I assume that my projector is not DDC/CI compatible since its manual does not mention it being so (while I found another projector from the same manufacturer whose manual does say it supports it). In any case the only input options I have are HDMI and VGA (and I am using HDMI, is it worth buying a VGA cable?).
In any case assuming that there isn't a solution to get my projector supported, I was wondering about simulating brightness- much the way flux does, or the way that Spotify does if I lower the Spotify volume rather than the projector volume

**Environment Information (please complete the following information):**
 - macOS version: 10.14.6
 - MonitorControl version: 2.0.0
 - Monitor(s): BenQ HT2150ST Projector
 - Mac model: iMac Pro
 - Monitor Cable(s)/Connection(s): HDMI to DisplayPort (Projector input is HDMI/MHL, which connects to an HDMI to USB-C adapter to connect to the iMac)

**Comment by sn0wyfall** [comment]
This would be super cool. In the meantime, check out ScreenShade. Works globally across monitors though.

**Comment by amard33p** [comment]
> This would be super cool. In the meantime, check out ScreenShade. Works globally across monitors though.

Also https://apps.apple.com/in/app/quickshade/id931571202

**Comment by amard33p** [comment]
This feature will also be helpful for cases where the monitor manufacturer did not release DDC compatible drivers for MacOS. A lot of great Dell monitors fall into that category. 
References:
https://www.dell.com/community/Monitors/Dell-monitor-Apple-FAQ/td-p/7380520
https://apple.stackexchange.com/questions/61045/does-apple-support-ddc-ci-for-3rd-party-displays-via-apples-thunderbolt-to-dvi

**Comment by sn0wyfall** [comment]
> > This would be super cool. In the meantime, check out ScreenShade. Works globally across monitors though.
> 
> A free, stripped down alternative https://apps.apple.com/in/app/quickshade/id931571202

Interesting, that's the one I actually use. I must have mistyped xD

**Comment by waydabber** [comment]
I added this in the new 3.0.0 beta builds (will be enabled by default in future releases as a fallback option). MonitorControl's implementation is superior to quickshade as it uses proper gamma table manipulation which results in better visuals and also affects the mouse cursors (unlike QuickShade).

Please try it and if it works, close this issue. Thanks!

**Comment by waydabber** [comment]
Hi, we have relased the [3.0.0 version](https://github.com/MonitorControl/MonitorControl/releases/tag/v3.0.0-rc1). Could you please test if this issue is resolved and report back? Thank you!

**Comment by amard33p** [comment]
@waydabber, In the [release notes of 3.0.0-rc1](https://github.com/MonitorControl/MonitorControl/releases/tag/v3.0.0-rc1) it says
>Enable software dimming if required, this is enabled by default.

But that was not the case when I installed it.

Also if only "Enable software dimming" is checked, the slider does not seem to have any effect on the brightness.
Only if we also check "Further lower brightness via s/w dimming" does the black overlay appear.

Check out the screen recording : https://ufile.io/i0mhnc9h

Monitor model: Dell P2419H connected via USB C <> HDMI

**Comment by waydabber** [comment]
Hi, the slider will only have effect if you disable "Use hardware DDC control" for the display in the Displays tab. Otherwise MC thinks it can control the display via DDC (while in practice it can't since something is wrong with the display firmware).

<img width="803" alt="Screen Shot 2021-08-21 at 17 38 39" src="https://user-images.githubusercontent.com/37590873/130327195-5280a138-1538-4374-8da5-ccb732adf14f.png">

**Comment by amard33p** [comment]
> Hi, the slider will only have effect if you disable "Use hardware DDC control" for the display in the Displays tab. Otherwise MC thinks it can control the display via DDC (while in practice it can't since something is wrong with the display firmware).
> 
> <img alt="Screen Shot 2021-08-21 at 17 38 39" width="803" src="https://user-images.githubusercontent.com/37590873/130327195-5280a138-1538-4374-8da5-ccb732adf14f.png">

Ahh I see...It works now! But it's not readily apparent to a new user.
Might I suggest that if "Enable software dimming" is checked "Use hardware DDC control" is automatically deselected?
I don't see a reason why a user would need both.

**Comment by waydabber** [comment]
There are displays that are not controllable and MontorControl knows about it. The feautre is mainly for these situations, but can be used for a display with faulty firmware as well - but since MC can't detect this, the user manually has to disable hardware control.

I'm glad that it works now, hope you like this new function! I'll close the issue for now then. :)
