### ISSUE TITLE
Change brightness in 1% increments 

### ISSUE THREAD

**Issue by sn0wyfall** [MonitorControl/MonitorControl#273]
**Checklist**

- [ ] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**
Some monitors have a strange flickering issue when changing brightness through DDC, as described in [this issue](https://github.com/kfix/ddcctl/issues/63).

**Describe the solution you'd like**
To avoid the issue, the brightness needs to gradually be changed down. For example, instead of telling the monitor to go to 20% from 80%, it can be told to go to 79%, then 78%, then 77%, etc. all the way to 20%. This would prevent the flickering issue. 

**Describe alternatives you've considered**
I have considered using a bash script with ddcctl, but that seems strange heh

**Comment by JoniVR** [comment]
You can use <kbd>shift</kbd>+<kbd>alt</kbd> modifiers to change brightness in 1% increments for now. iirc there's a different issue (which I can't remember) where we considered making a setting that allows the <kbd>shift</kbd>+<kbd>alt</kbd> behaviour to become the default. I think that's probably the best solution here.

**Comment by sn0wyfall** [comment]
Oh, that's neat, I didn't think of that. It makes it much better. However, the monitor sometimes glitches out and if I do it too long, it sometimes blanks out, lmao. Maybe that was the issue? 

But yes, I'll do this. It's not a huge deal anyway. I should just get a better monitor which implements DDC specs and functionality better...
