### ISSUE TITLE
External Displays turns off when using with macbook closed

### ISSUE THREAD

**Issue by lukassn** [MonitorControl/MonitorControl#280]
**Checklist**

- [X] I have searched for existing issues
- [X] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] I have updated MonitorControl to the latest version

**Describe the bug**
It does not work with macbook closed
Since I installed the app I cannot use only my monitor (macbook closed with charger connected)

**To Reproduce**
1. Install
2. Try the app with macbook opened, connected to charger and monitor
3. Close the macboook
4. Monitor turns down

**Expected behavior**
It should keep working and on! It should let the user use just the monitor on.

**Screenshots**

**Additional context**

**Environment Information (please complete the following information):**
 - macOS version: 10.15.6
 - MonitorControl version: 2.0
 - Monitor(s): LG HDR WFHD Ultrawide

**Comment by JoniVR** [comment]
Are you saying your external monitor turns off when you close your Macbook? If so, have you checked if this happens due to MonitorControl? (tried it when the app was not running).

**Comment by waydabber** [comment]
I'll close this issue due to lack of response. Please feel free to reopen it if the issue still persists or open a new issue about it! Thank you!
