### ISSUE TITLE
MonitorControl 2.0.0 Resume From Sleep Bug

### ISSUE THREAD

**Issue by danielxul** [MonitorControl/MonitorControl#285]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
My monitor (iiyama ProLite XB3288UHSU-B1) stays black or shows my desktop for a second and goes black (in an infinite loop) after resume from sleep. I have this issue since version 2.0.0 of MonitorControl. With version 1.7.1 everything works as it should.

**To Reproduce**
1. Start MonitorControl
2. Put Mac into sleep mode
3. Press a key on the keyboard to resume Mac from sleep
4. Monitor either stays black or goes into an infinite loop of reconnections 

**Expected behavior**
MonitorControl 2.0.0 should work like version 1.7.1 so that I can resume my Mac from sleep and my monitor connects as usual.

**Additional context**
Maybe my monitor is special because it needs some time to connect to my Mac (~5 seconds). My monitors usual connection behaviour is like this: My Macbook Pro detects my external monitor and transforms into a secondary screen, then it transforms back to primary screen and transforms back to secondary screen again with my main monitor being the primary screen and showing my desktop.

**Environment Information (please complete the following information):**
 - macOS version: 10.15.4, 10.15.5, 10.15.6, 11.0 Public Beta 2
 - MonitorControl version: 2.0.0
 - Monitor(s): iiyama ProLite XB3288UHSU-B1

**Comment by mkaflowski** [comment]
I have the same problem.

**Comment by diddyxking** [comment]
> I have the same problem.

Good to hear that I'm not the only person. Let's hope that this is getting fixed.

Also with MonitorControl 1.7.1 my monitor connects properly during resume from sleep but takes a lot more time than without MonitorControl running at all.

**Comment by JoniVR** [comment]
Can you try going into `Settings > Advanced` and set `Polling Mode` to `None`? Does that help resolve the issue? Might give a clue to the underlying problem.

**Comment by diddyxking** [comment]
> Can you try going into `Settings > Advanced` and set `Polling Mode` to `None`? Does that help resolve the issue? Might give a clue to the underlying problem.

I have already tried that. Same issue.

**Comment by diddyxking** [comment]
I only have this issue on resume from sleep and not on reboot.

**Comment by diddyxking** [comment]
I also have this issue with MonitorControl 1.7.1 now though. That is surprising because I never had this issue with version 1.7.1 and macOS <= 10.15.3. The issue only occurs when I changed the brightness with MonitorControl and put the Mac into sleep mode and wake it up again.

**Comment by ccharlton** [comment]
I am being bit by this, too.

**Comment by Lightblues** [comment]
I have the same problem and can not fix it even after uninstalling MonitorControl.

**Comment by JoniVR** [comment]
@mkaflowski @ccharlton @Lightblues Are you all using the same monitor (iiyama ProLite XB3288UHSU-B1)? Please try to provide information when you comment, just saying "I have the same issue" doesn't really add much value to the issue, in that case just give it a thumbs up 😉

**Comment by Marmelatze** [comment]
I have a Philips 346b1c and the same problem with 2.1.0. Setting polling to none fixed the wake from sleep problem for me.

**Comment by diddyxking** [comment]
Have you looked into the issue or do you have a clue why this bug exists?

**Comment by waydabber** [comment]
Hi, the new 3.0.0 versions handle sleep somewhat better. Please try and see if that helps. Thank you!

**Comment by waydabber** [comment]
Hi, we have relased the [3.0.0 version](https://github.com/MonitorControl/MonitorControl/releases/tag/v3.0.0-rc1). Could you please test if this issue is resolved and report back? Thank you!

**Comment by waydabber** [comment]
I'll close this one since it should be solved. If there is any issue with this, please feel free to comment and ask for a reopen! Thank you!

**Comment by danielxul** [comment]
The issue is solved. The new version works perfectly.

**Comment by waydabber** [comment]
Great, thanks for the confirmation! :)
