### ISSUE TITLE
Brightness function not working for MX279 monitor

### ISSUE THREAD

**Issue by GalacticLion7** [MonitorControl/MonitorControl#288]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
The volume functions works, but not the brightness function.

**Expected behavior**
For the brightness function to work.

**Additional context**
As per the Monitor Troubleshooting guide, I used `ddcctl` and ran `./ddcctl -d 1 -b 30`, but I had no luck.

**Environment Information (please complete the following information):**
 - macOS version: 10.15.6
 - MonitorControl version: 2.0.0
 - Monitor(s): MX279
 - Mac model: MacBook Air 2020
 - Monitor Cable(s)/Connection(s): (e.g. DisplayPort) HDMI

**Comment by JoniVR** [comment]
If it doesn't work with ddcctl either then I'm afraid it's probably simply bad implementation of the VESA spec..? Did you try the different cables etc? (probably won't do much if volume already works but worth a shot).

**Comment by GalacticLion7** [comment]
I fixed this issue by resetting my integrated monitor config on the OSD. It turns out my monitor does support DDC, but there was an issue with the config. Thank you for such a great software!
