### ISSUE TITLE
Doesn’t hide native volume bar on LG35Wn75c

### ISSUE THREAD

**Issue by marcdon2002** [MonitorControl/MonitorControl#289]
Hey there. I really like monitor control but I only have one issue. Beside the nice Mac OS volume slider there is also popping up the ugly native slider from my LG 35Wn75c. Is there any solution for that? Your help would be great. Keep up your nice work. Tanks ;)

**Comment by JoniVR** [comment]
`Settings > Advanced` then toggle `Hide OSD`. Please keep in mind that it's not working 100% currently as it was broken in an earlier update. (see #136)
