### ISSUE TITLE
Monitor brightness stopped working (Philips 276E8V) on Mac

### ISSUE THREAD

**Issue by addishp** [MonitorControl/MonitorControl#290]
Hi, 

I am using MonitorControl for my Philips 276E8V on my Mac Mini 2018 running Catalina 10.15.6. I believe it worked at first, but may have stopped working randomly. I really love this widget and would appreciate any support! 

I have used monitor control with this screen before with my work macbook pro and it had worked well during the summer. I downloaded SoundSource since I couldn't toggle monitor volume with sound like I can now. I don't think the volume worked for my monitor using MonitorControl so I'd love to pair these products. 

Thanks!

**Comment by rpajaziti** [comment]
I have Philips 346B1C, and have the same issue as well. Brightness stoped working, and cannot change it with keys, or with the slider(slider sits at minimum), and if i click the slider, monitor brightness goes to minimum.

**Comment by clarkFransje** [comment]
Same problem here, did any of you find a solution for this?

**Comment by waydabber** [comment]
Can you try the latest v3.0.0 version and confirm if it is still present? Also please be aware that the HDMI port of the Mac Mini 2018 is not working in terms of DDC control. Thank you!

**Comment by waydabber** [comment]
I'll close this issue for now but please feel free to comment if there is anything we can do. If the issue persists, we can reopen this issue! Thank you!
