### ISSUE TITLE
Monitor goes totally black when monitorcontrol is started

### ISSUE THREAD

**Issue by quin-q** [MonitorControl/MonitorControl#292]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
When I open monitorcontrol, the monitor screen simply goes totally black. After a few seconds the cursor appears and can be moved around but nothing else does. Adjusting the brightness through monitorcontrol on my laptop screen doesn't have any affect, and the blackness continues after mc is quit, until I disconnect the monitor and reconnect it.

**Screenshots**
The weird thing is that screenshots appear as if the display is functioning normally. Here's a comparison, I took a screen recording and then a video with my phone: [https://imgur.com/a/hCYSS0U](https://imgur.com/a/hCYSS0U)

**Environment Information:**
 - macOS version: catalina, 10.15.6
 - MonitorControl version: 2.1.0
 - Monitor(s): HP 24fw with audio, 24 inch
 - Mac model: macbook pro 2019, 13 inch
 - Monitor Cable(s)/Connection(s): HDMI and an adapter for USB-C "thunderbolt"

**Comment by grg909** [comment]
I have same issue, suddenly my screen goes black and can only see mouse cursor

**Environment Information:**

macOS version: catalina, 10.15.6
MonitorControl version: 2.1.0
Monitor(s): Dell S2721QS with audio, 27 inch
Mac model: mac mini 2018
Monitor Cable(s)/Connection(s): DisplayPort to USB-C "thunderbolt"

**Comment by grg909** [comment]
solved after I change another DisplayPort to USB-C "thunderbolt" cable. I guess the problem comes from hardware rather than software

**Comment by quin-q** [comment]
Damn, I tried that and it didn't do anything. Maybe neither adapter was good enough though, they were both 30 odd quid from amazon. I've seen direct USB-C to HDMI-out cables, so I might give that a go

**Comment by waydabber** [comment]
Since this seems to be a hardware/adapter problem, I'll close this issue. Some adapters scramble ddc communication which might cause issues with the display as it can't interpret the i2c communication properly and writes data to the wrong registers in this case making the display crash or reboot. This is a rare but real problem unfortunatelly.
