### ISSUE TITLE
MonitorControl not able to control volume when using AirPlay speaker in Music app

### ISSUE THREAD

**Issue by acousticbiker** [MonitorControl/MonitorControl#293]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
MonitorControl does not control volume in Music app when using AirPlay speaker

**To Reproduce**
1. Go to 'Music' app
2. Click on 'AirPlay' speaker
4. F10/11/12 do not mute or change volume of music

**Expected behavior**
F10/11/12 mutes and changes volume of music

**Environment Information (please complete the following information):**
 - macOS version: 10.15.6
 - MonitorControl version: 2.1.0 (Build 721)
 - Monitor(s): Philips 329P9H
-  AirPlay speaker: Pioneer A3

**Comment by val3riefr** [comment]
Sound control doesn't work at all..I have the Dell U2720Q on Catalina
brightness work, thought not darkening the screen totaly black...but audio nothing
help!

**Comment by JoniVR** [comment]
That's really out of our control and not intended functionality of the application unfortunately.. The app only controls your active macOS device output. I doubt there's even an api for us to hook into.
