### ISSUE TITLE
Works with LG5k (Thunderbolt 3 / TitanRidge) NOT on Pro Display XDR

### ISSUE THREAD

**Issue by samopus1io** [MonitorControl/MonitorControl#303]
Has anyone got any success using this with Pro Display XDR over either thunderbolt 3 / Single 1.4 or Dual DP 1.2?

**Comment by waydabber** [comment]
Hi, the Pro Display XDR probably requires DisplayServices control which is implemented but only for internal displays. We'll be working on that in this issue:

https://github.com/MonitorControl/MonitorControl/issues/364

**Comment by waydabber** [comment]
Also since not many users has this display, please let us help testing once we have something in this reagrd! Please follow issue #364! Thank you

**Comment by waydabber** [comment]
For those with Apple displays, there is a link to a test build with proper support here: https://github.com/MonitorControl/MonitorControl/issues/539
