### ISSUE TITLE
Philips 499p9 with eGPU not working

### ISSUE THREAD

**Issue by bargald** [MonitorControl/MonitorControl#304]
**Checklist**

- [X] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] I have updated MonitorControl to the latest version

**Describe the bug**
when connecting a display using an external gpu, the brightness control doesn't work. When changing brightness the screen flickers but always return to the same brightness level.

**To Reproduce**
1. connect MacBook to an egpu
2. connect a display to the egpu
3. try to change display brightness using monitorControl

**Expected behavior**
Screen should change brightness

**Additional context**
- changing brightness works when connecting the display directly to the computer, not using an egpu.
- tried using HDMI and DisplayPort cables

**Environment Information (please complete the following information):**
 - macOS version: Catalina 10.15.7
 - MonitorControl version: V. 2.1.0 build 721
 - Monitor(s): Philips 499p9

**Comment by jererobles** [comment]
Same issue. Not eGPU but using CalDigit dock. DisplayPort N°1 works OK, port N°2 doesn't no matter switching monitor or cable.

**Comment by JoniVR** [comment]
This feels like a setup issue, not an eGPU issue. How do I know this? I've been using an eGPU for years now with MonitorControl and it's working for me, I also know there are other people who have it working with their eGPU. 

I suggest you try some of the suggestions in the [Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting). 

If that doesn't help then I'm afraid there's probably not much we can do right now.

**Comment by JoniVR** [comment]
@bargald which eGPU and card? 
@jererobles What does your setup look like?

**Comment by bargald** [comment]
> @bargald which eGPU enclosure and card?
> @jererobles What does your setup look like?

I use the Sonnet Breakaway box 650W, with AMD Radeon RX 580 8 GB

**Comment by jererobles** [comment]
@JoniVR my setup is
```
 MBP 16" --TB3--> Caldigit USB-C Pro Dock --DP--> Dell U2713HM
                                          --DP--> LG 27UL650
```

You're right, this is not using eGPU.

**Comment by waydabber** [comment]
Hi, can you please try 3.0.0 if anything is changed? Probably not, but to be sure that this issue is still relevant. Also please try [ddctl if it works](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting) and also show us a screenshot of the Displays page of the 3.0.0 version to see what MC makes of your setup. Thank you!

**Comment by waydabber** [comment]
I'll close this issue for now but please feel free to comment if there is anything we can do. If the issue persists, we can reopen this issue! Thank you!
