### ISSUE TITLE
Provide an option to individually invert controls

### ISSUE THREAD

**Issue by brokenthorn** [MonitorControl/MonitorControl#305]
**Checklist**

- [x] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**
Some monitors have DDC values inverted. For example, raising brightness or raising contrast, actually lowers one or all of them.

For example on this monitor "LEN-27ICB-A" which is a Lenovo panel, contrast works normally, but brightness is inverted.
I can provide a real life photo if there's any interest. In order to set max brightness and max contrast on this display, settings look like this:

![image](https://user-images.githubusercontent.com/2119004/95744883-c84f3e00-0c9c-11eb-9759-f47775b53a5c.png)

**Describe the solution you'd like**
It would be nice if in the advanced preferences, we could have a check-mark to invert values for contrast and another to invert values for brightness. That way users can't enable only one of them depending on how they are affected.

**Describe alternatives you've considered**
I also tried Lunar.app, another similar application. The controls for brightness are also inverted with Lunar on the same monitor.

**Additional context**
Currently on Big Sur 11.0 Beta (20A5384c) on a MacBook Pro (Retina, 15-inch, Mid 2015).

**Comment by JoniVR** [comment]
I agree that this could be helpful for some people! PRs welcome!

**Comment by waydabber** [comment]
Since I am working on DDC ranges and things I'll add this one also.

<img width="803" alt="Screen Shot 2021-09-12 at 20 05 11" src="https://user-images.githubusercontent.com/37590873/132998079-0aac2acd-cb39-4e5f-b06f-8202919c7dcc.png">

**Comment by fleytman** [comment]
Inverting the checkbox does not work for the macbook display.

**Comment by waydabber** [comment]
Yes, the macbook display does not use DDC.

**Comment by fleytman** [comment]
Is it possible to implement the scroll inverting function for the macbook monitor as well? It is supposed to depend more on the scroll setting than on the DDC.

**Comment by waydabber** [comment]
You can swipe left or right on the trackpad to control the slider!

**Comment by fleytman** [comment]
There is no problem with the trackpad. I would like to invert the scroll for the mouse.

**Comment by waydabber** [comment]
I see. See this discussion about this issue: https://github.com/MonitorControl/MonitorControl/issues/885

**Comment by waydabber** [comment]
I'll resurrect that issue and we can continue the discussion there.
