### ISSUE TITLE
Retired iMac used as a monitor

### ISSUE THREAD

**Issue by Sarah-Calumet** [MonitorControl/MonitorControl#306]
I haven't been able to make this work on my retired 2009 iMac that is now serving as a monitor for a newer Macbook. It's default is max volume, and doesn't seem to be ajustable (except maybe by directly connecting a keyboard). 

This is an fyi only in case anyone else is trying to do this. It likely doesn’t affect many people. And is probably a built-in problem with the Apple "target" mode used for this situation.

**Comment by VovS-** [comment]
Why would you need a third-party app for that? Shouldn't it work natively?

**Comment by jackjansen** [comment]
Same problem here: I'm also using an old iMac in Target Display Mode (on a new Mac mini M1, connected via a HDMI->DP adapter and then a DP->MiniDP cable to the iMac.

My current workaround is that I have a second keyboard attached to the iMac, and I can use the volume keys on that.

The iMac is listed in the MonitorControl Preferences->Display with the DDC box off and disabled, so I guess that means Apple haven't implemented DDC (on the iMac in Target Display Mode).

A workaround could be to set the volume on the iMac, using something like

```
ssh imac.local osascript -e '"set Volume 10"'
```

but I can't think of a decent way to discover the name of the iMac (the `imac.local` in the example above).

**Comment by waydabber** [comment]
Well, to be honest it is a very special use case. What you'd need is a networked solution that can control the brightness of the display through the target machine. To be honest I don't think that such a functionality will be added anytime soon. What I'd recommend is to use any command line tool that can change native apple display birghtness like https://github.com/nriley/brightness, create a simple app that listens on a port via network and forwards requests to this nriley's brightness app and then create a some keyboard shortcuts using Hammerspoon on the computer connected to the iMac that forwards requests based on brightness keys. I know it sounds complicated but at most after a few days of tinkering this could be done and would be very satisfying to achieve something like this.

I'll close this issue for now, but let me know if you don't agree with this! Thank you!

**Comment by jackjansen** [comment]
@waydabber I understand (and agree), my workaround is now that I'm using a set of external speakers.
