### ISSUE TITLE
AOC Q24P2Q over HDMI is detected, but does not work

### ISSUE THREAD

**Issue by KronP** [MonitorControl/MonitorControl#307]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
Adjusting brightness or volume sliders in MonitorControl to an AOC Q24P2Q does not change brightness or volume on the monitor. 
Note: ddcctl does not work either, but ClickMonitorDDC on Windows (in Bootcamp) works.

**Expected behavior**
Brightness should change.

**Screenshots**

**Additional context**
The monitor is detected as a Q24P2W1 instead of a Q24P2Q. Mac OSX settings does also detect it as a Q23P2W1

**Environment Information (please complete the following information):**
 - macOS version: 10.14.6
 - MonitorControl version: 2.1.0 (build 721)
 - Monitor(s): AOC Q24P2Q
 - Mac model: Macbook Pro 13" Early 2015
 - Monitor Cable(s)/Connection(s): HDMI

**Comment by apryjom** [comment]
I've got exactly the same monitor. Connected to Mac Mini Late 2012. Detected exactly the same as Q24P2W1. Currently working in 1920x1080. Looking for cable mini Display Port (Thunderbolt) <-> Display Port. Hope that will be able to run in native monitor resolution.

**Comment by kanuni89** [comment]
Same issue on MacBook Pro (15-inch, 2018) running Mac OS 11.3.1. I have two of them and they are detected as Q27P2W.

**Comment by waydabber** [comment]
Hi, can you please confirm if this problem is still valid in light of the new v3.0.0 version?

I also want to let you know that if ddctl does not work as well then the issue probably lies with the macOS implementation of i2c display communication (which DDC uses) so we might not be able to do anything about it unfortunatelly. :(

**Comment by waydabber** [comment]
I'll close this issue for now but please feel free to comment if there is anything we can do. If the issue persists, we can reopen this issue! Thank you!
