### ISSUE TITLE
MonitorControl needs an ‘About’ tab

### ISSUE THREAD

**Issue by quinncomendant** [MonitorControl/MonitorControl#309]
**Checklist**
- [x] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't remember the name of this app or the URL to its Github page. Yes, I'm forgetful, but I think MonitorControl is partially to blame because nowhere in its menu or settings does it say **“Hi, I’m MonitorControl! You can find more info at https://github.com/MonitorControl/MonitorControl!”**

**Describe the solution you'd like**
I'd suggest adding two things:

1. A new line in the menu that says "MonitorControl version X.X.X".
2. An ‘About’ tab in the settings that includes the program name, version, names of author(s) and the URL to the Github page.

**Describe alternatives you've considered**
Well, I've resorted to opening my Applications folder to find the name of this app. 🙃

**Comment by JoniVR** [comment]
I agree this might be something we could add, although not very high priority, if anyone feels like implementing it, feel free to submit a PR 😄 

Also, I know it's not a perfect solution but the name should visible be in the general preferences section in the meantime:
![image](https://user-images.githubusercontent.com/7591717/96367422-08576a80-114e-11eb-8fa1-6246547585df.png)

**Comment by tomtastic** [comment]
Maybe it's just me, but :
```
c02a1a96a002a3e9f1072e3924ea66226233a227b5c971d617b3ef4f12acf206  MonitorControl.2.1.0.dmg
```
![image](https://user-images.githubusercontent.com/302127/97086633-6f789180-161c-11eb-90c5-b0904bea2218.png)

**Comment by JoniVR** [comment]
@tomtastic You seem to be running a different version than 2.1.0 as you also have the "Show Volume Slider" option which isn't present yet afaik, perhaps you were testing a PR earlier and are still running that version?

**Comment by tomtastic** [comment]
```  2   version "2.1.0"
  3   sha256 "c02a1a96a002a3e9f1072e3924ea66226233a227b5c971d617b3ef4f12acf206"
  4
  5   url "https://github.com/the0neyouseek/MonitorControl/releases/download/v#{version}/MonitorControl.#{vers    ion}.dmg"
```

**Comment by mmontag** [comment]
Big +1 to this, especially for the tiny effort to update the version string to "MonitorControl version X.X.X"

**Comment by patiljignesh** [comment]
Added "MonitorControl" to "version X.X.X" and added to PR.

**Comment by waydabber** [comment]
Hi, I added a nice about tab to version 3.0.0.

<img width="803" alt="Screen Shot 2021-08-19 at 9 37 35" src="https://user-images.githubusercontent.com/37590873/130027735-557db091-a7ed-4be9-82f2-4ce9fe246856.png">

**Comment by waydabber** [comment]
...therefore I'll close this issue. :) Thanks!

**Comment by patiljignesh** [comment]
Looks Beautiful 🤩, thanks
