### ISSUE TITLE
"Lower contrast after Brightness" is not working as expected - bug?

### ISSUE THREAD

**Issue by falcn** [MonitorControl/MonitorControl#31]
Problem: brightness=0 / contrast=75 is still too bright to work at night

Starting point:
Brightness=100
Contrast=75

What I expect:
1) By pressing F1 repeatedly, brightness gets lowered from 100 to zero, after that contrast gets gradually lowered from 75 to zero. 
2) Pressing F2 repeatedly increases contrast from 0 to 75, after that brightness starts to increase from 0 too 100 (do we need a setting for max contrast? it should not go above 75 in my case, but it may be different for other monitors)

What happens: 
1) By pressing F1, brightness gets lowered from 100 to zero. Next key press lowers contrast to 0 (bug?)
2) A single press of F2 increases contrast from 0 to 75 (bug?), brightness from 0 to 6. Slider for contrast stays at 0 at all times (bug?). Subsequent keypresses increase brightness as expected, effective contrast stays at 75 (good), but contrast slider shows 0 (bug?).

It's a very minor issue, since it's not that hard to use sliders to adjust contrast as needed.

**Comment by the0neyouseek** [comment]
Hi @falcn,

There are multiple issue here : 

1. The way the `Lower contrast after brightness` option currently work is, as you said, to set the contrast to zero when you press <kbd>F1</kbd> one more time after setting the brightness to zero. And return contrast to the previous value after pressing <kbd>F2</kbd>.  
This is the (currently) intended behavior, it allows for (some) monitors to set the screen darker than with brightness control only.
2. Now, controlling the contrast directly is something I intend to add to the app but I was thinking of something more like having to press a modifier key (<kbd>ctrl</kbd>, <kbd>alt</kbd> or <kbd>cmd</kbd>) in addition to <kbd>F1</kbd>F2</kbd>.

I don't know if this answer your question but please do comment here if you have other enhancement in mind, I'll be sure to look at it.

Have a nice day.

**Comment by renox92** [comment]
I agree with @falcn. Would be nice to be able to set maximum contrast, and after brightness hits 0 reduce contrast by increments of 6. When increasing it back, stop at whatever user set as max, then increase brightness. I myself use between 35 and 65 contast at night so this feature would be really helpful. 

Otherwise it's a great app, so thank you.

**Comment by joeyhoer** [comment]
I'm not sure, but it seems to me that the brightness and contrast of the native Mac display scale together. To me, it seems that there is a minimum and maximum threshold for contrast (perhaps also brightness), and as the function keys are pressed, the values both change at the same time.

I'm going to simplify for explanation purposes, but suppose that the minimum contrast is set to 25%, and the maximum contrast is set to 75% (range of 50% between values). When the display is set to 0 brightness, it would be set to 25% contrast. If the display brightness is increased by 10%, the contrast would be increased by 10% of the allowed range (5% in this example) until the maximum brightness is reached, where contrast would be 75%.
