### ISSUE TITLE
Add custom brightness/volume upper/lower bounds settings in Advanced Preferences

### ISSUE THREAD

**Issue by emiyl** [MonitorControl/MonitorControl#310]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
Going beyond around 60% brightness causes the brightness to wrap around to the lowest brightness, before going back up to the brightest setting to 100%.

**Expected behavior**
I expect the brightness to increase linearly from 0 to 100%

**Additional context**
I am using an incredibly niche setup, involving an iMac 5K panel hooked up to a [controller board](https://www.aliexpress.com/item/32965911057.html) that I got from AliExpress, which I believe is based on the hardware inside the DELL UP2715K. When looking at the in-built monitor settings, it seems that going beyond 60% with MonitorController causes the brightness to go over 100% on the monitor. When it reaches 130% brightness it wraps around to the lowest brightness.

I recognise that I am probably one of very few people who have this setup, but I thought I'd mention it, just in case. Perhaps a minimum/maximum brightness value could be added to the Advanced tab?

**Environment Information (please complete the following information):**
 - macOS version: 10.15.7
 - MonitorControl version: 2.1.0 (Build 721)
 - Monitor(s): iMac 5K Display Panel with [controller board](https://www.aliexpress.com/item/32965911057.html) possibly based on the DELL UP2715K?
 - Mac model: iMac15,1 (5K Late 2014)
 - Monitor Cable(s)/Connection(s): 2xDP1.2 cables

**Comment by JoniVR** [comment]
I think a min/max setting in Advanced Preferences is indeed a good solution here as we've probably changed the volume/brightness calculation logic a dozen times by now and it seems like there are always edge cases because of the wildly different configurations. 

Though it's pretty low priority in my opinion, if anyone feels like doing a PR I'd be happy to review it.

**Comment by matiaspl** [comment]
I vote for this feature too. My OEM (Uscreen) portable monitor also wraps around brightness and contrast values a couple of times using the default scale.

**Comment by ninggu2008** [comment]
Me, too. My monitor also wraps around brightness values a couple of times using the default scale.

**Comment by valfant** [comment]
I think the min/max clamp will also be very helpful for matching displays with different physical brightness.
e.g.
Display A with brightness measured from 60 to 400 nit
Display B with brightness measured from 20 to 300 nit
Set Display A min/max to 0%/71% would yield a 60 to 301.4 nit range
Set Display B min/max to 14%/100% would yield a 59.2 to 300 nit range

**Comment by Montvydas** [comment]
Voting this up. My EVICIV portable monitor reaches max brightness when MonitorControl is around 45%. After that it goes black, then until it reaches 100% in settings the monitor turns random brightness levels. The same goes for contrast, while the volume works perfectly fine.

**Comment by Neogene** [comment]
Vote up too. My external portable monitor 👍 

slider value 0% - monitor reports 5%
slider value 38% - monitor reports 100% (greater values repeat 5...38%)

**Comment by silvetti** [comment]
When will this feature be implemented? Been months now :(

**Comment by waydabber** [comment]
Hi @silvetti - we plan to add this in the future.

Also, you are always free to work on this and create a pull request if you'd like to contribute to the development or you can help financing the project by specifically pointing out a goal to see an issue prioritized. :) As of right now the project is rather understaffed and everybody's working on this in his spare time for free. :) Thank you for your understanding!

**Comment by waydabber** [comment]
It's gonna look something like this.

<img width="803" alt="Screen Shot 2021-09-12 at 18 46 14" src="https://user-images.githubusercontent.com/37590873/132995878-458582f1-299e-4800-9a1e-b4b3b090db05.png">

**Comment by emiyl** [comment]
Looks awesome :) thank you!
