### ISSUE TITLE
Shortcuts do not work with iterm2 and external keyboard

### ISSUE THREAD

**Issue by ibash** [MonitorControl/MonitorControl#314]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
When using iterm2 and monitor control the shortcuts to change brightness are not detected by monitor control.

**To Reproduce**
1. Install iterm2 and monitor control
2. Connct an external keyboard and monitor
3. Open iterm2 and give it focus
4. Press the f14 / f15 shortcuts to change brightness

**Expected behavior**
Brightness changes

**Actual**
Brightness does not change

**Additional context**
This might be an iterm2 only issue, but I wanted to see if anyone else has hit this or not.

**Environment Information (please complete the following information):**
 - macOS version: 10.15.7
 - MonitorControl version: 2.1.0
 - Monitor(s): viewsonic vp2768-4k

**Comment by JoniVR** [comment]
Possibly a duplicate of #282? Could be related to the secure text entry setting.

**Comment by ibash** [comment]
Yep! Thank you! Not sure why I didn't find that in my search...
