### ISSUE TITLE
sundown and sunrise feature?

### ISSUE THREAD

**Issue by pennies** [MonitorControl/MonitorControl#315]
**Checklist**

- [x] I have searched for existing issues

first of all, thank you for this amazing program.

I was wondering if there was a way to implement a feature to automatically dim with sundown and brighten with sunrise?

again this is amazing and you already made my life much better, have a great week!

**Comment by halfbusy** [comment]
Maybe it'd be possible to start with the ability to save and choose custom presets? I'm having to change the levels for all of my monitors a few times a day, eg. when it gets very overcast, when the sun comes in and gets very bright, when I'm working after dark, etc. 

In my case, I would create the following presets for myself:
- cloudy
- sunny
- nightime

**Comment by waydabber** [comment]
Hi, this request is valid, but a bit out of scope for MonitorControl. Why don't you try [Lunar](https://lunar.fyi) which has this capability? 

@alin23
