### ISSUE TITLE
Media Keys won't control volume

### ISSUE THREAD

**Issue by ryedog** [MonitorControl/MonitorControl#318]
I can use the volume slider on the MonitorControl app to adjust my monitors volume but the media keys on the keyboard have no effect on the monitor, just the laptop speakers. Since I can adjust the volume using the slide on the app it leads me to think this is a MonitorControl issue and not a monitor specific issue. Brightness keys work great.

- I'm running MonitorControl 2.1
- MonitorControl is set to listen for "Both Brightness & Volume" and have tried "Volume only"
- Running OSX Catalina 10.15.7

**Comment by JoniVR** [comment]
This is a feature, we only control the selected output device through hotkeys as it doesn't make sense to change a volume output which isn't active.

**Comment by JoniVR** [comment]
I'm going to close this for now as this is a feature, if you disagree with me, feel free to reopen or let me know to reopen it (please suggest a solution if so).
