### ISSUE TITLE
Select which sliders to display in preferences

### ISSUE THREAD

**Issue by ithakaa** [MonitorControl/MonitorControl#324]
Suggestion.

Can you allow us to choose which option to be visible
I would like to only see audio and not brightness
If possible that would be great
Thanks for your amazing work !!

**Comment by JoniVR** [comment]
Hi, this is currently being worked on for brightness (#312), however I think we should probably take the route of a dropdown so we can support hiding any slider as I mentioned in the PR.

**Comment by Elethom** [comment]
> Hi, this is currently being worked on for volume (#312), however I think we should probably take the route of a dropdown so we can support hiding any slider as I mentioned in the PR.

The correct way to do it is this.

Show sliders for:
- [x] brightness
- [ ] contrast
- [ ] volume

**Comment by ithakaa** [comment]
> > Hi, this is currently being worked on for volume (#312), however I think we should probably take the route of a dropdown so we can support hiding any slider as I mentioned in the PR.
> 
> The correct way to do it is this.
> 
> Show sliders for:
> - [x] brightness
> - [ ] contrast
> - [ ] volume

Do we have this version released yet?

**Comment by waydabber** [comment]
Well, it would make sense to have the ability to disable the brightness slider as well. We'll look into it!

**Comment by waydabber** [comment]
It seems like version 3.1.0 will be all about sliders (and apple displays):

<img width="803" alt="Screen Shot 2021-09-08 at 17 28 51" src="https://user-images.githubusercontent.com/37590873/132539067-b670c75d-d385-4e84-837d-964bd5dd8a51.png">

:)
