### ISSUE TITLE
Brightness change not working after disconnecting from external monitor

### ISSUE THREAD

**Issue by MartinJ2EX** [MonitorControl/MonitorControl#327]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

When disconnecting my external LG monitor, monitorcontrol shows “no compatible monitor found”, which is correct - BUT then it also blocks any brightness changes to the MacBook’s internal display!
This problem does not exist with version 1.7.1!

**To Reproduce**
1. Disconnect your external monitor, if you have a MacBook (Pro, Air)
2. Use your function keys to change your brightness 
3. Nothing will happen!

**Expected behavior**
With version 1.7.1, which I had prior to 2.x, when disconnecting my external monitor, monitorcontrol somehow deactivated itself and the MacBook’s internal display brightness could be changed as expected.

**Environment Information (please complete the following information):**
 - macOS version: 10.15.7
 - MonitorControl version: 2.1.0
 - Monitor(s): LG 27UD88, MacBook Pro 2016 15” internal display

**Comment by JoniVR** [comment]
I can confirm this as I've run into the issue myself a few times, thanks for opening the issue.

**Comment by waydabber** [comment]
This issue should be fixed in 3.0.0. Please test if it works. If not, please report here:

https://github.com/MonitorControl/MonitorControl/issues/456

I'll close this issue for now.

Thank you!
