### ISSUE TITLE
macOS Big Sur control centre

### ISSUE THREAD

**Issue by jajaperson** [MonitorControl/MonitorControl#329]
**Checklist**

- [x] I have searched for existing issues

macOS Big Sur introduced the control centre, featuring brightness and volume sliders, which currently do not work with my Samsung monitor (shown disabled in the screenshot below). It would be nifty if Monitor Control could make the control centre work.

![Screen Shot 2020-11-22 at 3 17 33 pm](https://user-images.githubusercontent.com/25611007/99897622-fc734100-2cd5-11eb-8bd2-d80e273f78b4.png)

**Comment by JoniVR** [comment]
Duplicate of #258
