### ISSUE TITLE
Discussion: Redesign Display and Advanced preference panes for better future-proofing

### ISSUE THREAD

**Issue by JoniVR** [MonitorControl/MonitorControl#330]
**Checklist**

- [x] I have searched for existing issues

**Discussion**

As mentioned in #213, I think we should start considering a different UI for Display/Advanced preferences as they're getting pretty cluttered and we're rapidly running out of space adding new features.
 
My personal suggestion would be an Xcode-like dual pane approach:

![Xcode example](https://user-images.githubusercontent.com/7591717/99906133-9edef480-2cd5-11eb-8c7f-eaa6e8928996.png)

The main idea would be having the monitors with name on the left pane and the properties for each monitor on the right. 

I'd like to get people's feedback/ideas for this as there are probably better ideas out there and I'm not a UI/UX expert.

**Comment by lvalenta** [comment]
That’d be great - much better than now.
