### ISSUE TITLE
Brightness on another VCP code

### ISSUE THREAD

**Issue by Giacomo-Sanna** [MonitorControl/MonitorControl#331]
**Checklist**

- [x] I have searched for existing issues

**Question**
When I try to change the brightness of the monitor, the black level is changed instead.
After some researches, I discovered that my monitor isn’t following the last VESA Monitor Control Command Set standard.
Basically to change the monitor brightness you set in`DDC.swift`
`case luminance = 0x10`
but for my monitor I need to set it to `0x13`.
I was wondering if I need to build the project with my changes, or I can edit something in the .dmg file.

**Comment by JoniVR** [comment]
Yes, you'd probably want to create a fork of this project, change the value to `.backlightControlLegacy` (0x13) and then build it yourself. I think we could also provide this as an advanced preferences option in the future, but that's probably a long way off unless you'd want to implement it in a PR.

**Comment by Giacomo-Sanna** [comment]
Thanks, I'll do it myself. 
But in the future, if you will develop it, it would be great.

**Comment by JoniVR** [comment]
If you want it in, you or someone else will have to submit a Pull Request. 

You can't expect maintainers to do all the work, that's not a sustainable approach for any of us as this is in no way something we do full-time. 

I'm open to merging it as an Advanced preferences feature if anyone is willing to submit it. Closing for now, feel free to reopen or ping me to reopen 🙂
