### ISSUE TITLE
Enumerate multiple displays with same name

### ISSUE THREAD

**Issue by Teneff** [MonitorControl/MonitorControl#333]
**Checklist**

- [x] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**
When connected multiple monitors of the same model it's hard to determine which one are you controlling
![image](https://user-images.githubusercontent.com/1176644/100317044-53259700-2fc4-11eb-82bf-411f0754e40e.png)

**Describe the solution you'd like**
Suffix the display name with a number, not sure if mac OS provides the number, but it's displayed in Display preferences
![image](https://user-images.githubusercontent.com/1176644/100317296-ca5b2b00-2fc4-11eb-94b0-b27413ca52b3.png)

**Describe alternatives you've considered**
Just any number would also do the job

**Comment by JoniVR** [comment]
You should be able to change the name in advanced preferences by double clicking the "display name" field iirc.

**Comment by waydabber** [comment]
While @JoniVR is right, this function is not that difficult to implement so we can still do this anyway.
