### ISSUE TITLE
Control headphone output volume

### ISSUE THREAD

**Issue by skirem** [MonitorControl/MonitorControl#338]
**Checklist**

- [x] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**
It's nice that I can control my Dell U3419W speakers and brightness with this tool, but unfortunately it can't control the volume ouf the headphone jacks output

**Describe the solution you'd like**
Another slider for headphone volume would be great

**Describe alternatives you've considered**
Using an offical Apple / Dell driver would be nice, but both of them dont offer driver for high tech products..

**Additional context**
Awesome tool so far :)

**Comment by JoniVR** [comment]
You should be able to do it through shortcuts, we currently detect the active audio output (and if it can set its own volume or not) and just stop listening for volume keys if the active audio output can set its own volume. Perhaps we could indeed add a slider for this as well.

**Comment by dac73** [comment]
I have passive headphones (no volume control on them) connected to U4320Q, Volume control works only on the monitor but not on headphones.

Cheers.

**Comment by inomdzhon** [comment]
Same wanting 🙏 

I turned off built-in speaker of `Dell S2316H` and I has connect separated speaker to output port.
When I change volume, `MonitorControl` turn on built-in speaker back.

Is it possible change this behavior?

Thank you anyway!

**Comment by waydabber** [comment]
It might be possible to solve this by using the following two DDC controls:

speakerSelect = 0x63
audioJackConnectionStatus = 0x65

Unfortunatelly rarely ever any display support this. We'll keep this open as a feature request though but probably somebody with such a display should try to implenet this feature and even then there won't be guarantee that it will work with other displays.

**Comment by waydabber** [comment]
I'll close this issue for now but if there is a popular demand for this or it turns out to be technically feasible, we still might do this. Also we'd need a developer with an access to such a display. 

Thank you for your understanding!
