### ISSUE TITLE
MonitorControl not working with Philips 329P9H after changing to M1 MacBook Air

### ISSUE THREAD

**Issue by acousticbiker** [MonitorControl/MonitorControl#339]
**Checklist**

- [x ] I have searched for existing issues
- [x ] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x ] I have updated MonitorControl to the latest version

**Describe the bug**
MonitorControl was working well with my Philips 329P9H on my 2020 Intel MacBook Air. I just switched today to an M1 MacBook Air and it no longer works. 

- When I click on the menubar icon, it says 'No supported display found'
- Pressing F1 shows the macOS monitor brightness overlay but no bar segments at the bottom and no change with repeated pressing
- Pressing F2 does nothing. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Environment Information (please complete the following information):**
 - macOS version: 11.0.1
 - MonitorControl version: 2.1
 - Monitor(s): Philips 329P9H

**Comment by CyberTx95** [comment]
Same issue with MacMini M1 & LG 27UL850-W monitor. Hopefully this gets fixed soon.

**Comment by BokunLin** [comment]
MonitorControll can't running in MacBookPro M1 & DELL U2720Q monitor too.

**Comment by joeyboey** [comment]
It would also be nice to have a universal binary. Unfortunately you can't compile the app yourself for Apple Silicon because of the OSD framework.

**Comment by markhealey** [comment]
Same on LG 32UD89-W 31.5" 4K with M1 MBP

**Comment by acousticbiker** [comment]
Apologies, I hadn't realized this [existing thread](https://github.com/MonitorControl/MonitorControl/issues/323) on the issue

**Comment by a137594942** [comment]
macbook air m1 & lg 27ul850 +1
