### ISSUE TITLE
Brightness buttons occasionally not responding

### ISSUE THREAD

**Issue by AlfHou** [MonitorControl/MonitorControl#340]
**Checklist**
- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
Occasionally the brightness buttons on my MacBook 15" (mid 2012) just ceases to respond. No overlay, no change in brightness. The only fix I've found is quitting MonitorControl. Note, this happens when there is no display connected.

**To Reproduce**
1. Either launch MonitorControl or have it auto start on boot
2. Use computer as normal for an unspecified time
3. See error

**Expected behavior**
Being able to use by brightness buttons as normal while MonitorControl is running in the background

**Additional context**
This happens very spordically, and only occurs maybe twice a month or something. Is there anywhere I can read the logs to better troubleshoot/provide better debugging info?

Super appreciative of your work! I think MonitorControl is a fantastic tool 😄 

**Environment Information (please complete the following information):**
 - macOS version: MacOS Mojave, 10.14.6
 - MonitorControl version: 2.1.0 (Build 721)
 - Monitor(s): Non connected

**Comment by ibash** [comment]
This is not #282 is it?

**Comment by AlfHou** [comment]
Hmm, it doesn't seem so. I tried with both `Secure Keyboard Entry` toggled on and off. I was still able to change brightness. To be clear, this bug only happens occasionally. I can use the brightness keys fine for days with the MonitorControl running in the background, then suddenly they stop working and I have to quit the program. 

I didn't see it described anywhere, but are there any logs I could look into?

**Comment by JoniVR** [comment]
Do you happen to disconnect the Monitor in between when this happens? I have noticed that when you disconnect the monitor, you'll need to restart MonitorControl before it'll actually work again with the internal display, but I'm not sure if this is related.

**Comment by achembarpu** [comment]
I have the same issue. Exact same cause, disconnecting all external monitors and leaving only the internal display. The brightness keys stop working, and need to quit MonitorControl to fix.

**Comment by jellybeaner101** [comment]
I now have the same issue. MontorControl has worked perfectly for years but now the brightness keys stop working intermittently. 

I recently updated to the latest security patch for 10.14.6 (2021-002). Not sure if its related but I didn't have the problem before the update.

**Comment by waydabber** [comment]
Hi all, can you please try the latest 3.0.0 release and see if this is still a problem? Thank you!

**Comment by waydabber** [comment]
I'll close this issue for now but please feel free to comment if there is anything we can do. If the issue persists, we can reopen this issue! Thank you!
