### ISSUE TITLE
Viewsonic VG2455

### ISSUE THREAD

**Issue by MacPepper** [MonitorControl/MonitorControl#341]
Brightness control don't working, just sound

**Comment by MacPepper** [comment]
Ok now with Usb-c to Display Port adapter...

**Comment by waydabber** [comment]
Hi, hope this issue has been resolved. If not, please try the 3.0.0 version as it might change things. If not, please provide us with a little more information by filling out a new Issue using the Issue Template. Thank you for your help! I'll close this issue for now.
