### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by drahamim** [MonitorControl/MonitorControl#344]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
Brew has deprecated the install command style you have in the readme

```Warning: Calling brew cask install is deprecated! Use brew install [--cask] instead.
```

**To Reproduce**
1. 'Run the brew command to install noted in the readme'
2. See error

**Expected behavior**
No warning about deprecated commands

**Screenshots**
![image](https://user-images.githubusercontent.com/3834219/101962231-78b7c080-3bc0-11eb-8ad3-738977e01763.png)

**Additional context**

**Environment Information (please complete the following information):**
 - macOS version: 10.15.7 (19H2)
 - MonitorControl version: 2.1.0(Build 721)
 - Homebrew Versions:
   - Homebrew 2.6.1
   - Homebrew/homebrew-core (git revision 331a6d; last commit 2020-12-11)
   - Homebrew/homebrew-cask (git revision f700f7; last commit 2020-12-11)
 - Monitor(s): Acer

**Comment by JoniVR** [comment]
See #350
