### ISSUE TITLE
Separate "Change Brightness/Volume for all screens" into 2 Different Options + option for volume audio device matching

### ISSUE THREAD

**Issue by trazaq** [MonitorControl/MonitorControl#345]
**Checklist**
- [x] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**
First, thanks for this awesome software!
It'll be very helpful to split the "Change Brightness/Volume for all screens" into 2 separate selections:

> "Change Brightness for all screens"

> "Change Volume for all screens"

I have 3 displays, each with their own speakers. If I want to change the volume using my keyboard volume keys, I have to make active the display I want to change the volume for. 

For example, if one display is playing a video and another is being used to read a PDF, I have to go the display playing the video then press the volume keys to control the sound. I would like to control the sound output regardless of which screen I'm currently active on. 

**Describe the solution you'd like**
I would like to control the volume for all screens at the same time. I would like to control the Brightness levels individually. 

**Additional context**
![image](https://user-images.githubusercontent.com/40772543/102029892-f244df80-3d75-11eb-9076-65efe5b3e904.png)

**Comment by JoniVR** [comment]
I agree that these could be split up, what we also could do is only change the volume for the active audio output display. Currently we ignore the volume keys if the active output can set its own volume (for example: Airpods, headphones, ...), we could perhaps also only send volume commands to the display that is set as audio output, though some people might not want that.

**Comment by waydabber** [comment]
Something like this:

<img width="803" alt="Screen Shot 2021-09-09 at 20 52 05" src="https://user-images.githubusercontent.com/37590873/132745709-52e2525b-355f-42f9-957c-ded46776b071.png">

**Comment by trazaq** [comment]
*THUMBS UP!!!*
