### ISSUE TITLE
Menu Bar Icon

### ISSUE THREAD

**Issue by RVSarch** [MonitorControl/MonitorControl#346]
**Checklist**

- [x ] I have searched for existing issues

I would like to be able to remove the menu bar icon but command clicking does not allow me to drag it off the bar. I only use Monitor Control to allow F1 and F2 keys to control the brightness of an LG monitor connected to my Mac Mini. I rarely change contrast and try to keep as few Icons in the menu bar as possible.

**Comment by JoniVR** [comment]
Duplicate of #189
