### ISSUE TITLE
Macs connected to dell ultrasharp U3818DW

### ISSUE THREAD

**Issue by climbzona** [MonitorControl/MonitorControl#347]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
A clear and concise description of the problem.
Two Macs connected to the same monitor:

1. **Doesn't Work**: Mac Mini M1 (2020) - OS 11.0.1, connected to ultrasharp by displayport. Volume and Brightness control greyed out.
2. **Works**: MacBook Pro (2019) - OS 10.15.7, connected to ultrasharp by USB-C. Volume and Brightness control and via sliders in Menu bar item. Volume control via MacBook and bluetooth Keychron keyboard.

**Expected behavior**
Mac Mini M1 to have same ability to control volume as MacBook which is confirmed and those details included.

**Screenshots**

**Additional context**

**Environment Information (please complete the following information):**
 - macOS version: 11.0.1
 - MonitorControl version: 2.1
 - Monitor(s): dell ultrasharp U3818DW
 - Mac model: Mac Mini M1
 - Monitor Cable(s)/Connection(s): DisplayPort

**Comment by JoniVR** [comment]
Dupe #323
