### ISSUE TITLE
Microphone (Audio Input) from Monitor

### ISSUE THREAD

**Issue by FeringaMind** [MonitorControl/MonitorControl#348]
**Checklist**

- [x] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**
This isn't really a "problem", but my Monitor (lima G-Master Black Hawk GE2288HS-B1) has an audio input jack and an audio output jack. Controlling the audio output (and Brightness and Contrast) of the Monitor works just fine by using the App, but is there a way for you to get audio input (eg.: a mic) from the Monitor?

**Describe the solution you'd like**
The best solution would be if the App would create and audio device that can be selected in "System Settings - Sound - Input".

**Comment by waydabber** [comment]
Sorry to say but if the display can't fed buck this information via USB to the computer, then I am afraid, it is not possible. :(

I'll close this issue now but please feel free to add your input if any new information comes to light on this! Thank you!
