### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by curiouskim** [MonitorControl/MonitorControl#352]
**Checklist**

- [x] I have searched for existing issues

**Discussion**
Is there a Korean translation in this application? If not, I'd like to help you translate.

**Comment by JoniVR** [comment]
I don't think there is, feel free to submit a Pull Request 👍 😀

**Comment by miniesam** [comment]
@JoniVR I'd also like to translate `README.md`, where do you want to save this file?

**Comment by waydabber** [comment]
Hi @curiouskim - can you help us making the Korean translation for version 3.0.0? Thank you!

**Comment by waydabber** [comment]
I'll close this issue for now but please let us know if you want to proceed with the translation work for 3.0.0. In that case we'll reopen this one and help. Thank you!
