### ISSUE TITLE
Mac M1 chip support 

### ISSUE THREAD

**Issue by jacie6056** [MonitorControl/MonitorControl#353]
**Checklist**

- [ ] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jacie6056** [comment]
Can we add new support for the new M1 chip?

Really enjoy this app!

**Comment by JoniVR** [comment]
Dupe. #323
