### ISSUE TITLE
Samsung U28570

### ISSUE THREAD

**Issue by cprada87** [MonitorControl/MonitorControl#354]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
I can't control any monitor status

**Screenshots**
<img width="256" alt="Captura de pantalla 2020-12-24 a las 16 10 08" src="https://user-images.githubusercontent.com/28503903/103096034-e2918a80-4602-11eb-8b9a-d948c777fa59.png">

<img width="762" alt="Captura de pantalla 2020-12-24 a las 16 22 55" src="https://user-images.githubusercontent.com/28503903/103096498-613af780-4604-11eb-81f3-85a09e139369.png">

**Environment Information (please complete the following information):**
 - macOS version: **Big Sur 11.1**
 - MonitorControl version: **2.1.0 (Build 721)**
 - Monitor(s): **Samsung U28570**
 - Mac model: **A2289**
 - Monitor Cable(s)/Connection(s): (e.g. DisplayPort) **USB-C to HDMI@60hz**
[https://www.amazon.es/gp/product/B08CSBPPR9/ref=ppx_yo_dt_b_asin_title_o07_s00?ie=UTF8&psc=1](url)

**Comment by cprada87** [comment]
any progress?

**Comment by BerkeAras** [comment]
Same issue :(

**Comment by BerkeAras** [comment]
_not working in 3.0.0-beta 2_

**Comment by waydabber** [comment]
Hi, can you please try the latest 3.0.0 RC1? Is it working properly with ddctl?

Also you could try setting DDC polling mode to 'None' under Displays/Advanced (you need to enable Advanced options in the General tab) and try if it works - as your display might provide erroneus max accepted values to MonitorControl and that's why you can't use the sliders.

<img width="803" alt="Screen Shot 2021-08-21 at 16 23 15" src="https://user-images.githubusercontent.com/37590873/130324814-ff10235f-50c8-42e3-a460-2389678a5ba6.png">

Thank you and please let me know if this helps!

**Comment by waydabber** [comment]
I'll close this issue for now but please feel free to comment if there is anything we can do. If the issue persists, we can reopen this issue! Thank you!

**Comment by cprada87** [comment]
the same @waydabber, still does not work, although now it recognizes the monitor model and allows me to move audio and brightness but without result.

**Comment by waydabber** [comment]
Hi @cprada87 - does it work properly via ddcctl or Lunar (@alin23)? The screenshot suggests so but it is still not clear if the display is actually controlled via an alternate app. Thank you!

**Comment by cprada87** [comment]
Hi waydabber, neither of them :( BR

**Comment by alin23** [comment]
@cprada87 For brightness you could try disabling the features listed in the [Lunar FAQ](https://lunar.fyi/faq#brightness-not-changing) to see if DDC starts working.

<img width="1060" alt="Shot_Safari app_Lunar - Frequently Asked Questions_PqHww9q1" src="https://user-images.githubusercontent.com/3819725/133071173-1f2e7a44-c7a8-4cff-959c-f8950503653e.png">


For volume, try disabling the **Auto Mute** setting if it is enabled, and maybe post a screenshot with the sound settings of your monitor in case there are other features that could block volume changing through DDC.

**Comment by waydabber** [comment]
Oh boy I wish MonitorControl had such a nice FAQ! :)

I'll move this issue to a discussion for future reference (especially if the above helps).
