### ISSUE TITLE
Brightness adjusting on wrong monitor

### ISSUE THREAD

**Issue by mmmgl** [MonitorControl/MonitorControl#357]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
The brightness key is adjusting the brightness of my main monitor when I'm on a fullscreen app on my external monitor. The brightness HUD is showing on my external monitor, though. I have to go to the desktop of the external monitor to make it works fine.

Strangely, everything works fine when the Preference screen is simply open. 

**Expected behavior**
Brightness to adjust on the external monitor, which I'm on, not my main monitor.

**Screenshots**
/

**Additional context**
/

**Environment Information (please complete the following information):**
 - macOS version: 10.15.7
 - MonitorControl version: 2.1.0
 - Monitor(s): LG ULTRAWIDE 29WK500

Thanks !

**Comment by waydabber** [comment]
This should be resolved in the new 3.0.0 release so I will close this issue. Please let me know if it does not work for you! 

Thank you!

Also see this: https://github.com/MonitorControl/MonitorControl/issues/424

**Comment by mmmgl** [comment]
> This should be resolved in the new 3.0.0 release so I will close this issue. Please let me know if it does not work for you!
> 
> Thank you!
> 
> Also see this: #424

It did ! Thansk for your hard work.

**Comment by waydabber** [comment]
Thanks for the reply! :) Happy to help!
