### ISSUE TITLE
Brightness sometimes changes on window switching

### ISSUE THREAD

**Issue by iamtcl** [MonitorControl/MonitorControl#358]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
My monitor brightness sometimes changes from a low brightness that I have set to a higher/maximum brightness when I switch to another window(alt-tab).

**Expected behavior**
Brightness shouldn't be changed without my control.

**Screenshots**
/

**Additional context**
/

**Environment Information (please complete the following information):**
 - macOS version: 11.1
 - MonitorControl version: 2.1.0
 - Monitor(s): PHL 224E5

**Comment by waydabber** [comment]
Well, to be honest I have no idea why is that happening. Do you experience the same without MonitorControl being used? Also can you please try out the new 3.0.0 version and report back if the issue persists? Thank you!

**Comment by waydabber** [comment]
I'll close this issue for now but please feel free to comment if there is anything we can do. If the issue persists, we can reopen this issue! Thank you!
