### ISSUE TITLE
Thunderbolt Display not working with MacBook Pro (However, a solution provided)

### ISSUE THREAD

**Issue by story1234** [MonitorControl/MonitorControl#361]
I am a LCD-less MacBook Pro that's hooked up to two monitors
1. Acer ET322QU with TB to HDMI cable.  This works fine.
2. Apple Thunderbolt Display.  When I click anything on the bar it will go to dimmest. I had to go into Sys Pref or the below app to turn it up again. I tried version 1.3 and 2.1.0

I always use this app to control the brightness and yours to control the Acer.  Maybe you can combine it together?
https://github.com/lucasbento/menubar-brightness

**Comment by waydabber** [comment]
Hi,

it is now possible in 3.0.0 to disable hardware control for a display and force software gammatable control (which is a new feature). We plan to add proper Thunderbolt display in the future as well - it will be followed in this thread:

https://github.com/MonitorControl/MonitorControl/issues/364

I'll close this issue, but let me know if I can be of any further help! Thank you!

**Comment by waydabber** [comment]
For those with Apple displays, there is a link to a test build with proper support here: https://github.com/MonitorControl/MonitorControl/issues/539
