### ISSUE TITLE
Benq ex2780q not supported

### ISSUE THREAD

**Issue by nunordm** [MonitorControl/MonitorControl#365]
[ x] I have searched for existing issues
[ x] I have updated MonitorControl to the latest version

My monitor has DDC but it appears as not supported and non of the actions (brightness or volume) work.

![Captura de ecrã 2021-01-05, às 19 59 29](https://user-images.githubusercontent.com/77023843/103693006-8a5a7100-4f90-11eb-9a77-dc5f12dd2a7f.png)

![Captura de ecrã 2021-01-05, às 19 55 47](https://user-images.githubusercontent.com/77023843/103692890-5da65980-4f90-11eb-91e8-1c25ff959373.png)

 - macOS version: 11.1
 - MonitorControl version: 2.1.0
 - Monitor(s): Benq ex2780q
 - Mac model: Mac mini M1
 - Monitor Cable(s)/Connection(s): HDMI 2.0

**Comment by matzr75** [comment]
Same here with a Benq PD3200U.
MonitorControl does recognise the model but no control possible.
![image](https://user-images.githubusercontent.com/20831919/105320592-a2ec9d00-5bc6-11eb-8d14-9d8c4668c5d6.png)

![image](https://user-images.githubusercontent.com/20831919/105320767-d92a1c80-5bc6-11eb-8bd2-0332c33b40a9.png)

macOs 10.15.7
MonitorControl 2.1.0
Connected via DP via a Belkin Thunderbolt Docking Station

**Comment by JoniVR** [comment]
#323
