### ISSUE TITLE
Automatically adjust brightness

### ISSUE THREAD

**Issue by dacrypt** [MonitorControl/MonitorControl#367]
Since the mac uses the camera to sense the ambience light and adjust the screen brightness. It would be great to be able to adjust the brightness of the external monitors automatically based on the brightness level of the main screen. Similar to https://github.com/OCJvanDijk/Brightness-Sync

**Comment by waydabber** [comment]
Hi, [Lunar](https://lunar.fyi) has this feature I think. MonitorControl might also add this in the future, but I feel it is a bit out of scope.

@alin23

**Comment by waydabber** [comment]
There is a similar issue here all the way back from 2018. :) Let's merge this one with that!

https://github.com/MonitorControl/MonitorControl/issues/27

**Comment by waydabber** [comment]
Brightness change synchronization from Built-In and Apple displays to other displays is now added. This makes Touch Bar, Ambient light sensor, Control Center and System Preferences induced changes affect all displays. Synchronization is not direct, but only changes are replicated - the user can intervene and adjust at any time.

https://github.com/MonitorControl/MonitorControl/discussions/596
https://github.com/MonitorControl/MonitorControl/issues/27
