### ISSUE TITLE
Display automatically dims if you work on the mac book's screen

### ISSUE THREAD

**Issue by ddofborg** [MonitorControl/MonitorControl#368]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**

The tool seems to be working just fine. When you are working on the monitor the brightness is kept. When you use the keys while the focus is on the monitor the brightness changes, all is fine. 

**Reproduce**

Then you work in a window on the laptop's screen for a while (3-7 minutes) without changing the focus to an app on the external monitor, the monitor starts to dimm and then it turns black within 30 seconds or so.

**Environment Information (please complete the following information):**
 - MacBook Pro
 - macOS version: macOS Catalina 10.15.7
 - MonitorControl version: 2.1.0 (build 721)
 - Monitor(s): Samsung C34H89x external monitor (connected via USB-C)

**Comment by waydabber** [comment]
Hey, this is a function of the OS itself. You might want to disable "Automatically adjust brightness" under Displays in System Preferences.

<img width="780" alt="Screen Shot 2021-08-21 at 15 57 53" src="https://user-images.githubusercontent.com/37590873/130324055-9793e64a-fc21-40b9-bb36-cfa0bc5afeac.png">

If I misunderstood the issue or you have anything to add, feel free to comment! I'll close this issue until then. Thank you!
