### ISSUE TITLE
Keyboard shortcut for contrast

### ISSUE THREAD

**Issue by Soneji** [MonitorControl/MonitorControl#369]
**Checklist**

- [x] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**
I find many of my displays' brightness settings do not have a noticable effect on the display brightness. I often have to click the menu bar icon and change the contrast slider instead to change the effective display brightness. 

**Describe the solution you'd like**
Keyboard shortcuts for contrast

**Describe alternatives you've considered**
Maybe we can link brightness and contrast, and add an option to pin the contrast to the same as the brightness.

**Comment by renaudguerin** [comment]
I second this : brightness control doesn't work on my monitor but the contrast slider works fine.
It would be awesome to be able to reassign brightness keys to contrast control instead.

**Comment by waydabber** [comment]
Hey, the new 3.0.0 release has gammatable brightness control which is superior to changing the display's brightness. If you unclick 'Use hardware control' in the Displays tab and has 'Enable software dimming...' enabled in the General tab, you'll be good to go!

<img width="803" alt="Screen Shot 2021-08-21 at 16 01 35" src="https://user-images.githubusercontent.com/37590873/130324147-b6a59626-59d7-451f-84a0-644d5ccc16f4.png">

I close this issue for now but let me know if there is anything you want to add or if maybe I did not understand the request properly. Thank you!

**Comment by Soneji** [comment]
This is really handy, thank you! :)

**Comment by waydabber** [comment]
You are welcome.

ps. btw I wanted to say gammatable is superior to changing display contrast (but not to display backlight brightness - I edited my repsonse. :)).

**Comment by Soneji** [comment]
I agree, it is definitely a lot better than changing the contrast, shame my monitor's brightness control has very little effect on the display brightness. Thanks again for helping with this and making a great project!
