### ISSUE TITLE
BenQ BL2711U recognized but nothing happen when changing the brightness  

### ISSUE THREAD

**Issue by Leshauts** [MonitorControl/MonitorControl#371]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through the wiki
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
I installed MonitorControl on my Hackintosh. My BenQ BL2711U is linked to my hacktintosh with a DisplayPort cable. Nothing happen when I change the brightness range, but it works for sound!

**To Reproduce**
Installed, rebooted.

**Expected behavior**
Brightness should change when I use the range.

**Environment Information (please complete the following information):**
macOS version: 15.5 (Hackintosh)
MonitorControl version: 2.1.0, Build 721
Monitor(s): BenQ BL2711U (DDC/CI: Enabled)

<img width="789" alt="Capture d’écran 2021-01-13 à 17 52 45" src="https://user-images.githubusercontent.com/16543063/104483482-72a26e80-55c8-11eb-9192-d309b9810154.png">
<img width="218" alt="Capture d’écran 2021-01-13 à 17 55 18" src="https://user-images.githubusercontent.com/16543063/104483523-8057f400-55c8-11eb-846a-edf4601350e3.png">

**Comment by shirehobbits** [comment]
I am facing a similar issue for BenQ EW3280U.

The brightness & contrast sliders are DISABLED.
They have worked in the past, but after few days they got disabled!

<img width="202" alt="Screen Shot 2021-01-14 at 10 01 10 AM" src="https://user-images.githubusercontent.com/49618139/104630268-6f9e9100-564f-11eb-888c-9824c6f8efdb.png">

**Comment by timbicker** [comment]
I have the same problem with my Philips 345B1C

**Comment by 0xdevalias** [comment]
I'm also seeing the brightness doing nothing (but contrast works) on my Kogan KAMN341FQULA (connected with a HDMI -> USB-C cable/integrated adapter)

**Comment by Leshauts** [comment]
I've just seen that it actually works with sound!

**Comment by shirehobbits** [comment]
Yes, the volume has no issue. Brightness, contrast do not work.
Any solution?

**Comment by shirehobbits** [comment]
@the0neyouseek 
@reitermarkus
@JoniVR

**Comment by Leshauts** [comment]
Ok I fixed it in a weird way I guess. I downloaded DDC Panel from [tonymacx86](https://www.tonymacx86.com/threads/controlling-your-monitor-with-osx-ddc-panel.90077/page-6#post-795208) and clicked on the "X" button next to the serial number. My screen restarted and then the shortcut worked!

**Comment by shirehobbits** [comment]
I fixed it by:
1. I disabled the HDR from mac displays option
2. Factory reset monitor
3. reinstalled monitorcontrol
