### ISSUE TITLE
Does not work with M1 new mac Processor

### ISSUE THREAD

**Issue by REOS471** [MonitorControl/MonitorControl#374]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
Worked perfectly on my 2018 Mac Mini using an Intel chip with Big Sur so it is not a Big Sur issue, on the New Mac Mini with apple's M1 chip it cannot find the exact same
monitor that I used on the 2018 Mac Mini Intel w/Big Sur. Display shown in Big Sur System Preferences is correct but Monitor Control cannot find
anything so it is just blank under display

**To Reproduce**

**Expected behavior**
It says No Supported Display Found even though it found it right away on my 2018 Mac Mini with Intel Processor.
Expected to work the same as it did on my Big Sur 2018 Mac Mini Intel.

**Screenshots**
![No Supported display found](https://user-images.githubusercontent.com/39271169/104762451-9d540a80-5721-11eb-87c7-9a6301729ed0.jpg)

**Additional context**

**Environment Information (please complete the following information):**
 - macOS version: Big Sur
 - MonitorControl version:Latest 2.1.0
 - Monitor(s): LG  27UL850-W

**Comment by lorda** [comment]
I have exactly the same problem. MonitorControl worked great with my 2020 Intel Macbook Pro.

Now that I have the 2020 M1 Macbook Pro my monitor is not detected.

However, in the settings I can see this:
![CleanShot 2021-01-16 at 13 55 45@2x](https://user-images.githubusercontent.com/2292327/104820428-8fc28180-5802-11eb-9d22-34754b659aef.png)

**Comment by JoniVR** [comment]
dupe #323
