### ISSUE TITLE
Lepow Z1 Gamut Brightness adjustment incorrect values

### ISSUE THREAD

**Issue by reviewher** [MonitorControl/MonitorControl#375]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
With the Lepow Z1-Gamut connected via USB-C, the brightness adjustment is incorrect.  The minimum MonitorControl value corresponds to ~50% brightness.  Ramping up the bar to about 50% gets you to the brightest setting.  Bumping the value a little bit higher drops down to the lowest setting, and then it scales up as you increase the bar.

It's as if MonitorControl is assuming brightness is an unsigned byte (0 to 255) while the display is interpreting it as a signed byte (-128 to 127).  The 0 value would be seen as the middle brightness, and it would ramp up to the max when MC sends 127 and the display interprets it as 127.  When MC sends 128, the display is interpreting as -128 and drops to lowest brightness.  And as MC scales up to the highest value 255, the display is seeing a scaling up to -1.

**Expected behavior**
Minimum MonitorControl setting should be 0 and maximum should be max brightness

**Additional context**
Volume appears to work correctly.  The app works correctly on other USB-C monitors using the same computer

**Environment Information (please complete the following information):**
 - macOS version: 10.15.6
 - MonitorControl version: 2.1.0 (Build 721)
 - Monitor(s): Lepow Z1-Gamut
 - Mac model: MacBook Pro (15-inch, 2018) Model Identifier MacBookPro15,1
 - Monitor Cable(s)/Connection(s): USB-C

**Comment by waydabber** [comment]
This might be the case. I'd suggest you to try ddctl and see how it works. If this indeed is the case, then we might have to add a special setting for this display (however this is a rather niche product and is definitely not standards compliant). We'll be working on this in the following issue:

https://github.com/MonitorControl/MonitorControl/issues/310

I think you should help testing this particular display and voice your findings when work is being done on this! Thank you!

I'll close this issue so we can focus all our energy on that one. Thank you!
