### ISSUE TITLE
M1 Support

### ISSUE THREAD

**Issue by MarianAlexandruAlecu** [MonitorControl/MonitorControl#377]
Monitor Control starts on new M1 MacBooks, but the external monitor is not recognized anymore:
<img width="689" alt="Screenshot 2021-01-20 at 12 52 11" src="https://user-images.githubusercontent.com/5826632/105164875-551c5a00-5b1e-11eb-8a8a-34f628ebaa9c.png">

I used to see there "LG 4K monitor"

**Comment by pandagreen464** [comment]
Same problem here with iMac M1. The volume keys work on the keyboard but not the brightness.

**Comment by the0neyouseek** [comment]
Duplicate #323
