### ISSUE TITLE
Not support AOC U3277FWQ

### ISSUE THREAD

**Issue by korzhan** [MonitorControl/MonitorControl#381]
Not support AOC U3277FWQ.
Writes that no supported monitors were found. Although this model supports DDC.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/47418633/106446820-898b0100-64a2-11eb-834b-a0331a848adc.png">

 - macOS version: 11.1
 - MonitorControl version: 2.1.0 (721)
 - Monitor(s): AOC U3277FWQ
 - Mac model: MacBook Air (M1, 2020)
 - Monitor Cable(s)/Connection(s): Type-c to DisplayPort

**Comment by korzhan** [comment]
The error is saved to macOS 11.2.

**Comment by JoniVR** [comment]
#323
