### ISSUE TITLE
Monitor stopped working via dock station after I installed MonitorControl

### ISSUE THREAD

**Issue by nlited** [MonitorControl/MonitorControl#382]
**Checklist**

- [x] I have searched for existing issues

**Discussion**
Hi all! 

My setup is MBP 15" 2018, Benq EW3280U 4к monitor and a usb-c dock station by some Chinese brand called Hagibis (and magic keyboard). The monitor connects to dock station via DP to DP cable. This setup had worked with no issues for several months until yesterday when I installed MonitorControl. MC didn't work with this setup, nothing changed when I pressed brightness and volume keys on magic keyboard, though MC did recognise that there is external monitor connected. Then I restarted MBP and the monitor simply did not work no more because it suddenly stopped "seeing" the MBP connection. 
However it is working with no problem when connected to MBP directly via usb c or DP cables (it has both), and this way MC also works like a charm - I can control brightness and volume with no issue. 
So obviously smth happened to the dock station. 

So my question is: 
Is there any chance the MC somehow could have caused the breakdown and death of the dock station in terms of DP functionality? Mini short circuit or smth. I know it may sound funny but the fact that the problem appeared right after I tried using MC is really warning...

**Comment by waydabber** [comment]
It would be great to know the exact type of the dock. If the dock has shady electronics and can't interpret DDC commands, this might be, but it has a very low probability as DDC is using the same i2c protocol as EDID but a different chip address and EDID is essential for the display to work in any meaningful way.

If there is anything else I can help with, please let me know or if you have any more information you want to share, we might look into it in more depth. I'll close this issue until that time. Thank you and sorry for responding late.
