### ISSUE TITLE
Benq EW2780U not supported

### ISSUE THREAD

**Issue by jondarrer** [MonitorControl/MonitorControl#383]
**Checklist**
- [x ] I have searched for existing issues
- [x ] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [ x] I have updated MonitorControl to the latest version

**Describe the issue**
The [Benq EW2780U](https://www.benq.eu/en-uk/monitor/entertainment/ew2780u.html) has **DDC switched on** but the monitor appears as not supported and none of the actions (brightness or volume) work.

**Expected behavior**
The Benq EW2780U to be recognised as **Benq EW2780U** and all the actions (brightness or volume) to work.

**Screenshots**

<img width="203" alt="Screenshot 2021-02-01 at 18 44 22" src="https://user-images.githubusercontent.com/5214011/106503886-2018eb80-64be-11eb-95a0-5f7bb35f86b6.png">

<img width="681" alt="Screenshot 2021-02-01 at 18 45 14" src="https://user-images.githubusercontent.com/5214011/106503903-25763600-64be-11eb-99b3-dfabcebe8442.png">

**Other information**

Having run `ddcctl` as suggested in the [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting), I found the following failures on each command (here setting the brightness to 1):

```bash
$ ddcctl -d 1 -b 1
D: CGDisplay D9F5565C-F61A-F34E-3D19-FC1626C9B248 dispID(#1) (1920x1080 0°) HiDPI
I: found 1 external display
E: Failed to parse WindowServer's preferences! (/Library/Preferences/com.apple.windowserver.plist)
E: Failed to acquire framebuffer device for display
```

**Environment Information (please complete the following information):**
 - macOS version: 11.1
 - MonitorControl version: 2.1.0 (Build 721)
 - Monitor(s): Benq EW2780U
 - Mac model: Mac mini (M1, 2020)
 - Monitor Cable(s)/Connection(s): HDMI 2.0

**Comment by jondarrer** [comment]
Okay, just realised this is most likely down to this issue around M1 support in general #323.

**Comment by FraggyFred** [comment]
Hi all
For your info
I have a MBP TouchBar (Intel) and the same monitor that I ca'nt control
The monitor is connected via : usb-c hub --> miniDP to DP cable
Connecting via HDMI does not allow to access full resolution of the monitor, thus an option for me
I'm waiting for a usb-c to DP cable for another try

Rgds

**Comment by JoniVR** [comment]
#323
