### ISSUE TITLE
No Support for Dell U3421we

### ISSUE THREAD

**Issue by Bill-Honey** [MonitorControl/MonitorControl#384]
**Checklist**

- [ x] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**
Doesn't recognise Dell U3421we - declares as
unknown, unknown, id = 2, vendor = 0x10AC, Model = 0xA185

**Describe the solution you'd like**
Can you support ? 

**Describe alternatives you've considered**
tried dccctl - but also doesn't work 

**Additional context**
I'm on mac mini Big Sur 11.1

**Comment by habitoti** [comment]
I have a MPB (2020, 16") with Big Sur, and my U3421WE is properly recognised and controls work just fine. Shouldn't be much different for a Mac Mini.

![image](https://user-images.githubusercontent.com/220421/111998318-2e79a000-8b1c-11eb-9a95-ca37c740532c.png)

**Comment by burdandrei** [comment]
Just tested with U3421WE connected to MacBook Pro M1, and receiving `No supported display found` as well
![image](https://user-images.githubusercontent.com/2526486/117314401-64d26b00-ae8f-11eb-8eba-a699fead7769.png)

**Comment by burdandrei** [comment]
@Bill-Honey is your Mac mini M1? if so i think https://github.com/MonitorControl/MonitorControl/issues/323 is aright place for us

**Comment by Bill-Honey** [comment]
Yes - mine is a Mac Mini M1

**Comment by waydabber** [comment]
Hey all, the new 3.0.0 release will have full Apple Silicon support (except for the HDMI port of the M1 mini which disables DDC by hardware for some reason it seems). Please check out that and report if you have any problem!

I'll close this issue meanwhile. Thank you!
