### ISSUE TITLE
AOC2790 not supported with MacBook Air M1 over USB-C Hub

### ISSUE THREAD

**Issue by kasti0** [MonitorControl/MonitorControl#385]
the monitor was supported on a laptop that was set up as a hackintosh and had direct HDMI connection. Are USB-C hubs not supported? the app detects the monitor but just display "no supported monitor connected"

**Comment by joeyboey** [comment]
Should be:
Duplicate of #323

**Comment by kasti0** [comment]
it should be a duplicate of that error.
However there's something else going on. When MonitorCOntrol is running I'm not even able to change the display brightness of the internal screen. I only can change between highest setting and one below.
