### ISSUE TITLE
DELL U3219Q - not supported

### ISSUE THREAD

**Issue by MaikD77** [MonitorControl/MonitorControl#386]
Hello, 

Unfortunately, the DELL U3219Q is  not yet supported . 

Vendor : 0x610 Model : 0xA03C
Vendor : 0x10AC Model : 0xA125

Sorry, but I don't know which monitor is which. One monitor is that of the MacBook Pro 13 inch M1.

**Comment by iamanders** [comment]
I have this monitor and both contrast and brightness works for me.

**Comment by JoniVR** [comment]
#323
