### ISSUE TITLE
LG 34WL850-W not supported

### ISSUE THREAD

**Issue by zar0ku1** [MonitorControl/MonitorControl#387]
**Checklist**

- [x] I have searched for existing issues
- [X] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] I have updated MonitorControl to the latest version

**Describe the issue**
The [LG 34WL850-W](https://www.lg.com/us/monitors/lg-34WL850-W-ultrawide-monitor) has DDC switched on but the monitor appears as not supported and none of the actions (brightness or volume) work.

**Expected behavior**
The LG 34WL850-W to be recognised as LG 34WL850-W and all the actions (brightness or volume) to work.

**Screenshots**
![Снимок экрана 2021-02-07 в 10 14 30](https://user-images.githubusercontent.com/2253124/107131771-9b9af280-692d-11eb-9ec8-bf95db9db1ac.png)
![Снимок экрана 2021-02-07 в 10 14 37](https://user-images.githubusercontent.com/2253124/107131773-9fc71000-692d-11eb-8c83-5cbc4dfc60f4.png)

**Additional context**

> ddcctl -d 1 -v 30
> D: CGDisplay 4E453C1D-C716-7451-0857-D6964E3302DB dispID(#2) (3440x1440 0°) 109.00 DPI
> I: found 1 external display
> E: Failed to find display in WindowServer's preferences! (/Library/Preferences/com.apple.windowserver.plist)
> I: polling EDID for #1 (ID 2 => (null))
> E: Failed to poll display!

**Environment Information (please complete the following information):**
 - macOS version: 11.2
 - MonitorControl version: 2.1.0 (Build 721)
 - Monitor(s): LG 34WL850-W
 - Mac model: Mac mini (M1, 2020)
 - Monitor Cable(s)/Connection(s): Thunderbolt

**Comment by beshkenadze** [comment]
Same here. I own LG 38GN950 and connect via HDMI to Mac Mini M1.

**Comment by JoniVR** [comment]
#323
