### ISSUE TITLE
what are the commands to use this?

### ISSUE THREAD

**Issue by pvijeh** [MonitorControl/MonitorControl#388]
what are the commands to use this?

**Comment by womeimingzi11** [comment]
I believe this repo is what you need [kfix/ddcctl](https://github.com/kfix/ddcctl).

**Comment by the0neyouseek** [comment]
@pvijeh MonitorControl isn't available as command line if that's what you meant but you can use https://github.com/kfix/ddcctl for the same functionalities.

If you meant the keyboard shortcut, simply use your brightness ou volume keys
