### ISSUE TITLE
Show % Value of brightness, contrast and volume for sliders

### ISSUE THREAD

**Issue by weiweihuanghuang** [MonitorControl/MonitorControl#390]
**Checklist**

- [ x ] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**
I know my regular values for when it's night vs day. And I'd rather be able to just go to it rather than guess it.

**Describe the solution you'd like**
A number next to the slider.

**Describe alternatives you've considered**
Number input could be nice too.

**Additional context**

**Comment by waydabber** [comment]
I agree, this would be useful as an expert option. I assigned this request to myself and will (hopefully) implement in one of the future releases.

**Comment by waydabber** [comment]
I added this one as an option (see settings page screenshot at https://github.com/MonitorControl/MonitorControl/discussions/596)

<img width="291" alt="Screen Shot 2021-09-15 at 23 12 12" src="https://user-images.githubusercontent.com/37590873/133510361-4db20fd9-d1e1-4d27-9109-4c527d50dcbf.png">
