### ISSUE TITLE
Control by CLI

### ISSUE THREAD

**Issue by arozhankov** [MonitorControl/MonitorControl#392]
Hello!

Thanks for the great and useful app. 

Sorry if my question has already been.
Can I control brightness through your application using the command line (CLI)? May be Apple Script?

For example,
- set brightness / volume
- request current brightness / volume

**Comment by donl** [comment]
You might want to look at:

https://github.com/kfix/ddcctl

**Comment by arozhankov** [comment]
> You might want to look at:
> 
> https://github.com/kfix/ddcctl

Yes thank you. I have to use both applications and I find it inconvenient.

**Comment by waydabber** [comment]
Unfortunatelly CLI control is not possible at the moment. Maybe in the future we'll do such a thing. I recommend you checking out [Lunar](https://lunar.fyi) by @alin23 as it have a CLI solution - it might better suit your needs.

I'll close this issue for now, but feel free to reply in case you have any recommendation on this or would like to contribute making CLI possible! Thank you!
