### ISSUE TITLE
Benq EX2780Q not working

### ISSUE THREAD

**Issue by Astraorion** [MonitorControl/MonitorControl#393]
The App is not working with Benq EX2780Q. 
It is not recognizing the model.

**Comment by sergeyfilimonov** [comment]
If you have an M1 Mac, see this https://github.com/MonitorControl/MonitorControl/issues/323

**Comment by waydabber** [comment]
I'll close this issue as there is no further feedback on this. @Astraorion - you can try the new 3.0.0 version with Apple Silicon support to see if it helps! Thank you!

**Comment by TomatoFryEggs** [comment]
TypeC Cable is worked now!
