### ISSUE TITLE
LG HDR WQHD 38WK95C not working

### ISSUE THREAD

**Issue by zhiyicai** [MonitorControl/MonitorControl#394]
**Describe the issue**
The MacBook Intel chip can run normally
The Mac Mini M1 won't work after the replacement
<img width="650" alt="Sceenshot5388217" src="https://user-images.githubusercontent.com/13891311/108609128-266afb00-73cc-11eb-9fcb-adfa248a2845.png">

**Screenshots**
#If applicable, add screenshots to help explain your problem.

**Environment Information (please complete the following information):**
 - macOS version: macOS Big Sur v11.1
 - MonitorControl version: 2.1.0 (Build 721)
 - Monitor(s): LG HDR WQHD 38WK95C
 - Mac model: MAC MINI M1

**Comment by JoniVR** [comment]
#379
