### ISSUE TITLE
volume balance control

### ISSUE THREAD

**Issue by AbiolaR** [MonitorControl/MonitorControl#395]
**Checklist**

- [x] I have searched for existing issues

Love this app youve built but I noticed a very useful feature missing. It would be great if there was an option to set the left-right balance of a monitors volume.

A slider like the volume slider but for left-right volume balance, similar as the one macOS has for normal audio output devices

**Comment by waydabber** [comment]
Hey, I added this to the following generic issue about advanced control options. I'll close this one as duplicate. Thank you!

https://github.com/MonitorControl/MonitorControl/issues/524
