### ISSUE TITLE
 Philips 279C9 not working

### ISSUE THREAD

**Issue by csz-Seven** [MonitorControl/MonitorControl#397]
**Checklist**

- [ ] I have searched for existing issues
- [ ] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [ ] I have updated MonitorControl to the latest version

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Environment Information (please complete the following information):**
 - macOS version:
 - MonitorControl version:
 - Monitor(s):

**Comment by waydabber** [comment]
Hi, does ddctl or m1ddc work with the display?

https://github.com/MonitorControl/MonitorControl/wiki/Advanced-Preferences

If so, MC should have no problem controlling the display. Please let me know if you have this issue still and can provide this info. I'll close the issue until that time. Thank you and sorry for responding so late!

**Comment by MaximumQuiet** [comment]
Hi @waydabber, I have the same monitor and facing this issue as well.

My results with m1ddc:

1. Can control brightness: `./m1ddc set b 0` `./m1ddc set b 100` works correct. But `./m1ddc get b` always returns -118;
2. As for volume, I can control only 'mute on/off', volume increasing/decreasing is not working. `./m1ddc get v` always returns -118, `./m1ddc max b` returns -85

**Comment by waydabber** [comment]
Hi, can you control the brightness with MonitorControl? If you have issues with initial ddc read on startup, you can press Shift during startup for safe mode, enable `Advanced..`. in General preferences and then set `Polling` to `None` under Displays.

**Comment by MaximumQuiet** [comment]
> Hi, can you control the brightness with MonitorControl? If you have issues with initial ddc read on startup, you can press Shift during startup for safe mode, enable `Advanced..`. in General preferences and then set `Polling` to `None` under Displays.

Yes. I tried every 'Polling' setting, but volume control still not working :( But brightness works correct

**Comment by waydabber** [comment]
Well, this is probably an issue with the display I am afraid then and probably can't be fixed on the software side. It's strange since Philips displays mostly support DDC-CI properly.

**Comment by csz-Seven** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
