### ISSUE TITLE
Not working with Dell u2518d and iMac 2017 4k

### ISSUE THREAD

**Issue by seanbperiod** [MonitorControl/MonitorControl#398]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
I have a Dell u2518d connected via USB C to the iMac 2017 4K - but MC says no display supported found. I checked to see if the monitor supported, which it does. I think the monitor shows up in MC Display preferences as unknown, ID 69933012 Vendor 0x610 and Model 0xAE1B. Enabled is checked, DDC is disabled. 

**Environment Information (please complete the following information):**
 - macOS version: Big Sur 11.2.2
 - MonitorControl version: 2.1 Build 721
 - Monitor(s): u2518d
 - Mac model: iMac 2017 4k
 - Monitor Cable(s)/Connection(s): (e.g. DisplayPort) USB C to Displayport

**Comment by waydabber** [comment]
Hey, can you please test the issue with the latest 3.0.0 version and report back if you still have this issue? Also, were you able to control the display using ddctl as described here?

https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting

Thank you!

**Comment by gcg** [comment]
with the 3 RC, it started to work for my mac mini (m1) and dell u2518d

**Comment by waydabber** [comment]
Great! I will close this issue then. Thanks for the reply! :)

**Comment by seanbperiod** [comment]
Yep confirmed working here too. Thanks! 👍

**Comment by waydabber** [comment]
Thanks for the feedback!
