### ISSUE TITLE
Brightness can't be controlled through control center

### ISSUE THREAD

**Issue by NedDong** [MonitorControl/MonitorControl#400]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
The brightness can't be adjust in the control center
**To Reproduce**
1. Go to 'Control Center' (right upper corner)
2. Click on 'Monitor'
3. See error 'Brightness is not selectable or controllable' 

**Expected behavior**
Brightness can be controlled through the control center

**Screenshots**
![image](https://user-images.githubusercontent.com/73497501/109604148-fcfb4f00-7af0-11eb-9db0-c249513c802e.png)

**Additional context**
None

**Environment Information (please complete the following information):**
 - macOS version: 11.2.2
 - MonitorControl version: 2.1.0
 - Monitor(s): U2718Q,AW2518H

**Comment by waydabber** [comment]
There is a similar issue https://github.com/MonitorControl/MonitorControl/issues/258, so I'll close this one as a duplicate.

Sorry to say, but as of now there is no known way to tap to that slider as it is a protected part of the OS so this issue will probably not be solved anytime soon or ever. :(
