### ISSUE TITLE
MacBook Pro screen keeps flashing black with Dell P2719H with Type C to HDMI cable

### ISSUE THREAD

**Issue by himgodfreyho** [MonitorControl/MonitorControl#401]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
My MacBook screen keeps turning black and on and black and on again and again when I plugged an aftermarket TypeC to HDMI cable to a Dell P2719H. The Dell screen won't receive any signal and will go to 'standby' mode. 

If I close MonitorControl, the monitor will work with the same TypeC to HDMI cable. Once I open MonitorControl (with the external monintor working), the problem happens again.

With the same monitor, if I use a normal HDMI<->HDMI cable and plug into a Typc C dock to my MacBook Pro, the monitor works and the MonitorControl app works flawlessly (e.g., brightness control works). 

 - macOS version: 10.15.7
 - MonitorControl version: 2.1.0
 - Monitor(s): Dell P2719H
 - Mac model: MacBook Pro 15 inch 2019 2.3GHz 8-Core i9 with Radeon Pro 560X
 - Monitor Cable(s)/Connection(s): (e.g. DisplayPort) Aftermarket (Non-Apple) TypeC to HDMI cable

**Comment by BuzzwordChief** [comment]
I have a similar issue with my Caldigit SOHO-Dock. Turning black and on and black and on again. Brightness control does not work. With my no name usb c adapter everything works flawlessly.

**Comment by waydabber** [comment]
Some docks and active cables mess up DDC communication unfortunatelly. There is no much to do with this, you need to try to use a different cable. :(

I'll close this issue for now, but feel free to comment if there is anything else we can help with! Thanks!
