### ISSUE TITLE
Dell U4021qw

### ISSUE THREAD

**Issue by rseckler** [MonitorControl/MonitorControl#403]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
So the tool is not working with the new Dell U4021qw. I can control neither the brightness nor the volume. (See screenshots bellow.) I also tried with the ddcctl tool, screenshot attached as well. Not sure about the "Failed to poll the display". Couldn't find much on Google about this error.

**Expected behavior**
Well, the tool should work with this monitor. I checked, whether it supports control over DDC, and according to the manufacturer, it does.

**Screenshots**
![Bildschirmfoto 2021-03-12 um 10 11 27](https://user-images.githubusercontent.com/5329317/110918454-78dc6f00-831b-11eb-9075-675bf7c16aa4.png)

**Environment Information (please complete the following information):**
 - macOS version: 11.2.3
 - MonitorControl version: 2.1.0
 - Monitor(s): Dell U4021qw
 - Mac model: MacBook Air M1
 - Monitor Cable(s)/Connection(s): USB-C / Thunderbolt, Original from Dell

**Comment by fifafu** [comment]
FYI: It’s working fine on my Intel MBP using the same display, so the problem seems to be m1 specific. I can verify this weekend.

**Comment by tgreco26** [comment]
I have this same issue but with Dell U4320Q. Was there any update on this? Thanks!

**Comment by the0neyouseek** [comment]
Related to #323
