### ISSUE TITLE
Not working on Samsung 55NU8000 model TV

### ISSUE THREAD

**Issue by ne0c0de** [MonitorControl/MonitorControl#407]
**Checklist**
- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
Not working on Samsung 55NU8000 model TV
I'm using MBP 2019 touchbar model with Big Sur 11.2.1

Brightness control not working on TV where I connected it with HDMI cable. 

**Environment Information (please complete the following information):**
 - macOS version: 11.2.1
 - MonitorControl version: Version 2.1.0 (Build 721)
 - Monitor(s): Samsung UE55NU8000 TV

**Comment by waydabber** [comment]
Hi @ne0c0de - unfortunatelly TVs do not support the DDC protocol which is needed for hardware brightness control. I recommend you trying one of the new 3.0.0 beta versions which support gamma table control as an alternative. Please let me know if you have any issues with that! Thank you!

https://github.com/MonitorControl/MonitorControl/releases
