### ISSUE TITLE
Not work Samsung C34J79

### ISSUE THREAD

**Issue by outsiderz** [MonitorControl/MonitorControl#410]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
A clear and concise description of the problem.

**Expected behavior**

**Screenshots**

**Additional context**

**Environment Information (please complete the following information):**
 - macOS version: BigSur 11.2.3
 - MonitorControl version: 2.1.0 release 721
 - Monitor(s): Samsung C34J79
 - Mac model: MBP 2020 m1
 - Monitor Cable(s)/Connection(s): (e.g. DisplayPort) thunderbolt 3

**Comment by JoniVR** [comment]
See #323
