### ISSUE TITLE
More granularity or making step offset configurable

### ISSUE THREAD

**Issue by alexanderadam** [MonitorControl/MonitorControl#411]
**Checklist**

- [x] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**

I can only change volume in steps of 6%. But this sometimes is too loud/silent thus better granularity would be great.

**Describe the solution you'd like**

Either more granularity or making the offset configurable.

**Describe alternatives you've considered**

Having sound that is too loud/silent? 😉

**Comment by ajonsacc** [comment]
Was just about to request this! My monitor volume is not linear, 0-15 goes loud and 16-100 is about the same. An input field for the step size would be great.

**Comment by gawin** [comment]
This is build into macOS by default.

Press and hold `Shift` + `Option` then use `Volume Up` and `Volume Down` keys to make a more granular adjustment.

**Comment by alexanderadam** [comment]
> Press and hold `Shift` + `Option` then use `Volume Up` and `Volume Down` keys to make a more granular adjustment.

Indeed. This (very non-obvious) shortcut is working perfectly!
Thank you!
