### ISSUE TITLE
App Launched, but no icon in toolbar.

### ISSUE THREAD

**Issue by paul-hammant** [MonitorControl/MonitorControl#413]
Not sure if I'm looking for a "sun" symbol in the toolbar or something else. The README doesn't say - jus shows pics of prefs (which I don't know how to get to).

- Paul

**Comment by waydabber** [comment]
Hi, definetly there should be a "sun icon" in the toolbar. If there is none, then the app probably did not start for some reason. The new 3.0.0 builds have an option to hide the menu bar icon (in this case you have to open the app again to enter Preferences), but this was not the case with earlier builds. I advise you to try a newer build and see if it works!

I'll close this issue for now but feel free to reply if it is still not working and we'll try to figure out what is happening! Thank you!
