### ISSUE TITLE
Apple Thunderbolt Display problem

### ISSUE THREAD

**Issue by ScarparoX** [MonitorControl/MonitorControl#414]
**Checklist**
- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
I have 2 monitors connected to my iMac 5k: A Dell P2715Q (is working normally with the MonitorControl) and an Apple Thunderbolt Display. When I click on the brightness keys using MonitorControl, the monitor goes dark at the minimum brightness level, being necessary to adjust manually through the MacOS Preferences Panel.

**To Reproduce**
1. Go to 'Select an Thunderbolt Display'
2. Click on 'brightness key'
3. Scroll down to 'not applicable'
4. See dark screen at minimum level of brightness

**Expected behavior**
I would expect the monitor to have the brightness adjusted as expected, just as it works on my iMac 5k and the other connected Dell monitor.

**Screenshots**
![ThunderboltDisplay](https://user-images.githubusercontent.com/81273390/112241471-0deb3c00-8c29-11eb-8c05-62a654a7250c.jpg)

**Additional context**
The Thunderbolt Display Monitor is connected to an iMac 5k, with another DELL monitor, model P217Q.

**Environment Information (please complete the following information):**
 - macOS version: 11.2.3
 - MonitorControl version: 2.1.0 (build 721)
 - Monitor(s): Apple Thunderbolt Display

**Comment by waydabber** [comment]
Hi @ScarparoX 

Apple Thunderbolt Display is not fully compliant with DDC commands but requires a different control method (DisplayServices). It is already implemented in MonitorControl but only for internal displays.

We plan to fix this problem. Future progress will be tracked in this issue, please feel free to comment there and follow developments. Your help might be needed when it comes the time for testing.

https://github.com/MonitorControl/MonitorControl/issues/364

Thank you!

**Comment by waydabber** [comment]
For those with Apple displays, there is a link to a test build with proper support here: https://github.com/MonitorControl/MonitorControl/issues/539
