### ISSUE TITLE
X34 Acer not working

### ISSUE THREAD

**Issue by Hanchao-Zhang** [MonitorControl/MonitorControl#415]
This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/xs/07f75z9d73x_g73xcl23m1c80000gn/T/carthage-xcodebuild.Djaeyc.log

here is the log

The following build commands failed:
	PhaseScriptExecution Run\ SwiftFormat /Users/ted/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/AMCoreAudio/3.4.0/Build/Intermediates.noindex/ArchiveIntermediates/AMCoreAudio/IntermediateBuildFilesPath/AMCoreAudio.build/Release/AMCoreAudio.build/Script-45CEB08223353071001F02CD.sh
(1 failure)

**Comment by Hanchao-Zhang** [comment]
sound is not working the the brightness works fine

**Comment by waydabber** [comment]
Hey @Hanchao-Zhang - thanks for the feedback. If you add more info about the display and your setup, I might help with the issue. Until that time, I'll close the issue, but feel free to respond anyway and I can reopen it. Sorry for the delayed feedback!

The build issue you mentioned doesn't seem to be related to MonitorControl but to [AMCoreAudio](https://cocoapods.org/pods/AMCoreAudio) which is currently not used by MonitorControl as far as I know.
