### ISSUE TITLE
cMP 5,1  Triple Monitor [Brightness works on 1 monitor, Audio doesn't adjust]

### ISSUE THREAD

**Issue by fireheadman** [MonitorControl/MonitorControl#416]
**Checklist**

- [ x] I have searched for existing issues
- [ x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [ x] I have updated MonitorControl to the latest version

**Describe the bug**
Couldn't locate a matrix of what hardware is supported.
I have  2010 cMP 5,1.   I use x3 ASUS VG248 gaming monitors (all connected by DisplayPort to Sapphire Radeon Vega 64)
Only 1 will dim the brightness.
Audio controls work from apple keyboard, but it doesn't actually adjust (lower/raise) volume the digital channel.

**To Reproduce**
1. Go to 'click F1/F2 keys for brightness'
2. Click on 'F10|F11|F12 to control audio'

**Expected behavior**
Expected brightness on all 3 monitors to work
Expected audio control to work

**Screenshots**

**Additional context**

**Environment Information (please complete the following information):**
 - macOS version:  BigSur 11.2.3
 - MonitorControl version: v2.1.0
 - Monitor(s): x3 - VG248 ASUS monitors - Display Port

PS:  I am willing to test if you have plans to support my profile.
THanks
Ben

**Comment by waydabber** [comment]
Hi, do you still have this problem? Normally only the active display is being controlled (on older versions the one with active menu bar) and there is a special setting to enable control for all displays. Does this help? Thank you!

**Comment by fireheadman** [comment]
dont know... uninstalled due to slow feedback

**Comment by waydabber** [comment]
Ok, no problem. Thanks for responding though!
