### ISSUE TITLE
Standardize the control range of different monitors when reported DDC ranges differ

### ISSUE THREAD

**Issue by womeimingzi11** [MonitorControl/MonitorControl#418]
**Checklist**

- [x] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I have two different model monitor, Monitor A and Monitor B. Their highest/lowest brightness are inconsistent,  it makes the dual screen experience not so delicate. 

Besides, the most interesting is monitor A provides a bad DDC implement, the 0 - 35%, 36-70%, 71-100% are replicates. So once I slide the slider of MonitorControl, the Monitor A goes to brighter and then become Dark, following it goes to brighter again.

**Describe alternatives you've considered**

Standardized the brightness of different monitors may solve this issue. For example, I can set 35% as the max brightness value of Monitor A, and 90% as the max brightness value of Monitor B. In this way, different displays can have more consistent brightness performance.

**Additional context**
Monitor A is Skyworth 27X1Q
Monitor B is AOC U2477WM

**Comment by waydabber** [comment]
This is a relevant issue. What we'll try to do is to add a gamma curve and min/max ddc brightness boundary option that helps to synchronize various displays - but perfect synchronization will be super difficult to achieve because display backlight ranges and controllers differ immensely from display to display.

**Comment by waydabber** [comment]
Here is @Teneff's requrest which is related (but not entirely the same as solving this problem with similar displays connected might be more trivial) and should be solved under the umbrella of this issue:

**Is your feature request related to a problem? Please describe.**
When multiple displays of the same kind(model) are connected as I want to change the brightness for all of them and I have to go through all of them one by one.

**Describe the solution you'd like**
Adding "All" menu on top of the displays with sliders to change the brightness for all of the displays would be great
image

**Describe alternatives you've considered**
Ideally the current brightness of each display would be mapped to the current internal display, and once the internal display's brightness changes by the sensor, the external displays' brightness would also change based on the mapping

**Comment by waydabber** [comment]
Regarding this issue the following will be the scope:

- Use a standardized internal range (from 0 to 100) for all kinds of control no matter what are the actual DDC control bounds and control protocol (GammaTable, DisplayServices or DDC)
- Matching the brightness levels of different display is not a scope of this issue.

Standardized internal range is required for #334 and #27.

**Comment by womeimingzi11** [comment]
> This is a relevant issue. What we'll try to do is to add a gamma curve and min/max ddc brightness boundary option that helps to synchronize various displays - but perfect synchronization will be super difficult to achieve because display backlight ranges and controllers differ immensely from display to display.

I definetly agree with you that the perfect synchronization is not easy. But you know, for low-end display, not so bad is perfect.

And I am so glad to know this feature is in progress.

**Comment by waydabber** [comment]
Hey @womeimingzi11 - the solution for this will not make differint displays match in min/max brightness and the progression of change. What I will be working on is the groundwork needed for a standardized internal scale among displays and then later build on this the options required if somebody want to match the brightness profile of differing displays + to have the ability to use a single scale to control multiple displays or replicate the brightness of internal displays to external displays.

So I am not sure if this is what you had originally in mind. I think if all related requests are resolved that deal with display min/max, curve and synchronization issues, then there is a good chance that things will work out. But its a long way, this is just a first step.

**Comment by womeimingzi11** [comment]
WOW @waydabber, it looks complicated but delicate.

I have carefully read your discussion with @JoniVR, and I find your plan is really academic. To tell the truth I am not sure whether I have understood the display profile feather.

But I am definitely looking forward to your contributions.

**Comment by waydabber** [comment]
@womeimingzi11 lol, no problem, don't worry about it. Takeaway is that there's gonna be a bunch of advanced settings to play with and you'll be able to experiment with them until you find the result satisfactory.

**Comment by womeimingzi11** [comment]
Fantastic @waydabber ! Your explaination is easy to understand, lol! I even can't wait to try all the features!

**Comment by waydabber** [comment]
<img width="803" alt="Screen Shot 2021-09-15 at 9 19 36" src="https://user-images.githubusercontent.com/37590873/133388914-5e66c8e9-037a-49e6-a9bb-87646f1547ef.png">

**Comment by womeimingzi11** [comment]
OMG! It looks really cool and delicate! I guess it even cover all the edge cases.

Especially the brightness/volume/contrast curves, it even beyond my original suggestions!

Cheers!

----------------------------------

Chen Han
E-mail: ***@***.***
School of Life Sciences, Lanzhou University, Lanzhou, 730000 P.R.China
在 2021年9月15日 +0800 PM3:22，waydabber ***@***.***>，写道：
