### ISSUE TITLE
Dell U4320Q Not recognized - iMac Mini M1

### ISSUE THREAD

**Issue by tgreco26** [MonitorControl/MonitorControl#420]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
 I have 2 external Dell U4320Q monitors connected to my iMac 2020 Mini

**Expected behavior**
Monitors not being recognized.

**Screenshots**
<img width="315" alt="image" src="https://user-images.githubusercontent.com/81693377/113150559-37483100-9202-11eb-99d2-c5a361be0355.png">

<img width="707" alt="image" src="https://user-images.githubusercontent.com/81693377/113150650-4a5b0100-9202-11eb-8cf4-bc5013dff49a.png">

**Additional context**

**Environment Information (please complete the following information):**
 - macOS version: Bug Sur v 11.2.3
 - MonitorControl version: 2.1.0 (Bud 721)
 - Monitor(s): U4320Q
 - Mac model: Mac mini M1
 - Monitor Cable(s)/Connection(s): (e.g. DisplayPort)
 - 1 - Thunderbolt USB-C
 - 2 - HDMI

**Comment by thebarbican19** [comment]
I am having the same issue with my Samsung Monitor on M1 Mac Mini as well. 

**Environment Information (please complete the following information):**
macOS version: Bug Sur v 11.2.3
MonitorControl version: 2.1.0 (Bud 721)
Monitor(s): 34" CJ791 Thunderbolt 3 Ultra Wide Screen Curved Monitor
Mac model: (Base 8GB) Mac mini M1 
Monitor Cable(s)/Connection(s): (e.g. DisplayPort)
1 - Thunderbolt USB-C
2 - HDMI

**Comment by the0neyouseek** [comment]
Please see #323
