### ISSUE TITLE
Greys out sliders while they are interactible

### ISSUE THREAD

**Issue by jorisw** [MonitorControl/MonitorControl#421]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
The sliders in the menu are grayed out even though they're perfectly interactible.

**To Reproduce**
1. Go to the Brightness menu added by this app
2. Notice the Brightness, Contrast and Volume sliders are grayed out but usable

**Expected behavior**
Expect them to be 'lit', i.e. enabled, not implying they are disabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/30017/113401513-be80da80-93a3-11eb-9aac-70d363186ab9.png)

**Environment Information (please complete the following information):**
 - macOS version: 11.2.3
 - MonitorControl version: 2.1.0
 - Monitor(s): Philips PHL 276E8V

**Comment by krypt-lynx** [comment]
I have pretty much the same issue except it monitor worked first time I started MonitorControl, but was going black while i was changing vales in MonitorControl

The monitor is Asus VS247, consentrator 
The adapter is A-CM-HDMIF-02-SG (this one: https://cablexpert.com/item.aspx?id=11205&lang=en)

_But_ everything was working perfectly fine on MacMini late 2012 with monitor connected to MacMini directly

**Comment by waydabber** [comment]
Hey, this is the standard look of the sliders in macOS slider control in Big Sur and Moterey in Dark Mode. We could override this but it would be against the standard ui design. :) I'll close this issue now. Let me know if we can do anything else about this!

<img width="261" alt="Screen Shot 2021-08-20 at 20 13 40" src="https://user-images.githubusercontent.com/37590873/130276420-e5ba9643-b4d0-4932-a692-632ca4210bae.png">

**Comment by krypt-lynx** [comment]
Oh. Apparently, I posted my reply under wrong issue
