### ISSUE TITLE
Dell U3821DW with M1 Mac Mini

### ISSUE THREAD

**Issue by benleembruggen** [MonitorControl/MonitorControl#423]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
The Dell U3821DW monitor is not picked up as a compatible monitor in the MonitorControl app.

**Expected behaviour**
Support for the Dell U3821DW (Dell U3818DW is the predecessor) would be ideal, allowing volume control from the keyboard.

**Environment Information (please complete the following information):**
 - macOS version: 11.2.1
 - MonitorControl version: 2.1.0
 - Monitor(s): Dell U3821DW
 - Mac model: 2020 M1 Mac Mini
 - Monitor Cable(s)/Connection(s): USB-C (display port)

**Comment by bjornorri** [comment]
Did you get this working? I have a similar situation...

**Comment by bjornorri** [comment]
Nevermind, found #323
