### ISSUE TITLE
Not support Dell U2720Q

### ISSUE THREAD

**Issue by asterism612** [MonitorControl/MonitorControl#426]
Unknown Display

**Comment by maxsquared** [comment]
Using the same display and it works fine for me.

**Comment by terryeah** [comment]
Can confirm Dell U2720Q shows Unknown Display

**Comment by chunheisiu** [comment]
Doesn't work for me when connected over USB-C.

**Comment by maxsquared** [comment]
Not sure why it's not working for you, but it works fine for me, mine runs Mac OS 11 Big Sur, connected with Caldigit TS3+ with DisplayPort, I am not sure if this information helps. If you want me to find out any monitor settings just let me know.

**Comment by Vchouliaras** [comment]
Happens to me as well! The monitor is connected over usb-c on a Macbook pro m1.

The "USB-C Prioritization" setting on the monitor is set to "High Resolution"

**Comment by vtns** [comment]
> Happens to me as well! The monitor is connected over usb-c on a Macbook pro m1.

M1 Mac  is not supported by this kind of utility which uses DDC/CI to control monitor's brightness.
There are nothing we can do about this unless Apple add a support of DDC to M1 Mac.

**Comment by JoniVR** [comment]
Pretty sure this is an M1 issue, see #323. Closing for now, feel free to comment if you have this issue on Intel.

**Comment by chunheisiu** [comment]
Mine was on an Intel. 2020 MacBook Pro 13".
