### ISSUE TITLE
No sound from the monitor, just stops working randomly

### ISSUE THREAD

**Issue by tierpinho** [MonitorControl/MonitorControl#427]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

*Describe the bug*
The Monitor Control software works in terms of making the volume UI go up/down but the actual sound from the monitor just stops working. If I switch back the laptop volume, it works fine. 

*To Reproduce*
Tap the volume buttons and nothing works.

*Expected behaviour*
The keyboard buttons should enable the function of volume (+/-) and sound should be heard.

*Environment Information (please complete the following information):*

macOS version: OSX 11.2.3
MonitorControl version: Latest
Monitor(s): LG49WL95

**Comment by wilbit** [comment]
I happened with me on version 2.2.0.
I reverted back to 2.1.0 and issue is gone.
But, I assume it is not your case, according to the issue's timeline, you should be using version 2.1.0...

**Comment by waydabber** [comment]
Does brightness control work well, onty the volume control has problem? Thank you!

**Comment by wilbit** [comment]
I don't use brightness control, so, I don't know.
I will test and let you know.

**Comment by waydabber** [comment]
Ok! I'd like to understand whether DDC control generally works or not.

**Comment by wilbit** [comment]
Huh, Release 2.2.0 does not exist anymore, I cannot download binaries to check...
With my current 2.1.0, I almost have no issues.

**Comment by wilbit** [comment]
Do you have the binaries to share?

**Comment by waydabber** [comment]
Hi, no unfortunatelly, 2.2.0 was broken, that's why it was pulled. You should wait a bit, later today (if things go well) we plan to release 3.0.0 RC1 - that's the one you should test! Thank you! :)

**Comment by waydabber** [comment]
I'll close this issue for now, I hope the new 3.0.0 fixed the issue. Please feel free to comment if the issue persists so we can reopen this issue! Thank you!

**Comment by wilbit** [comment]
The issue exists =(

The symptoms:
1. Monitor control is not able to set volume to zero. It decreases to zero according to DisplayIcon and monitor's embedded volume control window, but I still can hear sound. Mute button works the same, it decreases the sound, but does not set to zero.
2. When I increase sound by monitor's controls by 1, and then decrease it to zero - I don't hear sound anymore, BUT, after that MonitorControl stops to work. According to DisplayIcon, MonitorControl changes the volume level, but it does not. And not just that, monitor's embedded controls also stops to work - they change the volume level according to embedded volume control window, but there is no any effect.
3. When I turn off and turn on my monitor, everything is get back to item 1.
4. MonitorControl's restarting changes nothing.
5. Back to the brightness control - it works, no issues

**Comment by waydabber** [comment]
Hi,

yes, the LG 34"s are known to have issues regarding volume control. This seems to be a firmware issue. You might want to try what happens if you activate `Enable Mute DDC command` under Displays in the Advanced settings area (you need to enable `Show advanced settings under Displays` in General to have this option).

**Comment by waydabber** [comment]
See this thread as well, it's about an other LG 34" having issues with volume control: https://github.com/MonitorControl/MonitorControl/issues/170

**Comment by wilbit** [comment]
> yes, the LG 34"s are known to have issues regarding volume control. This seems to be a firmware issue. You might want to try what happens if you activate `Enable Mute DDC command` under Displays in the Advanced settings area (you need to enable `Show advanced settings under Displays` in General to have this option).

Well, `Enable Mute DDC command` fixes the issue with not zero volume level and makes MonitorControl "usable". But still, from time to time volume control does not work after it's set to zero. After few attempts (to zero and back) it works again.

**Comment by waydabber** [comment]
You seem to have the same issue as #170 then. I plan to make a test build which does not set the volume to 0 but only uses the mute/unmute command if `Enable Mute DDC` is on. Maybe to make sure, I'll issue these commands repeat. That might fix the issue, but I don't have a display like this to test.

**Comment by wilbit** [comment]
I have updated my https://github.com/MonitorControl/MonitorControl/issues/427#issuecomment-907596011, my monitor is Samsung, not LG, @waydabber

**Comment by waydabber** [comment]
Interesting turn of events. :)

**Comment by waydabber** [comment]
@wilbit can you try the build posted under the https://github.com/MonitorControl/MonitorControl/issues/170 issue and report back there? We better continue the discussion in that thread. Thank you!
