### ISSUE TITLE
(Limited) iPad Sidecar, Airplay, screen sharing and DisplayLink support

### ISSUE THREAD

**Issue by ChrisChinchilla** [MonitorControl/MonitorControl#428]
I imagine this is probably impossible for various "Apple reasons", but if it was possible, the ability to change the levels on an iPad connected by Sidecar would be amazing.

**Comment by waydabber** [comment]
Unfortunatelly this is not possible at the moment as threre is no way to change the brightness of a Sidecar display from macOS. The upcoming versions of the app will be able to detect Virutal displays (like SideCar) at least.

**Comment by waydabber** [comment]
The upcoming 3.1.0 will have some support for Airplay, screen sharing, Sidecar as well as DisplayLink devices in the form of display shading. This is a software based technique which is inferior to gamma control (which is also software based). Notably, mouse cursor will not be dimmed and also during full screen transitions there are irregularities. But still, this is better than nothing.
