### ISSUE TITLE
DELL P3421W - Unknown Device (no support)

### ISSUE THREAD

**Issue by stepansanda** [MonitorControl/MonitorControl#429]
Dell P3421W not supported. Great USB-C IPS monitor for macbook users. 
I can see DCC/CI on/off toggle in the monitor menu.
i have it connected via usb-c

MonitorControl displaying: unknown device

**Comment by JoniVR** [comment]
I'm guessing you're using an M1 mac? Check #323 and please close the issue if this is the case 🙂
