### ISSUE TITLE
F14+F15 keys trigger brightness control

### ISSUE THREAD

**Issue by Tabiskabis** [MonitorControl/MonitorControl#430]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
Brightness control is triggered by F14 and F15 keys, _even when these shortcuts are disabled in MacOS control panel_.
This even happens when those keys are remapped to by Karabiner Elements.

**To Reproduce**
Have an Apple Keyboard with keypad (and therefore F13-F19 keys)
Go to Mac Control Panel --> Keyboard
go to tab: Shortcuts
left select Monitor
disable increase/decrease monitor brightness (or change their shortcuts to some other keys)
press F14/F15
see brightness still be adjusted

**Expected behavior**
Don't use F14/F15 for brightness control unless they are actually in use for that.

**Additional context**
This bug is a problem when these are actually used for something different. I need them as "scroll lock" and "pause" for remote work over Windows RDP. Yes, I actually need them many times in a day. Yes, I might be a dinosaur.

Besides that: *huge f-in kudos* for this app!

**Environment Information (please complete the following information):**
 - macOS version: 10.14 (Mojave)
 - MonitorControl version: 2.1
 - Monitor(s): irrelevant (but they are 2x Dell S2721DGF which absolutely _rock_)

**Comment by Tabiskabis** [comment]
Addition: it seems that the issue is not actually specific with the F14/15 keys, but with the "scroll lock" + "pause" function..? I've just remapped F18/F19 for that purpose in Karabiner and bam, they *too* now control the monitors' brightness.

**Comment by JoniVR** [comment]
See #100
