### ISSUE TITLE
LG 34WK95U-W controls not working 

### ISSUE THREAD

**Issue by resilient-max** [MonitorControl/MonitorControl#431]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
A clear and concise description of the problem.
I am using an LG 34WK95U-W with a 2017 Macbook Pro 13" connected by Thunderbolt 3. Neither brightness nor volume controls work with this monitor. I connected a different HP Z27 Monitor (USB-C and not Thunderbolt 3) and brightness works, can't comment on volume since the HP has no speakers.
**Expected behavior**

**Screenshots**

**Additional context**

**Environment Information (please complete the following information):**
 - macOS version: 11.3
 - MonitorControl version: 2.1.0
 - Monitor(s): LG 34WK95U-W
 - Mac model: 2017 13 Macbook Pro i5 16GB Ram
 - Monitor Cable(s)/Connection(s): (e.g. DisplayPort) Thunderbolt 3

**Comment by tartanapp** [comment]
Yes, me too, the app no longer working after updating to big sur 11.3

**Comment by resilient-max** [comment]
I had the problem before the update too.

**Comment by sanguino** [comment]
I bought this monitor today, and at first I also have the same issues, and others related to resolution and color schemes in osx.

After updating the firmware, and configuring it to use display port 1.4 (from the OSD menu), it works as expected. Keep in mind that if the brightness is in automatic it does not allow to control it, so I deactivate automatic brightness too.

Now I'm looking for how to control it from the touch bar, because if I use the lg as output, the volume control is deactivated, and the brightness only controls the macbook monitor.

I hope it helps.

**Comment by sanguino** [comment]
#224

**Comment by resilient-max** [comment]
> I bought this monitor today, and at first I also have the same issues, and others related to resolution and color schemes in osx.
> 
> 
> 
> After updating the firmware, and configuring it to use display port 1.4 (from the OSD menu), it works as expected. Keep in mind that if the brightness is in automatic it does not allow to control it, so I deactivate automatic brightness too.
> 
> 
> 
> Now I'm looking for how to control it from the touch bar, because if I use the lg as output, the volume control is deactivated, and the brightness only controls the macbook monitor.
> 
> 
> 
> I hope it helps.

That sounds very possible, I cannot find a firmware update for this monitor. 

Without firmware update, if I switch to Display port 1.4 the resolution is messed up and the ratio is no longer Ultrawide. I read someone else has that issue with the same with the MacBook Pro 2017, http://lgcommunity.us.com/discussion/16546/lg-34wk95u-w-doesnt-have-correct-resolution-hdr-via-thunderbolt3-and-dp1-4-on-mac

Also, is it true that the in box cable only transmits 20GB/s?

**Comment by JoniVR** [comment]
Closing in favour of #224

**Comment by resilient-max** [comment]
> Closing in favour of #224

The issue is still present.
