### ISSUE TITLE
LG 32un880-B

### ISSUE THREAD

**Issue by JalevYT** [MonitorControl/MonitorControl#432]
It sadly does not work for the LG Ergo 32un880-B. 
It would be gorgeous if someone could fix it 🔢

**Comment by tartanapp** [comment]
It will not work if you updated to mac os 11.3,
it was working fine before , I have the same screen

**Comment by Levin09** [comment]
Ok Thanks I'll update it in a few minutes and give a feedback. 
If it's still not working it may is because I have a M1 Macbook.
The error inside the app is just because of the monitor so I thing the update could fix it

**Comment by JoniVR** [comment]
Yes, it's due to M1 not being supported yet, see #323.
