### ISSUE TITLE
The app not working after updated to big sur 11.3

### ISSUE THREAD

**Issue by tartanapp** [MonitorControl/MonitorControl#433]
The app GUI does not work with big sur 11.3, (it seems it just run at backend ) and sometimes I cant decrease/increase the brightness of the screen,

**Environment Information (please complete the following information):**
 - macOS version: 11.3
 - MonitorControl version: latest
 - Monitor(s): LG

**Comment by gvaneck-m4m** [comment]
The app disappeared after upgrade, works fine after I reinstalled it.

**Comment by tartanapp** [comment]
Thanks a lot. I tried it, it works fine now
