### ISSUE TITLE
no support Viewsonic VX3211-4K

### ISSUE THREAD

**Issue by jeske** [MonitorControl/MonitorControl#434]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/15093/116798982-2bc28100-aab2-11eb-9a00-d32508cea91c.png">

This is a Viewsonic VX3211-4K, not recognized. The monitor has DDC/CI support of some kind (it's turned on in the on screen menu)..

I did some searching, but couldn't easily find any documentation of the DDC commands supported. I'll keep looking.

**Comment by waydabber** [comment]
Hi, please test one of the latest 3.0.0 betas with M1 support and report back if it works + please close the issue. Thank you!

**Comment by waydabber** [comment]
Hi, we have relased the [3.0.0 version](https://github.com/MonitorControl/MonitorControl/releases/tag/v3.0.0-rc1). Could you please test if this issue is resolved and report back? Thank you!

**Comment by waydabber** [comment]
I'll close this one since it should be solved. If there is any issue with this, please feel free to comment and ask for a reopen! Thank you!
