### ISSUE TITLE
Remove volume slider toggle

### ISSUE THREAD

**Issue by bringmecoffeeortea** [MonitorControl/MonitorControl#435]
Similar to the option to remove the contrast slider, can you please add an option to remove the volume slider? I'm using a Dell U2515H and it doesn't have sound. The volume slider moves, but does nothing. I'm using a Dell USB sound bar thing that attaches to my monitor.

**Comment by waydabber** [comment]
Hi, I added this in the new 3.0.0 version. You can check out the current beta or wait for the release! Please test and close the issue if it works. Thanks!

**Comment by waydabber** [comment]
Hi, we have relased the [3.0.0 version](https://github.com/MonitorControl/MonitorControl/releases/tag/v3.0.0-rc1). Could you please test if this issue is resolved and report back? Thank you!

**Comment by waydabber** [comment]
I'll close this one since it should be solved. If there is any issue with this, please feel free to comment and ask for a reopen! Thank you!

**Comment by bringmecoffeeortea** [comment]
Thanks it works great!
