### ISSUE TITLE
localization-Chinese-Taiwan

### ISSUE THREAD

**Issue by dororojames** [MonitorControl/MonitorControl#438]
**Checklist**

- [x] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**
No, just want to support your localization

**Describe the solution you'd like**

**Describe alternatives you've considered**
I provide some string files for localization

**Additional context**

[zh-TW.lproj.zip](https://github.com/MonitorControl/MonitorControl/files/6445964/zh-TW.lproj.zip)

**Comment by waydabber** [comment]
Hey, we'll release a new 3.0.0 version which as a lot of changes in localization text. This will soon be in the Master branch. It would be great if you could update the translation based on that and then create a pull request! Let us know if you need any help! Thank you!

**Comment by waydabber** [comment]
There is a similar work here for the RC1 version therefore I close this one.

https://github.com/MonitorControl/MonitorControl/issues/528
