### ISSUE TITLE
Volume control doesn't work with DELL U2520D on v2.1.0

### ISSUE THREAD

**Issue by nvcken** [MonitorControl/MonitorControl#440]
**To Reproduce**

1. Go to MonitorControl on top menu bar
2. Click on Volume adjust level
3. Try to adjust the volume level
4. Sound output for Audio jack 3.5mm still in maximum level

**Expected behavior**
Volume adjustment should be work

- macOS version: Big Sur 11.2.3 (20D91)
- Mac model: MacBook Pro (13-inch, 2019, Two Thunderbolt 3 ports)
- MonitorControl version: v2.1.0
- Monitor(s): Dell Monitor U2520D
- Apple Silicon/M1 (yes or no): No

**Comment by dch09** [comment]
Same issue on DELL U2719DC.

**Comment by quantified-null** [comment]
Same monitor, same issue. DELL U2520D is displayed and recognised but no volume change occurs.

**Comment by brakthehack** [comment]
+1 for the DELL U3415W

**Comment by SR-TaTranky** [comment]
+1 for DELL U2717D

**Comment by beihai0xff** [comment]
+1 for DELL U2720D

**Comment by davidchoo12** [comment]
+1 for DELL U2422H

**Comment by JoniVR** [comment]
Seems like Dell issues are quite the trend, merging this one with #226
