### ISSUE TITLE
Sony Bravia KDL-32W705B Support

### ISSUE THREAD

**Issue by kvpb** [MonitorControl/MonitorControl#443]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
The sliders do not affect either brightness or volume. MonitorControl probably does not support KDL-32W705B.

**Expected behavior**
The sliders should affect what they are supposed to be affecting.

**Screenshots**
![Screenshot 1](https://i.imgur.com/OQ2WRm6.png "Screenshot 1")
![Screenshot 2](https://i.imgur.com/qOLoF0m.png "Screenshot 2")

**Additional context**
It happened on a factory-installed operating system and a fully working display.

**Environment Information (please complete the following information):**

- macOS version: 11.2.3
- MonitorControl version: 2.1.0 (Build 721)
- Monitor(s): Sony Bravia KDL-32W705B
- Mac model:
- Monitor Cable(s)/Connection(s): HDMI (e.g. DisplayPort)
- Apple Silicon/M1 (yes or no): no

---

|Enabled							|DDC								|Name		|Display Name	|ID			|Vendor	|Model
|:-:								|:-:								|:-			|:-				|:-			|:-		|:-
|<input type="checkbox" checked>	|<input type="checkbox" checked>	|SONY TV	|SONY TV		|1985134787	|0x4DD9	|0x4B03
<center><p><i>MonitorControl Preferences</i></p></center>

**Comment by waydabber** [comment]
Hi, unfortunatelly TVs cannot be controlled via DDC as they generally don't support this protocol. However the new 3.0.0 release will have software control so it will still be useful with your TV. Please test it if the release is out.

I'll close this issue for now. Thank you!
