### ISSUE TITLE
Help Wanted: Bug Sur styled Icon

### ISSUE THREAD

**Issue by JoniVR** [MonitorControl/MonitorControl#444]
Hi everyone,

I'm giving the app a fresh lick of paint to be more in line with Big Sur changes, such as updated prefs icons (along with some other fixes along the way) and was hoping someone with some better experience in designing icons would be willing to help out in designing an icon that fits in Big Sur.

Here's my boring attempt so far:

<img alt="new big sur icon" src="https://user-images.githubusercontent.com/7591717/118369807-216db000-b5a5-11eb-8d75-7afc403e2d79.png" width="200px"/>

Anyone better at design willing to take a go at it?

**Comment by alexandrerochasalles** [comment]
Hi @JoniVR , I did the same that you are doing, and to do that I have discovered a lot of icons in this site (where also have some options for MonitorControl, but I didn't like, so I've decided to use one for Apple TV that are available over there).

https://macosicons.com

**Comment by JoniVR** [comment]
Hi @alexandrerochasalles yes I saw that site, though we'd probably need permission from the creators if we were going to use one. 

If I ever do get some spare time I might try to make a decent one myself but there's just so much other stuff to do for this project and I'm not great at fancy icon design.

**Comment by waydabber** [comment]
Here is an attempt.

The idea was the following:

- Have some continuity with the old design.
- Depict a subtle Apple Thunderbolt Display like design (shiny black frame with a very subtle something at the botton that might resemble a logo) with the display showing a stylized full screen brightness OSD.
- Have some color beyond grays and blacks but no obvious images that tie the icon to a certain MacOS release (like Big Sur or Monterey) - so the brightness icon and chiclets are blue now.
- Avoid using copyrighted product designs (as required by [Apple's Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/))
- Look distinct both in bright and dark mode in Dock (for users who like to put the Applications folder there) and in Launchpad.

![Icon-512](https://user-images.githubusercontent.com/37590873/127773317-d66b4f58-5496-453c-9216-022d0e5a2890.png)

There might be better ideas out there, so this is just a suggestion (design is rather subjective). I put this one into the experimental branch though.

**Comment by waydabber** [comment]
Here are some other options:

This one has a more defined border, avoids blending in and looking small when Dark Mode is enabled:

![Icon-1024](https://user-images.githubusercontent.com/37590873/127834625-9fb10ba2-3e67-42da-9dbd-168f30731248.png)

This one is more friendly, not as gray:

![Icon-1024](https://user-images.githubusercontent.com/37590873/127834658-88a35d35-6978-42eb-85f7-941329fc729e.png)

This ione is cleaner with no border:

![Icon-1024](https://user-images.githubusercontent.com/37590873/127834668-a2e19fc8-8250-4749-a0a6-7de423aac97a.png)

This one has a rather passive mountains image background (does not look that well when small though):

![Icon-1024](https://user-images.githubusercontent.com/37590873/127834681-9565d557-45ba-4526-8e05-6e451f21813c.png)

This one has some bold colors and stand out more:

![Icon-1024](https://user-images.githubusercontent.com/37590873/127834686-caa44d8d-10ac-4f3a-9b84-33b6872dcc3c.png)

**Comment by jamesg311** [comment]
Maybe late to the party here, but whipped this up for you. I think it carries forward some of your original design but updated with some system elements (the blue is the system color for "Link", uses an Apple Pro Display XDR, and macOS Monterey background given we are near launch of macOS 12).

Thanks for all of your work. I can't help on the engineering side but thought I'd offer something up on the design side!

![MonitorControl](https://user-images.githubusercontent.com/5140425/128071657-6a91df8c-1eae-473e-b6d6-6253607205e8.png)

**Comment by waydabber** [comment]
Hey @jamesg311 ,

I like the attempt but I think we are not allowed to use Apple proprietary hardware designs unfortunately (this seems to be explicitly forbidden this in the interface design guide). :( Obviously the current icon violates this and nothing ever happened but still... :)

Hey @the0neyouseek,

I think it looks great, resembles a monitor and is clean and direct. Also fits with other display themed Apple icons (Terminal, Activity Control, Screen Sharing). I am unsure about directly reusing the Monterey wallpaper (it will tie the icon to a specific OS release + I am not sure if it is allowed - maybe we should use something similar royalty free?). Also I'd change the arc of the OSD corners just a bit to follow the arc of the icon itself so distances feel similar everywhere between the OSD and the monitor frame. What do you think? In overall this display-like icon might be a better approach than the ones I proposed. :)

**Comment by waydabber** [comment]
Hey @the0neyouseek 

Here is one inspired by your work to illustrate what I mean.

![Icon-1024](https://user-images.githubusercontent.com/37590873/128157523-34adc75b-94f7-4d1a-af0b-c4ec08dd3704.png)

The background pic is taken from [javierocasio](https://www.deviantart.com/javierocasio/art/Waves-Wallpapers-873299748) which is inspired by both Big Sur and Monterey and resembles the vibe of Apple's wallpaper.

What do you think?

**Comment by the0neyouseek** [comment]
@waydabber Looks great !

**Comment by JoniVR** [comment]
@waydabber I like it too! It's a bit of a mix of all the other great concepts.

**Comment by waydabber** [comment]
Great! Then I think it is decided! :)

(of course there is room for further improvements in the future).
