### ISSUE TITLE
MonitorControl stopped working

### ISSUE THREAD

**Issue by asheenlevrai** [MonitorControl/MonitorControl#445]
Hi :)

I was happily using the current version of MonitorControl on my hackintosh running 10.15.7 via OC.

Now it seems like it doesn't work anymore but I'm not sure since how long. When I press the brightness or volume keys nothing happens. The macOS toast notifications appear but nothing changes.

MonitorControl seems to still detect my monitor and the settings look like what they should be in the app.

I tried reinstalling. restarting the computer... I don't know how to troubleshoot this further

Can you help me out here please?

Thank a lot in advance for your help.

Best,
-a-

**Comment by kadiraydintp** [comment]
same issue here

**Comment by asheenlevrai** [comment]
Nevermind...
After unpluging/repluging everything and a couple restarts, now it all works again.
Weird...
