### ISSUE TITLE
Feature request: customize volume increment

### ISSUE THREAD

**Issue by monkpit** [MonitorControl/MonitorControl#447]
First off, I really love this application! I found it when I discovered that my new LG monitor has built-in speakers...

I really love being able to adjust the volume directly from my keyboard.

However, this monitor is SO LOUD! The volume apparently goes up to 100. If I put the volume all the way down, and start to increase it, MonitorControl set the volume from 0, to 6, then to 13 if I increase it again.

The trouble is, 13 is right on the threshold of being too loud. You can hear it across the house! I can't imagine how loud this thing would be if I set it to 100, or even 50.

But then again, 6 is too quiet.

So, I find myself using MonitorControl and the keyboard to set the volume to 13, but then reaching for the actual monitor buttons to bump the sound back down to 11 or 12. Which sort of defeats the purpose!

I am thinking one of the 2 following options would work:
* If I could set a custom volume increment for MonitorControl it would be perfect, but maybe it doesn't work this way
* Maybe the first option is impossible and it works by percentages... if that is the case, maybe there could be a setting to Override the maximum that the monitor can be set to... Like, if I could set the maximum Monitor volume to be 20, then MonitorControl calculates the percentages out... each time the volume is pressed, it increases/decreases by 2.

Another fix would be to limit the "line out" volume at the system level, but:
* I am not sure how to do that myself, and
* That's probably out of scope as a feature for this app? But maybe not :)

**Comment by AuxNuke** [comment]
First, thanks for the great program!  

I have the exact same issue with a pair of LG 32BL95U-W 4K monitors.  Pressing the volume up or down on the keyboard after enabling MonitorControl turns the volume up by large incremental steps just as described above 0 > 6 > 13 > 19, etc.  By volume level 19 these monitors are already LOUD.  Would love to be able to adjust the volume granularity and raise / lower the volume on the monitor by 1.  Thanks!

**Comment by quantified-null** [comment]
Try holding down Shift and Option when you use the keyboard buttons to increase/decrease volume. The volume should go up in increments of 1/64 instead of 1/16. (works for brightness and keyboard brightness too)

**Comment by AuxNuke** [comment]
> Try holding down Shift and Option when you use the keyboard buttons to increase/decrease volume. The volume should go up in increments of 1/64 instead of 1/16. (works for brightness and keyboard brightness too)

Is there an option or config to modify to make this the default behavior?  Thanks!

**Comment by waydabber** [comment]
Hi, this is a useful request, I assigned it to myself and will try to add this as an advanced option in one of the future releases.

**Comment by waydabber** [comment]
This will be dealt with in this issue:

https://github.com/MonitorControl/MonitorControl/issues/310
