### ISSUE TITLE
Fix dependencies

### ISSUE THREAD

**Issue by JonasGessner** [MonitorControl/MonitorControl#448]
- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
I tried cloning the project and building it myself and I ran into several issues all boiling down to the fact that the Cartfile has no versions/commit hashes set:

- AMCoreAudio is not called SimplyCoreAudio on version 4 and no longer source compatible with version 3 (AMCoreAudio) which is what this project uses. So the Cartfile should specify the version as `~> 3.4`.
- DDC and MediaKeyTap simply use `master` in the Cartfile. This is an issue because after I fixed the AVMCoreAudio problem I noticed that the app I compiled myself doesn't work properly – most of the time nothing changes on my display. Only after spamming volume/brightness keys anything starts to change. The latest version installed through homebrew does not have this problem. This could be a regression in `DDC`, but since there is no commit information/tag version for DDC in the Cartfile I do not know which commit you linked against!

**Environment Information (please complete the following information):**

- macOS version: 11.4
- Mac model: 2019 MBP
- MonitorControl version: master
- Monitor(s): LG HDR 5K
- Apple Silicon/M1 (yes or no): no

**Comment by JoniVR** [comment]
Hi, all of this is being worked on in the refactor/Preferences branch. 

I just need to fix some of the storyboard stuff and it'll be ready for a merge.

Changes so far:

- migrated Carthage to SPM
- Migrated MASPreferences To Preferences
- AMCoreAudio to SimplyCoreAudio
- Dependency updates in general

**Comment by JonasGessner** [comment]
That's great, thanks for the quick reply!
