### ISSUE TITLE
It does not work with M1 Mac

### ISSUE THREAD

**Issue by sherlock440** [MonitorControl/MonitorControl#454]
I used MonitorControl with Intel Mac (MacBook Pro 2014), and everything was OK. But recently I bought a MacBook Air 2020 (M1), and the app could not recognize my old monitor (which I used with Intel Mac). This monitor is showed in "Monitor" tab in "Settings" as an unknown device, but I cant adjust the brightness anyway.

<img width="789" alt="image" src="https://user-images.githubusercontent.com/63901545/121877459-4889df80-cd13-11eb-9349-024608e7ea08.png">
<img width="356" alt="image" src="https://user-images.githubusercontent.com/63901545/121877478-4de72a00-cd13-11eb-8e5b-9e50277412bf.png">

I am using AOC I2281FWH and I am connecting it to Mac via HDMI to USB-C hub by Baseus

**Comment by the0neyouseek** [comment]
Please see #323
