### ISSUE TITLE
Disable app when not connect to external monitor

### ISSUE THREAD

**Issue by LandonSchropp** [MonitorControl/MonitorControl#456]
**Checklist**

- [x] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**

Yes. When no monitors are connected, MonitorControl causes issues with the built-in brightness controls. This problem is described in more detail in #366.

**Describe the solution you'd like**

A simple solution would be to disable the app when no monitors are connected. This would allow the default system brightness controls to operate, and the app could re-enable itself when I connect to my external monitor. This could potentially be added as an option in the Preferences, but it might also make sense as a default behavior.

**Describe alternatives you've considered**

Right now I quit the app every time I unplug from my monitor and I restart it when I plug back in. This workflow isn't great.

**Additional context**

Nope.

**Comment by waydabber** [comment]
Hi, I made a change in the upcoming version - if there are no external displays connected, the app will disengage from listening to brightness/volume keys, handing back control to the OS. Hope this is what you requested!

**Comment by mmontag** [comment]
Nice!! Much appreciated

**Comment by LandonSchropp** [comment]
Awesome! That's exactly what I wanted. Thank you!

**Comment by LandonSchropp** [comment]
@waydabber Just to clarify, does this also include the automatic brightness adjustments? One of the big issues I run into with MonitorControl on my MacBook is it aggressively makes the screen too bright when I'm not connected to an external monitor.

**Comment by waydabber** [comment]
I think MonitorControl should not interfere with automatic brightness adjustments in any way as there is nothing implemented in the code that would do such a thing.

**Comment by waydabber** [comment]
Hi, we have relased the [3.0.0 version](https://github.com/MonitorControl/MonitorControl/releases/tag/v3.0.0-rc1). Could you please test if this issue is resolved and report back? Thank you!

**Comment by LandonSchropp** [comment]
Sure thing! I've downloaded the update and I'll report back soon.

**Comment by LandonSchropp** [comment]
This update works perfectly. Thank you!

**Comment by waydabber** [comment]
Amazing, thanks for the feedback!
