### ISSUE TITLE
Tested working M1 control code.

### ISSUE THREAD

**Issue by tao-j** [MonitorControl/MonitorControl#459]
**Checklist**

- [ x] I have searched for existing issues
Well I cannot comment on the original issue #323 . So open this one before I forget. 

**Discussion**
Please see below for an implementation that works for m1 brightness control. Tested working on one Dell one acer monitor.

https://github.com/alin23/Lunar/issues/210#issuecomment-872601088

Or you can compile this gist

https://gist.github.com/tao-j/c7a3c1ec7c2f59ebe45d161d620d9169

**Comment by dguerri** [comment]
LG works too :) Well done @tao-j !!

**Comment by bummoblizard** [comment]
It's also working on my Dell :)

**Comment by waydabber** [comment]
Amazing, working perfectly on my Macbook Air M1 + LG 4K 27UD88-W over USB-C!

**Comment by tao-j** [comment]
https://github.com/MonitorControl/MonitorControl/discussions/379

**Comment by JoniVR** [comment]
Thanks @tao-j 

I have been following up on the threads but am still on vacation. 

Great to see a possible solution. I'll try to look into it later.
