### ISSUE TITLE
Chinese Translation Recommend

### ISSUE THREAD

**Issue by iambjlu** [MonitorControl/MonitorControl#460]
Hi, I am really appreciate this project that helps me control my display, and I would like to help other people who use Chinese to use this project more easily, so I want to make this more locally.  However, I am not familiar with these codes, so I can only provide as much word translations as I can.  Here are translated words I can provide for Traditional and Simplified Chinese :

English word and translated words are separated with a comma 

•—•—•—•—•—•—• 🇬🇧 English,🇹🇼 🇭🇰 Traditional Chinese(繁體中文) •—•—•—•—•—•—•

Contrast, 對比度
Brightness, 亮度
Volume, 音量
Preferences... , 偏好設定... ,
Quit, 結束,

General, 一般
Version, 版本
Build, 版本號
Start MonitorControl at login, 在登入時打開 MonitorControl
Show a slider for contrast, 顯示對比度滑桿,
Lower contrast after brightness, 在調低亮度後降低對比度

Keys, 快捷鍵
Listen for, 接收
None, 無
Volume only, 僅音量
Brightness only, 僅亮度
Both Brightness & Volume, 亮度與音量

Display, 顯示器
Change Brightness/Volume for all screens, 調整所有顯示器的亮度/音量
Enabled, 啟用
Name, 名稱
Display Name, 顯示器名稱
ID just called ID
Vendor, 製造商
Model, 型號

Advanced, 進階
Warning, 警告
Changing some of these setting may cause system freezes or unexpected behaviour, 更改以下部分設定可能導致系統凍結或是無法預期的行為。
Display Name, 顯示器名稱
ID just called ID
Polling Mode, 輪詢模式
None, 無
Minimal, 較小
Normal, 一般
Heavy, 較大
Custom, 自訂
Polling Count, 輪詢計數
Longer Delay, 較長延遲
Hide OSD, 隱藏OSD
Reset Preferences, 重置偏好設定

•—•—•—•—•—•—• 🇬🇧 English, 🇨🇳 Simplified Chinese(简体中文) •—•—•—•—•—•—•

Contrast, 对比度
Brightness, 亮度
Volume, 音量
Preferences... , 偏好设定... ,
Quit, 结束,

General, 一般
Version, 版本
Build, 版本号
Start MonitorControl at login, 在登入时打开 MonitorControl
Show a slider for contrast, 显示对比度滑杆,
Lower contrast after brightness, 在调低亮度后降低对比度

Keys, 快捷键
Listen for, 接收
None, 无
Volume only, 仅音量
Brightness only, 仅亮度
Both Brightness & Volume, 亮度与音量

Display, 显示器
Change Brightness/Volume for all screens, 调整所有显示器的亮度/音量
Enabled, 启用
Name, 名称
Display Name, 显示器名称
ID just called ID
Vendor, 制造商
Model, 型号

Advanced, 进阶
Warning, 警告
Changing some of these setting may cause system freezes or unexpected behaviour, 更改以下部分设定可能导致系统冻结或是无法预期的行为。
Display Name, 显示器名称
ID just called ID
Polling Mode, 轮询模式
None, 无
Minimal, 较小
Normal, 一般
Heavy, 较大
Custom, 自定义
Polling Count, 轮询计数
Longer Delay, 较长延迟
Hide OSD, 隐藏OSD
Reset Preferences, 重置偏好设定

•—•—•—•—•—•—•

Thank you !!

**Comment by waydabber** [comment]
Hi iambjlu,

thanks for the contribution. We'll soon release the 3.0.0 version which has a major overhaul in terms of preferences and texts to translate. Please check out the localization files for that version (its in the experimental branch as of now but very soon it will be moved to the Master branch) and we'll need those files filled out properly with the Chinese translation.

Please let me know if you need any help with this! Thank you!

**Comment by waydabber** [comment]
I'll close this issue for now but please feel free to comment if there is any news on this or if you want to move forward with the translation for 3.0.0. Thank you!
