### ISSUE TITLE
Hiding OSD completly on LG HDR 4K 

### ISSUE THREAD

**Issue by hdsantos89** [MonitorControl/MonitorControl#462]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
After checking Hide OSD on Advanced Preferences for MonitorControl the Monitor's OSD still displays for a very short time

**To Reproduce**

1. On MonitorControl > Preferences > Advanced
2. Click Hide OSD
3. Press macOS volume control UP/DOWN keys

**Expected behavior**
To not display the monitor's native volume control slider at all

**Environment Information (please complete the following information):**

- macOS version: 11/4
- Mac model: MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports)
- MonitorControl version: 2.1.0
- Monitor(s): LG HDR 4k - vendor 0x1E6D - model 0x7750
- Apple Silicon/M1 (yes or no): no

**Comment by numbat77** [comment]
Same issue on my LG 34UM69G-B. It flickers on and off as I change the volume.

**Comment by dimitrij2k** [comment]
Same here with LG 32UN880…

**Comment by jmtakahashi** [comment]
Same here (after reverting from 2.2.0).

Environment Information (please complete the following information):

macOS version: 11.5
Mac model: MacBook Pro (13-inch, early 2015)
MonitorControl version: 2.1.0
Monitor(s): LG 34WL85C-B
Apple Silicon/M1 (yes or no): no

**Comment by jmtakahashi** [comment]
@hdsantos89 I would suggest changing the title to "Not Hiding the OSD Completely".  Your title suggests that Monitor Control IS hiding the OSD correctly, or it sounds like a Feature Request.

**Comment by waydabber** [comment]
Unfortunatelly this function is rather broken. It would be nice if it could be made to work properly. The implementation not only makes volume changes rather slow but results in a flickering monitor OSD (I have an LG UHD display myself). In the next version we'll have an option to disable the OS OSD instead and let the Display's OSD remain for those who don't like the two overlaying OSDs.

<img width="803" alt="Screen Shot 2021-08-17 at 11 03 56" src="https://user-images.githubusercontent.com/37590873/129696984-1f4a7a2d-e354-46c6-b934-f40614d480d3.png">

**Comment by waydabber** [comment]
I'll close this one since it is related to https://github.com/MonitorControl/MonitorControl/issues/480 in reverse. Since hiding the OSD cannot work properly due to hard technical limitations, the relevant option will work the other way around (disabling the macOS OSD). Hope this will suffice. Sorry about the fact that there is no better alternative though.
