### ISSUE TITLE
Some hope for DDC/CI support on Apple Silicon on macOS 12 beta

### ISSUE THREAD

**Issue by Kakise** [MonitorControl/MonitorControl#465]
**Checklist**

- [x] I have searched for existing issues

**Discussion**
I installed Lunar Pro on my Apple M1 mbp 13 with macOS 12 and discovered that Lunar supports hardware controls on my Asus VG24VQ (connected via DP on a TS3 Plus, Adaptive-Sync ON). Turns out that Apple re-added support for DDC/CI on their API. Yes, I did check that the brightness was changing and that it's not a fluke. No, I did not use software controls or a RPI server.

I checked monitor control to see if I'd have some luck with it, and, unlike previously, monitor control now shows my two screens (still unsupported though), my VG24VQ and my internal MBP screen, they still show as unsupported but it's a step towards the right direction.

My full setup:
VG24VQ connected to a TS3 Plus dock via DisplayPort, Standard mode, DDC/CI enabled in the monitor settings, connected to an M1 MBP13 w/ 16gb of ram, latest macOS 12 developer beta

**Comment by JoniVR** [comment]
Hi, please read #323, in short, we're aware of it :)

**Comment by Kakise** [comment]
> Hi, please read #323, in short, we're aware of it :)

Thank you very much ! Sorry for the dedup. Also my cat reacted with a confused emoji and I can't remove it lmao
