### ISSUE TITLE
Allow to specify manual shortcuts (e.g. F14 or F15)

### ISSUE THREAD

**Issue by aik099** [MonitorControl/MonitorControl#469]
**Checklist**

- [x] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**
I have 2 displays (built-in and external) and I want to control their brightness separately via the shortcut (Brightness Up/Down controls the built-in display, F14/F15 controls external display).

**Describe the solution you'd like**
Allow to manually specify shortcuts for brightness/volume increase/decrease actions as an alternative to using media keys.

**Describe alternatives you've considered**
I had to disable shortcuts completely and use the menubar icon of this app to change external monitor brightness.

P.S.
Might be related to #118, but not sure.

**Comment by waydabber** [comment]
This is an absolutely valid request. Full manual shortcut support is long overdue. @JoniVR is working on that I think. Hopefully we'll add this one soon. I agree that this seems to be the same as #118, so please follow that request (feel free to comment there!) to be informed about updates on this front. I'll close this one as a duplicate now. Thank you!
