### ISSUE TITLE
Dell DW 38 recognized, but not controllable - sliders disabled.

### ISSUE THREAD

**Issue by hstriepe** [MonitorControl/MonitorControl#470]
This is using the experimental M1 branch. I did a release build"

**Describe the bug**
- It does not recognize monitor plugged in after launch.
- Once connected with a relaunch it recognized a Dell DW38 Ultra Sharp Curved
- It lowered the contrast to a faint display.
- Brightness and volume controls were dimmed, so it could not be corrected.

**Comment by JoniVR** [comment]
Can you please reopen and fill in the template? Or copy paste it when clicking on opening the issue? The info in there is useful for identifying what could be the cause.
