### ISSUE TITLE
100% brightness in Monitorcontrol is only ~60% brightness on AW3821DW

### ISSUE THREAD

**Issue by timbiscuits** [MonitorControl/MonitorControl#471]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
100% brightness in Monitorcontrol is only ~60% brightness on AW3821DW.  OSD does not seem to update after changing brightness through Monitorcontrol so I'm not sure of an exact value.  I have Monitorian installed on my windows PC connected to the same monitor and it does not have this issue.

**Expected behavior**
100% brightness

- macOS version: 11.4
- MonitorControl version: 2.1.0/721
- Monitor(s): Dell AW3821DW
- Mac model: MacBook Pro 15 inch 2018
- Monitor Cable(s)/Connection(s): (e.g. DisplayPort) DP
- Apple Silicon/M1 (yes or no): No

**Comment by waydabber** [comment]
Hi, this is a valid issue and we plan to solve it in the following issue. Please follow that issue for updates! Thank you!

https://github.com/MonitorControl/MonitorControl/issues/310
