### ISSUE TITLE
MonitorControl not working with Dell S2721QS and 2018 Intel i7 Mac Mini over HDMI

### ISSUE THREAD

**Issue by troublecluster** [MonitorControl/MonitorControl#474]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
I just installed 2.1.0 for the very first time to use with a recently purchased Dell S2721QS paired with my 2018 i7 Mac Mini. I am connected using the built-in HDMI port on the Mac Mini and I have tried two different HDMI cables. Previously I was using an LG Ultrafine 4K via USB-C (the Apple partnered version) but decided to switch as I now need a monitor with multiple inputs and the LG was also ageing with panel discoloration.  

ddcctl also does not appear to change the Dell monitor's brightness or volume levels.

Example output when running ddcctl: 

./ddcctl -d 1 -b 30
D: CGDisplay C56F4C2B-23EE-A272-AC15-6A0B208F3BFF dispID(#724052430) (1920x1080 0°) HiDPI
I: found 1 external display
E: Failed to parse WindowServer's preferences! (/Library/Preferences/com.apple.windowserver.plist)
I: polling EDID for #1 (ID 724052430 => (null))
I: got edid.serial: JDB5M43
I: got edid.name: DELL S2721QS
D: action: b: 30
D: setting VCP control #16 => 30

**Expected behavior**
Brightness and Volume controls should change the monitor's state. 

**Screenshots**

**Additional context**
I also tried a USB-C hub (which included HDMI) from Satechi connected to one of the TB3/USB-C ports on the rear of the Mac Mini and I was able to control the brightness and volume. This shows that my cables appear to work and the monitor responds. This is not an ideal solution as the monitor is then limited to UHD @ 30fps with that hub. 

**Environment Information (please complete the following information):**

- macOS version: 11.4
- MonitorControl version: 2.1.0
- Monitor(s): Dell S2721QS
- Mac model: Mac Mini 2018 (Intel Core i7)
- Monitor Cable(s)/Connection(s): HDMI (I have tried the Dell supplied cable and a 2nd other brand cable)
- Apple Silicon/M1 (yes or no): No

**Comment by waydabber** [comment]
Unfortunatelly DDC control does not work through the HDMI port of the 2018 Intel Mac Mini. There is not much we can do about that at the moment. I recommend using USB-C to DisplayPort cable with this display for UHD 60Hz and DDC control.

For more information see: #102
