### ISSUE TITLE
Brightness & Volume Keys Don't work when MonitorControl menu bar is active

### ISSUE THREAD

**Issue by cryptoDevTrader** [MonitorControl/MonitorControl#475]
**Describe the bug**
When MonitorControl menu  bar is active, brightness & volume keys do not work as expected.

**To Reproduce**

1. Open MonitorControl
2. Click on MonitorControl in menu bar
3. Use brightness or volume control +/- buttons on the keyboard
4. Notice that brightness or volume is not changed and the sliders in the menu bar also don't change
5. Deactivate MonitorControl in menu bar by clicking elsewhere
6. Notice that the brightness or volume changes after deactivating MonitorControl

**Expected behavior**
I would expect that when using the brightness or volume keys that the change would be made on the monitor as well as reflected in the slider.

- macOS version: 10.5
- Mac model: MacBook Air M1
- MonitorControl version: experimental/apple-silicon branch
- Monitor(s): LG 49WL95C-WE via USB-C
- Apple Silicon/M1 (yes or no): yes

**Comment by waydabber** [comment]
Hi, I made a change that should fix this (and hopefully does not break other things :)). This will be in the next release.

**Comment by waydabber** [comment]
Hi, we have relased the [3.0.0 version](https://github.com/MonitorControl/MonitorControl/releases/tag/v3.0.0-rc1). Could you please test if this issue is resolved and report back? Thank you!

**Comment by waydabber** [comment]
I'll close this one since it should be solved. If there is any issue with this, please feel free to comment and ask for a reopen! Thank you!
