### ISSUE TITLE
3.0.0-beta2 not working on Intel Mac with Mojave

### ISSUE THREAD

**Issue by choongng** [MonitorControl/MonitorControl#484]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
In 3.0.0-beta2 keys show OSD and the brightness slider updates accordingly however the display's actual brightness does not change. 2.1.0 works perfectly. Nothing obvious in system logs. Happy to more diagnostics if it's helpful.

**Environment Information (please complete the following information):**

- macOS 10.14.6 (18G9323)
- MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports) (MacBookPro14,1)
- Philips PHL 272P7VU (connected via DisplayPort to internal Intel graphics, lid is closed)

**Comment by JoniVR** [comment]
Correct. There’s an issue in V2.2.0 and 3.0.0, I’ve added a note about it in the release notes 😉 see #478
