### ISSUE TITLE
Standby block function. Restarting App helps...

### ISSUE THREAD

**Issue by dimitrij2k** [MonitorControl/MonitorControl#485]
**Checklist**
- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
After Standby, monitor Control don't work. After restart the App, it works again!
**Update: It work most times, but sometimes I have to restart the app. Maybe not an App Bug!**

- macOS version: 11/5
- Mac model: MacBook Air (2021)
- MonitorControl version: 3.0.0-b1
- Monitor(s): LG 32UN880
- Apple Silicon/M1 (yes or no): yes

**Comment by JoniVR** [comment]
Did you try 3.0.0-b2? Also, if it does still persist on beta 2, please repost it in the release discussion linked on the release page :)
