### ISSUE TITLE
Semi-opaque black overlay as fallback for unsupported setups

### ISSUE THREAD

**Issue by fl034** [MonitorControl/MonitorControl#489]
**Checklist**

- [X] I have searched for existing issues

**Is your feature request related to a problem? Please describe.**
I have an unsupported monitor setup, but want to control brightness via MonitorControl.

**Describe the solution you'd like**
MonitorControl could implement a something like a generic display that can be added which does change brightness software-side via a black rectangle being drawn over the whole screen. 
Increasing brightness of the monitor will decrease alpha of the black overlay and vice versa.

I know this is not a pretty solution, but may be good as interim solution for some people.

**Comment by waydabber** [comment]
Hey, the latest beta6 has this option. However it activates only if MonitorControl deems your display uncontrollable - if it thinks it can be controlled, but in reality cannot, then it will not activate. We should probably add an option to force software mode.

**Comment by waydabber** [comment]
Hey in the next beta if you have 'Fallback to software' enabled and tick off the 'DDC' checkbox under Displays the app will control the brightness using software (colorsync gamma table) dimming.

**Comment by waydabber** [comment]
This now incorporated into 3.0.0-beta8. If there is anything wrong please let me know!

https://github.com/MonitorControl/MonitorControl/releases/tag/v3.0.0-beta8

**Comment by fl034** [comment]
Awesome :) gonna try it soon

**Comment by fl034** [comment]
It's working as expected in v3.0.0-beta8 🎉
