### ISSUE TITLE
Clicking point on slider does not change brightness

### ISSUE THREAD

**Issue by jacobgelling** [MonitorControl/MonitorControl#493]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
You cannot change the brightness by clicking a point on the slider - it visually changes position but the brightness does not change.

The brightness of the monitor only changes when you click and drag the slider.

**To Reproduce**
1. Click on the MonitorControl menu bar icon
2. Click on a point on the brightness slider
3. See the brightness of the monitor has not changed

**Expected behavior**
The brightness of the monitor should be adjusted.

**Screenshots**
![Screenshot 2021-07-31 at 19 08 13](https://user-images.githubusercontent.com/3254275/127747397-3e268280-f2e5-4e6c-88a0-7909dbaffdab.png)
So clicking where the red arrow is pointing changes the position of the slider dot, but does not change the brightness of the monitor. Only when clicking and sliding does the monitor brightness change.

**Environment Information (please complete the following information):**

- macOS version: 11.5.1
- Mac model: MacBook Pro (13-inch, 2020)
- MonitorControl version: 2.2.0 (Build 947)
- Monitor(s): Dell U2721DE
- Apple Silicon/M1 (yes or no): no

**Comment by JoniVR** [comment]
This is related to #478, basically, there's an issue right now where ddc commands on Intel will only succeed when spammed a few times, which is why it's working while sliding but not when clicking (sending multiple times vs only once)
