### ISSUE TITLE
ASUS VG289Q1A detected but not supported

### ISSUE THREAD

**Issue by Agusum** [MonitorControl/MonitorControl#495]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
The ASUS VG289Q1A monitor is detected but brightness and volume doesn't change when moving the sliders or using the keyboard.

**To Reproduce**

1. Click on MonitorControl in the menu bar
2. Move sliders up or down

Sliders are greyed out and even when moving them up or down it doesn't change the brightness nor volume of the display.

**Expected behavior**
Volume and brightness adjusted

**Screenshots**
https://imgur.com/a/gNyGlQL

**Additional context**

**Environment Information (please complete the following information):**

- macOS version: macOS 11.5.1
- Mac model: MacBook Pro 15-inch 2018
- MonitorControl version: 2.2.0 (Build 947)
- Monitor(s): ASUS VG289Q1A
- Apple Silicon/M1 (yes or no): No

**Comment by waydabber** [comment]
Hi @Agusum 

2.2.0 was pulled due to various issues. Do you have this problem with 2.1.0 or the latest 3.0.0 beta? Thank you!

**Comment by Agusum** [comment]
I updated to 3.0.0 beta 8 and it is still not working: https://imgur.com/a/IzTxgPy. Thanks for looking into it!

**Comment by waydabber** [comment]
Hi Agusum. The fact that the sliders are grayed out is normal (this is the standard Apple designed look of the sliders in dark mode in Big Sur and Monterey, it does not mean that they are disabled).

What you should try is whether using a different tool, can you control brightness or volume? If not, then it's probably a monitor issue and we can't do much about it. Please see the instructions here:

https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting

Thank you!

**Comment by Agusum** [comment]
I tried doing that when I got the monitor and raised [an issue](https://github.com/kfix/ddcctl/issues/111) in the ddcctl repo but I don't know if the error I get is because my monitor doesn't support it or because there's a bug in the software. Would you know based on the error message I get?

Thanks!

**Comment by waydabber** [comment]
I think something is wrong there then. I see that you are using a dock. Can you try it directly?

**Comment by Agusum** [comment]
I did that now with an old MacBook Pro that has an HDMI port (I don't have a HDMI to USB-C cable for the 15" atm) and MonitorControl works fine. Any idea how I can make it work with the dock or how to know which docks are compatible?

**Comment by waydabber** [comment]
This dock uses DisplayLink [which does not support DDC at all on mac](https://support.displaylink.com/forums/287786-displaylink-feature-suggestions/suggestions/16135240-add-brightness-support-to-non-windows-oses) and is more like a virtual display. You'll need a dock that routes the native displayport stream to the display. Such USB-C docks are available but they have USB2 only (because of bandwidth limitations), or there might be some more expensive Thunderbolt docks. The main thing is to avoid anything that has the DisplayLink logo or name in its product description.

I'll close this issue for now. Best of luck and thanks for the feedback!

**Comment by Agusum** [comment]
Thanks for the info @waydabber! How did you know the dock uses DisplayLink? I don't see any description of it nor the logo in the Amazon page.

**Comment by waydabber** [comment]
I found it somewhere (probably on the US amazon site). But every dock that is simple USB-C and has multiple display outputs or claims USB3 or gigabit lan while still providing 4K-60Hz out can only be displaylink (it uses a compressed USB video basically).

You can also try 3.0.0 and see if it reports the display controllable or as unsupported/virtual display.
