### ISSUE TITLE
LG UL850 2.2.0 and 3.0.0 invalid

### ISSUE THREAD

**Issue by tlerbao** [MonitorControl/MonitorControl#496]
LG UL850 DP

Version 2.1.0 can be used without problems.

2.2.0 and 3.0.0 After pressing the shortcut keys, there will be macos volume and brightness icons on the screen, but the volume and brightness are not actually changed.

**Comment by PhilippSalvisberg** [comment]
I have the same experience. 

Volume cannot be changed with version v2.2.0 and v3.3.0 anymore. No problems when using v2.1.0. 

My monitor is a Samsung C49J890DKU.

Thanks for this great utility.

**Comment by Brenndoerfer** [comment]
Same issue as Philipp with v2.2.0 with my `LG 43UN700-B 43`

**Comment by JoniVR** [comment]
See #478
