### ISSUE TITLE
Brightness change responsiveness via wireless Magic Keyboard is unreliable

### ISSUE THREAD

**Issue by jamesg311** [MonitorControl/MonitorControl#497]
**Checklist**

- [X] I have searched for existing issues
- [X] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] I have updated MonitorControl to the latest version

**Describe the bug**
The keyboard presses for brightness either A) don't work at all, or B) when they do work, they are delayed by a couple hundred milliseconds before the change occurs and is not responsive to a single press, only multiple presses appear to be processed after some time. However, when I slide the slider in the Menu Bar, the brightness changes accordingly; immediately and smoothly.

**To Reproduce**
1. Click brightness up or down on Magic Keyboard

**Expected behavior**
Brightness should change incrementally and with a quick response rate.

**Screenshots**
N/A

**Additional context**
N/A

**Environment Information (please complete the following information):**

- macOS version: 11.5.1
- Mac model: 2019 MacBook Pro 13" w/ TouchBar Intel i7
- MonitorControl version: 2.2.0 (Build 947)
- Monitor(s): BenQ PD3220U
- Apple Silicon/M1 (yes or no): No

**Comment by JoniVR** [comment]
See #478
