### ISSUE TITLE
CI & Automatic Updates

### ISSUE THREAD

**Issue by the0neyouseek** [MonitorControl/MonitorControl#5]
This issue is to simplify the debug and release process :

- [ ] Add a ci service to compile and deploy the new releases to github.
- [ ] Add an auto-update feature (with options to enable/disable the auto check for new releases) with something like [@macmade/GitHubUpdates](https://github.com/macmade/GitHubUpdates)

**Comment by JoniVR** [comment]
I think an auto-update feature would be awesome! 
I can look into implementing this if you want. 

I'd suggest the following things to be in there:
* Automatically look for updates on app launch
* Add a button "Check for updates..." to the menulet
* Add a setting to enable/disable checking for updates on launch

Is there a specific CI service you'd prefer? 
I'm personally only experienced with TravisCI but I'm fine with whatever.

**Comment by the0neyouseek** [comment]
@JoniVR Hi,
I've used CircleCI which works great with macOS/iOS but anything is fine for me (We could also add a bagde to the readme)

For automatic updates I've found this :
- https://github.com/macmade/GitHubUpdates
- https://github.com/sparkle-project/Sparkle

**Comment by JoniVR** [comment]
> I've used CircleCI which works great with macOS/iOS but anything is fine for me

CircleCI seems to be the more populair choice these days yes. I'm fine with that.

> (We could also add a badge to the readme)

Yup, would be useful. 



> For automatic updates I've found this :
> 
> * https://github.com/macmade/GitHubUpdates
> * https://github.com/sparkle-project/Sparkle

I wasn't aware of GitHubUpdates before, I've seen Sparkle before. I think Sparkle is generally more used and more supported, however, it looks like GitHubUpdates seems a lot easier to implement. So I'm not sure, I found a [nice article](https://yiqiu.me/2015/11/19/sparkle-update-on-github/) on using sparkle with github though.

**Comment by the0neyouseek** [comment]
I also think that Sparkle is the safe bet here as GithubUpdates doesn't seem maintained 👍

**Comment by JoniVR** [comment]
For the CI part, if/when we get to it, Github CI seems to be pretty good now from my experience, maybe that would be a better option now?

**Comment by the0neyouseek** [comment]
💯% agree with that

Le jeu. 2 avr. 2020 à 14:53, Joni Van Roost <notifications@github.com> a
écrit :

**Comment by waydabber** [comment]
I added sparkle 2 for updates.

**Comment by the0neyouseek** [comment]
@waydabber Did you find a way to auto-generate the AppCast xml file ?

**Comment by waydabber** [comment]
Nope, I just added the app side of the things but did not work on automation at all so there is room for improvement. :)

**Comment by waydabber** [comment]
But as far as I see the appcast xml can easily be edited manually so we could put together a script that automates everything from signing to publishing. But since I could not even apply for an Apple developer membership (somehow my application failed instantly after I enrolled and I should 'contact Apple' but the form offered is broken), I can't even sign or notarize the app so I have hard time trying out the whole process. I hope you or @JoniVR will help. It would be  nice if 4.0.0 betas and then stable versions could auto-update (I recommend having a separate beta and stable appcast channel).

**Comment by the0neyouseek** [comment]
@waydabber I was planning on adapting this script I found :
https://github.com/lwouis/alt-tab-macos/blob/master/scripts/update_appcast.sh

For signing @JoniVR could you invite @waydabber and I to your development team in appstoreconnect ? This would allow us to sign and notarize the app I think

**Comment by waydabber** [comment]
Nice, a script like that would work nicely with the appcast. It would be really great if there were be a simple scripted process to build and publish the app, both as pre-release and release!

**Comment by the0neyouseek** [comment]
We could use [Fastlane](https://github.com/fastlane/fastlane) for that

**Comment by JoniVR** [comment]
> For signing @JoniVR could you invite @waydabber and I to your development team in [App Store Connect](https://appstoreconnect.apple.com/access/users) ? This would allow us to sign and notarize the app I think

IIRC from my work place, an organisational account requires a D.U.N.S number, which requires a legal entity, not sure though. See:
https://developer.apple.com/programs/enroll/

I'd be happy to help with everything else. I agree Sparkle is pretty important.

**Comment by the0neyouseek** [comment]
@JoniVR Can you not add users to your personal account (if that's what you use to sign) and restrict access using roles ?

**Comment by JoniVR** [comment]
I think I might be able to do it through App Store connect, judging by:
https://help.apple.com/developer-account/#/dev3e8818774

That would require registering the bundle identifier in App Store Connect though. I'll look into it.

**Comment by JoniVR** [comment]
Reopened because I want to keep this visible until we get it all up-and-running if you don't mind.

**Comment by JoniVR** [comment]
> Nice, a script like that would work nicely with the appcast. It would be really great if there were be a simple scripted process to build and publish the app, both as pre-release and release!

Theoretically, We should be able to create a Github workflow that will be triggered when creating a tag, and then make it create a release based on that, updating appcast etc, but that might be quite a lot of work. Good news is that Apple created a better tool for signing and notarising this year, still have to look into that too.

**Comment by waydabber** [comment]
> Reopened because I want to keep this visible until we get it all up-and-running if you don't mind.

Yes of course, I just bulk closed all with the done tag.

**Comment by waydabber** [comment]
sidenote - here are some ideas and existing solutions to make Sparkle work from GitHub:

https://github.com/sparkle-project/Sparkle/issues/648

**Comment by JoniVR** [comment]
Notes on current sparkle to-do (for tracking purposes, step-by-step):

- [x] Manual implementation using appcast.xml inside /docs folder[^1]
- [ ] Automation of appcast update through ci workflow (detect when release is created and update appcast.xml through CI) -> store version etc in xcconfig file.
- [ ] Automation of the rest of the signing, notarisation & deployment process, trigger through git tag?

[^1]: This is using the `github-pages` branch, don't remove this branch for now as we'll use it to update the `appcast.xml` without Pull Requests for releases.
