### ISSUE TITLE
The software is not working on Big Sur 11.5.1 with Monitor ASUS VA325

### ISSUE THREAD

**Issue by chenzhendong** [MonitorControl/MonitorControl#501]
**Checklist**

- [ x ] I have searched for existing issues
- [ x ] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [ x ] I have updated MonitorControl to the latest version

**Describe the bug**
Screen turn black and lose both sound and image

**To Reproduce**
Install with the 
 brew install --cask monitorcontrol
 Downloading https://github.com/MonitorControl/MonitorControl/releases/download/v2.2.0/MonitorControl.2.2.0.dmg
And configure the permisson allow app change system
Run Find and type in monitorcontrol to run

**Expected behavior**
It could control the volume and lightness of monitor

**Screenshots**

**Additional context**

**Environment Information (please complete the following information):**

- macOS version: Big Sur 11.5.1 
- Mac model: MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports) 2.4 GHz Quad-Core Intel Core i5
- MonitorControl version:
- Monitor(s): ASUS VA325 with HDMI
- Apple Silicon/M1 (yes or no): no

**Comment by waydabber** [comment]
Hi @chenzhendong - the v2.2.0 was pulled due to various issues. Do you have this with 2.1.0 or 3.0.0 as well? Thanks!

**Comment by waydabber** [comment]
I'll close this issue for now but please feel free to comment if there is anything we can do. If the issue persists, we can reopen this issue! Thank you!

**Comment by govindrai** [comment]
I just had this issue after downloading the app. It recognized both of my HP E243 displays and then i adjusted one of the displays to 0. Now it won't come back on!! It won't recognize the signal even after pulling out the cord, as if it's bricked! 

![image](https://user-images.githubusercontent.com/13859249/168736467-6b92d69c-3caa-4952-873b-b19b8126c85b.png)

**Comment by govindrai** [comment]
after unplugging my monitor and unplugging my computer, my screen is responding to input signal again.
