### ISSUE TITLE
MonitorControl Not detected by Sound Preference

### ISSUE THREAD

**Issue by vincbeaulieu** [MonitorControl/MonitorControl#503]
The control using the keyboard is working. However, volume output is kept constant no matter what volume setting is chosen. Also, the app doesn't display in sound preferences as an output.

System:
Mac Big Sur 11.5
Macbook Pro 2014, 13 inch

**Comment by JoniVR** [comment]
Are you on v2.2.0? If you are, please either revert to v2.1.0 or use v3.0.0-beta4. If otherwise, please reopen and fill out the template ;)
