### ISSUE TITLE
MonitorControl Not detected by Sound Preference (Beta 3.0.0)

### ISSUE THREAD

**Issue by vincbeaulieu** [MonitorControl/MonitorControl#504]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**

The control using the keyboard is working. However, volume output is kept constant no matter what volume setting is chosen. Also, the app doesn't display in sound preferences as an output.

**To Reproduce**

1. Download the latest version (beta 3.0.0)
2. Launch the app
3. Go to Sound Preferences in System Preferences
4. The App is not listed
5. Click on Name:Samsung Type:HDMI (for testing)
6. Test volume control on keyboard
7. Volume indicator on monitor screen is increasing/decreasing, but volume output is kept constant, even when mute is enable.

**Expected behavior**

Volume indicator on screen is increasing/decreasing, and volume output is increasing/decreasing respectively.

**Screenshots**

<img width="228" alt="Screen Shot 2021-08-06 at 01 20 02" src="https://user-images.githubusercontent.com/37360448/128460103-f028b5d5-621f-4f98-96c8-389aac70d23e.png">

Figure above shows the "Volume indicator" which appears on my monitor. Sounds is being heard, but volume output is kept constant even when mute is enable.

**Additional context**

Problem occurs on all port: HDMI and both thunderbolt (thunder-both port are used with a mini-dp to HDMI adaptor).
The monitor is a SAMSUNG M7

**Environment Information (please complete the following information):**

- macOS version: Big Sur 11.5
- Mac model: Macbook Pro Retina mid-2014
- MonitorControl version: Beta 3.0.0.
- Monitor(s): Samsung M7
- Apple Silicon/M1 (yes or no): no (intel i5)

**Comment by JoniVR** [comment]
Hi, the app is not supposed to show up in your system preferences. It's a toolbar icon that you can then open or just control the monitor through shortcuts.
![image](https://user-images.githubusercontent.com/7591717/128600903-51972656-587a-4760-8466-685b7f606b19.png)
The app automatically controls the default selected output, so you need to set your monitor as the default sound output for it to work. 


Furthermore, what you are describing vaguely resembles #505. 

Can you try v2.1.0 and let me know if that version works for you?

**Comment by vevek** [comment]
@JoniVR Both brightness & sound controls were not working for me on v2.2 (on brew). After installing v2.1, brightness controls works as per normal but sound controls don't seem to work despite selecting Monitor for audio out.

**Comment by waydabber** [comment]
@vincbeaulieu, Since the original question was answered and the v2.2 was pulled meanwhile, I'll close this issue for now. If there is anything else to do, please let us know! Thanks!
