### ISSUE TITLE
Stopped working on Dell UP3017 on MBP16 since v2.2.0

### ISSUE THREAD

**Issue by anbroid** [MonitorControl/MonitorControl#505]
**Describe the bug**
monitorcontrol has been working great on my MBP16 on Catalina and later Big Sur and my Dell UP3017 monitor. I had installed it with brew. Yesterday I did brew update and it installed v2.2.0. The sliders seem grayed out however I can move them, but they do nothing. Only occasionally, if you move them around a lot, a change in brightness might register. I tried different polling settings etc to no avail. I then tried the v3.0.0 betas and they behaved the same way. I then installed the v2.1.0 dmg which works flawlessly.

**To Reproduce**
1. Install v2.2.0 (or later release)
2. Move the brightness slider around

**Expected behavior**
I expect to see change in brightness on my monitor, but it doesn't happen.

**Environment Information (please complete the following information):**

- macOS version: 11.5.0
- Mac model: 2019 Macbook Pro 16
- MonitorControl version: v2.2.0
- Monitor(s): Dell UP3017 (HDMI connected via StarTech DKT30CHCPD adapter)
- Apple Silicon/M1 (yes or no): no

**Comment by JoniVR** [comment]
See #478 🙂

**Comment by anbroid** [comment]
@JoniVR this is not #478, I'm not using function keys; I am moving the sliders with my mouse but they do nothing. Only rarely will I see a change in brightness actually happen as I move them.

**Comment by JoniVR** [comment]
Your best bet is following the steps in the linked thread for brew. 

I've been thinking about deleting 2.2.0 altogether but I'm not sure if that'd help brew users. 

I'm still thinking it's the same issue though.. have you tried 3.0.0 beta 4? It helps alleviate it a bit for some people. If it's unrelated I'll reopen it but for now I think it's probably the same issue..

**Comment by anbroid** [comment]
Yes, I tried v3.0.0-beta4 and it has the same, very intermittent behavior, it's hit or miss, as in 5% hit, 95% miss :-) . v2.1.0 is flawless: clicking or dragging the sliders changes the brightness immediately. Running ddcctl on the terminal always works (it's my last resort). I don't mind following #478 if it will fix the problem, although that one focuses on function key behavior and states moving sliders with the mouse in the menu works fine which is not the case for me. I guess I'm seeing what's reported reported in #238. Thank you for looking into this, and for a really great utility!

**Comment by JoniVR** [comment]
Yeah sliders worked but that was only because the slider move basically spams it, your specific config might be even more sensitive to it. 

I'm not sure what the issue is yet but I plan on either fixing it in DDC.swift or just swapping out the entire implementation soon anyways so hopefully that'll fix your issue too. If it still works intermittently then I hope that'll fix it for you, if it doesn't then feel free to reopen or create a new issue 🙂
