### ISSUE TITLE
Crash on startup on macOS 10.14.6 (3.0.0-beta5)

### ISSUE THREAD

**Issue by cpcallen** [MonitorControl/MonitorControl#508]
**Checklist**

- [X] I have searched for existing issues
- [X] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] I have updated MonitorControl to the latest version

**Describe the bug**
MonitorControl 3.0.0-beta5 crashes on startup on macOS 10.14.6 100% of the time.

**To Reproduce**

1. Go to Applications/
2. Double click on MonitorControl
3. Observe icon-opening animation

**Expected behaviour**
MonitorControl starts, and creates a new menu in the menu bar.

** Actual behaviour**
Nothing else is observed to happen—not even an error dialog—but a new entry is created in `~/⁨Library/Logs/⁨DiagnosticReports⁩/`.

**Additional context**
I tried starting MonitorControl several times but every occasion failed in the same way.

Excerpt from [MonitorControl_2021-08-09-162610_Hal.crash.gz](https://github.com/MonitorControl/MonitorControl/files/6955646/MonitorControl_2021-08-09-162610_Hal.crash.gz):

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: _CoreDisplay_DisplayCreateInfoDictionary
  Referenced from: /Applications/MonitorControl.app/Contents/MacOS/MonitorControl
  Expected in: /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
```

**Environment Information (please complete the following information):**

- macOS version: 10.14.6
- Mac model: MacBook Pro (Retina, 13-inch, Early 2015) ("MacBookPro12,1")
- MonitorControl version: 3.0.0-beta5
- Monitor(s): Built-in only or built-in + Apple Thunderbolt Display
- Apple Silicon/M1 (yes or no): no

**Comment by JoniVR** [comment]
Thanks for the detailed info!

**Comment by JoniVR** [comment]
Can you try on beta 6 and let us know if it helps?

**Comment by cpcallen** [comment]
Beta 6 appears to work properly, except for not fixing #212.
