### ISSUE TITLE
Dell U2414H Monitor not supported (M1 Beta) 

### ISSUE THREAD

**Issue by F3000** [MonitorControl/MonitorControl#510]
**Checklist**

- [ x] I have searched for existing issues
- [ x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [ x] I have updated MonitorControl to the latest version

**Describe the bug**
The above monitor is recognized . The App cant control him . 

**Expected behavior**

Adjust the Monitor . 

**Screenshots**

<img width="725" alt="Bildschirmfoto 2021-08-11 um 23 59 22" src="https://user-images.githubusercontent.com/8161283/129109245-913dada6-04c6-47a3-94d3-c50c4df7d32a.png">

**Additional context**

**Environment Information (please complete the following information):**

- macOS version: 11.4
- Mac model: MacBook Air M1
- MonitorControl version: Beta 3
- Monitor(s): Dell U2414H
- Apple Silicon/M1 (yes or no): yes

**Comment by JoniVR** [comment]
Can you try beta 7 and report if it's working better?

**Comment by waydabber** [comment]
Hmm. I think the Dell 2414H is connected via a DisplayLink dock as M1 MBAs don't support two external displays and the display ID will never be 3 for native devices on M1.

Unfortunatelly DisplayLink does not support DDC on Mac.

**Comment by waydabber** [comment]
@F3000 I close this now. Please let me know if you have anything to add though! Thanks!
