### ISSUE TITLE
The software fails after the computer sleeps and must be restarted to take effect

### ISSUE THREAD

**Issue by xzsaqe** [MonitorControl/MonitorControl#513]
The software fails after the computer sleeps and must be restarted to take effect. There is a probability that the monitor will be bright and flickering when the monitor wakes up with a shortcut key to adjust the brightness
PS:
macOS Big Sur 11.5.1
Apple M1 MacBook Air
MonitorControl v3.0.0-beta6
AOC U2701B

**Comment by JoniVR** [comment]
Can you please try beta 7 and report in #515 if you still have issues?
