### ISSUE TITLE
localization-Chinese-Taiwan in v3.0.0 RC1

### ISSUE THREAD

**Issue by ting10688** [MonitorControl/MonitorControl#528]
### Before opening the issue, have you...?

- [x] Searched for existing issues

### Discussion

I try my best to translate it into Chinese in v3.0.0 RC1

[zh-tw.lproj.zip](https://github.com/MonitorControl/MonitorControl/files/7027131/zh-tw.lproj.zip)

**Comment by waydabber** [comment]
Thanks, I'll add the localization in the next version.

Question: is Chinese-Taiwan the same as Chinese translation? Are there differences in the language?

_Thank you and hope this question is not sensitive as I know there are some geopolitical disputes._

**Comment by JoniVR** [comment]
I think when adding it to the project, we can use this one:
![image](https://user-images.githubusercontent.com/7591717/130354579-f33b7266-784c-47d5-8aaf-139f54bd9e60.png)

**Comment by waydabber** [comment]
Wow I see, right! So many Chinese options. :) We'll do that!

**Comment by waydabber** [comment]
@ting10688 - I noticed that some minor things like "Yes", "No" are not translated but remained English. Is that ok or just an oversight?

**Comment by ting10688** [comment]
> @ting10688 - 我注意到諸如“是”、“否”之類的一些小東西沒有被翻譯，但仍然是英文。這是可以的還是只是一個疏忽？

It won’t be a big problem for me, but I still fixed it.

[zh-tw.lproj.zip](https://github.com/MonitorControl/MonitorControl/files/7027329/zh-tw.lproj.zip)

**Comment by ting10688** [comment]
Made a small modification.

[zh-tw.lproj.zip](https://github.com/MonitorControl/MonitorControl/files/7027764/zh-tw.lproj.zip)

**Comment by waydabber** [comment]
Thanks @ting10688, I added the files, here is the pull request: https://github.com/MonitorControl/MonitorControl/pull/538

**Comment by waydabber** [comment]
This was added to the master branch. I'll close this issue now. Thank you!
