### ISSUE TITLE
External monitor input source switching

### ISSUE THREAD

**Issue by Romaxx** [MonitorControl/MonitorControl#543]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

It could be useful to have input source switching function on current screen, currently I use command line solution with [https://github.com/kfix/ddcctl](https://github.com/kfix/ddcctl) (with command ddcctl -d 1 -i 17) to switch from USB-C to HDMI input on a DELL monitor.

### Describe the solution you'd like

it could be great to have a menu button or a shortcut to switch the input of the current screen.

### Describe alternatives you've considered

multiple input source shortcut could be implemented [https://github.com/kfix/ddcctl#input-sources](https://github.com/kfix/ddcctl#input-sources)

**Comment by JoniVR** [comment]
Hi!

We've had an issue like this before, to me this is a bit out of scope. 

I'm sure there are plenty of utilities that you can use to bind a shortcut to a cli command, if that helps. 

Custom shortcuts is on the roadmap but probably not happening soon, so I think you're going to be faster off looking for a third party shortcut tool for this even if we were to support it in the future.

**Comment by waydabber** [comment]
I agree with @JoniVR. There were/are several requests for more arcane DDC controls that are typically out of scope for MonitorControl. I think the best approach is to have an option to enable 'Advanced controls' menu under the display where we can put all kind of stuff like this in the future. DDC input change can be added in this menu as well. This is already planned in this issue: https://github.com/MonitorControl/MonitorControl/issues/524 (see the `DDC Display Input` item)

I'll close this issue for now but feel free to comment in the other thread! Thank you!
