### ISSUE TITLE
Could be possible to turn off the monitor from the MonitorControl menu?

### ISSUE THREAD

**Issue by ellipticaldoor** [MonitorControl/MonitorControl#545]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

It's annoying to have to reach the monitor hidden button tu turn it off

### Describe the solution you'd like

I will like an option above preferences to turn off the monitor

### Describe alternatives you've considered

No alternatives

**Comment by waydabber** [comment]
Well, some displays support power mode 0xD6 command and has the ability to turn itself off if 0x5 is set as a value. This is not universal however. I now added this into the wishlist of planned advanced control options in this issue: https://github.com/MonitorControl/MonitorControl/issues/524

Please feel free to comment in that issue and track its progress. I'll close this one so we don't have a duplicate. Thank you!
