### ISSUE TITLE
100% isnt 100% reset default

### ISSUE THREAD

**Issue by fboulegue** [MonitorControl/MonitorControl#548]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Hey I did install the software turned the screen down and back to 100% but its not full light up (huawai MateView) anyway to reset it to default?

### Steps to reproduce

turn down screen light turn back on

### Expected behavior

should go back to 100%

### Environment Information (please complete the following information)

```markdown
- macOS version:
- Mac model:
- MonitorControl version:
- Monitor(s):
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment]
I'll close this issue since the core problem will be solved in #310. But please feel free to comment anyway or let me know if you need any further help with this! Thank you!
