### ISSUE TITLE
Function to disable an external monitor

### ISSUE THREAD

**Issue by McSpitz** [MonitorControl/MonitorControl#556]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

I am searching for a solution to disable an external monitor

### Describe the solution you'd like

I would like to switch off an external display

### Describe alternatives you've considered

did not found alternatives

**Comment by waydabber** [comment]
If you mean power control, then this is a planned advanced feature (DDC power control might work if the display supports it - https://github.com/MonitorControl/MonitorControl/issues/524). You can try ddcctl as well https://github.com/kfix/ddcctl as you can send power control signals with that utility.

If you mean disabling an external display without turning it off, then there are some tools for that (https://github.com/Eun/DisableMonitor), but this is not something we plan to add to MonitorControl.

**Comment by waydabber** [comment]
Hey, I'll close this issue but please let me know if I can be of any more help on this! Be sure to follow #524 to see if there is a progress on that and also try if ddcctl works (to see if your display is supported or not - note that ddcctl works on Intel only).
