### ISSUE TITLE
I turned on something and everything broke =)

### ISSUE THREAD

**Issue by doi7ing** [MonitorControl/MonitorControl#560]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Question

Good day.
First:
Thank you for your work! This program is very much needed by the entire community!
My system
- macOS version: 11.5.2
- Mac model: Mac mini (M1, 2020)
- MonitorControl version: 3.0.0
- Monitor(s): Philips 244E, AOC 22E1W
- Apple Silicon/M1 (yes or no): yes

I was very happy that you released a new version, downloaded it, installed it, if it doesn’t change my memory, then I turned on DDC and the application hung, and even deleting it via maccleaner does not help to return the application to a working state.

Please tell me how to reset all the settings of your application (that is, what files does it change or create and where) to return everything as it was before?

**Comment by JoniVR** [comment]
I can help with this one! When opening the app, hold down shift, it will launch in safe mode and will let you change the settings. This was recently added by @waydabber in 3.0.0 RC2 :)

**Comment by JoniVR** [comment]
Once you're in safe mode you can always try resetting the preferences in the General settings tab, but honestly it sounds like just disabling DDC should do the trick.

**Comment by doi7ing** [comment]
Thx mate its done=)

**Comment by doi7ing** [comment]
Thanks again =) after some manipulation, by trial and error, I found how to configure so that both monitors respond to control and the application does not freeze.

**Comment by JoniVR** [comment]
Good to hear, you might want to try setting Polling Mode to "None" in advanced settings and see if that helps resolve the issue while still having DDC enabled. You might have already tried this, just figured I'd mention it :)

**Comment by doi7ing** [comment]
Thanks, I tried it, it began to be controlled differently, but the application stopped freezing. while I turned it off in the future, I'll see if I can play with the settings again =)

**Comment by electrovir** [comment]
This feature was pretty hard to find. I spent a while searching through issues to find this after setting a DDC max value that insta-crashed the app on every launch 😅
