### ISSUE TITLE
Keyboard shortcut to change external display only

### ISSUE THREAD

**Issue by avichou** [MonitorControl/MonitorControl#563]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

impossibilty to change external display brightness only

### Describe the solution you'd like

im extremely thankful of being able to use ddc on m1 now !

just wanted to submit an idea which i am suprised not to see implemented yet:

using a custom shortcut ,whatever it be ,to control external display brightness only ,while keeping macbook display at the same brightness (in my case 0 nits/off )

### Describe alternatives you've considered

im extremely thankful of being able to use ddc on m1 now !

just wanted to submit an idea which i am suprised not to see implemented yet:

using a custom shortcut ,whatever it be ,to control external display brightness only ,while keeping macbook display at the same brightness (in my case 0 nits/off )

**Comment by waydabber** [comment]
There is a shortcut to change brightness for the internal display only (ctrl+brightness), we could add an other that does this in reverse and change external displays only (shift+ctrl+brightness).

**Comment by avichou** [comment]
> There is a shortcut to change brightness for the internal display only (ctrl+brightness), we could add an other that does this in reverse and change external displays only (shift+ctrl+brightness).

thanks that would be awesome !! also yes my syntax sucks ahaha

**Comment by waydabber** [comment]
I added this to 3.1.0. There is an unsigned interim version [here to test](https://www.dropbox.com/s/w1md5rjyll0lsyo/MonitorControl.zip?dl=0).

**Comment by avichou** [comment]
> I added this to 3.1.0. There is an unsigned interim version [here to test](https://www.dropbox.com/s/w1md5rjyll0lsyo/MonitorControl.zip?dl=0).
> 
> Update: the shortcut is now changed to **ctrl+command+brightness** (shift+ctrl+brightness was colliding with fine control if somebody wants to control internal display only)

works wonders,amazing ! i assume it'll be released as stable or at least beta ,within the next couple of days right?

thanks again and have a good day!

**Comment by waydabber** [comment]
We don't have an exact timetable, but surely we'll release it eventually. :)

**Comment by Converseallstar95** [comment]
Thanks for this suggestion I was just looking for it as a new MonitorControl user!

I just switched away from my two Thunderbolt Displays and they worked as follows, if I pressed the volume or brightness keys on my wireless keyboard, they only changed the external monitor. If I pressed those keys on the laptop, the only changed the laptop values.

Any way this can be added as an option for MonitorControl; thanks in advance!

**Comment by Converseallstar95** [comment]
> I added this to 3.1.0. There is an unsigned interim version [here to test](https://www.dropbox.com/s/w1md5rjyll0lsyo/MonitorControl.zip?dl=0).
> 
> Update: the shortcut is now changed to **ctrl+command+brightness** (shift+ctrl+brightness was colliding with fine control if somebody wants to control internal display only)

Thanks for this suggestion I was just looking for it as a new MonitorControl user!

I just switched away from my two Thunderbolt Displays and they worked as follows, if I pressed the volume or brightness keys on my wireless keyboard, they only changed the external monitor. If I pressed those keys on the laptop, the only changed the laptop values.

Any way this can be added as an option for MonitorControl; thanks in advance!

**Comment by waydabber** [comment]
Hi, this does not seem to be easily possible. MonitorControl uses MediaTapKey which does not currently distinguish between the brightness key from a Magic Keyboard and a built-in keyboard. MediaTapKey relies on IOKit's special key designations which also don't seem to distinguish between these. There is a distinction in real life of course and apparently some apps can capture this (for example Hammerspoon returns a different code for them and also Karabiner can distinguish between strokes from different keyboards). You might want to try to add a new Feature Request regarding differentiating between built-in/external keyboard keytaps here: https://github.com/MonitorControl/MediaKeyTap. If the devs make it work, MonitorControl can also implement something like this.

**Comment by Converseallstar95** [comment]
> Hi, this does not seem to be easily possible. MonitorControl uses MediaTapKey which does not currently distinguish between the brightness key from a Magic Keyboard and a built-in keyboard. MediaTapKey relies on IOKit's special key designations which also don't seem to distinguish between these. There is a distinction in real life of course and apparently some apps can capture this (for example Hammerspoon returns a different code for them and also Karabiner can distinguish between strokes from different keyboards). You might want to try to add a new Feature Request regarding differentiating between built-in/external keyboard keytaps here: https://github.com/MonitorControl/MediaKeyTap. If the devs make it work, MonitorControl can also implement something like this.

Thanks for the insight, I will try my luck with them. :)
