### ISSUE TITLE
Option to 'Reapply last set brightness upon startup or wake'

### ISSUE THREAD

**Issue by tsengwaiyong** [MonitorControl/MonitorControl#568]
### Before opening the issue, have you...?

- [x] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

brightness don't take effect when mac wakes up in sleep or launch the MonitorControl

### Steps to reproduce

1.Set the monitor brightness to 100%
![831630938722_ pic](https://user-images.githubusercontent.com/53459541/132232489-17483255-6cfd-421e-854e-b7cf40ab3335.jpg)

2.Launch the MonitorControl , set the brightness at about 20%,the brightness is getting lower
![image](https://user-images.githubusercontent.com/53459541/132232548-2d049e56-eac6-4aca-aacb-982a7a52bbdb.png)

3.Let mac enters sleep mode or restart
![image](https://user-images.githubusercontent.com/53459541/132232841-c5289053-0bdd-46c6-96d2-2cf0b4a2b775.png)

4.Wake up the mac

5.The monitor brightness will change back to 100% like i never launch the MonitorControl

### Expected behavior

The monitor brightness is take effect when mac wake up or launch  MonitorControl 

### Environment Information (please complete the following information)

```markdown
- macOS version:11.4 Big Sur
- Mac model:Mac mini M1
- MonitorControl version:3.0.0 Build 3095
- Monitor(s):Philips 288E2
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Hey @tsengwaiyong - this seems to be a display issue. It is rather rare but some displays don't store brightness set via DDC and after sleep they resume at 100% or the previously set OSD value. MonitorControl currently does not try to re-set the value after sleep but expects the display to retain the last setting.

I convert this issue to a Feature Request, it might be beneficial to have an option for this "Restore last set brightness upon startup or after sleep".

**Comment by tsengwaiyong** [comment]
@waydabber OK，thanks

**Comment by waydabber** [comment]
Something like this:

<img width="803" alt="Screen Shot 2021-09-09 at 20 51 04" src="https://user-images.githubusercontent.com/37590873/132745560-83418503-52f0-4bf7-bf16-c84a6dc8ffc0.png">

**Comment by tsengwaiyong** [comment]
😄thank you for solving this issue, I will try it in the next update
