### ISSUE TITLE
Have to reset LG-32UN880 after Mac Mini M1 restart

### ISSUE THREAD

**Issue by MmadJj** [MonitorControl/MonitorControl#572]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Hi,

first of all i am not 100% certain this is a "MonitorControl" issue. However the problem occured first after installing "MonitorControl".
I am using a LG-32UN880 connected to a Mac Mini M1 via USB-C. MonitorControl worked well for both brightness and volume, great work!
But when i restart or boot my Mac Mini now, the display´s USB-C Port becomes completely dead. It cant recognize any signal and also doesn´t work with other Hardware including charging. The only way to get it back working is resetting the Monitor, after that everything it back to normal until the next Mac Mini boot. Waking up from sleep always works.
Could that happen because of MonitorControl? Avoiding auto-start MonitorControl didnt help, deleting it (moving to bin) neither. Are there any settings MonitorControl changed that i could delete?

### Steps to reproduce

Restart or boot Mac Mini M1 with a USB-C connected LG32UN880

### Expected behavior

Don´t break USB-C Connection

### Anything else?

I am no programmer and new to Github, i hope telling my problem here is appropiate.

### Environment Information (please complete the following information)

```markdown
- macOS version: 11.5.2
- Mac model: Mac Mini M1 2020 8 / 256
- MonitorControl version: 3.0.0
- Monitor(s): LG-32UN880
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Hey @MmadJj. If you removed MonitorControl and the issue persists without it as well then there is virtually zero chance that the problem is related to MonitorControl especially if you did a factory reset on the display as that should wipe all data stored via DDC. Maybe it might be the case that the display had a previous condition which was somehow (?) triggered by sending DDC data but that is quite unlikely as well.

Sorry for not being able to offer any more substantial help with this.

**Comment by MmadJj** [comment]
Hi @waydabber, thanks for the very quick answer! It is help enough, as i can pretty much rule out MonitorControl now. Thanks for your great work, changing the brightness of external displays without the hardware buttons is really a lifesaver!
