### ISSUE TITLE
Support for DisplayLink (USB display adapter or dock)

### ISSUE THREAD

**Issue by GeoffreyPlitt** [MonitorControl/MonitorControl#582]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] I have read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

I have an HDMI monitor (Dell S2315H) connected via a USB dongle (https://www.amazon.com/gp/product/B01CSG7TUC/)

This software works great for my other monitors (USB-C or HDMI direct), but not for this one connected via USB adapter.

In preferences, it shows it is aware of the monitor, but says "No Control Available"

Wondering if it is possible fix?

### Expected behavior

Dimming for this monitor.

### Environment Information (please complete the following information)

```markdown
- macOS version: 11.2.3 Bug Sur
- Mac model: Mac Mini M1/2020
- MonitorControl version: 3.0.0 Build 3097
- Monitor(s): Dell S2315H
- Monitor Cable(s)/Connection(s):  https://www.amazon.com/gp/product/B01CSG7TUC and then HDMI
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Hi @GeoffreyPlitt 

DisplayLink currently does not support DDC/CI on macOS so there is no way to add support for these devices.

You can raise your voice regarding this here: https://support.displaylink.com/forums/287786-displaylink-feature-suggestions/suggestions/16135240-add-brightness-support-to-non-windows-oses

Also, as far as I know DisplayLink drivers are incompatible with gamma table calibration (used for software dimming), but I am not entirely sure about this, more experimentation would be needed with this. MonitorControl currently disables any kind of control for DisplayLink devices.

I convert this issue to a discussion, maybe the situation will change.
