### ISSUE TITLE
HP z27 monitor issues

### ISSUE THREAD

**Issue by jakedt** [MonitorControl/MonitorControl#585]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] I have read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

I was being bitten by #135 constantly before upgrading to 3.0.0. With 3.0.0, when resuming from sleep the external monitor won't wake up, and it won't be detected upon disconnect and reconnect. I had to un-plug the monitor to get it to be detected.

### Expected behavior

I would expect it to work like it does without monitor control: wake from sleep and continue to always be detected.

### Environment Information (please complete the following information)

```markdown
- macOS version: 11.5.2
- Mac model: 13-inch, 2020, Four Thunderbolt 3 ports
- MonitorControl version: 3.0.0
- Monitor(s): HP z27
- Monitor Cable(s)/Connection(s): usb-c thunderbolt
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment]
Hi @jakedt

can you please clarify what do you mean?

1) The display itself stays in sleep mode (no desktop, etc), after waking up the mac or 
2) The display wakes up fine and you can use the desktop, but DDC control is not working and MonitorControl does not detect the display

If 1) is the case then it is most probably not a MonitorControl issue but a generic one (search for 'display does not wake macos' on google for various fixes) as the app does not interfere with system sleep or the wake up process in any way. It actually waits for about 5 seconds after sleep until it tries to redetect the display and allow for DDC control. 

What might be possible (looking at #135) is that the z27s have something wrong with their firmware and have issues with sleep/wake once DDC control was used - but it would be a weird problem and also a hardware one. You can try to set polling to 'None' in the advanced section of Displays and disable Hardware DDC control for a while to see if that changes things. If you consistently have the sleep problem only when DDC was used then this might be the problem.

**Comment by waydabber** [comment]
Hi, I'll move this over to discussion as the issue seems to be sleeping + there is no much to do. Maybe other z27 owners will chime in as well.
