### ISSUE TITLE
Dear dev: do you know how much we appreciate you?

### ISSUE THREAD

**Issue by bradtchapman** [MonitorControl/MonitorControl#593]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Question

Because we do!  This app is AWESOME.  It has worked great with several Dell monitors since version 2.0.  And it works even better in 3.0.  There's a major improvement in responsiveness, especially when connecting to a docking station / external monitor.

Also, I was about to file 3 bugs / issues for 3.0.0 dealing with volume control, but they've already been opened AND they are all slated for inclusion in the 3.1.0 release.  Yippee!

That's all.  Have a great day!

**Comment by the0neyouseek** [comment]
Thanks for all the love, it means a lot ❤️

**Comment by waydabber** [comment]
Thank you indeed! :)
