### ISSUE TITLE
Not working with Samsung LS24R350FZNXZA displays

### ISSUE THREAD

**Issue by Vaasu-Dhand** [MonitorControl/MonitorControl#597]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] I have read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

I have two Samsung LS24R350FZNXZA displays that connect to my mac book pro with a Display link docking station. But, the sliders on Monitor Control do not change the brightness. 

Here's an [Amazon link ](https://www.amazon.ca/gp/product/B091BCRJR7/ref=ppx_yo_dt_b_asin_title_o00_s02?ie=UTF8&psc=1)for the displays

### Expected behavior

It should change the brightness.

### Environment Information (please complete the following information)

```markdown
- macOS version: 11.5.2 Big Sur
- Mac model: MacBook Pro (16-inch, 2019)
- MonitorControl version: 3.0.0
- Monitor(s): Samsung LS24R350FZNXZA, Samsung LS24R350FZNXZA
- Monitor Cable(s)/Connection(s): 
Mac Book Pro <- Type C Cable <- HDMI cable to Docking Station -> Samsung LS24R350FZNXZA
Mac Book Pro <- Type C Cable <- HDMI cable to Docking Station -> Samsung LS24R350FZNXZA
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment]
Hi, DisplayLink devices cannot be controlled on Mac at the moment. :(

https://github.com/MonitorControl/MonitorControl/discussions/583

I recommend you adding your giving your feedback to DisplayLink - see the relevant link in the above discussion.
