### ISSUE TITLE
Sound adjustments not working with Benq ew2780u display via the M1 mini M1's HDMI port

### ISSUE THREAD

**Issue by cwwmbm** [MonitorControl/MonitorControl#598]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Computer: Mac Mini M1, OS Big Sur 11.4

Latest version of the software enables the control of the sound using the keyboard, but the sound stays at constant level regardless of how much I increase or decrease it, or even turn on/off

### Steps to reproduce

1. Install latest version
2. Give permission to the app to control the Mac
3. Try to increase/decrease sound levels, try turning on/off

### Expected behavior

Sound levels are decreased/increased accordingly, or turned on/off. In reality nothing happens, sound levels stay the same all the time, whether it's done via keyboard, or a slider in sound control center.

### Environment Information (please complete the following information)

```markdown
- macOS version: 11.4
- Mac model: Mac Mini M1
- MonitorControl version: 3.0.0 Build 3097
- Monitor(s): Benq ew2780u
- Apple Silicon/M1 (yes or no): Yes
```

**Comment by waydabber** [comment]
HI @cwwmbm - what port is the display connected to?

**Comment by cwwmbm** [comment]
@waydabber hey sorry should have specified - it's HDMI.

**Comment by waydabber** [comment]
Hi @cwwmbm - I think your display is controlled via software mode which allows for brightness control only. You should try using USB-C on the M1 mini.

See the following Q&A item:

https://github.com/MonitorControl/MonitorControl/discussions/599

**Comment by waydabber** [comment]
I'll close this issue now but let me know if I can be of any help with this!
