### ISSUE TITLE
Volume can't be controlled!!!

### ISSUE THREAD

**Issue by FoodieLT** [MonitorControl/MonitorControl#600]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] I have read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

Volume can't be controlled on my monitor (U27N3G6R4B). It could be controlled while I was connecting it with Type-C cable. But after I connected it with HDMI, it does not work anymore.
![截图 2021-09-16@18 40 50@2x](https://user-images.githubusercontent.com/90837817/133598441-d91a922a-1d5b-4dd6-ab1e-4b1bd14f8b11.jpg)

### Expected behavior

Hope somebody can explain it for me.

### Environment Information (please complete the following information)

```markdown
- macOS version:macOS 12.0 beta
- Mac model:Mac mini(M1)
- MonitorControl version:3.0.0
- Monitor(s):AOC U27N3G6R4B
- Monitor Cable(s)/Connection(s):HDMI
- Apple Silicon/M1 (yes or no):Yes
```

**Comment by JoniVR** [comment]
See #599 

@waydabber Perhaps we should update the issue template to reference this? Or provide a wiki link or something to it as it seems to be generating lots of issues :D

**Comment by waydabber** [comment]
Yes, I'll add a more in depth explanation in 3.1.0 - I already added a tooltip when somebody hovers over "Software mode" but something more obvious would be needed.

Also, I created a Q&A page for it https://github.com/MonitorControl/MonitorControl/discussions/599 but - maybe we should add to the template in the Before opening the issue, have you...? section to check through Discussions, especially Questions as well. Also we could even add this singular issue as well to the list. :)

Something like this:

**Before opening the issue, have you...?**

- [ ]   Searched for existing issues
- [ ]   **Searched for answered questions in Discussions**
- [ ]   **Not using to use 2018 or 2020 minis via HDMI port**
- [ ]   I have read through the Monitor-Troubleshooting Wiki
- [ ]   Updated MonitorControl to the latest version (if applicable)

**Comment by waydabber** [comment]
@FoodieLT - regarding your question, the 2018 and 2020 Intel and M1 mini blocks DDC communication via the HDMI port. In this case MonitorControl falls back to software dimming (it does not directly access the backlight of the screen to dim the display but uses a cool technique called gammatable manipulation to achieve a similar result).
