### ISSUE TITLE
Slider scroll support using mouse scroll

### ISSUE THREAD

**Issue by ioswmtdeveloper** [MonitorControl/MonitorControl#601]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

Please provide slide scroll support using mouse scroll Similar as in system volume slider from status bar.

### Describe the solution you'd like

Please provide slide scroll support using mouse scroll Similar as in system volume slider from status bar.

### Describe alternatives you've considered

Please provide slide scroll support using mouse scroll Similar as in system volume slider from status bar.

### Anything else?

Hi,

Please provide slide scroll support using mouse scroll Similar as in system volume slider from status bar.

**Comment by waydabber** [comment]
I'll look into it. We could use this one as somebody already implemented such a thing: https://github.com/thompsonate/Scrollable-NSSlider

**Comment by waydabber** [comment]
This is added to , works beatifully.
