### ISSUE TITLE
Audio Control for DELL S2721DGF not working

### ISSUE THREAD

**Issue by doulakis** [MonitorControl/MonitorControl#612]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Hey Guys, I cannot control audio for my DELL S2721DGF. It is connected through HDMI. Contrast is working fine.

### Steps to reproduce

Audio Control adjustments doesn't represent the expected behavior, it seems that the audio changes in the Icon but the audio remains at the max level.

### Expected behavior

Ability to change Audio

### Environment Information (please complete the following information)

```markdown
- macOS version: 11.5.2
- Mac model: MacBook Pro mid 2014
- MonitorControl version: 3.0.0 (Tested the other version you provided in a bug)
- Monitor(s): DELL S2721DGF
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment]
This seems to be a display issue. If contrast works then DDC communication in general works between the display and the app. Please try ddcctl and see if the display accepts volume commands using that tool. If not, then there is probably not much to do about it, maybe you can find some setting in the monitor OSD that blocks volume changes somehow.

**Comment by Craiting** [comment]
I have the same monitor and same issue. Brightness controls work but not volume. I tried using ddcctl and again I could control brightness but not the volume.
