### ISSUE TITLE
HP Z32 Monitor doesn't turn on after using Monitor control

### ISSUE THREAD

**Issue by avishaan** [MonitorControl/MonitorControl#617]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

If I turn on monitor control, unplug my monitor, and plug back my monitor, the monitor doesn't turn on. In order to get it to turn on I have to power cycle my monitor

If I reset my monitor and do not turn on monitor control. When I unplug my monitor and plug it back in, the monitor will turn on

### Steps to reproduce

1. start monitor control app
2. unplug monitor
3. plug in monitor
4. monitor will not connect

### Expected behavior

I expect monitor to continue to reconnect without a power cycle when monitor control is one

### Environment Information (please complete the following information)

```markdown
- macOS version: 11.5.2
- Mac model: M1 MacBook Pro 13-inch, 2020
- MonitorControl version: 3.0.0 build 3097
- Monitor(s): HP Z32
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Hi, this is a known issue with the z27 as well. This is a HP "z" thing apparently. [Take a look at this discussion.](https://github.com/MonitorControl/MonitorControl/discussions/594)

I recommend you to join the discussion to help figure out what is wrong with these units.
