### ISSUE TITLE
software volume control

### ISSUE THREAD

**Issue by lu-mueller** [MonitorControl/MonitorControl#626]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

I have connected two DELL S2721QS to my mac mini M1. Only one screen can be controlled by DDC with the M1. The feature enable software dimming if required is available for this, but only for brightness and not for volume.

### Describe the solution you'd like

If an external display can´t be controlled, software volume control will be used instead.

### Describe alternatives you've considered

-

**Comment by waydabber** [comment]
I think the idea is solid but I am afraid implementing software volume control for digital outputs is out of scope for MonitorControl. This would require a virtual audio output device as a filter (which stands between the original output and the system output) that is able to adjust the level of the audio stream with volume control option exposed to the OS. Windows has this capability built-in to its default digital audio drivers but macOS lacks this - there are third party tools (like https://rogueamoeba.com/soundsource/ ) that can fix this but these are quite pricey (formerly you could use SoundFlower for this as a free option but it does not work anymore with recent macOS versions and M1). 

I'll close this issue now but if you have a better approach solving this problem, please let us know!

Thank you!

(@JoniVR please let me know if you feel differently about this request!)
