### ISSUE TITLE
Close Preferences Window with keyboard shortcuts

### ISSUE THREAD

**Issue by jajoho** [MonitorControl/MonitorControl#639]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

The preferences window can only be closed with a click on the red button ([related discussion](https://github.com/MonitorControl/MonitorControl/discussions/631#discussioncomment-1413716)).

### Describe the solution you'd like

It would be great if the window could also be closed with keyboard shortcuts, e.g. `cmd+w`, `cmd+q` and/or `esq`

### Describe alternatives you've considered

At this time I have to click the red button which is inconvenient when you have become accustomed to shortcuts

**Comment by waydabber** [comment]
Btw. added cmd+q for text based menu as well for platform conformity.
