### ISSUE TITLE
Enable Shades dimming on all types of displays (not only AirPlay ones)

### ISSUE THREAD

**Issue by giulianofichera** [MonitorControl/MonitorControl#670]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

I use a TV as a monitor. This device doesn't have DDC control so my only option is software dimming.

The problem arises when I want to use Gamma dimming with f.lux, that also modifies gamma values.
By using Shades dimming, I could use MonitorControl alongside f.lux (f.lux to change display temperature, MonitorControl to dim the display using shades).

### Describe the solution you'd like

I'd like to use f.lux to modify the **external display** temperature using **gamma values**, and dim the display using **Shades**.
The MacBook's internal display should be modified by f.lux via gamma, and via the native Apple brightness adjustments.

### Describe alternatives you've considered

Currently I'm using f.lux with QuickShade, but the issue is QuickShade **doesn't have a per display dimming option** so it also dims my MacBook display via software (unnecessary).

**Comment by waydabber** [comment]
Yes, this is a logical idea and could be implemented quite easily with a simple checkbox in Displays.

**Comment by giulianofichera** [comment]
> Yes, this is a logical idea and could be implemented quite easily with a simple checkbox in Displays.

That's great news! I'll be looking forward to it.
Thank you!

**Comment by waydabber** [comment]
You'll be able to toggle this with the 'Avoid gammatable manipulation' checkbox. Please be aware that with shade based dimming the mouse cursor will be exempt and upon entering/exiting full screen mode in an app, the app will briefly light up as the shade cover fails during the transition.

<img width="842" alt="Screen Shot 2021-10-04 at 22 55 51" src="https://user-images.githubusercontent.com/37590873/135923795-cd5a56bc-4ce2-47f6-a685-f553c0752ff6.png">

**Comment by giulianofichera** [comment]
Wow that was quick!
I donated and translated the app to my language, thank you!

**Comment by waydabber** [comment]
Thank you! :)
