### ISSUE TITLE
HDR brightness

### ISSUE THREAD

**Issue by ncortines** [MonitorControl/MonitorControl#672]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Question

Hi! this is a question.

Can MonitorControl help with brightness while using a display on HDR mode?

I recently purchased an external monitor with HDR support. While enabling HDR on Display settings, everything becomes much darker. Even shows with HDR support, are too dark.

Other observations:
- While HDR is enabled on the monitor, the OSD for brightness control is disabled.
- While trying to adjust brightness using MonitorControl while HDR is enabled, the display becomes brighter for the split of a second, then goes back to dark.

Thanks!
Juan

**Comment by waydabber** [comment]
I'll convert this one into to a Q&A entry.
