### ISSUE TITLE
Add feature "Dim display when screensaver is running"

### ISSUE THREAD

**Issue by derreisende77** [MonitorControl/MonitorControl#674]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

Dell´s  Display Manager Application offers an option to automatically dim the display or switch to sleep mode when a running screen saver is detected. I could not find a similar feature in this app.

### Describe the solution you'd like

Offer a preferences method to automatically dim the display darker or to put monitor to sleep mode when a running screensaver is detected. Screen dimming would be the preferred method.

### Describe alternatives you've considered

As an alternative I am currently using Dell Display Manager which supports this but lacks other features your software provides.

### Anything else?

![Bildschirmfoto 2021-10-05 um 10 38 12](https://user-images.githubusercontent.com/8466092/135989814-bb10744c-e30a-422a-ad9a-63495f916d38.jpg)
Unfortunately the screenshot is German but the checkbox translates to "Power-Nap Options" and the radiobuttons to:
- Dim display when screensaver is active
- Switch display to sleep mode when screensaver is active

**Comment by derreisende77** [comment]
AFAIK this feature request is not done yet. Would be nice to have it reopened.

**Comment by waydabber** [comment]
I already implemented this in [BetterDisplay](https://betterdisplay.pro), won't be carried over to MonitorControl I am afraid.
