### ISSUE TITLE
Detect apps which manipulate gamma tables and display a warning

### ISSUE THREAD

**Issue by the0neyouseek** [MonitorControl/MonitorControl#692]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

When using both MonitorControl and apps that use gamma table manipulations like `f.lux` issues can arise. Theses issues can be fixed by disabling either settings in MonitorControl or simply quitting the other app.

### Describe the solution you'd like

We could use [`urlForApplication(withBundleIdentifier:)`](https://developer.apple.com/documentation/appkit/nsworkspace/1534053-urlforapplication) to detect the installation of a list of apps (using their bundle id) and display a warning to the user about this issue.

The warning could look something like this :

<table>
    <thead>
        <tr>
            <th colspan=2>Gamma table app detected</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan=2>Hey! It looks likes you're using <code>&lt;app&gt;</code>, nothing wrong here but MonitorControl and <code>&lt;app&gt;</code> both use gamma table manipulation and can't do this at the same time, causing issue in both apps. If you'd like, you can disable gamma table manipulation in MonitorControl</td>
        </tr>
        <tr>
            <td>Disable gamma table manipulations</td>
            <td>Leave gamma table on</td>
        </tr>
    </tbody>
</table>

### Describe alternatives you've considered

We could also disable gamma table manipulations by default, but I don't think that would be ideal

**Comment by waydabber** [comment]
Yes, f.lux compatibility seems to be a recurring issue. We can also solve this by checking periodically whether gammatable changes persist (there is already a job in MC that mostly does brightness syncing, it could be easily added there). If it doesn't, then we can pop a notification. This could work for any other apps as well (for example running Lunar and MC side by side is also not ideal).
