### ISSUE TITLE
Apple Thunderbolt display stays dark

### ISSUE THREAD

**Issue by Dynynaxerny** [MonitorControl/MonitorControl#705]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Question

Hello! Do any of you have any advice? I installed MonitorControl and after a few tests my 27 inch Apple Thunderbolt display suddenly went very dark. All attempts to reverse this are unsuccessful. I can only darken further. The Apple Thunderbolt Display is connected to a 2018 MacBook Pro together with Apple LED Cinema Display. The Apple LED Cinema Display behaves as before.

**Comment by Dynynaxerny** [comment]
Hello! Sorry for forgetting something as important as the version number! I am using version 4.0.0 Build 6443 Intel.
The Apple Thunderbolt display doesn't have its own USB input, the monitor is only connected via Thunderbolt, right?
cable
• Integrated Thunderbolt cable
• Integrated universal MagSafe cable (up to 85 W)
Peripheral connections
• Three active USB 2.0 ports
• FireWire 800 connection
• Gigabit Ethernet connection
• Thunderbolt connection
• Connection for Kensington anti-theft device
Today I connected this monitor to a MacBook Pro 2015 and it is VERY dark there too, could it be broken by MonitorControl?
Is there any way to reset the monitor?

**Comment by Dynynaxerny** [comment]
I forgot! Thank you for your help!

**Comment by waydabber** [comment]
An other think I can think of is if the backlight was failing or about to fail, maybe if the brightness control was tested a bit too vigorously, it could push it over the edge. But I am not sure honestly. I am sorry that you have to deal with this.

If you want I can convert this issue into a discussion, maybe other Thunderbolt Display owners have some tips or feedbacks whether they experienced anything like this.

**Comment by Dynynaxerny** [comment]
Hello!
I use MonitorControl Version 4.0.0 Build 6851, have a MacBook Pro (15-inch, 2018), 2.9 GHz 6-Core Intel Core i9, 32 GB 2400 MHz DDR4 and with a Radeon Pro Vega 20 4 GB with macOS Monterey 12.0.1.
The Thunderbolt display is connected to another LED cinema display (27 inches), an old EIZO EV2333W and the internal 15-inch display on the above-mentioned MacBook Pro. Except for the Thunderbolt display, everything works without any problems. I've tried everything possible, but to no avail, the Thunderbolt display remains dark!
However, I tried a tip and held a flashlight in front of the monitor camera and lo and behold, the brightness was immediately there. Apparently the calibration of the automatic brightness adjustment has been lost. I don't know where to turn it off either. Does that help you? Greetings Andreas

**Comment by waydabber** [comment]
I think the ambient led sensor can be turned off in Displays Preferences. If the sensor has failed (for example always reports darkness) and is not turned off, the display will tend to tune down brightness all the time which is rather annoying.

![automatically-tweak-brightness](https://user-images.githubusercontent.com/37590873/139599717-e477d66d-f712-47a0-b61e-51459a4e59ec.png)

If you can't control the LED cinema display (but you should via USB) and turn it off then I don't know any other method to fix this, except maybe sticking a small led strip in front of the sensor and crank it up. :)

**Comment by waydabber** [comment]
(btw the light sensor is located next to the camera, so you should not direct the led to the camera but the sensor)
