### ISSUE TITLE
Add software color temperature (Kelvin to RGB) slider to the menu

### ISSUE THREAD

**Issue by waydabber** [MonitorControl/MonitorControl#726]
### Feature Request

Add additional software (gamma table) image control slider for color temperature. The presence of the control should be optional (user selectable) and only for displays with gamma table control.

For future reference: use the following to convert Kelvin (color temperature) to RGB:

https://tannerhelland.com/2012/09/18/convert-temperature-rgb-algorithm-code.html

(note: it is debatable whether color temperature control should be a scope of MonitorControl or not).

**Comment by Muirium** [comment]
Impressive demo in your link:

![](https://tannerhelland.com/images/True_Blood_Color_Temperature_Demo-600x450.jpg)

Should this be a function in MonitorControl? I don’t know. Do it want it on my Mac? YES!

I’ve played about with custom colour profiles a bit over the years but this is so much better. One slider to rule them all.

**Comment by Rusty-UX** [comment]
+1 to the addition of this feature. I agree that it's debatable whether this should be a function within MonitorControl.

Having MC be able to do this function vs. competing with another program (such as Iris) on the device would be great, and very streamlined. Additionally, adjusting brightness and color temperature are two tasks I often do together.

If anyone has found a workaround apps that pair well with MC would love to see them. So far Gamma Control app, and Iris both work ok, but trigger a warning within MonitorControl.

**Comment by dimaqq** [comment]
Ugh, the stale bot was too aggressive.
