### ISSUE TITLE
Change menu icon

### ISSUE THREAD

**Issue by Alpineo** [MonitorControl/MonitorControl#748]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

Improvements

### Describe the solution you'd like

I'd like to change the brightness icon to a speaker icon like the original Mac.
Maximal super would still be a simple equalizer function. Thanks :)

### Describe alternatives you've considered

eqMac

**Comment by cprcrack** [comment]
This would be great. I initially used MonitorControl just to be able to change the volume of my monitor, which is basically my main volume, so having a "brightness" icon is really strange to me. If we cannot customize the icon, why not choose an icon that at least have both symbols, the sun and the speaker, which better represents both main MonitorControl's functions?

**Comment by Nudeladder** [comment]
So, I am also wanting to change the menu bar icon into a more solid, bulkier one so that I can see it better, but I fumbled around in the contents folder but couldn't find it...I guess you can only change it using Xcode?

**Comment by waydabber** [comment]
Yes, you can change the icon in XCode.

Search the project for `sun.max` and replace this string to an other [SFSymbol](https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/) (download the app to browser).

Hope this helps!

**Comment by JoniVR** [comment]
I really don't see how this is a big issue. Seems like yeah "nice to have" for a few users I guess.. Going to close it now. If you want a custom icon, you can always fork/modify the code and change it there.
