### ISSUE TITLE
BIG thank you for build this app! 🙏

### ISSUE THREAD

**Issue by zamai** [MonitorControl/MonitorControl#751]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Question

I just wanted to say big thanks to you guys for putting this app together!!! 
And share my personal story how your software delights me every day! 

I have a LG monitor which I was using for couple of years, but never used it's speakers - because I find it inconvenient to play around with 3 sound sources at the same time (monitor, macOS, media player), but recently I've had no other choice but to use built in speakers... and I was fumbling with the volume control joystick on the monitor itself. 
But one good day I was frustrated with it and thought to myself - why I can change million other things about my OS, but it can't change the sound on the monitor speakers - and an idea hit me to google the problem. BOOM! I found your repo and was so delighted that somebody had the same problem (I imagine) and has kind enough to build solution for the rest of us for free! KUDOS! 

PS please send special love to the person who added "Use fine OSD scale for volume" 🚀

**Comment by waydabber** [comment]
Thanks @zamai for the kind word! :)

**Comment by ankit9j** [comment]
I got the same LG monitor today and this app saved me. Came here to thank you where zamai has summed it well already

**Comment by webmurkser** [comment]
As a Dell 2720Q and U2415 user, I can also only write a big THANK YOU. Brightness and contrast - that's all I need - quickly adjusted via slider. The adjustment on the monitor itself (the 2720Q is even worse than the U2415) was a disaster every time. Thank you!

**Comment by waydabber** [comment]
All right, all this love can continue under discussions. :)
