### ISSUE TITLE
Black screen show up whenever I switch between desktops on my virtual monitor

### ISSUE THREAD

**Issue by sunnytranco** [MonitorControl/MonitorControl#752]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

I'm using a Macbook Pro M1 with Monitor Control 4.0.0. I have a setup with 2 external monitors (Dell) via Dell Station D6000 as virtual monitors (due to limitation from Apple for M1). I've noticed that when switching between desktops in the virtual monitor, there is a black screen show up every time for half a second. It's really annoying for me. Could you take a look at this issue?

P/S: The app works just fine on the built-in-retina on my laptop. So I assume the virtual monitor is the cause of this. FYI: Another app, Luna, doesn't have this kind of bug

### Steps to reproduce

Switch desktop on your virtual monitor

### Expected behavior

The black screen between the switching process

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.0.1 Monterey
- Mac model: Macbook Pro M1 2020
- MonitorControl version: 4.0.0
- Monitor(s): Dell U2720Q & U2719D via Dell Station D6000
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Hi, can you elaborate a bit on what kind of Virtual Monitors are you using? Maybe a video of some kind would help understanding the issue.

I have experience with [BetterDummy](https://github.com/waydabber/BetterDummy) and SideCar, AirPlay which all utilize virtual displays and did not experience any issue, but maybe I just don't understand what should I look for.

**Comment by sunnytranco** [comment]
Hi @waydabber,

Sidecar is still okay on my devices. Since Apple M1 only allows me to connect with 2 monitors (including built-in-retina) so if I wanna use 2 external displays with my Macbook Pro M1 then I have to use a Dock Station that supports DisplayLink technology. Here is my setup [guideline](https://m1displays.com/docking-stations-for-m1-macbooks) 

Basically, my virtual displays are generated by [DIsplayLink](https://www.synaptics.com/products/displaylink-graphics) via Dell Station D6000

You can check the black screen in my attachment below
![bug with displaylink](https://user-images.githubusercontent.com/27778968/139611441-1d4b2d32-693d-45a3-ae24-2a5db8e2faf9.gif)

Thanks for the reply

**Comment by sunnytranco** [comment]
@waydabber I have an update for you.

I tried your **BetterDummy** app on Dell U2720Q (using DisplayLink, as the main display) and the black screen was gone. The other monitor, Dell U2719D, still has the bug.

**Comment by waydabber** [comment]
I see the issue. Honestly I am not entirely sure why this is happening, seems to be a DisplayLink related problem somehow (I don't have such a device to experiment with), maybe related to shade dimming which is the only option that can be used for DisplayLink devices at the moment. But SideCar uses that as well and it does not have this issue. Can you show me how the Displays tab under MonitorControl Preferences looks like?

Also, what is the app called Luna? Is that Luna Display?

**Comment by sunnytranco** [comment]
Sorry. I double-checked again on Sidecar, it has the issue too (now I'm not sure, last time I'd checked which app was being used :-( )

And this is [Luna](https://lunar.fyi). It's not Luna Display, it's a monitor control app just like yours.

![displays-2](https://user-images.githubusercontent.com/27778968/139639037-59c497d3-1769-4945-b7a1-c1410a111149.png)

![displays-1](https://user-images.githubusercontent.com/27778968/139639014-fe6a6d2a-907e-405e-b2e9-5cada03a8486.png)

**Comment by waydabber** [comment]
Ohh, yes, you mean Lunar by @alin23. :) Ok, I am familiar with it, it's really a great app, I highly recommend it!

Lunar has a completely different implementation when doing shade based control. I'll try to check out in depth what could be the difference. Thanks for the clarification!

@alin23 - as an unrelated sidenote, [BetterDummy](https://github.com/waydabber/BetterDummy) does not seem to work well with Lunar at default settings as Lunar does not figure out if a display is in a mirrored set and control based on mouse position does not work (it should control all displays in the mirrored set as all displays have the mouse). It is not a BetterDummy specific issue, but affects all mirrored setups. You might want to look at this. ;)

**Comment by waydabber** [comment]
Btw. if you create an other Dummy using BetterDummy (you can have two dummies of the same aspect ratio at the same time) and mirror that to the other display, does the problem go away on that display as well? Thanks!

**Comment by alin23** [comment]
> @alin23 - as an unrelated sidenote, [BetterDummy](https://github.com/waydabber/BetterDummy) does not seem to work well with Lunar at default settings as Lunar does not figure out if a display is in a mirrored set and control based on mouse position does not work (it should control all displays in the mirrored set as all displays have the mouse). It is not a BetterDummy specific issue, but affects all mirrored setups. You might want to look at this. ;)

Correct, I haven't thought of controlling all the monitors in a mirror set on the Display with Cursor option. 

I'll fix that in the next version of Lunar, thanks for the heads up!

**Comment by sunnytranco** [comment]
@waydabber thanks for the tip. I successfully fix the bug of black screen with one more Dummy. But now I cannot control brightness using Monitor Control app lolx

Anw, thanks for your support

**Comment by waydabber** [comment]
Hahh great! An other scenario to test and possibly fix - control of a virtual display (BetterDummy) mirrored to an other virtual display (DisplayLink). ;) I like it!

**Comment by quantumkv** [comment]
This issue is not limited to only virtual monitors. I am able to reproduce with a single standard monitor (Dell UP2720Q) connected directly via USB-C to a M1 Air.

I am using the hardware ddc based brightness control instead of the software shade, and I can reproduce this reliably only on the external monitor, and never on the internal one.

Another thing I have observed is that this issue only persists while the app is running. If I change the brightness and then quit the app, the bug is gone, but comes back instantly if I start it again.

**Comment by waydabber** [comment]
Hi, yes this issue appears whenever shade control is enabled and at least one dimming has occured (on hardware DDC displays this happens with combined dimming enabled below 50% brightness).

To solve this issue, please uncheck `Avoid gamma table manipulation` under Displays for the given device and restart the app (disabled is the default setting).

I'll fix this issue as soon as I get to it! Thanks for the input and the patience!

**Comment by waydabber** [comment]
So this issue will be about black bars, I opened an other for supporting [BetterDummy](https://github.com/waydabber/BetterDummy) mirrored Virtual Displays (like DisplayLink). https://github.com/MonitorControl/MonitorControl/issues/762
