### ISSUE TITLE
Why does v4 has LSMinimumSystemVersion 10.5

### ISSUE THREAD

**Issue by jonsummers** [MonitorControl/MonitorControl#758]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Question

Why does MonitorControl v4 have LSMinimumSystemVersion 10.5?
Is there an absolutely critical Swift framework required? 

I have a dev machine that is staying on 10.14 as I need to run 32bit apps sometimes.

**Comment by waydabber** [comment]
Hey, you can compile it to 10.14 as well. I am not sure about DisplayServices brightness working properly on 10.14 (for Apple display control) but it probably does - I just did not have a 10.14 to test it. What Mac model are you using?

**Comment by waydabber** [comment]
But well, we can release 10.14 with unofficial 10.14 compatibility that should not hurt actually.

**Comment by waydabber** [comment]
The new `fixes` branch should compile to 10.14, as it turned out master does not compile due to some minor incompatibilities.

**Comment by jonsummers** [comment]
"What Mac model are you using?"
I have restored 21.5" iMac 2012 16GB 1TB SSD with attached 1080p Samsung monitor S24A31.
Monitor has poor brightness range but older MonitorControl works as expected.
The iMac stays on macOS 10.14 for 32bit support as I need QuickTime Player 7 for sentimental reasons.
The use is for compiling ESP32 projects with PlatformIO.

**Comment by waydabber** [comment]
Hi, I made some changes so the newly released 4.0.1 so it should run on 10.14 (although it is not supported by the dev team if you encounter issues).

**Comment by jonsummers** [comment]
Verified v4.0.1 works splendidly on macOS 10.14.6 Mojave. v4 is a definite step up from v3. Thanks
