### ISSUE TITLE
Better support for BetterDummy + Sidecar, Airplay or DisplayLink

### ISSUE THREAD

**Issue by waydabber** [MonitorControl/MonitorControl#762]
Dummies including [BetterDummy](https://github.com/waydabber/BetterDummy) is now intentionally skipped from controlling displays (`Display.isDummy` checks).

Virtual Displays (like Sidecar, Airplay, DisplayLink displays) that support only shade control are banned from control when in mirrored setups (`DisplayManager.isDisqualifiedFromShade`).

Each of these factors are prohibiting [BetterDummy](https://github.com/waydabber/BetterDummy) mirrored Virtual Displays to benefit from shade based dimming.

An exception must be implemented to solve this issue.

**Comment by Fariusz** [comment]
<img width="699" alt="Zrzut ekranu 2022-02-8 o 22 38 26" src="https://user-images.githubusercontent.com/61850108/153079994-bfb3d483-dfbb-49fd-871b-cc2fdd32e3b3.png">

Should it work at this point? I use displaylink and BetterDummy.

**Comment by waydabber** [comment]
Hmm. Yes, BetterDummy->Sidecar/DisplayLink mirrored display brightness control via shading should be working in the latest version under Monterey.

**Comment by Fariusz** [comment]
How about Big Sur? Should it work as well?

**Comment by waydabber** [comment]
Probably should, but never tried it. :)

The No Control / unspecified control status is interesting though, I did program the app to show that message as a last resort - it seems like the app just has no idea what to do with a combination of DisplayLink and BetterDummy on Intel.

A few questions:

- Are you using the latest version of the app?
- If you do not enable BetterDummy, does the app work?
- If you try BetterDummy + a naitve (non-displaylink) display, does the app work?

What might help is if you could provide me with the console log of the app during startup, when the display detection is done. Here is how to do that: https://github.com/MonitorControl/MonitorControl/discussions/851
