### ISSUE TITLE
Brightness Control lock-out on MacBook screen wake

### ISSUE THREAD

**Issue by Muirium** [MonitorControl/MonitorControl#777]
About half the time I wake my M1 MacBook Air running Monterey 12.0.1, using it in laptop mode with no other displays connected, when I press the brightness keys, I see this:

![Screenshot 2021-11-08 at 10 55 54 pm](https://user-images.githubusercontent.com/221646/140832082-fa3223ff-a9a2-4d6b-b794-dafb9f30d9d5.jpg)

When I brought this up, I was told the behaviour is intended. But being locked out of your laptop's own brightness keys for a while when you open the lid is not a good experience. It makes MonitorControl a nuisance instead of the must-have utility it is whenever I'm hooked up to a desktop display.

Can we handle this smarter? Automatically dropping the time-out when there is no external display connected seems the right approach to me, certainly on quick-waking M1. I find immediate Brightness control on opening a laptop to be essential.

_Originally posted by @Muirium in https://github.com/MonitorControl/MonitorControl/discussions/773#discussioncomment-1609136_

**Comment by waydabber** [comment]
We can as well disengage from listening to the brightness keys in this state and let them work as default. This will not show the lock sign however even when a display is connected. We could also shorten the wake-up and configuration delays in general.

**Comment by pqhf5kd** [comment]
I also noticed this issue this morning

**Comment by waydabber** [comment]
All right, I'll tweak this in the next update. :)

**Comment by waydabber** [comment]
Ok, I added this in the 4.0.2 update. I can make an interim build if you'd like to test it or you can wait for 4.0.2. :) Let me know.

**Comment by Muirium** [comment]
Nice! I can test you like.

**Comment by waydabber** [comment]
Hi, sorry for the delay. The problem is that we have a mess around signatures and I can't sign with the same ID as @JoniVR does who usually manages releases. MacOS might ask you to re-add the app to the accessibility list. Please test it and let me know if it works.

https://www.dropbox.com/s/qkgl7oyzdmxhkm0/MonitorControl-v4.0.2b6957.zip?dl=1

Thank you!

**Comment by JoniVR** [comment]
Hi, I'll do a 4.0.2 release once the issue is confirmed as resolved 🙂

**Comment by Muirium** [comment]
Testing 4.0.2 just now: nope, still getting the brightness lock on waking up my M1 Air with no external display connected. Works fine from sleep with the 4K plugged in, though (which is a bit slower, naturally). The internal display control time-out does eventually end, but seems similar to before. 

And yes, I did quit the previous version of MonitorControl and put it in the trash before installing the new one. Perhaps I need to restart the Mac? I'll try that when I can.

**Comment by waydabber** [comment]
Is the about tab showing 4.0.2?

**Comment by Muirium** [comment]
Yes it is. Build 6957.

Restarted Monterey and the misbehaviour's still there. If I close the lid, wait a bit and open back up again… I get the lock icon when pressing Brightness up or down for several seconds. Eventually, normal control is restored. Can be as little as 2 seconds locked out, but is often up to 5 or 6.

These modern Macs are clearly too fast!

**Comment by waydabber** [comment]
Hmm. Interesting. I'll look at it again then. :)

**Comment by waydabber** [comment]
@Muirium - are you using the Apple keyboard or custom shortcuts?

To be honest, I am yet unable to reproduce the issue and I don't clearly see from the code how it is possible. Did you not maybe use MonitorControl with the icon turned off with autostart and the old version is somehow starting up still and takes precedence?

**Comment by waydabber** [comment]
Ok, I updated the build and removed even the function that could possibly display an OSD with a lock. Its just not there anymore, an empty void occupies its place. :) But I still don't understand how could the previous version possibly display an OSD with a lock.

https://www.dropbox.com/s/w6vcr3ui55sbnah/MonitorControl-v4.0.2b6963.zip?dl=1

Btw. did you encounter the security prompt upon installing the differently signed version of the app?

Thanks a lot for testing!

**Comment by Muirium** [comment]
You're right: the new build (6963) never shows the lock icon. Doing my lid wake / keyboard wake tests, what happens now is a brief pause (where F1 and F2 are just ignored) before brightness control returns. This feels faster! Don't know if it's just a psychological effect, but I much prefer never seeing the lock blocking my way! In my tests just now, the lockout is consistently 2 seconds or less with this build.

As for mysterious causes: I'm a heavy [Karabiner](https://karabiner-elements.pqrs.org) user with lots of keyboard customisation in place. That may well be in the mix. Technically, those two brightness keys on my MacBook Air's own keyboard are routed via a virtual keyboard device, as that's how Karabiner works (all connected keyboards are merged into this single device as well). I have F1 and F2 on all keyboards mapped to the keycodes Apple uses for those two keys: "key_code": "display_brightness_decrement" and "key_code": "display_brightness_decrement" in Karabiner terminology.

**Comment by waydabber** [comment]
Ahh, you are using Karabiner then. That messes things up it seems a bit. In reality there should be no wait time over what the OS needs at all if the standard Apple media keys are used. What matters is that its ok then now.

**Comment by waydabber** [comment]
(i closed the issue but let me know if there is any additional issues!  :))
