### ISSUE TITLE
Tiny language error 

### ISSUE THREAD

**Issue by jorisw** [MonitorControl/MonitorControl#779]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

![image](https://user-images.githubusercontent.com/30017/141125173-617fca0c-ed8e-426a-9907-df20102c86b7.png)

The help text here refers to a button below, while the button is said text.

### Steps to reproduce

- Open Preferences
- Choose to Hide the general menu items

### Expected behavior

Should say 'button above'

### Environment Information (please complete the following information)

```markdown
- macOS version:
- Mac model:
- MonitorControl version:
- Monitor(s):
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment]
Hmm. That looks weird. :) I'll fix it, thanks for reporting!

**Comment by waydabber** [comment]
I moved the button below. :)

<img width="842" alt="Screen Shot 2021-11-12 at 17 46 19" src="https://user-images.githubusercontent.com/37590873/141503483-9d304b3a-a5b1-4208-ac0e-c521e7ffce28.png">
