### ISSUE TITLE
Last brightness is not restored after wake with two non-DDC controlled display on Mac Mini M1

### ISSUE THREAD

**Issue by hagncola** [MonitorControl/MonitorControl#783]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

The last used brightness level does not work after wake from sleep. Always 100% if wake from sleep.
Mac Mini M1   Monterey 12.01
Dual Monitor (HDMI and USB-C/Displayport)

### Steps to reproduce

1. Set brightness to 50%
2. Use sleep on Mac
3. Wake up from sleep 100% instead of 50% before sleep.

### Expected behavior

After wake from sleep the same brighness level as before sleep.

### Anything else?

Video enclose

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.01
- Mac model: MacMini M1
- MonitorControl version: 4.01
- Monitor(s): Two iiyama 
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Hey @hagncola - so to clarify:

- The following option is enabled:

<img width="570" alt="Screen Shot 2021-11-12 at 10 18 43" src="https://user-images.githubusercontent.com/37590873/141442569-16187dee-edaf-49af-9007-2fcca7ee63e6.png">

- The brightness is not restored after a few seconds (this is not immediate) on either of the displays (one display is DDC the other should use software dimming as HDMI does not work on the M1 Mini).

Questions:

- Did you try a "Reset Preferences"?
- If you are set "Upon startup or wake" to "Assume last saved settings are valid", what happens?
- Are the last saved values reset upon app startup? Does the issue affect only sleep/wake?
- if you quit MonitorControl after setting DDC brightness, and then sleep - does the brightness reset as well? So the Iiyama display generally has the DDC reset bug after sleep?
- Can you please show the screenshots of the Displays tab?
- Screenshot of Graphics/Displays under System Report
- If you have a video of the phenomenon, that would be super helpful.

Thank you!

**Comment by hagncola** [comment]
The setting "Apply last saved values to the display" is active. I did also try to reset preferences and fully remove an install again. What do you mean with "Upon startup or wake" ?
I use only Software mode to control to get on both displays the same level.

Enclose the requested screenshots:


![Bildschirmfoto 2021-11-12 um 14 34 13](https://user-images.githubusercontent.com/93769189/141476483-4362a695-1edb-4b6c-8e42-f220725f31c8.jpg)
![Bildschirmfoto 2021-11-12 um 14 34 27](https://user-images.githubusercontent.com/93769189/141476492-a5acb094-1c85-438c-b18c-ecc2ff243e4c.jpg)

![Bildschirmfoto 2021-11-12 um 14 35 52](https://user-images.githubusercontent.com/93769189/141476498-8c466924-73b4-4414-a19e-42de8c92f7b7.jpg)

https://user-images.githubusercontent.com/93769189/141476508-11f496b5-af95-4724-9697-edbd5b5472c4.mp4

**Comment by waydabber** [comment]
Oh I see. So it is not a DDC issue. I do  not fully understand why does not the software brightness restore does not kick in (it should after a few seconds of wake). For software displays you don't actually need to change the "Upon startup or wake" option to "Apply last saved values" for values to be restored (but should still work if it is set to that obviously). I am still unable to reproduce the issue. Is there anything else that you changed from defaults? I'd like to somehow replicate the settings that lead to this issue.

Do the brightness sliders (or changing the keyboard) show 100% after wake or it reflects the (lower) values from before the sleep?

**Comment by hagncola** [comment]
The brightness slider show the correct value, and use after sleep the brightness button on keybord the corrent setting is active. It seems, the setting is stored, but will not activated.

**Comment by waydabber** [comment]
Ok, you should follow this procedure to gather more info:

- Reset MonitorControl
- Quit the app
- Open the `Console` app in your mac
- Select your Mac under devices in the left bar
- in the Action menu enable `Include Info Messages`
- Set up your console app to look exactly like this at the top (enter those strings in the search bar + press `Play` and `Now`)
<img width="653" alt="Screen Shot 2021-11-12 at 18 11 34" src="https://user-images.githubusercontent.com/37590873/141506995-b908cfed-9afb-466a-b1ea-cbbeff57081d.png">
- press the `Clear` button
- start MonitorControl
- set the brightness to 25% for both displays
- enter sleep mode - _please note the exact time (according to your mac) when this happens_
- wait 20 seconds
- exit sleep mode
- wait 20 seconds
- exit MonitorControl
- select all console messages (command+A)
- copy the whole thing into a text editor app
- save the text file and attach it here.

You can redo the whole stuff with the exception that after resetting the app originally, you also set up everything you normally set up in MonitorControl (for example disable DDC for the second display etc). For the second scenario please make a screenshot of all the Preference panes screenshot you changed.

I know it's a lot of work. :) Thank you!

**Comment by hagncola** [comment]
Thanks for your help, but the issue is gone. Today i had to do some changes and "cut" the power from the Mac and the displays, now it´s working. 

Thanks for your help and sorry to waste your time.

**Comment by waydabber** [comment]
All right, no problem. Thanks for the feedback!
