### ISSUE TITLE
Native brightness slide in Monterey is grayed out

### ISSUE THREAD

**Issue by brsnik** [MonitorControl/MonitorControl#789]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

Ability to adjust the brightness from the native brightness slider, as it's currently grayed out.

<img width="286" alt="Screen Shot 2021-11-15 at 23 30 02" src="https://user-images.githubusercontent.com/14618565/141864819-f880dc29-ad89-4d4f-8e89-800c71ace99d.png">

### Describe the solution you'd like

Use the native slider.

### Describe alternatives you've considered

N/A

**Comment by waydabber** [comment]
Unfortunately this is not possible as it is part of macOS and its workings cannot be altered. If you keep the lid open, you can use the slider and the brightness can be synchronized to the external display.
