### ISSUE TITLE
BackLight Keys no longer working

### ISSUE THREAD

**Issue by AihamMostafaAwad** [MonitorControl/MonitorControl#790]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Once I opened the app for the first time the backlight keys stopped working and no matter what they won't work again for some reason

### Steps to reproduce

Just open the app for the first time

### Expected behavior

I expected them to work normally

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.0.1
- Mac model: MacBook Pro (13-inch, 2011)
- MonitorControl version: v4.0.1
- Monitor(s): SMS19A100
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment]
The app does not affect keyboard illumination, but you can change this setting in System Preferences/Keyboard:

<img width="780" alt="Screen Shot 2021-11-16 at 7 17 35" src="https://user-images.githubusercontent.com/37590873/141931849-afebfde8-c937-49e3-91cd-05c09d271603.png">

Alternatively it might be that Apple API controlling the display brightness in Monterey and used by the app  is not fully compatible with the 2011 Macbook model as it is not officially supported by Monterey and this causes some strange issues (like changing brightness of the keyboard instead somehow?).

**Comment by waydabber** [comment]
(let me know if I can help with this somehow in any other way, I'll close the issue until then).
