### ISSUE TITLE
Volume control scaling (Dell U3419W)?

### ISSUE THREAD

**Issue by carefulcomputer** [MonitorControl/MonitorControl#799]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

On my dell U3419W, at 1% volume (minimum possible in ui slider) it is near 'normal' sound level (you can hear it in next room). And it goes up from there.
It gets little problematic when I want to get it lower than normal so that sound doesn't interrupt other family members in adjacent rooms because either it is at 1% (which is more than what I want) and or at 0% (mute)

Is there a setting or some way to 'scale' the sound so I can adjust the volume to be lower ?

### Steps to reproduce

1. Use dell U3419W monitor
2. Set volume to 1%
3. Observe sound level.

### Expected behavior

Ideally there would be way to scale the volume so that I can adjust max and min for 0 and 100%. That way I would be able to map 'current 1%' to '50% on new scale'.

### Environment Information (please complete the following information)

```markdown
- macOS version: 11.6
- Mac model:MacBook Pro (16-inch, 2019)
- MonitorControl version: 4.0.2 Build 6965
- Monitor(s):dell U3419W
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment]
Hi! You can scale the sound output in `Dispalys`/`DDC min`-`DDC max` if you enable `Show advnanced settings`. If the setting of `1` is still too loud, then there is nothing to do about that, as the display accepts only integer values (`1` being the lowest option after `0`).

Hope this helps!
