### ISSUE TITLE
MonitorControl exits after sleep/wake of LG 34WK95U

### ISSUE THREAD

**Issue by xszuflax** [MonitorControl/MonitorControl#804]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Hello, 

I'm using MonitorControl since version 3.x on this setup. Since I've update to macOS 12.0.1 or MonitorControl 4.0.1. Not sure exactly when it started MonitorControl exits after external monitor wakes up or goes to sleep. I need to reopen the app. All functions work well just the app is not there when I need it and need to reopen. 

Setup:
MacBook: MacBookPro17,1 (M1 MacBook Pro 13")
Monitor:  LG 34WK95U connected via Thunderbolt 3 (Newest firmware)
Dock: Elgato Dock Pro (Monitor is connected via TB3 to the dock and the dock to the MacBook also via TB3)

### Steps to reproduce

Put MacBook to the lock screen and let monitors to turn off. Once unlocked MonitorControl is not active and needs to be relaunched.

### Expected behavior

MonitorControl still works after monitor wakes up from sleep.

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.0.1
- Mac model: MacBookPro17,1 (M1 MacBook Pro 13")
- MonitorControl version: 4.0.2
- Monitor(s): LG 34WK95U
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Hi @xszuflax , handling of sleep was changed a bit in 4.0.2 (wait times were shortened). Can you please try 4.0.1 and see if the issue is present with that version as well? Thank you!

**Comment by xszuflax** [comment]
Hello @waydabber this issue actually started on 4.0.1. I've updated to 4.0.2 hoping for the fix... 

And now the funny thing. Since I created this very ticket the issue is gone... not sure what happened.

**Comment by waydabber** [comment]
Well, next time you have this issue, just create a ticket, that will solve it. :)

All right, if the problem comes back, let me know!
