### ISSUE TITLE
Audio through monitor stops working after sleep. Must disconnect and re-connect DP cable to fix.

### ISSUE THREAD

**Issue by ilium007** [MonitorControl/MonitorControl#806]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Everything ng works fine on a Samsung LU28R550UQEXXY using Display Port until the Macbook Pro (2015) goes to sleep. When woken up the audio through the monitor is not working.

### Steps to reproduce

1. Sleep machine
2. Wake machine
3. Play audio (Spotify, Safari etc), no sound through external speakers connected to monitor
4. Unplug Display Port cable and reconnect and sounds works again

### Expected behavior

Sound should work through monitor after speed / wake cycles.

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.0.1
- Mac model: MacBook Pro (Retina, 15-inch, Mid 2015) 
- MonitorControl version: 4.0.2 Build 6965
- Monitor(s): LU28R550UQEXXY
- Apple Silicon/M1 (yes or no): no
```

**Comment by ilium007** [comment]
Just did further testing, it seems the issue is intermittent.

**Comment by waydabber** [comment]
Does this issue happen without MonitorControl as well intermittently? If so, did this issue happen with 4.0.1 as well? What is your setting for `General`/`Upon startup or wake`?

Thanks!

**Comment by ilium007** [comment]
I only got this 4K monitor today so I’m not sure if it would do the same without MonitorControl installed. I needed the keyboard control functionality so installed straight away. Settings for “Upon startup or wake”: “Assume last saved settings are valid”

**Comment by waydabber** [comment]
All right, this is probably a display specific issue then. Also check if the audio output does not change during sleep somehow.  Let me know if the issue does not happen without MonitorControl or using previous versions of the app. Thank you!

I'll close the issue for now but if it turns out to be a MonitorControl issue, we'll reopen it.

**Comment by ilium007** [comment]
Ok, will uninstall and test. Output never changes (MacBook Pro, would have sound coming out of internal speakers if it changed). How many releases back do you want me to test?!

**Comment by ilium007** [comment]
Also, is there any debug logging that I can enable to try and catch the issue?

**Comment by waydabber** [comment]
You can use the Console app and look at the `info` messages for MonitorControl. You can try versions 4.00 and 3.00. In 4.0.2 there was a slight change in how sleep is handled (acutally wake up was made faster) but to be honest I don't think it should affect audio in any way. If you don't hear audio and even if you change the volume controls using the display OSD then it is most probably not a MonitorControl issue. If you can hear audio by changing volume controls using the display OSD or by changing the volume via DDC then probably the display forgets the audio volume level setting issued via DDC during sleep (this is still also a display firmware issue).

You can also try alternate apps for volume control like ddcctl or Lunar to see if that works.

**Comment by ilium007** [comment]
Have been running Lunar for a week and haven't had a single case of lost audio. ddctl form command line works as well. Will switch back to Monitor Control this week and see what happens.

**Comment by waydabber** [comment]
Super! Lunar is a great app (@alin23), I am glad you found a solution that works. If the issue consistently resurfaces with MC, we might have to look into it.

**Comment by YanMiaoW** [comment]
I encountered the same problem, my Macos version is 13.2.1, m1 macbook, my monitorControl version is 4.2.0, my display model is aoc U27N10R, 4k, this display is connected to a speaker, when I After my MacBook goes to sleep, and then wakes up, there is no audio output.. I have to close the monitorControl and reload it to fix it. @waydabber
