### ISSUE TITLE
LED Cinema Display Brightness issue

### ISSUE THREAD

**Issue by aganiban** [MonitorControl/MonitorControl#817]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

Recently installed the latest release and my original brightness level of my LED Cinema Display dropped, I tried to increase the brightness but it wont get any brighter than the original

### Expected behavior

I want my monitor to have original brightness 

### Environment Information (please complete the following information)

```markdown
- macOS version:
- Mac model:
- MonitorControl version:
- Monitor(s):
- Monitor Cable(s)/Connection(s):
- Apple Silicon/M1 (yes or no):
```

**Comment by aganiban** [comment]
macOS version: 12.0.1
mac model: Mac mini m1
monitor: Apple LED Cinema Display
Monitor Control: 4.0.2
Monitor Cable: displayport to thunderbolt
Apple Silicon/M1: yes

**Comment by the0neyouseek** [comment]
Please see this discussion for a solution to this issue

https://github.com/MonitorControl/MonitorControl/discussions/739

I'll close this for now but feel free to comment if it does not solve your problem and I'll reopen this issue.

Have a nice day

**Comment by aganiban** [comment]
Great it works!
