### ISSUE TITLE
Monterey Beta 12.1 Sound Control not working

### ISSUE THREAD

**Issue by andreT30** [MonitorControl/MonitorControl#822]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

Hello
I know this is under the beta version (12.1) but I thought to let you know that the sound control is not working on my DELL S3221QS. It was working as expected while on any previous macos version but not on the beta.
I'm not sure if this is a macos issue (being beta et all) or an app issue.
Brightness feature on the other hand, works perfectly fine.
Anyway I wanter to report it and help you guys continue doing an excellent job.

### Expected behavior

Using the app to control monitor's volume level.

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.1
- Mac model: Mac mini (2018)
- MonitorControl version: 4.0.2
- Monitor(s): DELL S3221QS
- Monitor Cable(s)/Connection(s): HDMI
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment]
Hi @andreT30 - I am on Monterey 12.1 beta (still beta3, updating now to beta4) and sound control does seem to work fine. If you are using the HDMI port of the 2018 mini, you won't be able to use DDC though, you need to use the USB-C port!

**Comment by andreT30** [comment]
Hello @waydabber. You are absolutely right. I connected the monitor with a type-c to DP cable and it works fine. I used to connect my monitor through an eGPU with HDMI and I did not have any issues but the eGPU was indeed connected to the mac mini through thunderbolt.
Thanks, issue is resolved :)
