### ISSUE TITLE
Further control of OSD in LG Monitors?

### ISSUE THREAD

**Issue by robroy90** [MonitorControl/MonitorControl#830]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

No, this is strictly a feature enhancement request

### Describe the solution you'd like

I was curious to know if it would somehow be possible to add further control over the OSD of an LG monitor? For example, change the input via software/remote control from the Mac?
![LG OSD](https://user-images.githubusercontent.com/2379627/144768274-c9dd048c-a65a-444f-9f6f-6166844a9846.jpg)

### Describe alternatives you've considered

Using the physical controls, of course...

### Anything else?

Nothing else, and thank you for your evaluation and consideration of this feature! I have no idea if it would even be possible, but a way to make my monitor input change without touching the monitor itself would be AMAZING!

**Comment by waydabber** [comment]
Yes, changing the input signal is possible and is a planned feature for the future. See this one: https://github.com/MonitorControl/MonitorControl/issues/720

I'll close this issue since this will be addressed in the mentioned issue.
