### ISSUE TITLE
Link internal keyboard to internal display, external keyboard to external display

### ISSUE THREAD

**Issue by lukeshingles** [MonitorControl/MonitorControl#855]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

I use MonitorControl to replace the brightness-key functionality that I had with a Thunderbolt Display, but now with a non-Apple display connected to my MacBook Pro. It works great! But there is an inconsistency. When using the Thunderbolt Display, the MBP brightness keys only control the MBP display, and the external Bluetooth keyboard controls the Thunderbolt display (or other external displays).

### Describe the solution you'd like

I would like the behaviour to match what happens when an Apple external display is connected to a MacBook Pro.

In the preferences, under the Keyboard -> Screen to Control, add an option to differentiate between the MBP keyboard brightness keys (for MBP display) and external keyboard brightness keys (for external monitors). It could be called something like 'Depends on internal/external keyboard'. 

### Describe alternatives you've considered

The internal/external keyboard distinction could be a checkbox below the existing 'Screen to Control' options, since if I recall correctly when I had both a Thunderbolt Display and an Apple Cinema Display connected, the external keyboard would then control whichever display had the cursor (but not the internal display).

**Comment by waydabber** [comment]
Theoretically it is possible to differentiate between the internal and external media keys but the library used by MC (MediaTapKey) does not distinguish between them I think. Currently MC controls the screen that has the mouse.
