### ISSUE TITLE
Toggle HDR mode on/off

### ISSUE THREAD

**Issue by disq** [MonitorControl/MonitorControl#877]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

I have an HDR600 compatible monitor (an LG 34WK95-U) and I turn on the HDR mode when consuming compatible media on it. Normally HDR is turned off, mostly because it just doesn't look right for normal desktop use.

So when watching content I need to go in the display settings and enable the HDR  checkbox, and later when I'm finished (or I get interrupted and need to do desktopy stuff) come back and disable it.

### Describe the solution you'd like

Some kind of an HDR toggle button next to the brightness toggle (or in the vicinity) for the HDR-supporting displays. I know it would be a clutter if one rarely toggles that option, so maybe make it an option in Preferences:
App menu / Additional controls / [x] Show HDR toggle on compatible displays

### Describe alternatives you've considered

I've checked in the options but it isn't there. I don't really want to run another menu app just to have this functionality.

**Comment by jiywww** [comment]
I have the same situation. The HDR setting is too deep. I have to go into the display settings, enable the HDR checkbox whenever I want to watch a movie (HDR), and go into the display settings again to disable the HDR checkbox after watching. Please think about adding an option for the HDR setting. Thank you.

**Comment by waydabber** [comment]
nahh, I was wrong, there is a way actually.
