### ISSUE TITLE
Change the vertical mouse scroll direction of sliders (or add an option)

### ISSUE THREAD

**Issue by Wiredframe** [MonitorControl/MonitorControl#885]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

Mouse wheel reacts opposing to what I've expected.

### Describe the solution you'd like

Would love it was possible to invert the mouse wheel direction in the settings.

### Describe alternatives you've considered

None

### Anything else?

THANKS! 👍 :love

**Comment by waydabber** [comment]
Hmm. Are you sure this is a MonitorControl issue? You can change this in System Preferences.

**Comment by waydabber** [comment]
Huhh, that is a tricky one. I thought the two things can be set separately in System Prefrences but now I see that if I change the mouse scrolling it changes the trackpad scrolling as well.

**Comment by Wiredframe** [comment]
Thats the problem unfortunately. But with apps like LinearMouse or ScrollReverser you can change it seperately. But never mind, I will just get used to it on the slider. Btw, thanks very much for you hard work, it's an awesome app!

**Comment by waydabber** [comment]
All right. I'll close this issue - I understand that it would be nice to have an option for this but with the same approach you'd need an option like this for all apps which does not make much sense, hence it is probably not the best idea to implement this into MonitorControl as well. :) Thanks for your understanding!

**Comment by waydabber** [comment]
An other similar request came in: https://github.com/MonitorControl/MonitorControl/issues/305#issuecomment-1063050640

I am not sure if an option is really needed for that but we can permanently reverse the scroll direction of the sliders in the vertical direction if that feels more logical (I am not sure about that).
