### ISSUE TITLE
Add Controls for Keyboard Backlight?

### ISSUE THREAD

**Issue by waydabber** [MonitorControl/MonitorControl#887]
### Discussed in https://github.com/MonitorControl/MonitorControl/discussions/886

<div type='discussions-op-text'>

<sup>Originally posted by **isametry** January 10, 2022</sup>
I think it would be really useful to have the option for a keyboard backlight brightness slider in this app.

Now, I know that it might seem a little off-topic for this app, since it is focused on monitors (and literally has the word _"monitor"_ in the name), but it's one of the native brightness sliders provided by macOS (in the Control Center), and having it alongside the monitor ones would simply be very practical.

Alternatively, if anyone knows about a tool as simple and native-looking as _MonitorControl_ which allows this, please let me know. Thank you!</div>

**Comment by mmcguffi** [comment]
Came here to ask for this -- given the lack of dedicated keyboard brightness on M1 keyboards and how they have hidden the controls in the control center, this would be much appreciated :)
