### ISSUE TITLE
A couple icons I have made for LG Displays, feel free to use.

### ISSUE THREAD

**Issue by ozturkabdulhamid** [MonitorControl/MonitorControl#888]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

https://macosicons.com/u/abdulhamidozturk

### Describe the solution you'd like

https://macosicons.com/u/abdulhamidozturk

### Describe alternatives you've considered

Already provided.

### Anything else?

Nope.

**Comment by waydabber** [comment]
Hey @ozturkabdulhamid - the icons look nice and would suit an "LG edition" of the app.

Maybe we could approach LG with some kind of collaboration proposal - we could create a MonitorControl version that is certified to work with LG products in return for test displays (or maybe some form of funding). This version of MC could have LG styling or branding and could even be offered as a download on LG's site. I think a step like this could boost their sales in the Mac community and would benefit the project as well.

@JoniVR @the0neyouseek

**Comment by the0neyouseek** [comment]
@waydabber Lg seems to have an official account: https://github.com/LGE-OSS, if you want to send them an email feel free.
