### ISSUE TITLE
Add option "set brightness from built-in display"

### ISSUE THREAD

**Issue by xand3r40r93** [MonitorControl/MonitorControl#889]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

When I connect an external monitor to my MacBook, the brightness can be very different. It is very uncomfortable.

### Describe the solution you'd like

Add option "set brightness from built-in display".

With this option, the brightness value must be copied from the built-in display after connecting.

Also, you can add "offset brightness" - is the constant that increases/decreases the built-in display brightness value.

### Describe alternatives you've considered

no

**Comment by waydabber** [comment]
You can enable "Attempt to read display" in "Upon startup or wake". If your display is set to the right brightness upon startup. Syncing from the built-in display would need a way to properly correlate/map the varying external and internal display brightnesses, that's why MonitorControl syncs only the changes, not the absolute values.

**Comment by xand3r40r93** [comment]
@waydabber I have enabled this setting. But that's different. I want to synchronize brightness value from built-display after connecting to MacBook.

For example:

I worked during the day and the brightness of the monitor was 100%. Then I disconnect the MacBook from the monitor and have worked without it. At night I have connected the MacBook to the monitor and the brightness on the monitor was at 100%.

There is already a very cool "sync change brightness" option, but "sync when connected" is very needed.

**Comment by waydabber** [comment]
Yes, I understand. A feature like this could be implemented however it will not work that well due to the brightness differences (a brightness of 50% means something totally different in term of nits for the internal display and various external displays).

**Comment by xand3r40r93** [comment]
@waydabber I have MacBook Pro M1 16 and Philips 288E2A. When I have enabled "combine software and hardware dimming", displays look ~ same on different brightness values. With "auto sync brightness from built-in display" it's very comfortable. But issues on startup "killing my eyes".

**Comment by xand3r40r93** [comment]
100/100
![image](https://user-images.githubusercontent.com/65961104/149183855-bb8e1213-b21b-4abf-8a70-b6b555aea694.png)
50/50
![image](https://user-images.githubusercontent.com/65961104/149183893-2892d457-72d4-4c5e-92c0-e49267c61ed3.png)
25/25
![image](https://user-images.githubusercontent.com/65961104/149183930-6bc5053f-4db9-4860-b9c8-bec911033088.png)
25/100
![image](https://user-images.githubusercontent.com/65961104/149183962-b30ee1d9-63bf-4be2-a171-e19330762a05.png)

**Comment by xand3r40r93** [comment]
I think that differences in brightness/nits can be ~ corrected with "startup delta value".

**Comment by xand3r40r93** [comment]
In "sync brightness with built-in display" you are not thinking about differences in brightness/nits - just changing value with calculated delta value. I suggest just adding "startup delta value" (as an option) and after startup sync brightness value from the built-in display with this delta value.

**Comment by waydabber** [comment]
Yes, we can work something out, but might need a thoughtful approach to improve syncing experience and allow for absolute syncing in general. I added it as a feature request.

**Comment by xand3r40r93** [comment]
thanks. sounds great.

**Comment by patrickrushton** [comment]
"Absolute" syncing would be great! I've never been in a situation where I wanted different a brightness on each display.

Currently my MacBook and Dell displays have pretty much identical brightness as long as each OSD shows the same number of chiclets (thanks to the combined hardware & software dimming). But they get out of sync throughout the day, for example after waking from sleep.

**Comment by waydabber** [comment]
@patrickrushton - absolute syncing is rather difficult especially if you want to match different display brightnesses. Some sort of calibration process should be involved and also a decision must be made what to do with the excess low/high range of some display. Absolute syncing would also reduce the brightness range to the most limited device.
