### ISSUE TITLE
Mirror displays shortcut

### ISSUE THREAD

**Issue by juanfal** [MonitorControl/MonitorControl#890]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

It could be great to have a shortcut to mirror/no-mirror displays included in the code of this cool app

### Describe the solution you'd like

When you press, for example ⌘-F1 it would toggle mirroring the display on the second monitor

### Describe alternatives you've considered

Existing utilities on this exist, but you have to have them apart, and it could be included in the code of this
[Fabián Cañas mirror display](https://github.com/fcanas/mirror-displays)

**Comment by waydabber** [comment]
Hi there - there is a shortcut implemented to mirror/unmirror the built-in display (same as the default macOS shortcut).

See this one: https://github.com/MonitorControl/MonitorControl/issues/227

**Comment by waydabber** [comment]
Hey @juanfal - I'll close this issue. Let me know if I did not understand the request properly and you asked for something else. Thank you!
