### ISSUE TITLE
Separate mute button in the app menu

### ISSUE THREAD

**Issue by carefulcomputer** [MonitorControl/MonitorControl#893]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

When working, several times there is a need to mute the sound temporarily and resume.
E.g. when I get a urgent phone call in middle of a zoom conference. Currently I have drag the volume slider to 0 and then bring it back to original volume later.

### Describe the solution you'd like

It would nice to have a toggle button to quickly mute the volume and then resume later.

### Describe alternatives you've considered

Keyboard shortcut would be nice.

**Comment by the0neyouseek** [comment]
The mute key (normally <kbd>F10</kbd> but could be different depending on your keyboard) should normally work.  
Does it not ?
![Mute key](https://user-images.githubusercontent.com/4009175/149390846-fa31fb57-c6d2-43d1-a40b-749d283c13b5.png)

**Comment by waydabber** [comment]
Let's merge this one into #892

**Comment by waydabber** [comment]
Oh no sorry, it's a different one. Having an issue with the Samsung C34J is a different, probably monitor issue and should not be confused with this one.

This is a feature request for a Mute icon in the menu if I get it right.

**Comment by carefulcomputer** [comment]
Yes different issue. This feature request is to have a quick way to mute and unmute from menu (tray menu).

**Comment by carefulcomputer** [comment]
ping to keep this alive.

**Comment by waydabber** [comment]
This was implemented in [BetterDisplay](https://betterdisplay.pro) (you can click the volume icon in the slider to mute/unmute), not planned in MonitorControl.
