### ISSUE TITLE
Ability to deactivate/hide a connected display

### ISSUE THREAD

**Issue by icesof** [MonitorControl/MonitorControl#907]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

My external display with 2 cables, one for MacBook Pro, another for a desktop. After switching to the desktop (by the menu on display), the MacBook Pro is keeping showing something on the external display, unless plug out the cable.

### Describe the solution you'd like

the possibility to disable the external display with MonitorControl? and enabling it back later..

### Describe alternatives you've considered

not yet.

**Comment by waydabber** [comment]
This can be done. One approach would be to have an option to change the external display to the mirror of the internal display (which effectively makes it disappear). An other option is to take the screen exclusively and fill it with a blank screen. The same would be useful for a notebook - if somebody wants to use it with display opened (for example to use the touchpad or the keyboard) but does not want the screen to display anything (the internal display's brightness can be turned down to zero in this case).

**Comment by shado23** [comment]
Apparently there is an internal API to actually disable a monitor. There is an app called DisableMonitor that makes use of it:
https://github.com/Eun/DisableMonitor/blob/3a690419041ae78cb4d776f2cb07919356817b49/DisableMonitorAppDelegate.m#L303

In some cases there seems to be a noticeable difference in UI performance when only one monitor is active. The downside is that if you disable your internal screen and detach the other screen, the internal screen stays disabled and you have to reboot or reattach the secondary screen to see anything. Maybe that's just a flaw in the way DisableMonitor implements this, and it could be avoided by checking for display changes and re-enabling the disabled screen if it's the only one left, but it's something to watch out for.

**Comment by waydabber** [comment]
Wow. I wasn't aware of this one (an other undocumented api call). :) I'll try it for sure, it would be great to implement this one!

**Comment by shado23** [comment]
There seem to be quite a few undocumented APIs. I found this list/headers from a couple of years ago: https://github.com/NUIKit/CGSInternal/issues/3

**Comment by waydabber** [comment]
Yes, we've been using a host of undocumented API calls (that's why the full MonitorControl cannot go to the App Store) - was just now aware of this one. Will experiment with it if it still works on M1.

**Comment by waydabber** [comment]
https://github.com/MonitorControl/MonitorControl/issues/1105

**Comment by tfbecker** [comment]
I am also interested in having Lunar support this!

**Comment by waydabber** [comment]
This feature is available now (for Apple Silicon macs) in the latest BetterDisplay beta: https://github.com/waydabber/BetterDisplay/releases

I do not plan to add this one to MonitorControl as it does not really fit the profile of the app, other contributors might of course create a pull request for this.

**Comment by tfbecker** [comment]
Thank you for releasing this - Improves my morning by a lot! - I stopped searching for a solution and gave up.
Thank you!

**Comment by waydabber** [comment]
This feature is not planned in MonitorControl as the current feature set is considered final.
