### ISSUE TITLE
"Sync brightness from Built-in and Apple displays" stops working after sleep

### ISSUE THREAD

**Issue by patrickrushton** [MonitorControl/MonitorControl#922]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Syncing brightness from my MacBook Pro 2019 to my Dell display with hardware DDC works fine... until my Mac sleeps. After a sleep cycle, the brightness changes caused by the Ambient light sensor are no longer synced to the external display. 

I have verified MonitorControl is still running in Activity Monitor, and brightness changes made by the keyboard shortcuts in MonitorControl are applied successfully to the external display.

If I quick and relaunch MonitorControl, then syncing will resume until the next sleep cycle.

### Steps to reproduce

1. Launch MonitorControl with Sync brightness changes enabled.
2. Put the Mac to sleep
3. Cover the light sensor on the Macbook or change the built-in display brightness in System Preferences

### Expected behavior

Brightness on both on the displays should adjust. Instead, only the built-in display brightness changes while the external display brightness remains constant.

### Anything else?

![image](https://user-images.githubusercontent.com/6472595/151700294-14c41147-fb4f-4d09-a153-576756312851.png)
![image](https://user-images.githubusercontent.com/6472595/151700301-cd023760-574b-4c8b-84f4-86696f651b18.png)
![image](https://user-images.githubusercontent.com/6472595/151700307-c156f28e-c780-447b-a5f8-971040a32d80.png)

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.1
- Mac model: MacBook Pro (16-inch, 2019)
- MonitorControl version: 4.0.2
- Monitor(s): DELL U2713HM
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment]
Do you have this issue only with ambient light sensor? If you change the brightness using the built-in (macOS native) brightness slider, what happens?

**Comment by waydabber** [comment]
All right. We'll look into this, thanks for the report!

**Comment by patrickrushton** [comment]
To clarify this issue. I've noticed that it's not necessary for the Macbook to fully go to sleep in order for syncing to break. 

If I have an application running that prevents sleep (such as Logic Pro) the displays will turn off after the period of inactivity specified in System Preferences. 

When the displays wake up again, brightness syncing will be broken until I quit and restart MonitorControl.

**Comment by leoskyrocker** [comment]
```
- macOS version: 12.3
- Mac model: Macbook Pro (2019)
- MonitorControl version: 4.0.2
- Monitor(s): HP 24es
- Apple Silicon/M1 (yes or no): no
```

Not sure if it's the same issue, but I noticed that some of the folks above are getting different behaviors than mine, but essentially they all experience some sort of sync issue.

To clarify, there are 4 types of controls I tried:
1. The slider on the touch bar (macbook pro native)
2. The brightness buttons (not a slider) on the same touch bar, when the menu is expanded
3. The brightness buttons on my PC layout keyboard ('F1' & 'F2') (which should be sending the same signals as 2)
4. The brightness slider from MonitorControl in the menu bar (I have it setup as control all so it's probably working regardless of the sync option)

My sync setting is checked, and after sleep I noticed that 1 stops working while 2 and 3, 4 still works.

**Comment by waydabber** [comment]
2 will send proper keyboard commands which are intercepted by MonitorControl so 2,3,4 is the same. So the issue affects only reading 1. upon sleep. We'll have to look into that.

**Comment by lsy66666** [comment]
```
- macOS version: 12.3
- Mac model: Macbook Pro (2019)
- MonitorControl version: 4.0.2
- Monitor(s): T270LG
- Apple Silicon/M1 (yes or no): no
```

我也遇到了这个问题。希望能修复，感谢。

**Comment by pizza496** [comment]
- macOS version: 12.3
- Mac model: Macbook Pro (2020)
- MonitorControl version: 4.0.2 build 6965
- Monitor(s): S24H85x
- Apple Silicon/M1 (yes or no): no

I'm also experiencing this issue.

**Comment by te6-in** [comment]
```
- macOS version: 12.5
- Mac model: MacBook Pro (13-inch, 2018)
- MonitorControl version: 4.1.0 build 7034
- Monitor(s): HP 5DQ99AA
- Apple Silicon/M1 (yes or no): no
```
I'm experiencing the same issue on the latest available version. Type 2, 3, and 4 work, but Type 1 nor the sliders in the control center and System Preferences won't work.

By the way, thanks for this fantastic software!

**Comment by andrew-stupchuk** [comment]
I'm also experiencing this issue.
```
- macOS version: 12.5.1
- Mac model: MacBook Pro (16-inch, 2019)
- MonitorControl version: 4.1.0 build 7034
- Monitor(s): Dell s2721dgfa
- Apple Silicon/M1 (yes or no): no
```

**Comment by fnwbr** [comment]
Now on Ventura and still experiencing this.
```
- macOS version: 13.3
- Mac model: MacBook Pro (16-inch, 2019)
- MonitorControl version: 4.1.0 build 7034
- Monitor(s): Dell U3223QE
- Apple Silicon/M1 (yes or no): no
```

**Comment by silver886** [comment]
I'm also experiencing this issue.
```
- macOS version: 12.6.8 (21G725)
- Mac model: MacBook Pro (15-inch, 2017)
- MonitorControl version: 4.1.0 build 7034
- Monitor(s): HP E24d G4 Display * 2
- Apple Silicon/M1 (yes or no): no
```

**Comment by Porencephaly** [comment]
I'm also having this issue. 
`- macOS version: 13.6.1
- Mac model: iMac(27-inch, 2017)
- MonitorControl version: 4.2.0
- Monitor(s): Dell P2222H
- Apple Silicon/M1 (yes or no): no`

**Comment by waydabber** [comment]
Hopefully this issue is resolved with the latest version. If not, will reopen. :)
