### ISSUE TITLE
It doesn't work for the sidecar display with ipad

### ISSUE THREAD

**Issue by ycxbox** [MonitorControl/MonitorControl#927]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

Hi Bro,

Does anyone has ever tried the monitorcontrol for the iPad sidecar display with mac book pro?
it doesn't work in this scenario, or maybe it doesn't support it well. when I tried in this way, it popup with an error message asking me to decide eighter to quit the blocking program or stop something with gamma which i don't understand.... but anyway, it just can not adjust the sidecar iPad brightness as it does with any other monitor else.
wish it can support the sidecar approach, thanks, guys !!

<img width="1680" alt="截屏2022-02-02 上午9 20 01" src="https://user-images.githubusercontent.com/4571144/152078537-330c526d-1201-48af-8380-975c16819b2d.png">

Best regards,
Jeff Yu

### Expected behavior

hope it can support sidecar display brightness control

### Anything else?

nothing else ~

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.1
- Mac model: MBP 2019
- MonitorControl version: latestone
- Monitor(s): ipad
- Monitor Cable(s)/Connection(s): wifi/cable
- Apple Silicon/M1 (yes or no): No
```

**Comment by waydabber** [comment]
Sidecar brightness change should work in software mode. Sidecar does not support gamma mode so there should not be a popup like that.

**Comment by ycxbox** [comment]
Hi Bros~

it does give an error message like what I mentioned above, I tried to replicate the same error by using another mac book pro, please see the message below:
<img width="1112" alt="截屏2022-02-02 上午10 46 07" src="https://user-images.githubusercontent.com/4571144/153106563-bab3c206-415e-4f52-806b-fcfb07d60598.png">

Is there any workaround that I can do to make it works under the sidecar scenario, thanks, man!

Best regards,
Jeff

**Comment by waydabber** [comment]
Sidecar control should work just fine. The message (I think - I can't read Chinese) is about some other app interfering with MonitorControl when trying to use gamma control - this method of control is not used with Sidecar. What happens if you just allow the app to disable gamma control?

**Comment by waydabber** [comment]
I'll close this one for now due to inactivity. If there is any more info about this, please let me know!
