### ISSUE TITLE
MonitorControl interferes with True Tone after waking from sleep

### ISSUE THREAD

**Issue by patrickrushton** [MonitorControl/MonitorControl#930]
Edit: After trying to reproduce this some more, I'm not convinced this is a MonitorControl issue, therefore I'm going to close it. Will reopen if I can figure out if it's really related to MonitorControl.

> 
> ### Before opening the issue, have you...?
> 
> - [X] Searched for existing issues
> - [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
> - [X] Updated MonitorControl to the latest version (if applicable)
> 
> ### Describe the bug
> 
> When MonitorControl is not running, True Tone on my Macbook will adjust the warmth on both the integrated display _and_ my external display. As long as MonitorControl is not running, the behaviour continues after waking from sleep.
> 
> With MonitorControl running, the behaviour is the same, but only until the Mac goes to sleep. After waking from sleep, the external monitor warmth is reset and no longer synced.
> 
> ### Steps to reproduce
> 
> 1. Ensure True Tone is enabled in System Preferences
> 2. Start MonitorControl
> 3. Adjust ambient lighting to a warm colour.
> 4. Wait for both displays to adjust their tone and make a visual note or photo of the result.
> 5. Put the Mac to sleep
> 6. Wake from sleep
> 7. Colours on the external screen are now cool
> 
> To restore True Tone syncing to the external display, I have to disable and re-enable True Tone in Control Center or System Preferences.
> 
> ### Expected behavior
> 
> If the above steps are followed but instead quit MonitorControl in step 2, then in step 7 the warm tone of the external monitor is restored when waking from sleep.
> 
> ### Anything else?
> 
> Possibly related to https://github.com/MonitorControl/MonitorControl/issues/922 
> Unlike this issue, True Tone is not fixed by quitting and restarting MonitorControl. I have to toggle TrueTone off and on again to restore True Tone to the external display.
> 
> ### Environment Information (please complete the following information)
> 
> ```markdown
> - macOS version: 11.2
> - Mac model: MacBook Pro 2019
> - MonitorControl version: 4.0.2
> - Monitor(s): DELL U2713HM
> - Apple Silicon/M1 (yes or no): no
> ```
>

**Comment by waydabber** [comment]
No, it does not run any background processes. Also, one can't interfere with True Tone easily programmatically.

**Comment by dgmulf** [comment]
I see. Sounds like a problem with the OS, then.
