### ISSUE TITLE
Built-in display will sometimes flash when the "automatically adjust brightness" is on.

### ISSUE THREAD

**Issue by yuchengruan** [MonitorControl/MonitorControl#931]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

For example, when I set the brightness to 80 (range: 0-100) and the light condition changes, the brightness is switched to 10 automatically. At the moment, if I adjust the brightness using the app shortcuts, the built-in monitor will flash, which means the brightness will jump to 80 and then back to around 10 almost simultaneously.

### Steps to reproduce

You can reproduce this bug as I mentioned above but I'm not sure if this only appears on my Mac.

### Expected behavior

The app is supposed to adjust the brightness without any flashing on built-in display.

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.1 Monterey
- Mac model: Macbook Pro (13-inch, 2020)
- MonitorControl version: v4.0.2
- Monitor(s): ASUS VA24E
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Yes, this is an issue - in certain circumstances the app does not deal with the fact that the brightness is unexpectedly changed by the OS. This could be fixed by queriying the current panel brightness and updating the app's internal representation in this regard when changing the brightness.

**Comment by waydabber** [comment]
Ok, this issue is deeper, the app does not behave properly even when the change is known. See this one: https://github.com/MonitorControl/MonitorControl/issues/1000#issuecomment-1095121770

**Comment by mecirmartin** [comment]
Hey, @waydabber why is this issue closed?
I'm experiencing similar bug with my macbook m1 air connected with usb-c cable to Dell monitor
However this issue is really infrequent (happens once a 2-3 weeks) and i'm not really sure what causes the issue

The screen on external monitor flashes even after the device is disconnected (i can see the overlay flashing)

**Comment by waydabber** [comment]
Hi, it was closed by a stale bot automatically.
