### ISSUE TITLE
Control only volume via DDC 

### ISSUE THREAD

**Issue by lloeki** [MonitorControl/MonitorControl#932]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

I have two identical LG 4K displays on a Mac Mini M1.

As is known:

- Only one display can be connected over USB-C, the other one must be HDMI
- Internal HDMI blocks DDC

So to keep brightness consistent between both I use Software (gamma) mode, forcing it on the USB-C display. Still, I would like to keep being able to adjust volume via DDC.

### Describe the solution you'd like

Have "Use hardware DDC control" per-display checkbox split into "Use hardware DDC control for picture" and "Use hardware DDC control for volume", or something to that effect in the advanced mode table that would allow me to uncheck the former but still check the latter.

### Describe alternatives you've considered

I tried tricking it using advanced settings:

- unticking "brightness available" completely disables the USB-C screen's control, even by software.
- moving the "combined dimming switchover point" all the way to the right in hopes it would give up on ddc and favour software only produces unsatisfactory results.

**Comment by waydabber** [comment]
You are right, there is no way to achieve this now. Probably Brightness DDC unavailable when hardware DDC control is enabled should kick in software mode.
