### ISSUE TITLE
Update message

### ISSUE THREAD

**Issue by jajoho** [MonitorControl/MonitorControl#936]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

The update message shows twice the version number.

![Update Message](https://user-images.githubusercontent.com/15175599/153163963-17c0054a-e2c3-4633-ae19-12f3d0ec45f1.png)

### Steps to reproduce

Click on Check for updates (when no is available)

### Expected behavior

From my point of view, it would be sufficient if only the top text, without the one in the brackets below, would be displayed.

### Environment Information (please complete the following information)

```markdown
- macOS version:12.2
- Mac model: MBP
- MonitorControl version: 4.0.2
- Monitor(s):
- Apple Silicon/M1 (yes or no): yes
```

**Comment by the0neyouseek** [comment]
Hi @jajoho,

Updates are handled using https://github.com/sparkle-project/Sparkle and this message comes from their library.
Please feel free to open an issue there if you want, I'll close this issue for now.

Have a nice day!
