### ISSUE TITLE
Allow zero brightness on iMacs

### ISSUE THREAD

**Issue by montanaflynn** [MonitorControl/MonitorControl#941]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

I enabled the option but cannot turn my iMac screen to zero brightness, assuming that to mean black screen like on a macbook pro. I would really love this option for when I'm trying to watch a movie on an external monitor or TV.

![Uploading Screen Shot 2022-02-11 at 7.51.01 PM.png…]()

### Steps to reproduce

1. Install MonitorControl
2. Enable "Allow zero brightness...." option
3. Use keyboard or menubar to bring brightness all the way down
4. Still see the monitor, just very dim.

### Expected behavior

The screen to go completely black like a macbook when fully dimmed.

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.2
- Mac model: m1 iMac
- MonitorControl version: 4.0.2
- Monitor(s): iMac
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Hi, the "Allow zero brightness..." option is for software (and combined software+ddc) controlled displays only. The M1 iMac's display does not use software control but uses Apple's protocol. Apparently unlike on MacBooks, zero brightness on the M1 iMac does not mean display off.

**Comment by montanaflynn** [comment]
@waydabber that's disappointing, was the main selling point for me. Maybe that should be clarified, my interpretation was the "software" was MonitorControl, and that's what allowed Zero brightness to work on iMac, etc.....
