### ISSUE TITLE
Any option to set offset for "Sync brightness changes from Built-in and Apple displays"?

### ISSUE THREAD

**Issue by swalahamani** [MonitorControl/MonitorControl#943]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Question

First Thanks for this awesome tool!

I have been using the **Sync brightness changes from Built-in and Apple displays** for a while and it seems to be a cool feature to have. But the maximum and minimum capacity of the brightness for the built-in display of my MacBook and Dell P2419H is different, and I was wondering whether there is an option to set an offset to adjust this? Also, an option to ignore the too-frequent back-n-forth adjustment by setting an interval or something would be nice.

PS: Wasn't sure about these options are already existing or not. Couldn't find it in preferences. Thought to post this as a question for confirmation than directly posting in feature-request.

**Comment by waydabber** [comment]
There are no options like this. Only delta values are syncing and the offset is dynamically calculated (you can change the brightness separately and the app tries to keep this offset but reduces it when the min or max boundary is being approached). The functionality could be improved though, I'll flag this one as a feature request for future consideration.

**Comment by swalahamani** [comment]
Thank you @waydabber for the update.

**Comment by HenryQW** [comment]
I second this. I have been doing this for a while and it seems to work as intended. You can adjust the value to sync the brightness.

<img width="605" alt="Screenshot 2022-03-07 at 22 57 21" src="https://user-images.githubusercontent.com/5896343/157132194-0b6e0432-28a2-4a98-9eba-780a610601fc.png">

**Comment by waydabber** [comment]
@base08 - this option is available for third party external displays only with support for DDC control. 

However the feature set of the app is now considered final by the team, no more feature additions are planned. I advise you to try [Lunar](https://lunar.fyi) by @alin23 as that app has various advanced syncing features. I plan implementing advanced syncing in [BetterDisplay](https://betterdisplay.pro) as well.
