### ISSUE TITLE
Custom volume steps

### ISSUE THREAD

**Issue by iqwrwq** [MonitorControl/MonitorControl#951]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

My monitor is the LG-38WN95C and I'm using this repository to control the settings via my macbook and an iMac. I have no problem with the brightness, but would like a custom step option for volume adjustment. In earlier versions the volume steps for my monitor where absolutly random (0 -> 6 -> 13 -> 18 ...). With the newer update it got consitant (0 -> 6 -> 12 ...). I figured out that the default usage would be a volume of 10 (not too loud, not too quiet)

### Describe the solution you'd like

I would like a feature to customize the steps in which the monitor is adjusting its volume. Like a Bar or an input field with an Integer value for step-able volume.
It might be a feature for LG-only monitors, let me know if this is a valid issue. 

### Describe alternatives you've considered

Another idea would be the implementation of a shortcut trigger for the SHIFT + OPTION + Volume Up/Down combination so I could set this to my MX Master 3. This would allow me to toggle the volume with the side-scroll one by one volume point.

**Comment by iqwrwq** [comment]
Issue is closed due to OSD Settings, which is exactly what I wanted. Great software ! Keep it going !

**Comment by waydabber** [comment]
Yes, you can use "Use fine OSD scale" or go to Displays/Adanced asettings and you can adjust the DDC scale (Volume min/max) and the mapping curve if you want to skew the scale and have finer control at lower volume settings.
