### ISSUE TITLE
Brightness offset between displays

### ISSUE THREAD

**Issue by NathanielIR** [MonitorControl/MonitorControl#962]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

Different displays have different max brightnesses

### Describe the solution you'd like

Suggestion: The ability to change the value of an external display when the internal display is at a certain value. For instance, if the internal display is set to 100% make the external display 100%. But if the internal display is at 50%, set the external display to 75%, etc. A lot of external displays (including mine) can't reach the same brightness as Apple's so when they're at the same brightness value the external one can be a lot dimmer. Having the ability to equalise this would be super helpful. Especially when you've got keyboard shortcuts set to "Change for all screens"

### Describe alternatives you've considered

There are none in the app

**Comment by JessBinder** [comment]
I also can't increase brightness of my external monitors to match MBP brightness :( 
the 100% for external is very dark
