### ISSUE TITLE
App menu shows strange text for Sidecar display name

### ISSUE THREAD

**Issue by riobard** [MonitorControl/MonitorControl#963]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Please see the screenshot below. It looks like Korean, but my macOS system, the iOS on the iPad, and the iPad's name are all in English.

### Steps to reproduce

I don't know if you can reproduce it, but I can do whatever necessary to help pinpoint the issue.

### Expected behavior

The menu should probably just say Sidecar (since only one sidecar display is allowed anyway), or the name of the iPad running Sidecar? Definitely not some Korean text.

### Anything else?

<img width="271" alt="image" src="https://user-images.githubusercontent.com/22984/156911868-22885e4f-72c8-4e0e-8aa2-ce46bbed44e6.png">

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.2.1 (21D62)
- Mac model: Mac mini (2018)
- MonitorControl version: 4.0.2 build 6965
- Monitor(s): Main monitor is LG 4K over DisplayPort. Sidecar display is on an iPad Air 3.
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment]
Hi, the display names are taken from the relevant dictionary by factoring the `Locale.current.identifier` into account. This is probably the same as the terminal command `defaults read -g AppleLocale` which you can check. It is probably set to Korean?

**Comment by riobard** [comment]
What is it supposed to show? The name of the iPad running Sidecar?

Maybe there's a misconfigured locale mapping somewhere? 

```sh
$ defaults read -g AppleLocale
en_CN
```

The current locale is not Korean.

**Comment by waydabber** [comment]
It shows simply Sidecar for me. But the name should be locale specific. If it really annoys you, why don't you just rename it? Click on the name under Displays in the app Preferences. Hopefully this feature works with virtual displays (like Sidecar) properly, this use case wasn't tested. :)

**Comment by waydabber** [comment]
Sorry, it shows `Sidecar Display` Probably the stuff there stands for `Display` in some language.

<img width="299" alt="Screen Shot 2022-03-06 at 12 11 17" src="https://user-images.githubusercontent.com/37590873/156920558-6d67ede9-c8fb-4f7c-94bb-41eb9392275b.png">

Good news is that renaming works well and the name is remembered after reconnect so the implementation is fine. :)

**Comment by riobard** [comment]
Hmmm… I think it's actually a bug here. Repeatedly clicking the Reset settings button right to the Custom Name field will rotate the name in different languages. 


https://user-images.githubusercontent.com/22984/156924820-d881f7f9-a1bb-4457-af8a-1029b156f29d.mov

**Comment by waydabber** [comment]
Well, in today's multicultural environment I think we should consider this a feature, not a bug. :)

**Comment by waydabber** [comment]
All right, the same issue came up at BetterDisplay and we found the root cause. This should be fixed in MonitorControl as well.

https://github.com/waydabber/BetterDisplay/issues/1047
