### ISSUE TITLE
Why Are You So Amazing?!?!

### ISSUE THREAD

**Issue by mattzollinhofer** [MonitorControl/MonitorControl#974]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Question

Ok, it's not really a question. I just wanted to say thanks for the amazing software, super easy to download & install. Then it worked exactly as I'd expect, fantastic.

Great job, thank you!

**Comment by waydabber** [comment]
Hey @mattzollinhofer - thank you and glad that you found the app useful! :)

**Comment by robertf26** [comment]
I have to agree, especially synching the external display to the ambient light sensor is a killer feature! Thanks for this great piece of FOSS!

**Comment by clarkfw** [comment]
Thanks to all contributors of MonitorControl! 😄 

Finally I'm able to get rid of Dell's ddm.app. With MonitorControl I can change brightness use macbook's function keys!👍

**Comment by phoggren** [comment]
Yep, this utility works flawlessly. Does what it's supposed to do without disturbing my sooo (🤞) otherwise productive hours. Be prepared for a fork because this sounds like a fun project!

**Comment by gruckionvit** [comment]
Woohoo, awesome solution guys this is an awesome bit of software -- from a fellow developer :)

**Comment by mejedi** [comment]
This app is light years ahead of the pack, can finally use non-Apple external displays comfortably.

Visited the issue tracker to open a feature request, and then, while scouting the UI to use the same wording the app uses, discovered that the app already had the feature. Hilarious! (For the record — I wanted modifier key for the brightness-control keys to adjust in fine steps, found that `Option-Shift-` does the job.)

**Comment by razvanphp** [comment]
This piece of software is just that type of thing that you need and you just don't know yet. Works beautifully, thank you!

Thought this is a hardware limitation, can't understand why Apple did not implement CEC/DDC on their own...
