### ISSUE TITLE
MonitorControl brightness not reset after switching user

### ISSUE THREAD

**Issue by pauloord123** [MonitorControl/MonitorControl#976]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Switching user does not restore brightness level of external monitor.

### Steps to reproduce

- Installed MC on Mojave and it works perfect, 
- I use a BenQ external monitor, mirroring the screen of Macbook Pro
- I set my external monitor at 33% brightness, built in Macbook Pro on 0%. 
- when I change user (who not has MC installed) the BenQ switches to its own brightness. Ok. 
- when I switch user back again, first the BenQ dims to 33% but immediately returns to the standard (higher) brightness while MC panel shows 33%. 
- when (only) I touch the brightness slider, the monotor switches back to 33%.  

### Expected behavior

When switching back the BenQ should return to the value set in MC without any ado.

### Anything else?

no

### Environment Information (please complete the following information)

```markdown
- macOS version: 10.14.6
- Mac model: MacBook Pro (Retina, 15-inch, Early 2013)
- MonitorControl version:4.0.2 Build 6965
- Monitor(s): BenQ PD2500Q and build-in
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment]
Hey, does this happen if you disable software and combined hardware/software dimming?

**Comment by waydabber** [comment]
Thanks @pauloord123 for the response!

It seems like hardware DDC control does not work.

As for the change of brightness in software mode, it seems like upon user switching something resets the gamma table (I suppose this is the software dimming method used). I'll try to recreate this issue.
