### ISSUE TITLE
App is quitting randomly

### ISSUE THREAD

**Issue by jaredbm** [MonitorControl/MonitorControl#987]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

I find that the app quits on its own randomly, I go to look for it and it's not there and the keyboard shortcuts don't work. It seems to happen around every other day. 

### Steps to reproduce

Wait a few days and it's quit itself

### Expected behavior

Wait a few days and it's quit itself

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.3
- Mac model: 2019 MB pro 15"
- MonitorControl version: 4.0.2
- Monitor(s): LG Ultragear 34" ultrawide
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment]
Hey @jaredbm - Yeah, sorry about that! We had reports like this but it is super hard to solve as it tends to happen with specific configurations and not much is known about the issue. We could figure out what's wrong with a crash report. If you have one, @JoniVR can symbolicate it (as he did the actual release build) and check where the crash happened exactly - that might shed some light on what is going on.

**Comment by pakerwreah** [comment]
For me it always happens after a long sleep. When I wake my macbook in the morning I have to launch the app again because it has been killed.

Here's my crash reports if that helps.
[MonitorControl-crashes.zip](https://github.com/MonitorControl/MonitorControl/files/8562565/MonitorControl-crashes.zip)

**Comment by mihiralve** [comment]
I've also been seeing similar routine crashes and have to relaunch the app every day. 

Attached my crash reports if they're helpful
[Crash Reports.zip](https://github.com/MonitorControl/MonitorControl/files/8720839/Crash.Reports.zip)

**Comment by waydabber** [comment]
Thanks, we'll definetly have to look into these crash logs!

**Comment by thepeopleseason** [comment]
I've been seeing this as well, so I put together the crash reports that I have here:

[mc_crash.zip](https://github.com/MonitorControl/MonitorControl/files/8949713/mc_crash.zip)

**Comment by pakerwreah** [comment]
It was definitely the HDMI's fault (in my case). 
Since I've changed to a USB-C to DP cable I haven't had another crash. ✨

**Comment by shaungrady** [comment]
Here's another crash report for you:

MacBook Pro (16-inch, 2021) (Apple M1 Pro), macOS 12.5, two LG Ultrafine 5K displays

[MonitorControl-2022-07-19-064056.ips.zip](https://github.com/MonitorControl/MonitorControl/files/9177337/MonitorControl-2022-07-19-064056.ips.zip)

**Comment by Dave-NN** [comment]
I'm also experiencing this issue.
- MacBook Pro (14-inch, 2021)
- macOS 12.6.1
- DELL U2520D Display – connected with USB-C

Attaching three crash reports.
[3x_MonitorControl_Crash_Reports.zip](https://github.com/MonitorControl/MonitorControl/files/9895849/3x_MonitorControl_Crash_Reports.zip)
