### ISSUE TITLE
Status Bar icon with % of brightness 

### ISSUE THREAD

**Issue by Volodymyr-13** [MonitorControl/MonitorControl#998]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

I'm looking for a % of currently set brightness. 

### Describe the solution you'd like

Add % to icon into Menu Bar

### Describe alternatives you've considered

![](https://github.com/KAMIKAZEUA/NativeDisplayBrightness/raw/master/Info/nativeUI.png)

**Comment by waydabber** [comment]
It is certainly possible to add this, similar to [NativeDisplayBrightness](https://github.com/KAMIKAZEUA/NativeDisplayBrightness).

**Comment by Volodymyr-13** [comment]
@waydabber  But why this simple task is abandoned too? Just add percentage to status bar?
