### ISSUE TITLE
App does not start sometimes

### ISSUE THREAD

**Issue by mxmlndml** [MonitorControl/MonitorControl#999]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Sometimes the app will neither start on login nor if it is explicitly opened (nothing happens). Most of the time everything works as it should, but in those cases where the issue occurs only a reboot seems to help.

### Steps to reproduce

Unfortunately, this issue seems to occur randomly. I haven't figured out any pattern yet.

### Expected behavior

The app should start on login and by launching the app.

### Anything else?

The
[crash report](https://github.com/MonitorControl/MonitorControl/files/8449682/MonitorControl-2022-04-08-092451.ips.zip) in a `.zip` archive because Github doesn't allow me to upload the actual `.ips` file.

### Environment Information (please complete the following information)

```markdown
- macOS version: 12.3.1 Monterey (also occurred on 12.3)
- Mac model: Mac Studio (2022)
- MonitorControl version: v4.0.2
- Monitor(s): LG 27UP600, BenQ GW2780
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Thanks for the report, we'll try to look into it.

hey @JoniVR - can you symbolicate the crash report and check where the crash happens (if you still have the dSYM files for it in your xcode's organizer/archive?).

**Comment by JoniVR** [comment]
@waydabber yes, I'm currently on vacation but I'll be home by Tuesday and have access to the device 🙂

**Comment by waydabber** [comment]
of course, I don't think it's that urgent as the current version was out there for a long-long time now and the issue doesn't seem to be too frequent otherwise we'd know about it - enjoy the vacation! :)

**Comment by JoniVR** [comment]
@waydabber Not sure how to symolicate it (haven't done it yet), here are the dSYMs:
[dSYMs.zip](https://github.com/MonitorControl/MonitorControl/files/8475533/dSYMs.zip)

**Comment by JoniVR** [comment]
> Hey @JoniVR - can you attach the dSYMs for version v4.1.0 as well? :) Thanks!

Yes! I'm on vacation right now but I'll be back next week. Will set a reminder!

**Comment by waydabber** [comment]
@JoniVR - Thanks and happy vacation! :)

**Comment by JoniVR** [comment]
@waydabber Posted in dev channel :)

**Comment by TeddyRuxpin83** [comment]
Hi,

I only am using one Apple Studio Display 30” now, I sold the other as it was a pretty frustrating experience.

However I still notice that sometimes I start my Mac Studio and there Monitor Control app hasn’t launched. I just use the controls on the side of the screen or restart the machine, or manually launch Monitor Control app.

Thanks,

Ed

**Comment by Yepitsmeposting** [comment]
I have the same issue on my Mac Studio. Whenever I turn off and on my Mac (which I do every evening) EVEN with the start at login selected in the monitor control app and proper permissions in settings I have to open the twice through spotlight (twice the first time I press enter to open it nothing happens) for the app to open and work. I love the app so its too bad its not working well :(

<img width="476" alt="Screenshot 2023-12-19 at 14 06 34" src="https://github.com/MonitorControl/MonitorControl/assets/152500173/9f6c138b-05b1-4feb-9a32-772f714b4411">
